import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_COMPOSITION_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function boot(page:Page,value:string,position:number){await page.goto(url);await page.evaluate(value=>{const h=(window as any).host;h.load(value);h.editor.view.focus();},value);await expect(page.locator('#editor>.tegg-sdk-frame .cm-content').first()).toBeFocused();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.evaluate(position=>(window as any).host.editor.view.dispatch({selection:{anchor:position}}),position);expect(await page.evaluate(()=>(window as any).host.editor.view.state.selection.main.head)).toBe(position);}
async function undoOnce(page:Page,original:string){await expect.poll(()=>page.evaluate(()=>(window as any).host.editor.commandStatus('undo').enabled)).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);}

test('real composed Unicode input becomes source before any projection redraw and one Undo restores the exact document',async({page})=>{const original='Before after\n\nTail';await boot(page,original,7);await page.keyboard.insertText('中文🙂');await expect.poll(()=>source(page)).toBe('Before 中文🙂after\n\nTail');await undoOnce(page,original);});

test('real consecutive compositions preserve armed rich formatting and do not lose the following text',async({page})=>{await boot(page,'after',0);await page.evaluate(()=>{const e=(window as any).host.editor;e.command('bold');e.command('italic');});await page.keyboard.insertText('你好');await expect.poll(()=>source(page)).toBe('***你好***after');await page.keyboard.insertText('!');await expect.poll(()=>source(page)).toBe('***你好!***after');expect(await page.evaluate(()=>(window as any).host.errors)).toEqual([]);});

test('real composition beside an inactive multiline comment preserves author comment bytes and rejoins visible prose',async({page})=>{const original='Before <!-- First\nSecond --> after\n\nTail';await boot(page,original,0);await page.keyboard.insertText('中文');await expect.poll(()=>source(page)).toBe('中文'+original);await expect.poll(()=>page.locator('#editor .cm-line').first().textContent()).toBe('中文Before  after');await undoOnce(page,original);});

test('real composition inside an explicitly focused comment retains its literal source and hides it again on leave',async({page})=>{const original='Before <!-- First\nSecond --> after\n\nTail',position=original.indexOf('First');await boot(page,original,position);await expect(page.locator('#editor .cm-content')).toContainText('First');await page.keyboard.insertText('中文');await expect.poll(()=>source(page)).toBe(original.replace('First','中文First'));await page.evaluate(()=>(window as any).host.editor.view.dispatch({selection:{anchor:(window as any).host.editor.view.state.doc.length}}));await expect.poll(()=>page.locator('#editor .cm-line').first().textContent()).toBe('Before  after');await undoOnce(page,original);});
