import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function load(page:Page,value:string){await page.goto(url);await page.evaluate(text=>(window as any).host.load(text),value);await expect(page.locator('.cm-content').first()).toBeVisible();}
async function pasteEvent(page:Page,selector:string,data:{text:string;html?:string;structured?:string}){await page.evaluate(({selector,data})=>{const target=document.querySelector(selector)!;document.body.addEventListener('tegg-read-content',event=>{event.preventDefault();(event as CustomEvent).detail.complete(data);},{once:true});const event=new Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:(type:string)=>type==='text/plain'?'contradictory plain':type==='text/html'?'<p>contradictory HTML</p>':'',types:['text/plain','text/html'],files:[]}});target.dispatchEvent(event);},{selector,data});}
test('native three-format read prefers exact structure and definitions over contradictory event fallbacks, then one Undo',async({page})=>{
 const original='target';await load(page,original);const content=page.locator('.cm-content').first();await content.focus();await page.keyboard.press('ControlOrMeta+a');const copy='[Linked][ref] **bold** &amp; text',definition='[ref]: <secret.md> "Exact title"';await pasteEvent(page,'.cm-content',{text:'Linked bold & text',html:'<p>different</p>',structured:JSON.stringify({version:1,kind:'content',format:'tegg',source:copy,definitions:[definition]})});await expect.poll(()=>source(page)).toBe(copy+'\n\n'+definition);await content.focus();await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);
});
test('Reader whole-document Copy keeps folded type, hidden children, raw object references and original shared definitions',async({page})=>{
 const original='> [!warning]- Title\n> hidden **body**\n\n[Linked][ref]\n\n[ref]: <secret.md> "Exact title"';await load(page,original);await page.evaluate(()=>(window as any).host.editor.setMode('reader'));const reader=page.getByLabel('Markdown Reader',{exact:true});await expect(reader).toBeVisible();await page.evaluate(()=>{(window as any).clipboard=[];document.body.addEventListener('tegg-copy-content',event=>{event.preventDefault();const data=(event as CustomEvent).detail;(window as any).clipboard.push(data);data.complete(true);});const root=document.querySelector('[aria-label="Markdown Reader"]')!,range=document.createRange();range.selectNodeContents(root);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});await page.keyboard.press('ControlOrMeta+c');await expect.poll(()=>page.evaluate(()=>(window as any).clipboard.length)).toBe(1);const copied=await page.evaluate(()=>{const data=(window as any).clipboard[0];return {text:data.text,html:data.html,semantic:JSON.parse(data.structured)};});expect(copied.semantic.source).toBe(original);expect(copied.text).toContain('Title');expect(copied.text).toContain('hidden body');expect(copied.text).toContain('Linked');expect(copied.text).not.toContain('secret.md');expect(copied.html).toContain('<strong>body</strong>');expect(await source(page)).toBe(original);
});
test('a GFM cell native semantic paste stages missing definitions and the cell until one outer commit, and Cancel drops both',async({page})=>{
 const original='| H | R |\n| --- | --- |\n| old | untouched |',copy='[Linked][ref]',definition='[ref]: secret.md';await load(page,original);const cell=page.getByRole('button',{name:'Edit table cell: old',exact:true});await cell.focus();await cell.press('F2');const input=page.locator('.md-table-inline-editor .cm-content');await input.focus();await page.keyboard.press('ControlOrMeta+a');const data={text:'Linked',html:'<a href="secret.md">Linked</a>',structured:JSON.stringify({version:1,kind:'content',format:'tegg',source:copy,definitions:[definition]})};await pasteEvent(page,'.md-table-inline-editor .cm-content',data);expect(await source(page)).toBe(original);await expect(input).toContainText('Linked');await page.keyboard.press('Escape');expect(await source(page)).toBe(original);await cell.focus();await cell.press('F2');await input.focus();await page.keyboard.press('ControlOrMeta+a');await pasteEvent(page,'.md-table-inline-editor .cm-content',data);expect(await source(page)).toBe(original);await page.keyboard.press('Enter');await expect.poll(()=>source(page)).toBe(original.replace('| old | untouched |','| [Linked][ref] | untouched |')+'\n\n'+definition);await page.getByRole('button',{name:'Edit table cell: [Linked][ref]',exact:true}).focus();await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);
});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lZ0AAAAASUVORK5CYII=','base64');
test('HTML cell image parameter Complete only changes the local cell; outer Cancel and Complete retain exact attributes and one Undo',async({page})=>{
 await page.route('**/old.png',route=>route.fulfill({contentType:'image/png',body:png}));await page.route('**/new.png',route=>route.fulfill({contentType:'image/png',body:png}));const original="<table><tr><td><p>Before <img SRC='old.png' alt='old' width='80' data-author='keep'> After</p></td><td><strong>untouched</strong></td></tr></table>";await load(page,original);const cell=page.locator('.cm-live-html-table td').first();for(const cancel of [true,false]){await cell.focus();await cell.press('F2');await cell.getByRole('button',{name:'Edit image',exact:true}).click();const panel=page.locator('.tegg-editing-panel:not([hidden])');await panel.getByLabel('Target',{exact:true}).fill('new.png');await panel.getByLabel('Width',{exact:true}).fill('120');expect(await source(page)).toBe(original);await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original);await expect(cell.locator('img')).toHaveAttribute('src','new.png');await expect(cell.locator('img')).toHaveAttribute('width','120');await page.locator('.md-html-table-controls').getByRole('button',{name:cancel?'Cancel':'Done',exact:true}).click();if(cancel)expect(await source(page)).toBe(original);}await expect.poll(()=>source(page)).toBe(original.replace("SRC='old.png'","SRC='new.png'").replace("width='80'","width='120'"));await page.locator('.cm-live-html-table td').first().focus();await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);
});
test('HTML cell independent Formula Complete preserves unselected markup and remains cancellable until the outer commit',async({page})=>{
 const original='<table><tr><td><p>Before <span data-tegg-math="inline" data-tex="x+1" data-author="keep"></span> After</p></td><td>untouched</td></tr></table>';await load(page,original);const cell=page.locator('.cm-live-html-table td').first();await cell.focus();await cell.press('F2');await cell.getByRole('button',{name:'Edit formula',exact:true}).click();const panel=page.locator('.tegg-editing-panel:not([hidden])');await panel.locator('.tegg-object-body').fill('x+2');await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original);await page.locator('.md-html-table-controls').getByRole('button',{name:'Done',exact:true}).click();await expect.poll(()=>source(page)).toBe(original.replace('data-tex="x+1"','data-tex="x+2"'));await page.locator('.cm-live-html-table td').first().focus();await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);
});
test('a nested HTML image field protects mode changes and IME without replay before one outer cell commit',async({page})=>{
 await page.route('**/old.png',route=>route.fulfill({contentType:'image/png',body:png}));await page.route('**/new.png',route=>route.fulfill({contentType:'image/png',body:png}));const original="<table><tr><td><p>Before <img SRC='old.png' alt='old' width='80'> After</p></td><td>untouched</td></tr></table>\n\nAfter";await load(page,original);const cell=page.locator('.cm-live-html-table td').first();await cell.focus();await cell.press('F2');await cell.getByRole('button',{name:'Edit image',exact:true}).click();const panel=page.locator('.tegg-editing-panel:not([hidden])'),target=panel.getByLabel('Target',{exact:true});await target.fill('new.png');expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);await panel.getByRole('button',{name:'Keep editing',exact:true}).click();expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');await target.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);expect(await page.evaluate(()=>(window as any).host.ui.awaitingLeaveChoice)).toBe(false);await target.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);await panel.getByRole('button',{name:'Complete and continue',exact:true}).click();expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);await expect.poll(()=>source(page)).toBe(original.replace("SRC='old.png'","SRC='new.png'"));await page.evaluate(()=>(window as any).host.editor.setMode('live'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>source(page)).toBe(original);
});
