import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const value='Before\r\n\r\n<details><summary>Fold</summary><p>Inside <!-- secret --> after</p></details>\r\n\r\n> [!note]- Callout\r\n>\r\n> Body <!-- nested --> after\r\n\r\n```js\r\nconst value = 1\r\n```\r\n\r\nEnd';
const reader='[aria-label="Markdown Reader"]';
async function mode(page:Page,name:string){await page.evaluate(name=>(window as any).host.editor.setMode(name),name);await page.evaluate(()=>(window as any).host.editor.ready());}
async function boot(page:Page,source=value){await page.goto(url);await page.evaluate(source=>(window as any).host.load(source),source);await mode(page,'reader');}
async function source(page:Page){return page.evaluate(()=>(window as any).host.editor.source);}
async function remember(page:Page){await page.evaluate(()=>{const root=document.querySelector('[aria-label="Markdown Reader"]')!;(window as any).displayNodes={details:root.querySelector('details'),callout:root.querySelector('blockquote.callout'),code:root.querySelector('.code-block')};});}
async function unchangedNodes(page:Page){expect(await page.evaluate(()=>{const root=document.querySelector('[aria-label="Markdown Reader"]')!,old=(window as any).displayNodes;return {details:root.querySelector('details')===old.details,callout:root.querySelector('blockquote.callout')===old.callout,code:root.querySelector('.code-block')===old.code};})).toEqual({details:true,callout:true,code:true});}
async function locate(page:Page,term:string){
 await page.evaluate(()=>{const h=(window as any).host;document.body.addEventListener('tegg-inspection-locate',event=>{const detail=(event as CustomEvent).detail;(window as any).located=detail;h.editor.locateSourceRange(detail.ownerRange);},{once:true});h.ui.openInspection({projection:'reader'});});
 const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await panel.getByLabel('Search document inspection',{exact:true}).fill(term);const item=panel.locator('.tegg-inspection-entries>details');await expect(item).toHaveCount(1);await item.locator('summary').click();await item.getByRole('button',{name:/^Locate and expand \d+ levels$/}).click();await expect(panel).toBeHidden();
}
test('mounted Reader and unchanged reused blocks share actual Live Details, Callout and code-wrap state with original CRLF bytes',async({page})=>{
 await boot(page);await remember(page);await mode(page,'live');
 await page.locator('.cm-live-html-block details > summary').click();await page.locator('.callout-editor-header .callout-fold').click();await page.locator('.cm-content .md-code-actions button[aria-label="Wrap lines"]').click();
 // The already mounted Reader paints the same session even while the Live surface owns focus.
 await expect(page.locator(reader+' details')).toHaveAttribute('open','');await expect(page.locator(reader+' blockquote.callout')).toHaveAttribute('data-callout-expanded','true');await expect(page.locator(reader+' .md-code-wrap-action')).toHaveAttribute('aria-pressed','true');
 expect(await source(page)).toBe(value);await mode(page,'reader');await unchangedNodes(page);await expect(page.locator(reader+' .code-block pre')).toHaveCSS('white-space','pre-wrap');
 await mode(page,'source');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);expect(await source(page)).toBe(value);
});
test('same-line pretext editing rebases actual retained CRLF owners before Inspector Locate and creates no additional source undo',async({page})=>{
 await boot(page);await remember(page);await mode(page,'source');await page.evaluate(()=>{const view=(window as any).host.editor.view;view.dispatch({changes:{from:6,insert:' longer'}});});const next=value.replace('Before','Before longer');expect(await source(page)).toBe(next);await mode(page,'reader');await unchangedNodes(page);
 const selection=await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return {anchor:s.anchor,head:s.head};});
 await locate(page,'secret');await expect(page.locator(reader+' details')).toHaveAttribute('open','');expect(await page.evaluate(()=>(window as any).located.sourceRange)).toEqual({from:next.indexOf('<!-- secret -->'),to:next.indexOf('<!-- secret -->')+'<!-- secret -->'.length});expect(await page.evaluate(()=>document.activeElement?.textContent)).toContain('Inside');
 await locate(page,'nested');await expect(page.locator(reader+' blockquote.callout')).toHaveAttribute('data-callout-expanded','true');expect(await page.evaluate(()=>document.activeElement?.textContent)).toContain('Body');expect(await source(page)).toBe(next);expect(await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return {anchor:s.anchor,head:s.head};})).toEqual(selection);await unchangedNodes(page);
 await mode(page,'live');await page.locator('.cm-content .md-code-actions button[aria-label="Wrap lines"]').click();await expect(page.locator(reader+' .md-code-wrap-action')).toHaveAttribute('aria-pressed','true');await mode(page,'reader');await unchangedNodes(page);
 await mode(page,'source');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(value);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
test('actual nested HTML table Details and footnote code-wrap paint the already mounted Reader without a source transaction',async({page})=>{
 const nested='Before\r\n\r\n<table><tr><td><details><summary>Outer</summary><details><summary>Inner</summary><p>Text</p></details></details></td></tr></table>\r\n\r\nText[^n]\r\n\r\n[^n]: ```js\r\n    long code\r\n    ```\r\n\r\nEnd';
 await boot(page,nested);await mode(page,'live');const table=page.locator('.cm-live-html-table');await table.locator('details > summary').first().click();await table.locator('details > details > summary').click();await expect(page.locator(reader+' details')).toHaveCount(2);for(const detail of await page.locator(reader+' details').all())await expect(detail).toHaveAttribute('open','');
 await page.locator('.cm-live-footnotes .md-code-actions button[aria-label="Wrap lines"]').click();await expect(page.locator(reader+' .footnote-body .md-code-wrap-action')).toHaveAttribute('aria-pressed','true');expect(await source(page)).toBe(nested);
 await mode(page,'reader');for(const detail of await page.locator(reader+' details').all())await expect(detail).toHaveAttribute('open','');await expect(page.locator(reader+' .footnote-body .code-block pre')).toHaveCSS('white-space','pre-wrap');expect(await source(page)).toBe(nested);await mode(page,'source');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
test('reused nested Callout and HTML Details expand both actual ancestors through Inspector Locate without revealing comment source',async({page})=>{
 const nested='Before\r\n\r\n> [!note]- Outer\r\n>\r\n> <details><summary>Inner</summary><p>Nested <!-- deep --> body</p></details>\r\n\r\nEnd';await boot(page,nested);await remember(page);await mode(page,'source');await page.evaluate(()=>{(window as any).host.editor.view.dispatch({changes:{from:6,insert:' longer'}});});const next=nested.replace('Before','Before longer');await mode(page,'reader');expect(await page.evaluate(()=>{const root=document.querySelector('[aria-label="Markdown Reader"]')!,old=(window as any).displayNodes;return root.querySelector('details')===old.details&&root.querySelector('blockquote.callout')===old.callout;})).toBe(true);
 const selection=await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return {anchor:s.anchor,head:s.head};});await locate(page,'deep');await expect(page.locator(reader+' blockquote.callout')).toHaveAttribute('data-callout-expanded','true');await expect(page.locator(reader+' details')).toHaveAttribute('open','');await expect(page.locator(reader)).toContainText('Nested  body');await expect(page.locator(reader)).not.toContainText('<!-- deep -->');expect(await page.evaluate(()=>(window as any).located.expandedCount)).toBe(2);expect(await page.evaluate(()=>(window as any).located.sourceRange)).toEqual({from:next.indexOf('<!-- deep -->'),to:next.indexOf('<!-- deep -->')+'<!-- deep -->'.length});expect(await page.evaluate(()=>document.activeElement?.textContent)).toContain('Nested');expect(await source(page)).toBe(next);expect(await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return {anchor:s.anchor,head:s.head};})).toEqual(selection);
 await mode(page,'source');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(nested);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
test('Live state changes follow mapped session identity while the hidden retained Reader still has its preceding source projection',async({page})=>{
 await boot(page);await remember(page);await mode(page,'source');await page.evaluate(()=>{(window as any).host.editor.view.dispatch({changes:{from:6,insert:' longer'}});});const next=value.replace('Before','Before longer');await mode(page,'live');
 await page.locator('.cm-live-html-block details > summary').click();await page.locator('.callout-editor-header .callout-fold').click();await page.locator('.cm-content .md-code-actions button[aria-label="Wrap lines"]').click();await expect(page.locator(reader+' details')).toHaveAttribute('open','');await expect(page.locator(reader+' blockquote.callout')).toHaveAttribute('data-callout-expanded','true');await expect(page.locator(reader+' .md-code-wrap-action')).toHaveAttribute('aria-pressed','true');expect(await source(page)).toBe(next);
 await mode(page,'reader');await unchangedNodes(page);await expect(page.locator(reader+' details')).toHaveAttribute('open','');await page.locator(reader+' .md-code-wrap-action').click();await expect(page.locator(reader+' .md-code-wrap-action')).toHaveAttribute('aria-pressed','false');await mode(page,'live');await expect(page.locator('.cm-content .md-code-area textarea')).toHaveAttribute('wrap','off');expect(await source(page)).toBe(next);await mode(page,'source');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(value);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
