import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source='<!-- Exact hidden comment -->\n\n# Heading {#section}\n\n[shared]: old.md "Keep"\n\n[Current][shared]';
async function boot(page:Page,value=source,mode='source'){
 await page.goto(url);await page.evaluate(({value,mode})=>{const h=(window as any).host;h.load(value,{copyText:(text:string)=>{(window as any).copied=text;return new Promise<void>((resolve,reject)=>{(window as any).ack={resolve,reject};});}});h.editor.setMode(mode);}, {value,mode});await page.evaluate(()=>(window as any).host.editor.ready());
}
test('readonly document inspection searches actual declarations and Copy waits for ACK without changing source or history',async({page})=>{
 await boot(page);expect(await page.evaluate(()=>(window as any).host.ui.openInspection())).toBe(true);const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await expect(panel).toBeVisible();expect(await panel.evaluate(node=>node.getBoundingClientRect().width)).toBe(560);await expect(panel.getByRole('button',{name:'Done',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).host.ui.captureActiveDrafts().length)).toBe(0);
 const search=panel.getByLabel('Search document inspection',{exact:true});await search.fill('Exact hidden');const item=panel.locator('.tegg-inspection-entries>details');await expect(item).toHaveCount(1);await item.locator('summary').click();await expect(item.getByLabel('Original declaration',{exact:true})).toHaveText('<!-- Exact hidden comment -->');await item.getByRole('button',{name:'Copy',exact:true}).click();expect(await page.evaluate(()=>(window as any).copied)).toBe('<!-- Exact hidden comment -->');await expect(panel.locator('[role="status"]')).not.toContainText('Copied');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);
 await page.evaluate(()=>(window as any).ack.resolve());await expect(panel.locator('[role="status"]')).toHaveText('Copied');await panel.getByRole('button',{name:'Close',exact:true}).click();expect(await page.evaluate(()=>(window as any).host.ui.inspectionElement)).toBeNull();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
test('Reader Locate expands the actual collapsed session and focuses a visible source owner without switching mode or author syntax',async({page})=>{
 const value='> [!note]- Collapsed\n>\n> Body <!-- secret -->\n\nTail';await boot(page,value,'reader');await expect(page.locator('blockquote.callout')).toHaveAttribute('data-callout-expanded','false');
 await page.evaluate(()=>{const h=(window as any).host;document.body.addEventListener('tegg-inspection-locate',event=>{const detail=(event as CustomEvent).detail;(window as any).located=detail;h.editor.locateSourceRange(detail.ownerRange);});h.ui.openInspection({projection:'reader'});});
 const panel=page.getByRole('dialog',{name:'Document inspection',exact:true}),search=panel.getByLabel('Search document inspection',{exact:true});await search.fill('secret');const item=panel.locator('.tegg-inspection-entries>details');await expect(item).toHaveCount(1);await item.locator('summary').click();await item.getByRole('button',{name:'Locate and expand 1 levels',exact:true}).click();await expect(panel).toBeHidden();await expect(page.locator('blockquote.callout')).toHaveAttribute('data-callout-expanded','true');expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('reader');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>(window as any).located)).toMatchObject({sourceRange:{from:value.indexOf('<!--'),to:value.indexOf('-->')+3},expandedCount:1});expect(await page.evaluate(()=>{const current=document.activeElement;return current?.closest('[aria-label="Markdown Reader"]')!==null;})).toBe(true);
 await page.evaluate(()=>(window as any).host.editor.setMode('source'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);
});
test('inspection refuses dirty object and IME attempts without replay, then revokes old panel authority on close and reuse',async({page})=>{
 const value='$x$\n\n<!-- secret -->\n\nBody';await boot(page,value);await page.evaluate(()=>(window as any).host.ui.openObject('math',{from:0,to:3}));const object=page.getByRole('dialog',{name:'Edit formula',exact:true}),field=object.getByLabel('Formula source',{exact:true});await field.fill('local');await field.focus();await field.dispatchEvent('compositionstart');expect(await page.evaluate(()=>(window as any).host.ui.openInspection())).toBe(false);await expect(field).toBeFocused();expect(await page.evaluate(()=>(window as any).host.ui.inspectionElement)).toBeNull();await field.dispatchEvent('compositionend');expect(await page.evaluate(()=>(window as any).host.ui.openInspection())).toBe(false);const guard=object.getByRole('dialog',{name:'Unsaved changes',exact:true});await expect(guard).toBeVisible();await guard.getByRole('button',{name:'Discard changes',exact:true}).click();await expect(object).toBeHidden();expect(await page.evaluate(()=>(window as any).host.ui.inspectionElement)).toBeNull();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);
 expect(await page.evaluate(()=>(window as any).host.ui.openInspection())).toBe(true);const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await panel.getByLabel('Search document inspection',{exact:true}).fill('secret');await panel.locator('.tegg-inspection-entries summary').click();await page.evaluate(()=>(window as any).host.editor.view.dispatch({changes:{from:(window as any).host.editor.source.length,insert:' external'}}));await panel.getByRole('button',{name:'Locate',exact:true}).click();await expect(panel).toBeVisible();await expect(panel.locator('[role="status"]')).toHaveText('The document changed. Reopen document inspection.');await panel.getByRole('button',{name:'Close',exact:true}).click();await page.evaluate(()=>(window as any).host.ui.openSearch());expect(await page.evaluate(()=>(window as any).host.ui.inspectionElement)).toBeNull();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value+' external');
});
test('mobile inspection uses independent system chrome with no completion action and keeps large text controls reachable',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage();try{await boot(page);await page.evaluate(()=>{const h=(window as any).host;h.ui.openInspection();h.ui.element.style.setProperty('--tegg-ui-action-size','53px');h.ui.element.style.setProperty('--tegg-ui-action-line','62px');h.ui.element.style.setProperty('--tegg-ui-input-size','53px');h.ui.element.style.setProperty('--tegg-ui-input-line','79.5px');});const panel=page.getByRole('dialog',{name:'Document inspection',exact:true}),close=panel.getByRole('button',{name:'Close',exact:true});await expect(close).toHaveCSS('font-size','53px');await expect(close).toHaveCSS('line-height','62px');await expect(panel.locator('header button')).toHaveText(['Close']);await expect(panel.locator('footer button')).toHaveCount(0);await expect(panel.getByLabel('Search document inspection',{exact:true})).toHaveCSS('font-size','53px');for(const width of [390,640])for(const zoom of [1,4]){await page.setViewportSize({width,height:844});await page.evaluate(zoom=>document.documentElement.style.setProperty('--reader-font-scale',String(zoom)),zoom);const box=await close.boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44);expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(width);expect(box!.y+box!.height).toBeLessThanOrEqual(844);expect(await panel.evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true);}await close.click();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);}finally{await context.close();}
});

test('original CRLF inspection Copy and Reader location preserve raw bytes and expand the matching real session key',async({page})=>{
 const value='Intro\r\n\r\n<!-- First\r\nSecond -->\r\n\r\n> [!note]- Title\r\n>\r\n> Inside <!-- target -->\r\n\r\nTail';await boot(page,value,'reader');await page.evaluate(()=>{const h=(window as any).host;document.body.addEventListener('tegg-inspection-locate',event=>{(window as any).located=(event as CustomEvent).detail;h.editor.locateSourceRange((event as CustomEvent).detail.ownerRange);});h.ui.openInspection({projection:'reader'});});
 const panel=page.getByRole('dialog',{name:'Document inspection',exact:true}),search=panel.getByLabel('Search document inspection',{exact:true});await search.fill('First');let item=panel.locator('.tegg-inspection-entries>details');await expect(item).toHaveCount(1);await item.locator('summary').click();await item.getByRole('button',{name:'Copy',exact:true}).click();expect(await page.evaluate(()=>(window as any).copied)).toBe('<!-- First\r\nSecond -->');await page.evaluate(()=>(window as any).ack.resolve());await expect(panel.locator('[role="status"]')).toHaveText('Copied');await search.fill('target');item=panel.locator('.tegg-inspection-entries>details');await expect(item).toHaveCount(1);await item.locator('summary').click();await item.getByRole('button',{name:'Locate and expand 1 levels',exact:true}).click();await expect(page.locator('blockquote.callout')).toHaveAttribute('data-callout-expanded','true');expect(await page.evaluate(()=>(window as any).located)).toMatchObject({coordinates:'source',sourceRange:{from:value.indexOf('<!-- target'),to:value.indexOf('<!-- target')+'<!-- target -->'.length},expandedCount:1});expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>document.activeElement?.textContent)).toContain('Inside');await page.evaluate(()=>(window as any).host.editor.setMode('source'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);
});

test('inactive multiline comments have zero block height and preserve mixed prose in one line with exact source positions',async({page})=>{
 await boot(page,'Intro\n\n<!-- First\nSecond -->\n\nTail','live');const hidden=page.locator('.cm-live-collapsed-source');expect(await hidden.count()).toBeGreaterThan(0);for(const line of await hidden.all())expect((await line.boundingBox())!.height).toBe(0);await expect(page.locator('.cm-content')).not.toContainText('First');await expect(page.locator('.cm-content')).not.toContainText('Second');const visible=await page.locator('.cm-line[data-block-role="paragraph"]').evaluateAll(rows=>rows.filter(row=>row.getBoundingClientRect().height>0).map(row=>row.textContent));expect(visible).toEqual(['Intro','Tail']);await page.evaluate(()=>(window as any).host.editor.setMode('reader'));await expect(page.locator('[aria-label="Markdown Reader"] p')).toHaveText(['Intro','Tail']);
 const value='Before <!-- First\nSecond --> after\n\nTail';await boot(page,value,'live');const live=await page.evaluate(()=>{const h=(window as any).host,view=h.editor.view,row=[...view.contentDOM.querySelectorAll('.cm-line')].find(node=>node.textContent?.includes('Before'))!,walker=document.createTreeWalker(row,NodeFilter.SHOW_TEXT),positions:{text:string;from:number}[]=[];let node:Node|null;while(node=walker.nextNode())if(node.textContent?.trim())positions.push({text:node.textContent,from:view.posAtDOM(node,0)});return {source:h.editor.source,text:row.textContent,height:row.getBoundingClientRect().height,positions};});expect(live.source).toBe(value);expect(live.text).toBe('Before  after');expect(live.positions).toEqual([{text:'Before ',from:0},{text:' after',from:value.indexOf(' after')}]);await page.evaluate(()=>{const view=(window as any).host.editor.view;view.focus();view.dispatch({selection:{anchor:view.state.doc.toString().indexOf('First')}});});await expect(page.locator('.cm-content')).toContainText('First');await expect(page.locator('.cm-content')).toContainText('Second');await page.evaluate(()=>{const view=(window as any).host.editor.view;view.dispatch({selection:{anchor:view.state.doc.length}});});await expect(page.locator('.cm-content')).not.toContainText('First');await page.evaluate(()=>(window as any).host.editor.setMode('reader'));const paragraph=page.locator('[aria-label="Markdown Reader"] p').first();await expect(paragraph).toHaveText('Before  after');expect(Math.abs((await paragraph.boundingBox())!.height-live.height)).toBeLessThan(1);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);await page.evaluate(()=>(window as any).host.editor.setMode('source'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});


test('Live Locate synchronizes expanded Callout body and header without revealing a hidden comment or moving the prose selection',async({page})=>{
 const value='> [!note]- Title\n>\n> Before <!-- secret --> after\n\nTail';await boot(page,value,'live');const header=page.locator('.callout-editor-header'),fold=header.locator('.callout-fold');await expect(header).toHaveAttribute('data-callout-expanded','false');await expect(fold).toHaveAttribute('aria-expanded','false');const selection=await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return {anchor:s.anchor,head:s.head};});
 await page.evaluate(()=>{const h=(window as any).host;document.body.addEventListener('tegg-inspection-locate',event=>{(window as any).located=(event as CustomEvent).detail;const view=h.editor.view;view.dispatch({selection:view.state.selection,scrollIntoView:true});});h.ui.openInspection({projection:'live'});});const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await panel.getByLabel('Search document inspection',{exact:true}).fill('secret');const item=panel.locator('.tegg-inspection-entries>details');await item.locator('summary').click();await item.getByRole('button',{name:'Locate and expand 1 levels',exact:true}).click();await expect(panel).toBeHidden();await expect(header).toHaveAttribute('data-callout-expanded','true');await expect(fold).toHaveAttribute('aria-expanded','true');await expect(fold).toHaveAttribute('aria-label','Collapse Callout');await expect(page.locator('.cm-content')).toContainText('Before  after');await expect(page.locator('.cm-content')).not.toContainText('secret');expect(await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return {anchor:s.anchor,head:s.head};})).toEqual(selection);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>(window as any).located.expandedCount)).toBe(1);
 await fold.click();await expect(header).toHaveAttribute('data-callout-expanded','false');await expect(fold).toHaveAttribute('aria-label','Expand Callout');await fold.click();await expect(header).toHaveAttribute('data-callout-expanded','true');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});


test('Live Locate paints already mounted nested Details using matching CRLF session keys without source reveal or selection changes',async({page})=>{
 const value='Intro\r\n\r\n<details><summary>Outer</summary><details><summary>Inner</summary><p>Before <!-- Secret --> after</p></details></details>\r\n\r\nEnd';await boot(page,value,'live');const details=page.locator('.cm-html-direct-editor details');await expect(details).toHaveCount(2);for(const node of await details.all())await expect(node).not.toHaveAttribute('open','');
 const before=await page.evaluate(()=>{const h=(window as any).host,s=h.editor.view.state.selection.main;(window as any).originalDetails=[...document.querySelectorAll('.cm-html-direct-editor details')];document.body.addEventListener('tegg-inspection-locate',event=>{(window as any).located=(event as CustomEvent).detail;const view=h.editor.view;view.dispatch({selection:view.state.selection,scrollIntoView:true});});h.ui.openInspection({projection:'live'});return{anchor:s.anchor,head:s.head};});
 const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await panel.getByLabel('Search document inspection',{exact:true}).fill('Secret');const item=panel.locator('.tegg-inspection-entries>details');await item.locator('summary').click();await item.getByRole('button',{name:'Locate and expand 2 levels',exact:true}).click();await expect(panel).toBeHidden();for(const node of await details.all())await expect(node).toHaveAttribute('open','');await expect(details.last().locator('p')).toBeVisible();await expect(details.last().locator('p')).toHaveText('Before  after');await expect(page.locator('.cm-content')).not.toContainText('Secret');
 expect(await page.evaluate(()=>[...document.querySelectorAll('.cm-html-direct-editor details')].every((node,index)=>node===(window as any).originalDetails[index]))).toBe(true);expect(await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return{anchor:s.anchor,head:s.head};})).toEqual(before);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>(window as any).located)).toMatchObject({coordinates:'source',sourceRange:{from:value.indexOf('<!--'),to:value.indexOf('-->')+3},expandedCount:2});expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
 await details.last().locator(':scope > summary').click();await expect(details.last()).not.toHaveAttribute('open','');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);
});

test('Live Locate paints mounted Details inside a selected HTML table cell without creating a cell draft or author open attribute',async({page})=>{
 const value='Intro\r\n\r\n<table><tr><td><details><summary>Cell</summary><p>Before <!-- Cell secret --> after</p></details></td><td>untouched</td></tr></table>\r\n\r\nEnd';await boot(page,value,'live');const cell=page.locator('.cm-live-html-table td').first(),details=cell.locator('details');await expect(details).not.toHaveAttribute('open','');await cell.click({position:{x:2,y:2}});await expect(cell).not.toHaveAttribute('contenteditable','true');await expect(details).not.toHaveAttribute('open','');
 const before=await page.evaluate(()=>{const h=(window as any).host,s=h.editor.view.state.selection.main;(window as any).originalCell=document.querySelector('.cm-live-html-table td');h.ui.openInspection({projection:'live'});return{anchor:s.anchor,head:s.head};});const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await panel.getByLabel('Inspection type',{exact:true}).selectOption('comment');await panel.getByLabel('Search document inspection',{exact:true}).fill('Cell secret');const item=panel.locator('.tegg-inspection-entries>details');await item.locator('summary').click();await item.getByRole('button',{name:'Locate and expand 1 levels',exact:true}).click();await expect(details).toHaveAttribute('open','');await expect(details.locator('p')).toBeVisible();await expect(details.locator('p')).toHaveText('Before  after');expect(await cell.evaluate(node=>node===(window as any).originalCell)).toBe(true);expect(await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return{anchor:s.anchor,head:s.head};})).toEqual(before);await expect(cell).not.toHaveAttribute('contenteditable','true');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});


for(const mode of ['reader','live'])test(`${mode} inspection expands the actual scoped footnote Details using original CRLF body ranges without duplicating or rewriting its definition`,async({page})=>{
 const value='Use[^n]\r\n\r\n[^n]: <details><summary>Folded</summary><p>Before <!-- Secret --> after</p></details>';await boot(page,value,mode);const scope=mode==='reader'?page.locator('.tegg-reader .footnote-body'):page.locator('.cm-live-footnotes .footnote-body'),details=scope.locator('details');await expect(details).toHaveCount(1);await expect(details).not.toHaveAttribute('open','');if(mode==='live')await expect(page.locator('.cm-html-direct-editor details')).toHaveCount(1);
 const before=await page.evaluate(({mode})=>{const h=(window as any).host,s=h.editor.view.state.selection.main;(window as any).scopedDetails=document.querySelector(mode==='reader'?'.tegg-reader .footnote-body details':'.cm-live-footnotes .footnote-body details');document.body.addEventListener('tegg-inspection-locate',event=>{const detail=(event as CustomEvent).detail;(window as any).located=detail;if(mode==='reader')h.editor.locateSourceRange(detail.ownerRange);else{const view=h.editor.view;view.dispatch({selection:view.state.selection,scrollIntoView:true});}});h.ui.openInspection({projection:mode});return{anchor:s.anchor,head:s.head};},{mode});
 const panel=page.getByRole('dialog',{name:'Document inspection',exact:true});await panel.getByLabel('Inspection type',{exact:true}).selectOption('comment');await panel.getByLabel('Search document inspection',{exact:true}).fill('Secret');const item=panel.locator('.tegg-inspection-entries>details');await expect(item).toHaveCount(1);await item.locator('summary').click();await item.getByRole('button',{name:'Locate and expand 1 levels',exact:true}).click();await expect(panel).toBeHidden();await expect(details).toHaveAttribute('open','');await expect(details.locator('p')).toBeVisible();await expect(details.locator('p')).toHaveText('Before  after');expect(await details.evaluate(node=>node===(window as any).scopedDetails)).toBe(true);expect(await page.evaluate(()=>{const s=(window as any).host.editor.view.state.selection.main;return{anchor:s.anchor,head:s.head};})).toEqual(before);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);expect(await page.evaluate(()=>(window as any).located)).toMatchObject({coordinates:'source',sourceRange:{from:value.indexOf('<!--'),to:value.indexOf('-->')+3},ownerRange:{from:value.indexOf('<p>'),to:value.indexOf('</p>')+4},expandedCount:1});if(mode==='reader')expect(await page.evaluate(()=>!!document.activeElement?.closest('.tegg-reader .footnote-body'))).toBe(true);await page.evaluate(()=>(window as any).host.editor.setMode('source'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(value);
});
