import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_HTML_TABLE_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const original="before\n\n<table class='retain'><tbody><tr><td rowspan='2'><p data-value='exact'>原<strong>文</strong></p></td><td>C</td></tr><tr><td>D</td></tr></tbody></table>\n\nafter";
async function load(page:Page){await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),original);await expect(page.locator('.cm-live-html-table')).toBeVisible();}
async function source(page:Page){return page.evaluate(()=>(window as any).host.editor.source as string);}
test('HTML cell focus and rich draft cancel preserve content geometry and exact source',async({page})=>{
 await load(page);const cell=page.locator('.cm-live-html-table td').first(),before=await cell.boundingBox();await cell.click();expect(await source(page)).toBe(original);await cell.press('F2');expect(await cell.boundingBox()).toEqual(before);await expect(cell).toHaveAttribute('contenteditable','true');await cell.locator('strong').evaluate(node=>{node.textContent='未提交';node.dispatchEvent(new InputEvent('input',{bubbles:true}));});expect(await source(page)).toBe(original);await cell.press('Escape');await expect(cell).toHaveText('原文');expect(await source(page)).toBe(original);
});
test('valid HTML draft commits before switching Reader and one parent Undo restores source bytes',async({page})=>{
 await load(page);const cell=page.locator('.cm-live-html-table td').first();await cell.dblclick();await cell.locator('strong').evaluate(node=>{node.textContent='新';node.dispatchEvent(new InputEvent('input',{bubbles:true}));});expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);expect(await source(page)).toBe(original.replace('<strong>文</strong>','<strong>新</strong>'));await page.evaluate(()=>(window as any).host.editor.setMode('live'));await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(original);
});
test('HTML range closure contains whole merged cells and clearing never removes spans',async({page})=>{
 await load(page);const cells=page.locator('.cm-live-html-table td');await cells.first().click();await cells.nth(2).click({modifiers:['Shift']});await expect(page.locator('.md-html-cell-selected')).toHaveCount(3);await cells.first().click({modifiers:['Shift']});await expect(page.locator('.md-html-cell-selected')).toHaveCount(1);await cells.nth(2).click({modifiers:['Shift']});await expect(page.locator('.md-html-cell-selected')).toHaveCount(3);await page.keyboard.press('Backspace');await expect.poll(()=>source(page)).toContain("<td rowspan='2'></td>");expect(await source(page)).toContain("<table class='retain'>");await page.keyboard.press('ControlOrMeta+z');expect(await source(page)).toBe(original);await expect(page.locator('.md-html-cell-selected')).toHaveCount(3);
});

async function loadTable(page:Page,value:string){await page.goto(url);await page.evaluate(text=>(window as any).host.load(text),value);await expect(page.locator('.cm-live-html-table')).toBeVisible();}
async function menu(page:Page,label:string){await page.locator('.md-html-table-controls summary').click();await page.locator('.md-html-table-controls button').filter({hasText:new RegExp('^'+label+'$')}).click();}
async function endOf(page:Page,selector:string){await page.locator(selector).evaluate(node=>{const range=document.createRange();range.selectNodeContents(node);range.collapse(false);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});}
test('real HTML draft local Undo and Redo retain rich source, Return commits down, final Tab exits',async({page})=>{
 const value="before\n\n<table><tr><td data-x='keep'><p>A<strong>B</strong></p></td><td>C</td></tr><tr><td>D</td><td>E</td></tr></table>\n\nafter";await loadTable(page,value);const cells=page.locator('.cm-live-html-table td'),first=cells.first();await first.dblclick();await endOf(page,'.cm-live-html-table td strong');await page.keyboard.type('X');await expect(first).toHaveText('ABX');expect(await source(page)).toBe(value);
 await page.keyboard.press('ControlOrMeta+z');await expect(first).toHaveText('AB');expect(await source(page)).toBe(value);await page.keyboard.press('ControlOrMeta+Shift+z');await expect(first).toHaveText('ABX');await page.keyboard.press('Enter');await expect(cells.nth(2)).toBeFocused();expect(await source(page)).toBe(value.replace('<strong>B</strong>','<strong>BX</strong>'));
 await cells.last().click();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.classList.contains('cm-content'))).toBe(true);expect(await source(page)).toBe(value.replace('<strong>B</strong>','<strong>BX</strong>'));await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(value);
});
test('real HTML code subtree Tab, Shift Tab, Return and Escape precede parent cell commands',async({page})=>{
 const value="before\n\n<table><tr><td><pre><code>x</code></pre></td><td>next</td></tr></table>\n\nafter";await loadTable(page,value);const cell=page.locator('.cm-live-html-table td').first(),code=cell.locator('code');await cell.dblclick();await endOf(page,'.cm-live-html-table td code');await page.keyboard.press('Tab');await expect(code).toHaveText('x    ');await page.keyboard.press('Enter');expect(await code.textContent()).toBe('x    \n');await page.keyboard.press('Tab');expect(await code.textContent()).toBe('x    \n    ');await page.keyboard.press('Shift+Tab');expect(await code.textContent()).toBe('x    \n');expect(await source(page)).toBe(value);await page.keyboard.press('Escape');await expect(cell).toHaveAttribute('contenteditable','true');expect(await source(page)).toBe(value);await page.keyboard.press('Escape');await expect(cell).not.toHaveAttribute('contenteditable','true');expect(await source(page)).toBe(value);
});
test('native clipboard ACK preview keeps overflow input until explicit expansion and one Undo',async({page})=>{
 const value="before\n\n<table class='retain'><tr><td>A</td><td>B</td></tr></table>\n\nafter";await loadTable(page,value);await page.evaluate(()=>{document.addEventListener('tegg-read-table',event=>{event.preventDefault();(event as CustomEvent).detail.complete({text:'x\ty\nz\tw'});});});await page.locator('.cm-live-html-table td').last().click();await menu(page,'Paste');const review=page.locator('.md-html-table-review');await expect(review).toBeVisible();await expect(review).toContainText('2 rows and 3 columns');expect(await source(page)).toBe(value);await review.getByRole('button',{name:'Cancel',exact:true}).click();expect(await source(page)).toBe(value);await menu(page,'Paste');await review.getByRole('button',{name:'Expand and paste',exact:true}).click();expect(await source(page)).toContain('<td>x</td><td>y</td>');await page.evaluate(()=>(window as any).host.editor.setMode('source'));await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(value);
});


test('HTML table inline-code state toggles only that source-backed draft and preserves local history',async({page})=>{
 const value="before\n\n<table class='keep'><tr><td data-x='exact'><p>start <code data-role='author'>literal</code> end</p></td><td>unchanged</td></tr></table>\n\nafter";await loadTable(page,value);const cell=page.locator('.cm-live-html-table td').first();await cell.dblclick();await cell.locator('code').evaluate(node=>{const range=document.createRange();range.selectNodeContents(node);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});
 expect(await page.evaluate(()=>(window as any).host.editor.state.code)).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.commandStatus('bold').enabled)).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.commandStatus('code').enabled)).toBe(true);
 expect(await page.evaluate(()=>(window as any).host.editor.command('code'))).toBe(true);await expect(cell.locator('code')).toHaveCount(0);expect(await source(page)).toBe(value);
 await page.keyboard.press('ControlOrMeta+z');await expect(cell.locator('code')).toHaveAttribute('data-role','author');expect(await source(page)).toBe(value);await page.keyboard.press('ControlOrMeta+Shift+z');await expect(cell.locator('code')).toHaveCount(0);await page.keyboard.press('Enter');expect(await source(page)).toBe(value.replace("<code data-role='author'>literal</code>",'literal'));await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(value);
});
test('HTML table title-only details Return provides a real source-free caret and shares expansion between modes',async({page})=>{
 const value="before\n\n<table class='keep'><tr><td data-x='exact'><details><summary>Title</summary></details></td><td>unchanged</td></tr></table>\n\nafter";await loadTable(page,value);const cell=page.locator('.cm-live-html-table td').first();await cell.dblclick();await cell.locator('summary').evaluate(node=>{const range=document.createRange();range.selectNodeContents(node);range.collapse(false);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});await page.keyboard.press('Enter');expect(await source(page)).toBe(value);await expect(cell.locator('details')).toHaveAttribute('open','');await page.keyboard.type('Body');expect(await source(page)).toBe(value);await page.keyboard.press('Enter');const edited=value.replace('<summary>Title</summary>','<summary>Title</summary><p>Body</p>');expect(await source(page)).toBe(edited);
 await cell.locator('summary').click();await expect(cell.locator('details')).not.toHaveAttribute('open','');expect(await source(page)).toBe(edited);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);await expect(page.locator('.tegg-reader details:visible')).not.toHaveAttribute('open','');await page.evaluate(()=>(window as any).host.editor.setMode('live'));await expect(page.locator('.cm-live-html-table td details')).not.toHaveAttribute('open','');expect(await source(page)).toBe(edited);await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(value);
});


test('HTML table missing-summary fallback follows locale and never inserts a placeholder into source',async({page})=>{
 const value="before\n\n<table class='keep'><tr><td data-x='exact'><details><p>Body</p></details></td><td>unchanged</td></tr></table>\n\nafter";await loadTable(page,value);const cell=page.locator('.cm-live-html-table td').first(),summary=cell.locator('summary');await expect(summary).toHaveAttribute('data-tegg-temporary','true');await page.evaluate(()=>(window as any).host.editor.setUI({locale:'zh-CN'}));await expect(summary).toHaveAttribute('aria-label','详情');expect(await summary.evaluate(node=>getComputedStyle(node,'::after').content)).toBe('"详情"');expect(await source(page)).toBe(value);await cell.focus();await cell.press('F2');await expect(cell).toHaveAttribute('contenteditable','true');await summary.click();await expect(cell.locator('details')).toHaveAttribute('open','');const body=cell.locator('p');await expect(body).toBeVisible();await body.click();await body.evaluate(node=>{const range=document.createRange();range.selectNodeContents(node);range.collapse(false);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});await page.keyboard.type('X');await expect(body).toHaveText('BodyX');expect(await source(page)).toBe(value);await page.keyboard.press('Enter');expect(await source(page)).toBe(value.replace('Body','BodyX'));expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);await expect(page.locator('.tegg-reader details summary')).toHaveText('详情');expect(await source(page)).not.toContain('<summary');
});

test('HTML code selected-line indentation preserves code, local history and one parent transaction',async({page})=>{
 const value="before\n\n<table class='keep'><tr><td data-x='exact'><pre data-role='author'><code class='retain'>alpha\nbeta\ngamma</code></pre></td><td>unchanged</td></tr></table>\n\nafter";await loadTable(page,value);const cell=page.locator('.cm-live-html-table td').first(),code=cell.locator('code');await cell.dblclick();await code.evaluate(node=>{const text=node.firstChild!,range=document.createRange();range.setStart(text,0);range.setEnd(text,11);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});
 expect(await page.evaluate(()=>(window as any).host.editor.state.inlineFormattingEnabled)).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.command('bold'))).toBe(false);await page.keyboard.press('Tab');expect(await code.textContent()).toBe('    alpha\n    beta\ngamma');expect(await source(page)).toBe(value);await page.keyboard.press('Shift+Tab');expect(await code.textContent()).toBe('alpha\nbeta\ngamma');await page.keyboard.press('ControlOrMeta+z');expect(await code.textContent()).toBe('    alpha\n    beta\ngamma');expect(await source(page)).toBe(value);await page.keyboard.press('ControlOrMeta+Shift+z');expect(await code.textContent()).toBe('alpha\nbeta\ngamma');await page.keyboard.press('Tab');expect(await code.textContent()).toBe('    alpha\n    beta\ngamma');expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);expect(await source(page)).toBe(value.replace('alpha\nbeta','    alpha\n    beta'));await page.evaluate(()=>(window as any).host.editor.setMode('live'));await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(value);
});
