import {test,expect} from '@playwright/test';
const url=process.env.TEGG_LIVE_LINK_CONTRACT_URL??'http://127.0.0.1:18930/reliable.html';
const raw="Caret A\n\n<table class='keep'><tr><td><p>Before <a href='https://example.com/?x=1&amp;y=2' rel='author'>A&amp;B</a> after</p></td><td>next</td></tr></table>\n\nEnd";
test('default HTML controls preserve the grid while touch targets and the complete More menu stay reachable',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));try{
 await page.goto(url);await page.evaluate(raw=>{window.host.load(raw);window.host.editor.view.dispatch({selection:{anchor:2}});window.host.editor.view.focus();},raw);
 const state=()=>page.evaluate(()=>{const e=window.host.editor;return {source:e.source,selection:e.view.state.selection.main.toJSON(),sequence:e.snapshot().sequence,undo:e.state.canUndo,redo:e.state.canRedo};}),before=await state(),table=page.locator('#editor table'),cell=table.locator('td').first(),link=cell.locator('a'),grid=await table.boundingBox();await link.tap();await cell.press('F2');await expect(cell).toHaveAttribute('contenteditable','true');expect(await table.boundingBox()).toEqual(grid);
 const controls=page.locator('.md-html-table-controls');for(const label of ['Cancel','Done','Line break']){const button=controls.getByRole('button',{name:label,exact:true});await expect(button).toBeVisible();expect(await button.evaluate(node=>{const r=node.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.width>=44&&r.height>=44&&!!hit&&node.contains(hit);})).toBe(true);}
 expect(await link.evaluate(node=>{const r=node.getBoundingClientRect();return node.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);await controls.locator('summary').tap();const menu=controls.locator('details > div');await expect(menu).toBeVisible();const count=await menu.getByRole('button').count();expect(count).toBe(17);for(let i=0;i<count;i++){const action=menu.getByRole('button').nth(i);await action.scrollIntoViewIfNeeded();expect(await action.evaluate(node=>{const r=node.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.height>=44&&r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&!!hit&&node.contains(hit);})).toBe(true);}await controls.locator('summary').tap();await controls.getByRole('button',{name:'Cancel',exact:true}).tap();expect(await state()).toEqual(before);expect(await table.boundingBox()).toEqual(grid);expect(errors).toEqual([]);
 }finally{await context.close();}
});
