import {test,expect,type Page} from '@playwright/test';
const html='<p data-original="yes">原<strong>文</strong> &amp; text</p>';
const original='before\n\n'+html+'\n\nafter';
async function load(page:Page,source=original){await page.goto(process.env.TEGG_HTML_DIRECT_TEST_URL??'http://127.0.0.1:18930/reliable.html');await page.evaluate(value=>(window as any).host.load(value),source);await expect(page.locator('.cm-html-direct-editor')).toBeVisible();}
async function source(page:Page){return page.evaluate(()=>(window as any).host.editor.source as string);}
async function selectText(page:Page,selector:string,backward=false){await page.locator(selector).evaluate((node,backward)=>{(node.closest('[contenteditable=true]') as HTMLElement).focus();const range=document.createRange();range.selectNodeContents(node);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);if(backward)selection.setBaseAndExtent(range.endContainer,range.endOffset,range.startContainer,range.startOffset);},backward);}
test('direct HTML actual input retains caret and source attributes across repeated dispatches and parent Undo',async({page})=>{
 await load(page);await selectText(page,'.cm-html-direct-editor strong');await page.keyboard.type('new');await expect.poll(()=>source(page)).toContain('<strong>new</strong>');await page.keyboard.type(' more');await expect.poll(()=>source(page)).toContain('<strong>new more</strong>');expect(await source(page)).toContain('data-original="yes"');expect(await source(page)).toContain('&amp;');expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);await page.evaluate(()=>(window as any).host.editor.setMode('live'));await page.evaluate(()=>(window as any).host.editor.command('undo'));await expect.poll(()=>source(page)).toBe(original);
});
test('direct HTML composition blocks leaving and does not replay an earlier mode switch',async({page})=>{
 await load(page);const wrapper=page.locator('.cm-html-direct-editor');await wrapper.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await wrapper.locator('strong').evaluate(node=>{node.textContent='中文';node.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertCompositionText',isComposing:true}));});expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);expect(await source(page)).toBe(original);await wrapper.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文'})));await expect.poll(()=>source(page)).toContain('<strong>中文</strong>');expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);
});
test('title-only details Return is temporary and fold changes preserve author bytes',async({page})=>{
 const value='before\n\n<details><summary>Title</summary></details>\n\nafter';await load(page,value);await selectText(page,'.cm-html-direct-editor summary');await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');expect(await source(page)).toBe(value);await expect(page.locator('details:visible')).toHaveAttribute('open','');await page.keyboard.type('Body');await expect.poll(()=>source(page)).toContain('<details><summary>Title</summary><p>Body</p></details>');await page.locator('.cm-html-direct-editor summary').click();expect(await source(page)).not.toContain('<details open');await page.evaluate(()=>(window as any).host.editor.setMode('reader'));await expect(page.locator('details:visible')).not.toHaveAttribute('open','');await page.evaluate(()=>(window as any).host.editor.setMode('live'));await expect(page.locator('details:visible')).not.toHaveAttribute('open','');
});

test('collapsed details Shift Return keeps the disclosure closed and inserts only a summary hard break',async({page})=>{
 const value='before\n\n<details><summary>Title</summary><p data-x="keep">Body</p></details>\n\nafter',edited=value.replace('Title</summary>','Title<br></summary>');await load(page,value);await selectText(page,'.cm-html-direct-editor summary');await page.keyboard.press('ArrowRight');await expect(page.locator('details:visible')).not.toHaveAttribute('open','');await page.keyboard.press('Shift+Enter');expect(await source(page)).toBe(edited);await expect(page.locator('details:visible')).not.toHaveAttribute('open','');await page.evaluate(()=>(window as any).host.editor.setMode('reader'));await expect(page.locator('details:visible')).not.toHaveAttribute('open','');await page.evaluate(()=>(window as any).host.editor.setMode('live'));await expect(page.locator('details:visible')).not.toHaveAttribute('open','');await page.evaluate(()=>(window as any).host.editor.command('undo'));expect(await source(page)).toBe(value);
});


test('actual HTML activation and document-edge keys keep repeated ASCII input in its author paragraph with one Undo',async({page})=>{
 const value='<p data-x="keep">old</p>\n\nEnd';await load(page,value);await page.locator('.cm-live-html-block').dblclick();const field=page.locator('.cm-html-direct-editor');await field.focus();await page.keyboard.press('ControlOrMeta+End');expect(await page.evaluate(()=>{const range=document.getSelection()!.getRangeAt(0),field=document.querySelector('.cm-html-direct-editor')!;return range.collapsed&&field.contains(range.startContainer)&&range.startContainer.nodeType===Node.TEXT_NODE&&range.startOffset===3;})).toBe(true);await page.keyboard.type(' before');await expect.poll(()=>source(page)).toBe(value.replace('old','old before'));await expect(field).toBeFocused();await page.keyboard.type(' more');await expect.poll(()=>source(page)).toBe(value.replace('old','old before more'));await expect(field).toBeFocused();await expect.poll(()=>page.evaluate(()=>(window as any).host.editor.commandStatus('undo').enabled)).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>source(page)).toBe(value);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});

test('a child-targeted out-of-scope HTML beforeinput is refused and actual child edge navigation safely resumes input',async({page})=>{
 const value='<p data-x="keep">old</p>\n\nEnd';await load(page,value);const field=page.locator('.cm-html-direct-editor');await field.focus();await page.evaluate(()=>{const field=document.querySelector('.cm-html-direct-editor')!,outside=[...document.querySelectorAll('.cm-content>.cm-line')].find(n=>n.textContent==='End')!,range=document.createRange();range.setStart(field.querySelector('p')!.firstChild!,3);range.setEnd(outside.firstChild!,0);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);const input=new InputEvent('beforeinput',{bubbles:true,cancelable:true,inputType:'insertText',data:'X'});field.dispatchEvent(input);(window as any).invalidHtmlInputPrevented=input.defaultPrevented;});expect(await page.evaluate(()=>(window as any).invalidHtmlInputPrevented)).toBe(true);expect(await source(page)).toBe(value);await expect(field.locator('.md-html-direct-notice')).toBeVisible();await field.focus();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type(' safe');await expect.poll(()=>source(page)).toBe(value.replace('old','old safe'));
});


test('HTML activation retains legal code and strong semantic selection identities through queued focus and preserves code toggle',async({page})=>{
 for(const tag of ['code','strong']){const value='<p>start <'+tag+' data-x="keep">literal</'+tag+'> end</p>\n\nEnd';await load(page,value);await selectText(page,'.cm-html-direct-editor '+tag,true);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));expect(await page.evaluate(tag=>{const node=document.querySelector('.cm-html-direct-editor '+tag)!,selection=document.getSelection()!;return selection.anchorNode===node&&selection.focusNode===node&&selection.anchorOffset===1&&selection.focusOffset===0&&selection.toString()==='literal';},tag)).toBe(true);expect(await page.evaluate(tag=>(window as any).host.editor.state[tag==='code'?'code':'bold'],tag)).toBe(true);expect(await source(page)).toBe(value);if(tag==='code'){expect(await page.evaluate(()=>(window as any).host.editor.commandStatus('code').enabled)).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.command('code'))).toBe(true);expect(await source(page)).toBe(value.replace('<code data-x="keep">literal</code>','literal'));await page.keyboard.press('ControlOrMeta+z');expect(await source(page)).toBe(value);}}
});
test('collapsed HTML wrapper endpoints stay collapsed at the author start, paragraph boundary and end with Shift document-edge direction',async({page})=>{
 const value='<p data-x="keep">first</p><p>last</p>\n\nEnd';await load(page,value);const field=page.locator('.cm-html-direct-editor');await field.focus();for(const [offset,paragraph,position] of [[0,0,0],[1,1,0],[2,1,4]]){await page.evaluate(offset=>{const field=document.querySelector('.cm-html-direct-editor')!,range=document.createRange();range.setStart(field,offset);range.collapse(true);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);field.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));},offset);expect(await page.evaluate(({paragraph,position})=>{const field=document.querySelector('.cm-html-direct-editor')!,nodes=field.querySelectorAll('p'),selection=document.getSelection()!;return selection.isCollapsed&&selection.anchorNode===nodes[paragraph].firstChild&&selection.anchorOffset===position;},{paragraph,position})).toBe(true);expect(await source(page)).toBe(value);}await page.keyboard.press('ControlOrMeta+Shift+Home');expect(await page.evaluate(()=>{const s=document.getSelection()!,nodes=document.querySelectorAll('.cm-html-direct-editor p');return {text:s.getRangeAt(0).cloneContents().textContent,anchor:s.anchorNode===nodes[1].firstChild,anchorOffset:s.anchorOffset,focus:s.focusNode===nodes[0].firstChild,focusOffset:s.focusOffset};})).toEqual({text:'firstlast',anchor:true,anchorOffset:4,focus:true,focusOffset:0});expect(await source(page)).toBe(value);
});
