import {test,expect,type Page} from '@playwright/test';
async function load(page:Page,value:string){await page.goto(process.env.TEGG_HTML_DIRECT_TEST_URL??'http://127.0.0.1:18930/reliable.html');await page.evaluate(value=>(window as any).host.load(value),value);await expect(page.locator('.cm-html-direct-editor')).toBeVisible();}
async function select(page:Page,selector:string,start?:number,end?:number,backward=false){await page.locator(selector).evaluate((node,{start,end,backward})=>{(node.closest('[contenteditable=true]') as HTMLElement).focus();const range=document.createRange();if(start===undefined)range.selectNodeContents(node);else{range.setStart(node.firstChild!,start);range.setEnd(node.firstChild!,end??start);}const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);if(backward)selection.setBaseAndExtent(range.endContainer,range.endOffset,range.startContainer,range.startOffset);},{start,end,backward});}
async function source(page:Page){return page.evaluate(()=>(window as any).host.editor.source as string);}
test('direct HTML inline code disables ordinary formats while allowing explicit code toggle off',async({page})=>{
 const value='before\n\n<p data-x="keep">start <code data-role="author">literal</code> end</p>\n\nafter';await load(page,value);await select(page,'.cm-html-direct-editor code');expect(await page.evaluate(()=>(window as any).host.editor.state.inlineFormattingEnabled)).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.commandStatus('bold').enabled)).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.command('bold'))).toBe(false);expect(await source(page)).toBe(value);expect(await page.evaluate(()=>(window as any).host.editor.commandStatus('code').enabled)).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.command('code'))).toBe(true);expect(await source(page)).toBe(value.replace('<code data-role="author">literal</code>','literal'));await page.keyboard.press('ControlOrMeta+z');expect(await source(page)).toBe(value);
});
test('direct HTML code selected-line Tab and Shift Tab preserve literal content and each Undo',async({page})=>{
 const value='before\n\n<div data-x="keep"><pre data-role="author"><code class="retain">alpha\nbeta\ngamma</code></pre><p>body</p></div>\n\nafter',indented=value.replace('alpha\nbeta','    alpha\n    beta');await load(page,value);await select(page,'.cm-html-direct-editor pre code',0,11,true);expect(await page.evaluate(()=>(window as any).host.editor.state.inlineFormattingEnabled)).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.command('code'))).toBe(false);expect(await page.evaluate(()=>(window as any).host.editor.command('bold'))).toBe(false);expect(await source(page)).toBe(value);await page.keyboard.press('Tab');expect(await source(page)).toBe(indented);expect(await page.evaluate(()=>document.getSelection()!.anchorOffset>document.getSelection()!.focusOffset)).toBe(true);await page.keyboard.press('Shift+Tab');expect(await source(page)).toBe(value);await page.keyboard.press('ControlOrMeta+z');expect(await source(page)).toBe(indented);expect(await page.evaluate(()=>document.getSelection()!.anchorOffset>document.getSelection()!.focusOffset)).toBe(true);await page.keyboard.press('ControlOrMeta+Shift+z');expect(await source(page)).toBe(value);
 await select(page,'.cm-html-direct-editor pre code',16);await page.keyboard.press('Enter');await page.keyboard.press('Shift+Enter');expect(await source(page)).toBe(value.replace('gamma</code>','gamma\n\n</code>'));expect(await page.locator('.cm-html-direct-editor pre code').textContent()).toBe('alpha\nbeta\ngamma\n\n');await page.evaluate(()=>(window as any).host.editor.setMode('reader'));expect(await page.locator('.tegg-reader pre code').textContent()).toBe('alpha\nbeta\ngamma\n\n');await page.evaluate(()=>(window as any).host.editor.setMode('live'));await expect(page.locator('.cm-html-direct-editor pre code')).toHaveText('alpha\nbeta\ngamma\n\n');
});
