import {test,expect,type Page} from "@playwright/test";
const url=process.env.TEGG_CLIPBOARD_TEST_URL??"http://127.0.0.1:18930/reliable.html";
async function pixels(page:Page,points:{x:number;y:number}[]){const png=(await page.screenshot()).toString('base64');return page.evaluate(async({png,points})=>{const image=new Image();image.src='data:image/png;base64,'+png;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(image,0,0);return points.map(point=>Array.from(ctx.getImageData(Math.round(point.x),Math.round(point.y),1,1).data));},{png,points});}
test('selecting an image preserves opaque and transparent pixels while a continuing text selection still paints prose',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage();try{
 await page.goto(url);const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=200;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#e01f45';ctx.fillRect(0,0,160,200);return canvas.toDataURL('image/png');});await page.route('**/pixels.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));const source='Before\n\n![Artwork](pixels.png)\n\nAfter';await page.evaluate(source=>(window as any).host.load(source),source);const image=page.locator('.cm-live-image img');await expect(image).toBeVisible();await expect.poll(()=>image.evaluate(node=>(node as HTMLImageElement).naturalWidth)).toBe(320);const bounds=(await image.boundingBox())!,points=[{x:bounds.x+bounds.width*.25,y:bounds.y+bounds.height*.75},{x:bounds.x+bounds.width*.75,y:bounds.y+bounds.height*.75}];const before=await pixels(page,points);expect(before[0]).toEqual([224,31,69,255]);await image.tap();await expect(page.locator('.cm-live-image')).toHaveClass(/cm-live-object-selected/);await expect.poll(()=>page.locator('.cm-selectionBackground').evaluateAll(nodes=>nodes.some(node=>!!(node as HTMLElement).style.clipPath))).toBe(true);await expect.poll(()=>pixels(page,points)).toEqual(before);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);const range=await page.evaluate(()=>(window as any).host.editor.view.state.selection.main.toJSON());expect(range).toEqual({anchor:source.indexOf('!['),head:source.indexOf('\n\nAfter')});
 const prose=page.locator('.cm-line').filter({hasText:/^Before$/}).first(),line=(await prose.boundingBox())!,textPoint={x:line.x+line.width-5,y:line.y+line.height/2},plain=await pixels(page,[textPoint]);await page.evaluate(()=>(window as any).host.editor.view.dispatch({selection:{anchor:0,head:(window as any).host.editor.view.state.doc.length}}));await expect.poll(()=>page.locator('.cm-selectionBackground').evaluateAll(nodes=>nodes.some(node=>!!(node as HTMLElement).style.clipPath))).toBe(true);await expect.poll(()=>pixels(page,points)).toEqual(before);expect(await pixels(page,[textPoint])).not.toEqual(plain);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);
 }finally{await context.close();}
});
