import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_VIEWER_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function boot(page:Page,mode:'reader'|'live',attrs:string,original:{width:number;height:number},result='static'){
 await page.goto(url);const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2048;canvas.height=1;canvas.getContext('2d')!.fillRect(0,0,2048,1);return canvas.toDataURL('image/png');});await page.route('**/metadata-proxy.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));
 const raw=`<figure data-author='exact'><img src='metadata-proxy.png' alt='Authored &amp; alt'${attrs}></figure>\n\nOriginal **text**.`;
 await page.evaluate(({raw,mode,original,result})=>{const host=(window as any).host;host.bindViewer({resolveImageMetadata:async({signal}:any)=>{await new Promise(resolve=>setTimeout(resolve,30));if(signal.aborted)return {status:'unavailable',reason:'access'};return result==='static'?{status:'static',...original}:{status:'unavailable',reason:'budget'};}});host.load(raw);if(mode==='reader'&&!host.editor.setMode('reader'))throw Error('Reader did not open');},{raw,mode,original,result});const root=page.locator(mode==='reader'?'.tegg-reader':'.cm-content'),image=root.locator("img[src$='metadata-proxy.png']").filter({visible:true});return {raw,root,image};
}
test('both modes use original oriented dimensions for proxy images with no, one or both author dimensions while retaining exact Source',async({page})=>{
 const pageErrors:string[]=[];page.on('pageerror',error=>pageErrors.push(error.message));
 await page.setViewportSize({width:390,height:740});
 for(const mode of ['reader','live'] as const)for(const original of [{width:5000,height:1},{width:1,height:5000},{width:8,height:12}])for(const attrs of [''," width='500'"," height='120'"," width='500' height='120'"]){
  const {raw,image}=await boot(page,mode,attrs,original);await expect(image).toHaveAttribute('data-image-original-size-state','ready');
  const measured=await image.evaluate(node=>{const image=node as HTMLImageElement,box=image.getBoundingClientRect(),parent=image.parentElement!,style=getComputedStyle(parent),available=parent.clientWidth-(parseFloat(style.paddingLeft)||0)-(parseFloat(style.paddingRight)||0);return {width:box.width,height:box.height,available,natural:[image.naturalWidth,image.naturalHeight],attrWidth:image.getAttribute('width'),attrHeight:image.getAttribute('height'),fit:getComputedStyle(image).objectFit,ratio:getComputedStyle(image).aspectRatio,css:image.style.cssText};});expect(measured.natural).toEqual([2048,1]);
  const hasW=attrs.includes("width='"),hasH=attrs.includes("height='"),baseW=hasW?500:hasH?120*original.width/original.height:original.width,baseH=hasH?120:hasW?500*original.height/original.width:original.height,k=Math.min(1,measured.available/baseW);const detail=JSON.stringify({mode,attrs,original,measured,baseW,baseH,k});expect(Math.abs(measured.width-baseW*k),detail).toBeLessThanOrEqual(.025);expect(Math.abs(measured.height-baseH*k),detail).toBeLessThanOrEqual(.025);expect(measured.ratio).toBe(hasW&&hasH?'500 / 120':`${original.width} / ${original.height}`);expect(measured.fit).toBe('contain');expect(measured.attrWidth).toBe(hasW?'500':null);expect(measured.attrHeight).toBe(hasH?'120':null);expect(await source(page)).toBe(raw);
 }
 await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));expect(pageErrors).toEqual([]);
});
test('unavailable original raster size follows the existing unavailable-image projection instead of claiming a proxy ratio',async({page})=>{
 for(const mode of ['reader','live'] as const)for(const attrs of [''," height='120'"," width='500'"," width='500' height='120'"]){const {raw,root}=await boot(page,mode,attrs,{width:5000,height:1},'unavailable');const image=root.locator("img[src$='metadata-proxy.png']");await expect(image).toHaveAttribute('data-image-original-size-state','unavailable');if(attrs.includes("width='")&&attrs.includes("height='")){await expect(image).toBeVisible();await expect(root.locator('.md-image-unavailable:visible')).toHaveCount(0);}else{await expect(image).toBeHidden();await expect(root.locator('.md-image-unavailable:visible')).toContainText('Authored & alt');}expect(await source(page)).toBe(raw);}
});


test('original metadata presentation stays out of adjacent rich HTML keyboard edits and one Undo',async({page})=>{
 await page.goto(url);const proxy=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2048;c.height=1;return c.toDataURL('image/png');});await page.route('**/metadata-edit-proxy.png',r=>r.fulfill({contentType:'image/png',body:Buffer.from(proxy.split(',')[1],'base64')}));
 const raw="<figure data-exact='author'><img src='metadata-edit-proxy.png' alt='Authored &amp; alt' height='120'><figcaption>Original &#32;text</figcaption></figure>\n\nEnd";
 await page.evaluate(raw=>{const host=(window as any).host;host.bindViewer({resolveImageMetadata:async()=>({status:'static',width:5000,height:1})});host.load(raw);},raw);const editable=page.locator('.cm-live-html-block .cm-html-direct-editor');await expect(editable.locator('img')).toHaveAttribute('data-image-original-size-state','ready');await expect(editable.locator('img')).toBeVisible();
 await editable.focus();await editable.evaluate(node=>{const text=node.querySelector('figcaption')!.firstChild!,r=document.createRange();r.setStart(text,0);r.setEnd(text,8);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(r);});await page.keyboard.type('Changed');await expect.poll(()=>source(page)).toBe(raw.replace('Original','Changed'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>source(page)).toBe(raw);
});
