import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_REFERENCE_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function setup(page:Page,value:string,mobile:boolean,large:boolean|'ax5'=false){
 await page.goto(url);await page.evaluate(({value,mobile,large})=>{const host=(window as any).host;host.load(value);const overlay=document.createElement('aside');overlay.id='independent-link-overlay';overlay.dataset.interfacePlatform=mobile?'mobile':'macos';for(const [key,entry] of Object.entries({'--tegg-ui-font':'system-ui,sans-serif','--tegg-ui-input-size':mobile?(large==='ax5'?'53px':large?'34px':'16px'):'13px','--tegg-ui-input-line':mobile?(large==='ax5'?'79.5px':large?'51px':'24px'):'19.5px','--tegg-ui-action-size':mobile?(large==='ax5'?'53px':large?'34px':'17px'):'13px','--tegg-ui-action-line':mobile?(large==='ax5'?'62px':large?'41px':'22px'):'18px','--tegg-ui-title-size':mobile?(large==='ax5'?'53px':large?'34px':'17px'):'15px','--tegg-ui-title-line':mobile?(large==='ax5'?'62px':large?'41px':'22px'):'21px','--tegg-ui-label-size':mobile?(large==='ax5'?'42px':large?'28px':'13px'):'12px','--tegg-ui-label-line':mobile?(large==='ax5'?'51px':large?'34px':'18px'):'17px'}))overlay.style.setProperty(key,entry);document.body.append(overlay);host.editor.view.dom.style.setProperty('--font-body','monospace');host.editor.view.dom.style.setProperty('--font-size','68px');host.editor.setUI({mobile,overlayContainer:overlay});host.select('[One][id]');host.editor.view.focus();if(!host.editor.command('link'))throw Error('Link did not open');},{value,mobile,large});await expect(page.locator('#independent-link-overlay .md-link-editor')).toBeVisible();return page.locator('.md-link-editor');
}
test('desktop dedicated link card uses independent roles and bottom Cancel/Done with an exact source Undo',async({page})=>{
 await page.setViewportSize({width:1024,height:740});const original='[One][id] [Two][id]\n\n[id]: old.md "author&#10;title"',dialog=await setup(page,original,false);await expect(dialog.locator(':scope > header')).toHaveText('Edit link');await expect(dialog.locator('.md-link-editor-actions button')).toHaveText(['Cancel','Done']);await expect(dialog.locator('form .md-link-remove')).toBeVisible();await expect(dialog.locator('.md-link-editor-actions .md-link-remove')).toHaveCount(0);
 const roles=await dialog.evaluate(node=>{const header=node.querySelector('h2')!,field=node.querySelector('input')!,action=node.querySelector('.md-link-save')!;return {title:getComputedStyle(header).fontSize,input:getComputedStyle(field).fontSize,action:getComputedStyle(action).fontSize,family:getComputedStyle(action).fontFamily,box:node.getBoundingClientRect().toJSON()};});expect(roles).toMatchObject({title:'15px',input:'13px',action:'13px'});expect(roles.family).not.toContain('monospace');expect(roles.box.width).toBeCloseTo(440,0);
 await dialog.getByRole('button',{name:'Shared target (2 occurrences)',exact:true}).click();await dialog.getByLabel('Link destination',{exact:true}).fill('next.md');await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await source(page)).toBe(original.replace(': old.md ',': <next.md> '));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);await expect(page.locator('#independent-link-overlay .tegg-overlay-root')).toHaveCount(0);
});
test('phone dedicated link card keeps Cancel and Done in its header, no duplicate footer and protects composition',async({page})=>{
 await page.setViewportSize({width:390,height:680});const original='[One][id]\n\n[id]: old.md',dialog=await setup(page,original,true);await expect(dialog.locator(':scope > header')).toHaveText('CancelEdit linkDone');await expect(dialog.locator('.md-link-editor-actions')).toHaveCount(0);
 const metrics=await dialog.evaluate(node=>{const action=node.querySelector<HTMLButtonElement>('header .md-link-save')!,field=node.querySelector('input')!,box=action.getBoundingClientRect();return {input:getComputedStyle(field).fontSize,action:getComputedStyle(action).fontSize,width:box.width,height:box.height,body:getComputedStyle(node.querySelector('form')!).overflowY};});expect(metrics).toMatchObject({input:'16px',action:'17px',body:'auto'});expect(metrics.width).toBeGreaterThanOrEqual(44);expect(metrics.height).toBeGreaterThanOrEqual(44);
 await dialog.getByLabel('Display text',{exact:true}).fill('Changed');const field=dialog.getByLabel('Display text',{exact:true});await field.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await dialog.getByRole('button',{name:'Done',exact:true}).click();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog).toBeVisible();expect(await source(page)).toBe(original);await field.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await dialog.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe('[Changed][id]\n\n[id]: old.md');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);
});
test('large mobile roles keep the action header visible while the shared occurrence body scrolls and preserves all reference bytes',async({page})=>{
 await page.setViewportSize({width:390,height:680});const original='[One][id]\n\n'+Array.from({length:40},(_,index)=>`[Occurrence ${index+2}][id]`).join('\n\n')+'\n\n[id]: old.md',dialog=await setup(page,original,true,true);await dialog.getByRole('button',{name:'Shared target (41 occurrences)',exact:true}).click();await expect(dialog.locator('.md-link-reference-occurrences li')).toHaveCount(41);
 const boxes=await dialog.evaluate(node=>{const form=node.querySelector('form')!,header=node.querySelector('header')!,action=header.querySelector('button:last-child')!,field=form.querySelector('input')!;return {header:header.getBoundingClientRect().toJSON(),action:action.getBoundingClientRect().toJSON(),font:getComputedStyle(action).fontSize,input:getComputedStyle(field).fontSize,client:form.clientHeight,scroll:form.scrollHeight,overflow:form.scrollWidth-form.clientWidth};});expect(boxes.font).toBe('34px');expect(boxes.input).toBe('34px');expect(boxes.header.y).toBeGreaterThanOrEqual(0);expect(boxes.header.y+boxes.header.height).toBeLessThanOrEqual(680);expect(boxes.action.width).toBeGreaterThanOrEqual(44);expect(boxes.action.height).toBeGreaterThanOrEqual(44);expect(boxes.scroll).toBeGreaterThan(boxes.client);expect(boxes.overflow).toBeLessThanOrEqual(1);await dialog.getByLabel('Link destination',{exact:true}).fill('next.md');await dialog.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace(': old.md',': <next.md>'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);
});

test('AX5 header keeps both actions fully reachable at phone and iPad widths independently of reading zoom',async({page})=>{
 const original='[One][id]\n\n[id]: old.md';
 for(const width of [390,640])for(const readingScale of [1,4]){
  await page.setViewportSize({width,height:740});const dialog=await setup(page,original,true,'ax5');await page.evaluate(scale=>{const view=(window as any).host.editor.view;view.dom.style.fontSize=`${17*scale}px`;},readingScale);
  const buttons=dialog.locator(':scope > header > button');await expect(buttons).toHaveText(['Cancel','Done']);
  const metrics=await buttons.evaluateAll(nodes=>nodes.map(node=>({box:node.getBoundingClientRect().toJSON(),font:getComputedStyle(node).fontSize,line:getComputedStyle(node).lineHeight})));
  for(const value of metrics){expect(value.font).toBe('53px');expect(value.line).toBe('62px');expect(value.box.width).toBeGreaterThanOrEqual(44);expect(value.box.height).toBeGreaterThanOrEqual(44);expect(value.box.x).toBeGreaterThanOrEqual(0);expect(value.box.x+value.box.width).toBeLessThanOrEqual(width);expect(value.box.y+value.box.height).toBeLessThanOrEqual(740);}
  expect(await dialog.evaluate(node=>node.scrollWidth-node.clientWidth)).toBeLessThanOrEqual(1);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
 }
});

test('editing link is a real modal, cycles available controls and requires explicit Command-Return instead of single-line Return',async({page})=>{
 const original='[One][id]\n\n[id]: old.md',dialog=await setup(page,original,false);expect(await dialog.evaluate(node=>node.matches(':modal'))).toBe(true);
 const display=dialog.getByLabel('Display text',{exact:true});await display.fill('Changed');await display.press('Enter');expect(await source(page)).toBe(original);await expect(dialog).toBeVisible();
 await dialog.getByRole('button',{name:'Done',exact:true}).focus();await page.keyboard.press('Tab');await expect(display).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'Done',exact:true})).toBeFocused();
 await page.evaluate(()=>{document.querySelector<HTMLButtonElement>('#tools button')!.focus();});expect(await dialog.evaluate(node=>node.contains(document.activeElement))).toBe(true);
 await display.focus();await display.press('Meta+Enter');await expect(dialog).toHaveCount(0);expect(await source(page)).toBe('[Changed][id]\n\n[id]: old.md');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);
});
test('unexpected leave focuses Keep, isolates and cycles only protective actions and restores the exact field selection without replay',async({page})=>{
 const original='[One][id]\n\n[id]: old.md',dialog=await setup(page,original,true);const field=dialog.getByLabel('Display text',{exact:true});await field.fill('Changed text');await field.evaluate(node=>(node as HTMLInputElement).setSelectionRange(2,6,'backward'));
 expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);const protection=dialog.getByRole('alertdialog');await expect(protection).toBeVisible();const keep=protection.getByRole('button',{name:'Keep editing',exact:true});await expect(keep).toBeFocused();expect(await dialog.locator(':scope > header').evaluate(node=>(node as HTMLElement).inert)).toBe(true);expect(await dialog.locator(':scope > form').evaluate(node=>(node as HTMLElement).inert)).toBe(true);
 await page.keyboard.press('Shift+Tab');await expect(protection.getByRole('button',{name:'Complete and continue',exact:true})).toBeFocused();await page.keyboard.press('Tab');await expect(keep).toBeFocused();await page.keyboard.press('Escape');await expect(protection).toHaveCount(0);await expect(field).toBeFocused();expect(await field.evaluate(node=>[(node as HTMLInputElement).selectionStart,(node as HTMLInputElement).selectionEnd,(node as HTMLInputElement).selectionDirection])).toEqual([2,6,'backward']);expect(await dialog.locator(':scope > form').evaluate(node=>(node as HTMLElement).inert)).toBe(false);expect(await source(page)).toBe(original);await field.press('Meta+Enter');expect(await source(page)).toBe('[Changed text][id]\n\n[id]: old.md');expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);
});
test('unfinished link composition keeps its field focused and cannot run or replay Cancel, Done or a mode leave',async({page})=>{
 const original='[One][id]\n\n[id]: old.md',dialog=await setup(page,original,true);const field=dialog.getByLabel('Display text',{exact:true});await field.fill('Changed');await field.evaluate(node=>{(node as HTMLInputElement).setSelectionRange(2,4);node.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});
 await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(field).toBeFocused();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(field).toBeFocused();expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);await expect(dialog.getByRole('alertdialog')).toHaveCount(0);expect(await source(page)).toBe(original);await field.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await expect(dialog).toBeVisible();expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');expect(await source(page)).toBe(original);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
