import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
// Native-decoded RGB fixtures; this suite verifies real canvas playback, not native codec acceptance.
const nativeFrames=JSON.parse(readFileSync(new URL('./fixtures/decoded-image-animation.json',import.meta.url),'utf8')) as Record<string,any>;
const url=process.env.TEGG_VIEWER_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const graph='```dot\ndigraph { A -> B }\n```\n\nEnd';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function diagram(page:Page,width=1000,height=2000){await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),graph);const canvas=page.locator('.cm-preview-widget .diagram-canvas');await expect(canvas).toHaveAttribute('data-render-state','ready',{timeout:15000});await canvas.locator('svg').evaluate((node,size)=>{node.setAttribute('width',String(size.width));node.setAttribute('height',String(size.height));node.setAttribute('viewBox',`0 0 ${size.width} ${size.height}`);}, {width,height});const trigger=page.locator('.cm-preview-widget').getByRole('button',{name:'View diagram',exact:true});await trigger.focus();await trigger.press('Enter');const viewer=page.locator('.md-object-viewer');await expect(viewer).toHaveAttribute('data-natural-size',`${width}x${height}`);await expect.poll(()=>viewer.evaluate(node=>Number((node as HTMLElement).dataset.viewerScale))).toBeLessThanOrEqual(1);return {viewer,canvas,trigger};}
async function center(page:Page){return page.locator('.md-object-viewer').evaluate(node=>{const stage=node.querySelector<HTMLElement>('.md-object-stage')!,graphic=node.querySelector<HTMLElement>('.md-object-graphic')!,a=stage.getBoundingClientRect(),b=graphic.getBoundingClientRect(),s=Number((node as HTMLElement).dataset.viewerScale);return {x:(a.left+stage.clientLeft+stage.clientWidth/2-b.left)/s,y:(a.top+stage.clientTop+stage.clientHeight/2-b.top)/s,scale:s};});}
async function image(page:Page,kind:'static'|'animated'|'budget'|'late',animation=nativeFrames['three.gif']){
 await page.goto(url);const setup=await page.evaluate(({kind,animation})=>{const make=(color:string,width:number,height:number)=>{const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;ctx.fillStyle=color;ctx.fillRect(0,0,width,height);return canvas.toDataURL('image/png');};const preview=make('#0000ff',160,80),full=make('#ff0000',320,160),green=make('#00ff00',320,160);const host=(window as any).host;let calls=0;const snapshots:any[]=[];(window as any).viewerDecoded={get calls(){return calls},snapshots};host.bindViewer({decodeAnimatedImage:async(request:any)=>{calls++;snapshots.push({source:request.source,signal:request.signal});if(kind==='late')return await new Promise(resolve=>{(window as any).resolveViewer=()=>resolve({status:'ready',width:320,height:160,frames:[{dataURL:full,durationMs:70},{dataURL:green,durationMs:150}]});});await new Promise(resolve=>setTimeout(resolve,80));if(kind==='budget')return {status:'unavailable',reason:'budget'};return kind==='animated'?animation:{status:'static',width:320,height:160,dataURL:full};}});return {preview};},{kind,animation});await page.route('**/viewer-source.png',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(setup.preview.split(',')[1],'base64')}));
 // Load once after routing so the real decoded image, not a missing resource placeholder, is used.
 await page.evaluate(()=>(window as any).host.load('![Authored alt](viewer-source.png)\n\nEnd'));const picture=page.locator('.cm-live-image');await expect.poll(()=>picture.locator('img').evaluate(node=>(node as HTMLImageElement).naturalWidth)).toBe(160);const trigger=picture.getByRole('button',{name:'View image',exact:true});await trigger.focus();await trigger.press('Enter');return {viewer:page.locator('.md-object-viewer'),trigger};
}

// Keep failure diagnostics in the fixture: capture which real control received
// the pointer and its playback state without changing timers, actions or asserts.
test.beforeEach(async({page},info)=>{
 if(!info.title.startsWith('Native decoded '))return;
 await page.addInitScript(()=>{
  const rows:any[]=[];(window as any).__viewerPlaybackClicks=rows;
  for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,event=>{
   const e=event as MouseEvent,target=e.target as HTMLElement,dialog=target.closest<HTMLElement>('.md-object-viewer');if(!dialog)return;
   const button=target.closest('button');
   rows.push({event:type,time:performance.now(),button:button?.textContent,pressed:button?.getAttribute('aria-pressed'),frame:dialog.dataset.animationFrame,x:e.clientX,y:e.clientY});
   if(type==='click')queueMicrotask(()=>rows.push({event:'after-click',time:performance.now(),button:button?.textContent,pressed:button?.getAttribute('aria-pressed'),frame:dialog.dataset.animationFrame}));
  },true);
 });
});
test.afterEach(async({page},info)=>{
 if(!info.title.startsWith('Native decoded ')||page.isClosed())return;
 const rows=await page.evaluate(()=>(window as any).__viewerPlaybackClicks);
 await info.attach('actual-playback-clicks',{body:JSON.stringify(rows??[],null,2),contentType:'application/json'});
});

test('Fit uses both dimensions, keeps trusted SVG coordinates and Reader/Live produce the same viewer geometry',async({page})=>{
 await page.setViewportSize({width:1050,height:700});const {viewer,canvas,trigger}=await diagram(page);const measurements=await viewer.evaluate(node=>{const stage=node.querySelector<HTMLElement>('.md-object-stage')!,content=node.querySelector<HTMLElement>('.md-object-content')!,style=getComputedStyle(content),w=stage.clientWidth-(parseFloat(style.paddingLeft)+parseFloat(style.paddingRight)),h=stage.clientHeight-(parseFloat(style.paddingTop)+parseFloat(style.paddingBottom));return {fit:Number((node as HTMLElement).dataset.viewerScale),expected:Math.min(1,w/1000,h/2000),scrollWidth:stage.scrollWidth,width:stage.clientWidth,scrollHeight:stage.scrollHeight,height:stage.clientHeight};});expect(measurements.fit).toBeCloseTo(measurements.expected,4);expect(measurements.scrollWidth).toBeLessThanOrEqual(measurements.width+1);expect(measurements.scrollHeight).toBeLessThanOrEqual(measurements.height+1);await viewer.getByRole('button',{name:'Close',exact:true}).click();await expect(trigger).toBeFocused();expect(await source(page)).toBe(graph);
 expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);const reader=page.locator('.tegg-reader .diagram-canvas');await expect(reader).toHaveAttribute('data-render-state','ready');await reader.locator('svg').first().evaluate(node=>{node.setAttribute('width','1000');node.setAttribute('height','2000');node.setAttribute('viewBox','0 0 1000 2000');});const readerTrigger=reader.getByRole('button',{name:'View diagram',exact:true});await readerTrigger.focus();await readerTrigger.press('Enter');await expect(viewer).toHaveAttribute('data-natural-size','1000x2000');await expect.poll(()=>viewer.evaluate(node=>Number((node as HTMLElement).dataset.viewerScale))).toBeCloseTo(measurements.fit,4);expect(await source(page)).toBe(graph);
});
test('zoom steps, min-fit and 400 percent bounds preserve the visible center and rotation anchor',async({page})=>{
 await page.setViewportSize({width:1050,height:700});const {viewer}=await diagram(page,2000,2000);const initial=await center(page);await viewer.getByRole('button',{name:'Actual size',exact:true}).click();const before=await center(page);expect(before.scale).toBe(1);await viewer.getByRole('button',{name:'+',exact:true}).click();const after=await center(page);expect(after.scale).toBe(1.25);expect(after.x).toBeCloseTo(before.x,0);expect(after.y).toBeCloseTo(before.y,0);await page.setViewportSize({width:800,height:850});await expect.poll(async()=>Math.abs((await center(page)).x-after.x)).toBeLessThan(2);await expect.poll(async()=>Math.abs((await center(page)).y-after.y)).toBeLessThan(2);
 for(let n=0;n<12;n++)await viewer.getByRole('button',{name:'+',exact:true}).click();expect((await center(page)).scale).toBe(4);for(let n=0;n<40;n++)await viewer.getByRole('button',{name:'−',exact:true}).click();const lower=await center(page);const fit=await viewer.evaluate(node=>{const s=node.querySelector<HTMLElement>('.md-object-stage')!,c=getComputedStyle(node.querySelector('.md-object-content')!);return Math.min(1,(s.clientWidth-parseFloat(c.paddingLeft)-parseFloat(c.paddingRight))/2000,(s.clientHeight-parseFloat(c.paddingTop)-parseFloat(c.paddingBottom))/2000);});expect(lower.scale).toBeCloseTo(Math.min(fit,.25),4);await viewer.locator('.md-object-stage').focus();await viewer.locator('.md-object-stage').press('0');expect((await center(page)).scale).toBeCloseTo(fit,4);expect(initial.scale).toBeLessThan(.25);expect(await source(page)).toBe(graph);
});
test('small objects are not enlarged and unavailable natural dimensions never produce a pretend 100 percent',async({page})=>{
 const {viewer,canvas}=await diagram(page,50,30);await expect(viewer).toHaveAttribute('data-viewer-scale','1');const small=await center(page);expect(small.x).toBeCloseTo(25,0);expect(small.y).toBeCloseTo(15,0);await viewer.getByRole('button',{name:'+',exact:true}).click();const enlarged=await center(page);expect(enlarged.x).toBeCloseTo(small.x,0);expect(enlarged.y).toBeCloseTo(small.y,0);await viewer.getByRole('button',{name:'Close',exact:true}).click();await canvas.locator('svg').evaluate(node=>{node.removeAttribute('viewBox');node.setAttribute('width','100%');node.removeAttribute('height');});const nextTrigger=page.locator('.cm-preview-widget').getByRole('button',{name:'View diagram',exact:true});await nextTrigger.focus();await nextTrigger.press('Enter');await expect(viewer).toHaveAttribute('data-natural-size','unknown');await expect(viewer.getByRole('button',{name:'Natural size unavailable',exact:true})).toBeDisabled();await expect(viewer.locator('output')).toHaveText('Natural size unavailable');expect(await source(page)).toBe(graph);
});
test('an actual formula uses its resolved rendered extent and a viewer stays single with precise close and document cleanup',async({page})=>{
 await page.goto(url);const original=String.raw`$$
\frac{a}{b}+c^2
$$

End`;await page.evaluate(value=>(window as any).host.load(value),original);const block=page.locator('.cm-preview-widget').filter({has:page.locator('.katex')});await expect(block.locator('.katex-html')).toBeVisible();const trigger=block.getByRole('button',{name:'View formula',exact:true});await trigger.focus();await trigger.press('Enter');const viewer=page.locator('.md-object-viewer');await expect(viewer).toHaveCount(1);await expect(viewer).not.toHaveAttribute('data-natural-size','unknown');await expect(viewer.getByRole('button',{name:'Actual size',exact:true})).toBeEnabled();await viewer.press('Escape');await expect(viewer).toHaveCount(0);await expect(trigger).toBeFocused();expect(await source(page)).toBe(original);await trigger.focus();await trigger.press('Enter');await page.evaluate(()=>(window as any).host.load('New document'));await expect(viewer).toHaveCount(0);expect(await source(page)).toBe('New document');
});
test('decoded static source metadata replaces a thumbnail extent without loading the original URL again',async({page})=>{
 let requests=0;page.on('request',request=>{if(request.url().endsWith('/viewer-source.png'))requests++;});const {viewer,trigger}=await image(page,'static');const openedRequests=requests;await expect(viewer.getByRole('button',{name:'Natural size unavailable',exact:true})).toBeDisabled();await expect(viewer).toHaveAttribute('data-animation-state','static');await expect(viewer).toHaveAttribute('data-natural-size','320x160');await viewer.getByRole('button',{name:'Actual size',exact:true}).click();await expect(viewer).toHaveAttribute('data-viewer-scale','1');expect(await viewer.locator('canvas').evaluate(node=>[node.width,node.height,...node.getContext('2d')!.getImageData(0,0,1,1).data])).toEqual([320,160,255,0,0,255]);await viewer.getByLabel('Viewing background',{exact:true}).selectOption('#202124');expect(await viewer.locator('canvas').evaluate(node=>[...node.getContext('2d')!.getImageData(0,0,1,1).data])).toEqual([255,0,0,255]);expect(requests).toBe(openedRequests);expect(await page.evaluate(()=>(window as any).viewerDecoded.calls)).toBe(1);await viewer.getByRole('button',{name:'Close',exact:true}).click();await expect(trigger).toBeFocused();expect(await source(page)).toBe('![Authored alt](viewer-source.png)\n\nEnd');expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);const readerImage=page.locator('.tegg-reader img');await expect.poll(()=>readerImage.evaluate(node=>(node as HTMLImageElement).naturalWidth)).toBe(160);const before=await readerImage.boundingBox();const viewImage=page.locator('.tegg-reader').getByRole('button',{name:'View image',exact:true});await viewImage.focus();await viewImage.press('Enter');await expect(viewer).toHaveAttribute('data-natural-size','320x160');await viewer.getByRole('button',{name:'Close',exact:true}).click();await expect(viewImage).toBeFocused();expect(await readerImage.boundingBox()).toEqual(before);
});
for(const format of ['three.gif','three.png','three.webp'])test(`Native decoded ${format} frames really pause and replay while Reduce Motion starts on frame zero`,async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});const {viewer}=await image(page,'animated',nativeFrames[format]);await expect(viewer).toHaveAttribute('data-animation-state','ready');await expect(viewer).toHaveAttribute('data-animation-frame','0');await expect(viewer.getByRole('button',{name:'Play',exact:true})).toHaveAttribute('aria-pressed','false');await page.waitForTimeout(260);await expect(viewer).toHaveAttribute('data-animation-frame','0');await viewer.getByRole('button',{name:'Play',exact:true}).click();await expect.poll(()=>viewer.getAttribute('data-animation-frame'),{intervals:[20,30,40]}).toBe('1');await viewer.getByRole('button',{name:'Pause',exact:true}).click();const paused=await viewer.getAttribute('data-animation-frame');const pixel=await viewer.locator('canvas').evaluate(node=>[...node.getContext('2d')!.getImageData(0,0,1,1).data]);await page.waitForTimeout(300);await expect(viewer).toHaveAttribute('data-animation-frame',paused!);expect(await viewer.locator('canvas').evaluate(node=>[...node.getContext('2d')!.getImageData(0,0,1,1).data])).toEqual(pixel);await viewer.getByRole('button',{name:'Replay',exact:true}).click();await expect(viewer).toHaveAttribute('data-animation-frame','0');await expect.poll(()=>viewer.getAttribute('data-animation-frame'),{intervals:[20,30,40]}).toBe('1');await expect(viewer.getByRole('button',{name:'Play',exact:true})).toHaveAttribute('aria-pressed','false',{timeout:2500});await expect(viewer).toHaveAttribute('data-animation-frame','2');expect(await source(page)).toBe('![Authored alt](viewer-source.png)\n\nEnd');
});
test('budget failures and decoder results arriving after close retain truthful state and cannot resurrect a viewer',async({page})=>{
 const budget=await image(page,'budget');await expect(budget.viewer).toHaveAttribute('data-animation-reason','budget');await expect(budget.viewer.getByRole('button',{name:'Natural size unavailable',exact:true})).toBeDisabled();await expect(budget.viewer).toContainText('Image exceeds the viewing budget.');await expect(budget.viewer.getByRole('button',{name:'Play',exact:true})).toHaveCount(0);await budget.viewer.getByRole('button',{name:'Close',exact:true}).click();const late=await image(page,'late');await expect(late.viewer).toHaveAttribute('data-animation-state','checking');await late.viewer.getByRole('button',{name:'Close',exact:true}).click();expect(await page.evaluate(()=>(window as any).viewerDecoded.snapshots[0].signal.aborted)).toBe(true);await page.evaluate(()=>(window as any).resolveViewer());await page.waitForTimeout(100);await expect(page.locator('.md-object-viewer')).toHaveCount(0);expect(await source(page)).toBe('![Authored alt](viewer-source.png)\n\nEnd');
});

test('inline safe HTML images gain no overlay while actual adjacent text input and one Undo preserve author bytes',async({page})=>{
 await page.goto(url);const original="<p data-exact='yes'>Original <img src='viewer-html.png' alt='Authored &amp; alt' width='80'> text</p>\n\nEnd";
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=80;canvas.height=40;canvas.getContext('2d')!.fillRect(0,0,80,40);return canvas.toDataURL('image/png');});await page.route('**/viewer-html.png',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));await page.evaluate(value=>(window as any).host.load(value),original);
 const editable=page.locator('.cm-live-html-block .cm-html-direct-editor');await expect(editable).toBeVisible();await expect(editable.locator('.md-image-view-actions')).toHaveCount(0);await editable.focus();await editable.evaluate(node=>{const text=node.querySelector('p')!.firstChild!,range=document.createRange();range.setStart(text,0);range.setEnd(text,'Original'.length);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});await page.keyboard.type('Changed');await expect.poll(()=>source(page)).toBe(original.replace('Original','Changed'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>source(page)).toBe(original);
});

test('safe authored two-dimensional images retain their rectangle in Reader and Live, including an extreme original bitmap',async({page})=>{
 await page.goto(url);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=5000;c.height=1;c.getContext('2d')!.fillRect(0,0,5000,1);return c.toDataURL('image/png');});
 await page.route('**/author-rectangle.png',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));
 const original='<figure><img src="author-rectangle.png" alt="Author rectangle" width="500" height="120"></figure>\n\nEnd';
 await page.evaluate(value=>(window as any).host.load(value),original);
 for(const mode of ['live','reader']){
  if(mode==='reader')expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);
  const img=page.locator(mode==='live'?'.cm-live-html-block img:visible':'.tegg-reader img:visible').first();await expect.poll(()=>img.evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(5000);
  const measure=()=>img.evaluate(i=>{const r=i.getBoundingClientRect();return {width:r.width,height:r.height,attrs:[i.getAttribute('width'),i.getAttribute('height')],fit:getComputedStyle(i).objectFit}});
  const wide=await measure();expect(wide.attrs).toEqual(['500','120']);expect(wide.width).toBeCloseTo(500,1);expect(wide.height).toBeCloseTo(120,1);expect(wide.fit).toBe('contain');
  await page.setViewportSize({width:390,height:700});await expect.poll(async()=>{const m=await measure();return m.width}).toBeLessThan(500);const narrow=await measure();expect(narrow.height).toBeCloseTo(narrow.width*120/500,1);expect(await source(page)).toBe(original);
  await page.setViewportSize({width:1280,height:720});
 }
});

test('a single authored height completes only its decoded intrinsic ratio without modifying source attributes',async({page})=>{
 const pageErrors:string[]=[];page.on('pageerror',error=>pageErrors.push(error.message));
 await page.goto(url);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=500;c.height=250;return c.toDataURL('image/png');});await page.route('**/author-height.png',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));const original='<figure><img src="author-height.png" alt="Height" height="120"></figure>\n\nEnd';await page.evaluate(value=>(window as any).host.load(value),original);
 for(const mode of ['live','reader']){if(mode==='reader')await page.evaluate(()=>(window as any).host.editor.setMode('reader'));const img=page.locator(mode==='live'?'.cm-live-html-block img:visible':'.tegg-reader img:visible').first();await expect.poll(()=>img.evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(500);const box=await img.boundingBox();expect(box!.width).toBeCloseTo(240,1);expect(box!.height).toBeCloseTo(120,1);expect(await img.getAttribute('width')).toBeNull();expect(await img.getAttribute('height')).toBe('120');expect(await source(page)).toBe(original);}
 await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));expect(pageErrors).toEqual([]);
});

test('touch image entry is selection only until the explicit View action, then outside touch clears selection',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:700}});const page=await context.newPage();
 try{await page.goto(url);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=200;c.getContext('2d')!.fillRect(0,0,320,200);return c.toDataURL('image/png');});await page.route('**/select-only.png',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));const original='![Selected image](select-only.png)\n\nOutside';await page.evaluate(value=>(window as any).host.load(value),original);
 for(const mode of ['live','reader']){if(mode==='reader')await page.evaluate(()=>(window as any).host.editor.setMode('reader'));const root=page.locator(mode==='live'?'.cm-live-image':'.tegg-reader .md-image-container').first(),img=root.locator('img'),entry=root.getByRole('button',{name:'View image',exact:true});await expect.poll(()=>img.evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(320);await expect(root).toHaveAttribute('data-image-selected','false');await expect.poll(()=>entry.evaluate(e=>getComputedStyle(e.parentElement!).opacity)).toBe('0');await img.tap();await expect(root).toHaveAttribute('data-image-selected','true');await expect(page.locator('.md-object-viewer')).toHaveCount(0);await expect.poll(()=>entry.evaluate(e=>getComputedStyle(e.parentElement!).opacity)).toBe('1');await entry.tap();await expect(page.locator('.md-object-viewer')).toHaveCount(1);await page.getByRole('button',{name:'Close',exact:true}).tap();await page.locator(mode==='live'?'.cm-content':'.tegg-reader').getByText('Outside',{exact:true}).last().tap();await expect(root).toHaveAttribute('data-image-selected','false');expect(await source(page)).toBe(original);}
 }finally{await context.close();}
});

test('presentation rectangle and generated viewer controls stay out of real rich HTML writes and Undo',async({page})=>{
 await page.goto(url);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=5000;c.height=1;return c.toDataURL('image/png');});await page.route('**/rectangle-draft.png',r=>r.fulfill({status:200,contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));const original="<figure data-exact='authored'><img src='rectangle-draft.png' alt='Authored &amp; alt' width='500' height='120'><figcaption>Original text</figcaption></figure>\n\nEnd";await page.evaluate(value=>(window as any).host.load(value),original);const editable=page.locator('.cm-live-html-block .cm-html-direct-editor');await expect(editable.locator('img')).toBeVisible();await expect.poll(()=>editable.locator('img').evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(5000);await editable.focus();await editable.evaluate(node=>{const text=node.querySelector('figcaption')!.firstChild!,r=document.createRange();r.setStart(text,0);r.setEnd(text,8);const s=document.getSelection()!;s.removeAllRanges();s.addRange(r);});await page.keyboard.type('Changed');await expect.poll(()=>source(page)).toBe(original.replace('Original','Changed'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>source(page)).toBe(original);
});


test('Reader tight image-first list View keeps nested author blocks and touch selection geometry intact',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:700}});const page=await context.newPage();
 try{
  await page.goto(url);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=200;return c.toDataURL('image/png');});
  await page.route('**/tight-image.png',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));
  const original='- ![Tight image](tight-image.png)\n  - Nested author text\n\nOutside';await page.evaluate(value=>(window as any).host.load(value),original);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);
  const owner=page.locator('.tegg-reader li').filter({has:page.locator('img')}).first(),image=owner.locator('img'),entry=owner.getByRole('button',{name:'View image',exact:true});
  await expect.poll(()=>image.evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(320);await expect(entry).toHaveCount(1);const before=await image.boundingBox();const nestedBefore=await owner.getByText('Nested author text',{exact:true}).boundingBox();
  await image.tap();await expect(owner).toHaveAttribute('data-image-selected','true');await expect(page.locator('.md-object-viewer')).toHaveCount(0);expect(await image.boundingBox()).toEqual(before);expect(await owner.getByText('Nested author text',{exact:true}).boundingBox()).toEqual(nestedBefore);
  await entry.tap();await expect(page.locator('.md-object-viewer')).toHaveCount(1);await page.getByRole('button',{name:'Close',exact:true}).tap();await expect(entry).toBeFocused();
  await page.locator('.tegg-reader').getByText('Outside',{exact:true}).tap();await expect(owner).toHaveAttribute('data-image-selected','false');expect(await image.boundingBox()).toEqual(before);expect(await source(page)).toBe(original);
 }finally{await context.close();}
});


test('controlled HTML image Edit and View share the complete fitting group while linked and small images retain their existing behavior',async({page})=>{
 await page.goto(url);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=200;return c.toDataURL('image/png');});
 await page.route('**/group-image.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from(png.split(',')[1],'base64')}));
 for(const sourceHTML of ['<figure><img src="group-image.png" width="240" height="160"><figcaption>Caption</figcaption></figure>','<p><img src="group-image.png" width="240" height="160"></p>']){
  const original=sourceHTML+'\n\nAfter';await page.evaluate(value=>(window as any).host.load(value),original);const root=page.locator('.cm-live-html-block'),image=root.locator('img'),group=root.locator('.md-image-view-actions');await expect.poll(()=>image.evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(320);
  await expect(group.getByRole('button',{name:'Edit image',exact:true})).toHaveCount(1);await expect(group.getByRole('button',{name:'View image',exact:true})).toHaveCount(1);
  const extent=await image.boundingBox();const actions=await group.boundingBox();expect(actions!.x).toBeGreaterThanOrEqual(extent!.x+7.5);expect(actions!.y).toBeGreaterThanOrEqual(extent!.y+7.5);expect(actions!.x+actions!.width).toBeLessThanOrEqual(extent!.x+extent!.width-7.5);expect(actions!.y+actions!.height).toBeLessThanOrEqual(extent!.y+extent!.height-7.5);
  const view=group.getByRole('button',{name:'View image',exact:true});await view.focus();await view.press('Enter');await expect(page.locator('.md-object-viewer')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await expect(view).toBeFocused();expect(await image.boundingBox()).toEqual(extent);expect(await source(page)).toBe(original);
 }
 for(const sourceHTML of ['<figure><img src="group-image.png" width="40" height="30"><figcaption>Small</figcaption></figure>','<p><a href="target.md"><img src="group-image.png" width="240" height="160"></a></p>']){
  const original=sourceHTML+'\n\nAfter';await page.evaluate(value=>(window as any).host.load(value),original);const root=page.locator('.cm-live-html-block');await expect.poll(()=>root.locator('img').evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBe(320);await expect(root.getByRole('button',{name:'View image',exact:true})).toHaveCount(0);await expect(root.getByRole('button',{name:'Edit image',exact:true})).toHaveCount(1);expect(await source(page)).toBe(original);
 }
});
