import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const original='$$\nx+1\n$$\n\nEnd';
async function open(page:Page){await page.goto(url);await page.evaluate(value=>{(window as any).host.load(value);(window as any).host.ui.openObject('math',{from:0,to:value.indexOf('\n\nEnd')});},original);const panel=page.locator('.tegg-editing-panel:not([hidden])');await expect(panel).toBeVisible();return panel;}
test('desktop object sheets use the approved UI roles, math stack and only Cancel/Done while changes remain an independent draft',async({page})=>{const panel=await open(page);const measure=await panel.evaluate(node=>{const style=(selector:string)=>{const element=node.querySelector<HTMLElement>(selector)!,s=getComputedStyle(element);return {font:parseFloat(s.fontSize),line:parseFloat(s.lineHeight),height:element.getBoundingClientRect().height}};return {width:node.getBoundingClientRect().width,title:style('h2'),field:style('.tegg-object-body'),action:style('[data-label="Apply"]'),label:style('label>span'),columns:(node as HTMLElement).dataset.columns}});expect(measure.width).toBe(560);expect(measure.title).toMatchObject({font:15,line:21});expect(measure.field).toMatchObject({font:13,line:19.5});expect(measure.action).toMatchObject({font:13,line:18});expect(measure.label).toMatchObject({font:12,line:17});expect(measure.columns).toBe('1');await expect(panel.getByRole('button',{name:'Close',exact:true})).toHaveCount(0);await expect(panel.locator('.tegg-editing-footer button')).toHaveText(['Cancel','Done']);await expect(panel.getByText('Markdown source',{exact:true})).toHaveCount(0);await expect(panel.locator('.tegg-object-preview')).toHaveCSS('border-top-width','1px');await panel.getByLabel('Formula source',{exact:true}).fill('x+2');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);await panel.getByRole('button',{name:'Done',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).host.editor.source)).toBe(original.replace('x+1','x+2'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);});
test('touch sheet fields and top actions use system UI roles and stay independent of reading zoom',async({browser})=>{const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage();try{const panel=await open(page);await expect(panel.locator('header button')).toHaveText(['Cancel','Done']);await expect(panel.locator('.tegg-editing-footer button')).toHaveCount(0);const before=await panel.getByRole('button',{name:'Done',exact:true}).evaluate(node=>{const s=getComputedStyle(node);return {font:s.fontSize,line:s.lineHeight,height:node.getBoundingClientRect().height}});expect(before.font).toBe('17px');expect(before.line).toBe('22px');expect(before.height).toBeGreaterThanOrEqual(44);expect(await panel.locator('.tegg-object-body').evaluate(node=>parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(16);await page.evaluate(()=>{document.documentElement.style.setProperty('--reader-font-scale','4');document.documentElement.style.setProperty('--md-body','68px');document.documentElement.style.setProperty('--md-user-scale','4');});expect(await panel.getByRole('button',{name:'Done',exact:true}).evaluate(node=>({font:getComputedStyle(node).fontSize,line:getComputedStyle(node).lineHeight,height:node.getBoundingClientRect().height}))).toEqual(before);for(const width of [390,640]){await page.setViewportSize({width,height:844});for(const action of ['Cancel','Done'])await expect(panel.getByRole('button',{name:action,exact:true})).toBeInViewport();}expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);}finally{await context.close();}});
test('a host system UI change increases actual sheet type without using reading metrics',async({browser})=>{const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage();try{const panel=await open(page);await panel.evaluate(node=>{const root=node.closest<HTMLElement>('.tegg-editing-ui')!;for(const [key,value] of Object.entries({'action-size':'24px','action-line':'30px','input-size':'24px','input-line':'36px','title-size':'24px','title-line':'30px','label-size':'18px','label-line':'24px'}))root.style.setProperty('--tegg-ui-'+key,value);});await expect(panel.getByRole('button',{name:'Done',exact:true})).toHaveCSS('font-size','24px');await expect(panel.locator('.tegg-object-body')).toHaveCSS('font-size','24px');await expect(panel.locator('h2')).toHaveCSS('line-height','30px');for(const action of ['Cancel','Done'])await expect(panel.getByRole('button',{name:action,exact:true})).toBeInViewport();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);}finally{await context.close();}});

test('largest system action type remains at its full size and both mobile exits fit at phone and iPad widths',async({browser})=>{const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage();try{const panel=await open(page);await panel.evaluate(node=>{const root=node.closest<HTMLElement>('.tegg-editing-ui')!;for(const [key,value] of Object.entries({'action-size':'53px','action-line':'62px','input-size':'53px','input-line':'79.5px','title-size':'53px','title-line':'62px','label-size':'44px','label-line':'53px'}))root.style.setProperty('--tegg-ui-'+key,value);});for(const width of [390,640])for(const zoom of [1,4]){await page.setViewportSize({width,height:844});await page.evaluate(zoom=>{document.documentElement.style.setProperty('--reader-font-scale',String(zoom));document.documentElement.style.setProperty('--md-body',17*zoom+'px');},zoom);for(const action of ['Cancel','Done']){const button=panel.getByRole('button',{name:action,exact:true});await expect(button).toHaveCSS('font-size','53px');await expect(button).toHaveCSS('line-height','62px');const bounds=await button.boundingBox();expect(bounds!.height).toBeGreaterThanOrEqual(44);expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.y).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(width);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(844);}expect(await panel.evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true);}await panel.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);}finally{await context.close();}});

test('leave protection isolates its three choices, Escape restores the exact draft selection and the explicit completion shortcut creates one Undo',async({page})=>{
 const panel=await open(page),field=panel.getByLabel('Formula source',{exact:true});await field.fill('x+123');await field.press('Home');await field.press('ArrowRight');await field.press('Shift+ArrowRight');await field.press('Shift+ArrowRight');const selected=await field.evaluate(node=>{const f=node as HTMLTextAreaElement;return [f.selectionStart,f.selectionEnd,f.selectionDirection]});await field.press('Escape');const guard=panel.getByRole('dialog',{name:'Unsaved changes',exact:true});await expect(guard.getByRole('button')).toHaveText(['Keep editing','Discard changes','Complete and continue']);await expect(guard.getByRole('button',{name:'Keep editing',exact:true})).toBeFocused();expect(await panel.locator('.tegg-editing-content').evaluate(node=>(node as HTMLElement).inert)).toBe(true);for(let n=0;n<8;n++){await page.keyboard.press('Tab');expect(await guard.evaluate(node=>node.contains(document.activeElement))).toBe(true);}await page.keyboard.press('Escape');await expect(guard).toHaveCount(0);await expect(field).toBeFocused();expect(await field.evaluate(node=>{const f=node as HTMLTextAreaElement;return [f.selectionStart,f.selectionEnd,f.selectionDirection]})).toEqual(selected);await expect(field).toHaveValue('x+123');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);await field.press('End');await field.press('Enter');await field.press('x');await expect(field).toHaveValue('x+123\nx');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);await field.press('ControlOrMeta+Enter');await expect(panel).toBeHidden();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original.replace('x+1','x+123\nx'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);
});
test('a stale object cannot complete through its leave choice and its local draft remains available',async({page})=>{
 const panel=await open(page),field=panel.getByLabel('Formula source',{exact:true});await field.fill('local');await page.evaluate(()=>(window as any).host.editor.view.dispatch({changes:{from:3,to:4,insert:'y'}}));const external=original.replace('x+1','y+1');await field.press('Escape');const guard=panel.getByRole('dialog',{name:'Unsaved changes',exact:true}),complete=guard.getByRole('button',{name:'Complete and continue',exact:true});await expect(complete).toBeDisabled();await complete.evaluate(node=>(node as HTMLButtonElement).click());expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(external);await page.keyboard.press('Escape');await expect(field).toHaveValue('local');await expect(field).toBeFocused();await panel.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(external);
});

test('Source rich link fields preserve author formatting and only replace the destination in one Undo',async({page})=>{
 const source='[**Rich** `code` &amp; text](old.md "title")\n\nEnd';await page.goto(url);await page.evaluate(value=>{const host=(window as any).host;host.load(value);host.editor.setMode('source');host.ui.openObject('link',{from:0,to:value.indexOf('\n\nEnd')});},source);const panel=page.locator('.tegg-editing-panel:not([hidden])'),label=panel.getByLabel('Display text (read-only)',{exact:true});await expect(label).toHaveAttribute('readonly','');await expect(panel.locator('.md-link-label-preview strong')).toHaveText('Rich');await expect(panel.locator('.md-link-label-preview code')).toHaveText('code');await panel.getByLabel('Target',{exact:true}).fill('new.md');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);await panel.getByLabel('Target',{exact:true}).press('ControlOrMeta+Enter');const changed=await page.evaluate(()=>(window as any).host.editor.source);expect(changed).toBe(source.replace('(old.md "title")','(<new.md> "title")'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);
});
test('Source reference editing remains an explicit source draft and does not silently convert or update its shared definition',async({page})=>{
 const source='[Original][shared]\n\n[Other][shared]\n\n[shared]: old.md "keep"';await page.goto(url);await page.evaluate(value=>{const host=(window as any).host;host.load(value);host.editor.setMode('source');host.ui.openObject('link',{from:0,to:value.indexOf('\n\n')});},source);const panel=page.locator('.tegg-editing-panel:not([hidden])');await expect(panel.getByLabel('Target',{exact:true})).toHaveCount(0);const raw=panel.getByLabel('Object Markdown',{exact:true});await expect(raw).toBeVisible();await raw.fill('[Changed][shared]');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);await raw.press('ControlOrMeta+Enter');expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source.replace('[Original][shared]','[Changed][shared]'));expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);
});

test('mobile extension review uses a single top Done and completes its real local draft in one Undo',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:390,height:844}}),page=await context.newPage();try{
  const source='[old](old.md)\n\nEnd';await page.goto(url);await page.evaluate(value=>{const h=(window as any).host;h.load(value);h.select('old');},source);await page.getByRole('button',{name:'Prepare revised link',exact:true}).click();
  const panel=page.getByRole('dialog',{name:'Review extension draft',exact:true});await expect(panel.locator('header button')).toHaveText(['Cancel','Done']);await expect(panel.locator('.tegg-editing-footer button')).toHaveCount(0);const done=panel.getByRole('button',{name:'Done',exact:true});await expect(done).toBeInViewport();expect(await done.evaluate(node=>({font:getComputedStyle(node).fontSize,line:getComputedStyle(node).lineHeight,height:node.getBoundingClientRect().height}))).toMatchObject({font:'17px',line:'22px'});expect(await done.evaluate(node=>node.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);
  await done.click();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe('[reviewed](old.md)\n\nEnd');expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(source);
 }finally{await context.close();}
});

test('literal sheet Copy pointer actions keep IME focus and selection and are not replayed after composition ends',async({page})=>{
 await page.goto(url);await page.evaluate(value=>{const h=(window as any).host;(window as any).copyCalls=0;h.load(value,{copyText:async()=>{(window as any).copyCalls++;}});h.ui.openObject('math',{from:0,to:value.indexOf('\n\nEnd')});},original);
 const panel=page.getByRole('dialog',{name:'Edit formula',exact:true}),field=panel.getByLabel('Formula source',{exact:true});await panel.locator('.tegg-editing-more>summary').click();await field.focus();await field.evaluate(node=>(node as HTMLTextAreaElement).setSelectionRange(0,2,'backward'));const selection=await field.evaluate(node=>{const f=node as HTMLTextAreaElement;return [f.selectionStart,f.selectionEnd,f.selectionDirection]});await field.dispatchEvent('compositionstart');await panel.getByRole('button',{name:'Copy expression',exact:true}).click();await expect(field).toBeFocused();expect(await field.evaluate(node=>{const f=node as HTMLTextAreaElement;return [f.selectionStart,f.selectionEnd,f.selectionDirection]})).toEqual(selection);expect(await page.evaluate(()=>(window as any).copyCalls)).toBe(0);expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);await field.dispatchEvent('compositionend');await page.waitForTimeout(100);expect(await page.evaluate(()=>(window as any).copyCalls)).toBe(0);await panel.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).host.editor.source)).toBe(original);
});
