import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function reader(page:Page,value:string){await page.goto(url);await page.evaluate(value=>{(window as any).host.load(value);(window as any).host.editor.setMode('reader');(window as any).clipboard=[];document.body.addEventListener('tegg-copy-content',event=>{event.preventDefault();const data=(event as CustomEvent).detail;(window as any).clipboard.push(data);data.complete(true);});},value);await expect(page.getByLabel('Markdown Reader',{exact:true})).toBeVisible();}
async function copy(page:Page,selector:string,mode:'node'|'contents'|'text'='node',span?:[number,number]){await page.evaluate(({selector,mode,span})=>{(window as any).clipboard=[];const node=document.querySelector(selector)!,range=document.createRange();if(mode==='text'){const text=node.firstChild!;range.setStart(text,span?.[0]??0);range.setEnd(text,span?.[1]??text.textContent!.length);}else if(mode==='contents')range.selectNodeContents(node);else range.selectNode(node);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);},{selector,mode,span});await page.keyboard.press('ControlOrMeta+c');await expect.poll(()=>page.evaluate(()=>(window as any).clipboard.length)).toBe(1);return page.evaluate(()=>{const {text,html,structured}=(window as any).clipboard[0];return {text,html,semantic:JSON.parse(structured)};});}
test('Reader object selection copies exact individual code/table/image/collapsed Callout source without adjacent blocks',async({page})=>{
 const objects=[{value:'```text\n\t**literal**\n\n```',selector:'.tegg-reader .md-render-code'},{value:'| A | B |\n| :--- | ---: |\n| **rich** | x |',selector:'.tegg-reader .md-table-scroll'},{value:'![Actual alt](image.png "Author title")',selector:'.tegg-reader p:has(img)'},{value:'> [!warning]- Rich **Title**\n> hidden **body**',selector:'.tegg-reader blockquote.callout'}];
 for(const {value,selector}of objects){const original='Before\n\n'+value+'\n\nAfter';await reader(page,original);const data=await copy(page,selector);expect(data.semantic.source).toBe(value);expect(data.text).not.toContain('Before');expect(data.text).not.toContain('After');expect(data.text).not.toContain('Copy code');expect(data.text).not.toContain('View image');if(value.includes('[!warning]')){expect(data.text).toContain('hidden body');await expect(page.locator(selector)).toHaveAttribute('data-callout-expanded','false');}expect(await source(page)).toBe(original);}
});
test('Reader internal code and cell text retain innermost literal/rich scope instead of promoting the whole object',async({page})=>{
 await reader(page,'```text\n\t**literal**\nnext\n```\n\n| H |\n| --- |\n| **Cell** |');const code=await copy(page,'.tegg-reader .md-render-code pre code','text',[0,13]);expect(code.text).toBe('\t**literal**\n');expect(code.semantic.format).toBe('html');expect(code.html).toContain('<pre><code>');expect(code.semantic.source).not.toContain('```');const cell=await copy(page,'.tegg-reader td strong','text',[1,3]);expect(cell.text).toBe('el');expect(cell.html).toMatch(/<strong[^>]*>el<\/strong>/);expect(cell.semantic.source).not.toContain('<table');
});
test('Reader Callout title-only copy excludes hidden children and its first body paragraph excludes the header',async({page})=>{
 const original='> [!warning]- Rich **Title**\n> hidden **body**\n\nAfter';await reader(page,original);const title=await copy(page,'.tegg-reader .callout-title-text strong','contents');expect(title.text).toBe('Title');expect(title.html).toMatch(/<strong[^>]*>Title<\/strong>/);expect(title.semantic.source).not.toContain('hidden');expect(title.text).not.toContain('warning');await page.locator('.tegg-reader .callout-fold').click();const body=await copy(page,'.tegg-reader blockquote.callout > p');expect(body.semantic.source).toBe('> hidden **body**');expect(body.text).not.toContain('Title');expect(await source(page)).toBe(original);
});
test('Reader ordinary multi-block copy keeps CRLF bytes and only its referenced definition',async({page})=>{
 const original='---\r\ntags: [one]\r\n---\r\n\r\nBefore\r\n\r\n[Linked][ref] **bold**\r\n\r\nSecond &amp; text\r\n\r\nAfter\r\n\r\n[ref]: <secret.md> "Exact title"\r\n[unused]: other.md';await reader(page,original);await page.evaluate(()=>{const ps=[...document.querySelectorAll('.tegg-reader > p')],from=ps.find(node=>node.textContent==='Linked bold')!,to=ps.find(node=>node.textContent==='Second & text')!,range=document.createRange();range.setStartBefore(from);range.setEndAfter(to);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});await page.keyboard.press('ControlOrMeta+c');await expect.poll(()=>page.evaluate(()=>(window as any).clipboard.length)).toBe(1);const copied=await page.evaluate(()=>JSON.parse((window as any).clipboard[0].structured));expect(copied.source).toBe('[Linked][ref] **bold**\r\n\r\nSecond &amp; text');expect(copied.definitions).toEqual(['[ref]: <secret.md> "Exact title"']);expect(await source(page)).toBe(original);
});
test('Reader partial rich HTML retains authored UI-like classes and attributes while filtering actual generated controls',async({page})=>{
 const original='<p>before <span class="callout-icon" data-tegg-editor-projection="true">authored visible</span> after</p>';await reader(page,original);const data=await copy(page,'.tegg-reader span.callout-icon','contents');expect(data.text).toBe('authored visible');expect(data.html).toContain('authored visible');expect(data.semantic.source).toContain('authored visible');expect(await source(page)).toBe(original);
});
test('an outer caret at the beginning of controlled HTML and Details retains the direct projection and explicit object operations',async({page})=>{
 await page.route('**/figure.png',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="160"><rect width="240" height="160" fill="red"/></svg>'}));
 for(const original of ['<figure><img src="figure.png" width="240" height="160" alt="Author"><figcaption>Caption</figcaption></figure>\n\nAfter','<details><summary>Title</summary><p>Body</p></details>\n\nAfter']){await page.goto(url);await page.evaluate(value=>{(window as any).host.load(value);const view=(window as any).host.editor.view;view.dispatch({selection:{anchor:0}});view.focus();},original);await expect(page.locator('.cm-live-technical-source')).toHaveCount(0);await expect(page.locator('.cm-live-html-block .cm-html-direct-editor')).toBeVisible();if(original.startsWith('<figure')){await expect.poll(()=>page.locator('.cm-live-html-block img').evaluate(node=>(node as HTMLImageElement).naturalWidth)).toBe(240);await expect(page.locator('.cm-live-html-block').getByRole('button',{name:'View image',exact:true})).toHaveCount(1);}expect(await source(page)).toBe(original);}
});
