import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_REFERENCE_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const currentSource=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function open(page:Page,value:string,occurrence:string){await page.goto(url);await page.evaluate(source=>(window as any).host.load(source),value);await expect(page.locator('.cm-content').first()).toBeVisible();expect(await page.evaluate(text=>{const host=(window as any).host;host.select(text);host.editor.view.focus();return host.editor.command('link');},occurrence)).toBe(true);await expect(page.locator('.md-link-editor')).toBeVisible();}
async function save(page:Page){await page.locator('.md-link-editor').getByRole('button',{name:'Done',exact:true}).click();}
async function undo(page:Page,value:string){expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>currentSource(page)).toBe(value);}

test('reference target edit requires explicit shared scope, exposes actual affected locations, patches only the definition and supports one Undo',async({page})=>{
 const source='[First][id] [ID][] [ID]\n\n[ordinary](old.md) [[old.md]]\n\n[id]: old.md "author&#10;title"';await open(page,source,'[First][id]');const dialog=page.locator('.md-link-editor');await expect(dialog.getByLabel('Link destination',{exact:true})).toHaveAttribute('readonly','');await expect(dialog.locator('.md-link-reference-occurrences')).toHaveCount(0);await dialog.getByRole('button',{name:'Shared target (3 occurrences)',exact:true}).click();
 await expect(dialog.locator('.md-link-reference-occurrences li')).toHaveText(['First — Line 1','ID — Line 1','ID — Line 1']);expect(await dialog.locator('.md-link-reference-occurrences li').evaluateAll(nodes=>nodes.map(node=>Number((node as HTMLElement).dataset.sourceFrom)))).toEqual([0,source.indexOf('[ID][]'),source.indexOf('[ID]',source.indexOf('[ID][]')+6)]);await dialog.getByLabel('Link destination',{exact:true}).fill('new.md#heading');expect(await currentSource(page)).toBe(source);await save(page);await expect(dialog).toHaveCount(0);const next=source.replace(': old.md ',': <new.md#heading> ');await expect.poll(()=>currentSource(page)).toBe(next);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);await expect(page.getByRole('link',{name:'First',exact:true})).toHaveAttribute('href','new.md#heading');await expect(page.getByRole('link',{name:'ordinary',exact:true})).toHaveAttribute('href','old.md');expect(await page.evaluate(()=>(window as any).host.editor.setMode('live'))).toBe(true);await undo(page,source);
});
test('current label edits keep full/collapsed/shortcut reference identity and preserve the shared definition',async({page})=>{
 for(const occurrence of ['[Label][id]','[id][]','[id]']){const source=occurrence+"\n\n[id]: old.md 'title'";await open(page,source,occurrence);await page.locator('.md-link-editor').getByLabel('Display text',{exact:true}).fill('Changed');await save(page);await expect.poll(()=>currentSource(page)).toBe("[Changed][id]\n\n[id]: old.md 'title'");await undo(page,source);}
});
test('rich labels use read-only semantic previews and changing only target or title preserves all other authored bytes',async({page})=>{
 const source="[**Bold** &amp; `code`](<folder/a%20b.md?raw=%2520> 'author &amp; title')";await open(page,source,source);const dialog=page.locator('.md-link-editor');await expect(dialog.locator('input[aria-label="Display text"]')).toHaveCount(0);await expect(dialog.locator('.md-link-label-preview strong')).toHaveText('Bold');await expect(dialog.locator('.md-link-label-preview code')).toHaveText('code');await expect(dialog.locator('.md-link-title-details')).toHaveAttribute('open','');await dialog.getByLabel('Link destination',{exact:true}).fill('new.md');await save(page);await expect.poll(()=>currentSource(page)).toBe(source.replace('<folder/a%20b.md?raw=%2520>','<new.md>'));await undo(page,source);
 await page.evaluate(text=>{const host=(window as any).host;host.select(text);host.editor.view.focus();host.editor.command('link');},source);await dialog.getByLabel('Description (optional)',{exact:true}).fill('new title');await save(page);await expect.poll(()=>currentSource(page)).toBe(source.replace("'author &amp; title'",'"new title"'));await undo(page,source);
});
test('Wiki target-only changes never invent aliases or fragments and rich explicit aliases remain authored',async({page})=>{
 for(const [source,next,target] of [['[[Old]]','[[New]]','New'],['[[Old|Old]]','[[New|Old]]','New'],['[[Old#^block|**Rich**]]','[[New#^block|**Rich**]]','New#^block']]){await open(page,source,source);const dialog=page.locator('.md-link-editor');await expect(dialog.locator('.md-link-shared-target')).toHaveCount(0);await expect(dialog.getByLabel('Description (optional)',{exact:true})).toHaveCount(0);await dialog.getByLabel('Link destination',{exact:true}).fill(target);await save(page);await expect.poll(()=>currentSource(page)).toBe(next);await undo(page,source);}
});
test('missing and duplicate definitions show explicit scope, create only after completion or retain conflicts unchanged',async({page})=>{
 const missing='[One][none] [Two][none]';await open(page,missing,'[One][none]');let dialog=page.locator('.md-link-editor');await dialog.getByRole('button',{name:'Shared target (2 occurrences)',exact:true}).click();await expect(dialog.locator('.md-link-shared-scope')).toContainText('definition is missing');await dialog.getByLabel('Link destination',{exact:true}).fill('new.md');expect(await currentSource(page)).toBe(missing);await save(page);await expect.poll(()=>currentSource(page)).toBe(missing+'\n\n[none]: <new.md>');await undo(page,missing);
 const conflict='[One][id]\n\n[id]: first.md\n[id]: second.md';await open(page,conflict,'[One][id]');dialog=page.locator('.md-link-editor');await dialog.getByRole('button',{name:'Shared target (1 occurrences)',exact:true}).click();await expect(dialog.locator('.md-link-conflicting-definition')).toHaveText(['[id]: first.md','[id]: second.md']);await expect(dialog.getByLabel('Link destination',{exact:true})).toHaveAttribute('readonly','');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await currentSource(page)).toBe(conflict);
});
test('shared link drafts protect IME and retain Keep editing without replaying an old mode request',async({page})=>{
 const source='[One][id]\n\n[id]: old.md';await open(page,source,'[One][id]');const dialog=page.locator('.md-link-editor');await dialog.getByRole('button',{name:'Shared target (1 occurrences)',exact:true}).click();const destination=dialog.getByLabel('Link destination',{exact:true});await destination.fill('draft.md');expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);await dialog.getByRole('button',{name:'Keep editing',exact:true}).click();await destination.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog).toBeVisible();expect(await currentSource(page)).toBe(source);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);await destination.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await save(page);await expect.poll(()=>currentSource(page)).toBe(source.replace(': old.md',': <draft.md>'));expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');await undo(page,source);
});

test('a rich GFM cell resolves full-document references, discards shared drafts on cell Cancel and commits the definition once with the outer cell',async({page})=>{
 const source='[Outside][id]\n\n| A | B |\n| --- | --- |\n| [**Cell**][id] | untouched |\n\n[id]: old.md "author title"';
 await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),source);const preview=page.getByRole('button',{name:'Edit table cell: [**Cell**][id]',exact:true});await expect(preview).toBeVisible();
 async function draft(){await preview.focus();await preview.press('F2');const cell=page.locator('.md-table-inline-editor .cm-content');await cell.press('ControlOrMeta+A');expect(await page.evaluate(()=>(window as any).host.editor.command('link'))).toBe(true);const dialog=page.locator('.md-link-editor');await expect(dialog.locator('.md-link-label-preview strong')).toHaveText('Cell');await expect(dialog.getByLabel('Link destination',{exact:true})).toHaveValue('old.md');await dialog.getByRole('button',{name:'Shared target (2 occurrences)',exact:true}).click();await expect(dialog.locator('.md-link-reference-occurrences li')).toHaveText(['Outside — Line 1','Cell — Line 5']);await dialog.getByLabel('Link destination',{exact:true}).fill('new.md');await save(page);expect(await currentSource(page)).toBe(source);return cell;}
 const cancelled=await draft();await cancelled.press('Escape');expect(await currentSource(page)).toBe(source);await expect(page.locator('.md-table-inline-editor')).toHaveCount(0);
 await draft();expect(await page.evaluate(()=>(window as any).host.editor.prepareLeave())).toBe(true);const next=source.replace(': old.md ',': <new.md> ');await expect.poll(()=>currentSource(page)).toBe(next);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(true);await expect(page.getByRole('link',{name:'Outside',exact:true})).toHaveAttribute('href','new.md');await expect(page.getByRole('link',{name:'Cell',exact:true})).toHaveAttribute('href','new.md');expect(await page.evaluate(()=>(window as any).host.editor.setMode('live'))).toBe(true);await undo(page,source);
});
test('a footnote reference link changes current label and its full-document shared definition in one parent Undo',async({page})=>{
 const source="[Outside][id] and note[^n]\n\n[id]: old.md 'title'\n\n[^n]: [Note][id]";await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),source);const body=page.locator('[data-footnote-label="n"] .footnote-body .cm-content');await expect(body).toBeVisible();await body.focus();await body.press('ControlOrMeta+A');expect(await page.evaluate(()=>(window as any).host.editor.command('link'))).toBe(true);const dialog=page.locator('.md-link-editor');await expect(dialog.getByLabel('Link destination',{exact:true})).toHaveValue('old.md');await dialog.getByLabel('Display text',{exact:true}).fill('Changed');await dialog.getByRole('button',{name:'Shared target (2 occurrences)',exact:true}).click();await expect(dialog.locator('.md-link-reference-occurrences li')).toHaveText(['Outside — Line 1','Note — Line 5']);await dialog.getByLabel('Link destination',{exact:true}).fill('new.md');await save(page);await expect.poll(()=>currentSource(page)).toBe(source.replace(': old.md ',': <new.md> ').replace('[Note][id]','[Changed][id]'));await body.focus();expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);await expect.poll(()=>currentSource(page)).toBe(source);
});

test('reopened cell references show composed shared drafts, Cancel discards all and Complete needs exactly one parent Undo',async({page})=>{
 const source='[Outside][id]\n\n| A | B |\n| --- | --- |\n| [Cell][id] | untouched |\n\n[id]: old.md "author title"';
 for(const outcome of ['cancel','complete']){
  await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),source);const preview=page.getByRole('button',{name:'Edit table cell: [Cell][id]',exact:true});await preview.focus();await preview.press('F2');const cell=page.locator('.md-table-inline-editor .cm-content');
  async function sharedSave(expected:string,target:string){await cell.focus();await cell.press('ControlOrMeta+A');expect(await page.evaluate(()=>(window as any).host.editor.command('link'))).toBe(true);const dialog=page.locator('.md-link-editor');await expect(dialog.getByLabel('Link destination',{exact:true})).toHaveValue(expected);await dialog.getByRole('button',{name:'Shared target (2 occurrences)',exact:true}).click();await expect(dialog.locator('.md-link-reference-occurrences li')).toHaveText(['Outside — Line 1','Cell — Line 5']);await dialog.getByLabel('Link destination',{exact:true}).fill(target);await save(page);expect(await currentSource(page)).toBe(source);}
  await sharedSave('old.md','first-long-target.md');await sharedSave('first-long-target.md','final.md#heading');
  if(outcome==='cancel'){await cell.press('Escape');await expect(page.locator('.md-table-inline-editor')).toHaveCount(0);expect(await currentSource(page)).toBe(source);}
  else{expect(await page.evaluate(()=>(window as any).host.editor.prepareLeave())).toBe(true);await expect.poll(()=>currentSource(page)).toBe(source.replace(': old.md ',': <final.md#heading> '));await undo(page,source);}
 }
});
