import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function load(page:Page,value:string){await page.goto(url);await page.evaluate(text=>(window as any).host.load(text),value);await expect(page.locator('.cm-content').first()).toBeVisible();}
async function beginning(page:Page,text:string){const line=page.locator('.cm-line').filter({hasText:new RegExp('^'+text+'$')});await line.click({position:{x:Math.min(40,(await line.boundingBox())!.width-1),y:Math.max(1,(await line.boundingBox())!.height/2)}});await page.keyboard.press('Home');}
for(const [kind,object,widget]of [['code','```text\ncode\n```','.cm-live-code-block'],['table','| A | B |\n| --- | --- |\n| x | y |','.cm-live-table'],['image','![Actual alt](image.png)','.cm-live-image'],['diagram','```dot\ndigraph {a -> b}\n```','.cm-preview-widget.md-render-diagram']] as const)test(`natural ${kind} boundary selection, Escape, second deletion and three Undo/Redo cycles preserve both paragraphs`,async({page})=>{
 const original='before\n\n'+object+'\n\nafter';await load(page,original);await beginning(page,'after');const origin=await page.evaluate(()=>(window as any).host.editor.view.state.selection.main.head);await page.keyboard.press('Backspace');expect(await source(page)).toBe(original);await expect(page.locator(widget+'.cm-live-object-selected')).toBeVisible();const selected=await page.evaluate(()=>{const range=(window as any).host.editor.view.state.selection.main;return {from:range.from,to:range.to};});expect(original.slice(selected.from,selected.to).trim()).toBe(object);await page.keyboard.press('Escape');expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.view.state.selection.main.head)).toBe(origin);await page.keyboard.press('Backspace');await page.keyboard.press('Backspace');const deleted=await source(page);expect(deleted).not.toContain(object);expect(deleted).toMatch(/^before\n(?:\s*\n)+after$/);for(let n=0;n<3;n++){await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);await expect(page.locator(widget+'.cm-live-object-selected')).toBeVisible();const restored=await page.evaluate(()=>{const range=(window as any).host.editor.view.state.selection.main;return {from:range.from,to:range.to};});expect(restored).toEqual(selected);await page.keyboard.press('ControlOrMeta+Shift+z');await expect.poll(()=>source(page)).toBe(deleted);}await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);
});
test('natural system word selection sees formatted text and Chinese words without exposing hidden syntax',async({page})=>{
 const original='**hello** world\n\n你好世界';await load(page,original);await beginning(page,'hello world');await page.keyboard.press(await page.evaluate(()=>/Mac/.test(navigator.platform)?'Alt+Shift+ArrowRight':'Control+Shift+ArrowRight'));const selected=await page.evaluate(()=>{const view=(window as any).host.editor.view,range=view.state.selection.main;return view.state.sliceDoc(range.from,range.to);});expect(selected).toBe('hello');expect(await source(page)).toBe(original);await page.keyboard.press('Backspace');await expect.poll(()=>source(page)).toContain('world');expect(await source(page)).not.toContain('**');await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);await beginning(page,'你好世界');await page.keyboard.press(await page.evaluate(()=>/Mac/.test(navigator.platform)?'Alt+Shift+ArrowRight':'Control+Shift+ArrowRight'));const chinese=await page.evaluate(()=>{const view=(window as any).host.editor.view,range=view.state.selection.main;return view.state.sliceDoc(range.from,range.to);});const expected=await page.evaluate(()=>[...new Intl.Segmenter(undefined,{granularity:'word'}).segment('你好世界')].find(item=>item.isWordLike)!.segment);expect(chinese).toBe(expected);expect(chinese.length).toBeLessThan(4);expect(await source(page)).toBe(original);
});
test('an explicit saved empty paragraph is removed before an adjacent object is selected',async({page})=>{
 const original='before\n\n```text\ncode\n```\n\n<p><br></p>\n\nafter';await load(page,original);const empty=page.locator('.cm-line[data-explicit-empty=true]');await empty.click({position:{x:Math.min(40,(await empty.boundingBox())!.width-1),y:Math.max(1,(await empty.boundingBox())!.height/2)}});await page.keyboard.press('Home');await page.keyboard.press('Backspace');expect(await source(page)).not.toContain('<p><br></p>');expect(await source(page)).toContain('```text\ncode\n```');const range=await page.evaluate(()=>(window as any).host.editor.view.state.selection.main.empty);expect(range).toBe(true);await page.keyboard.press('Backspace');await expect(page.locator('.cm-live-code-block.cm-live-object-selected')).toBeVisible();
});
