import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function load(page:Page,value:string){await page.goto(url);await page.evaluate(text=>{const host=(window as any).host;host.load(text);const root=host.editor.view.dom;const state=(window as any).semanticClipboard={success:true,writes:[],hold:false,complete:null};for(const type of ['content','table'])root.addEventListener('tegg-copy-'+type,(raw:Event)=>{raw.preventDefault();const detail=(raw as CustomEvent).detail;state.writes.push({text:detail.text,html:detail.html,structured:detail.structured,mime:detail.mime});if(state.hold)state.complete=detail.complete;else detail.complete(state.success,'fixture clipboard failure');});},value);await expect(page.locator('.cm-content').first()).toBeVisible();}
async function uiUndo(page:Page,value:string){await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(value);}

test('ordinary keyboard Copy/Cut writes three semantic formats and retains source plus selection on failed ACK',async({page})=>{
 const original='before **bold** [label](secret.md) after';await load(page,original);await page.locator('.cm-content').first().focus();await page.keyboard.press('ControlOrMeta+a');await page.keyboard.press('ControlOrMeta+c');await expect.poll(()=>page.evaluate(()=>(window as any).semanticClipboard.writes.length)).toBe(1);const copied=await page.evaluate(()=>(window as any).semanticClipboard.writes[0]);expect(copied.text).toBe('before bold label after');expect(copied.text).not.toContain('secret.md');expect(copied.html).toContain('<strong>bold</strong>');expect(copied.html).toContain('href="secret.md"');expect(JSON.parse(copied.structured).source).toBe(original);
 const beforeSelection=await page.evaluate(()=>{const r=(window as any).host.editor.view.state.selection.main;return {anchor:r.anchor,head:r.head};});await page.evaluate(()=>(window as any).semanticClipboard.success=false);await page.keyboard.press('ControlOrMeta+x');await expect(page.locator('.md-clipboard-status')).toContainText('fixture clipboard failure');expect(await source(page)).toBe(original);expect(await page.evaluate(()=>{const r=(window as any).host.editor.view.state.selection.main;return {anchor:r.anchor,head:r.head};})).toEqual(beforeSelection);
 await page.evaluate(()=>(window as any).semanticClipboard.success=true);await page.keyboard.press('ControlOrMeta+x');await expect.poll(()=>source(page)).toBe('');await uiUndo(page,original);expect(await page.evaluate(()=>{const r=(window as any).host.editor.view.state.selection.main;return {anchor:r.anchor,head:r.head};})).toEqual(beforeSelection);
});
test('a delayed successful Cut ACK does not delete a new selection or replay after composition',async({page})=>{
 const original='alpha beta gamma';await load(page,original);await page.locator('.cm-content').first().focus();await page.keyboard.press('ControlOrMeta+a');await page.evaluate(()=>(window as any).semanticClipboard.hold=true);await page.keyboard.press('ControlOrMeta+x');await expect.poll(()=>page.evaluate(()=>!!(window as any).semanticClipboard.complete)).toBe(true);await page.keyboard.press('ArrowLeft');await page.evaluate(()=>(window as any).semanticClipboard.complete(true));await expect(page.locator('.md-clipboard-status')).toContainText('selection changed');expect(await source(page)).toBe(original);
});
test('GFM range keyboard Cut retains tracks, rich copy and range across failure, clear and Undo',async({page})=>{
 const original='before\n\n| A | B |\n| --- | --- |\n| **bold** | [label](secret.md) |\n\nafter';await load(page,original);const left=page.getByRole('button',{name:'Edit table cell: **bold**',exact:true});await left.focus();await left.press('Shift+ArrowRight');await expect(page.locator('[data-cell-state="selected"]')).toHaveCount(2);await page.evaluate(()=>(window as any).semanticClipboard.success=false);await page.keyboard.press('ControlOrMeta+x');await expect(page.locator('.md-table-error')).toContainText('fixture clipboard failure');expect(await source(page)).toBe(original);await expect(page.locator('[data-cell-state="selected"]')).toHaveCount(2);
 await page.evaluate(()=>(window as any).semanticClipboard.success=true);await page.keyboard.press('ControlOrMeta+x');await expect.poll(()=>source(page)).toBe(original.replace('| **bold** | [label](secret.md) |','|  |  |'));const copied=await page.evaluate(()=>(window as any).semanticClipboard.writes.at(-1));expect(copied.text).toBe('bold\tlabel');expect(copied.html).toContain('<strong>bold</strong>');expect(copied.html).toContain('href="secret.md"');expect(JSON.parse(copied.structured).cells).toHaveLength(2);await expect(page.locator('[data-cell-state="selected"]')).toHaveCount(2);
 await page.getByRole('button',{name:'Edit table cell: ',exact:true}).last().focus();await uiUndo(page,original);await expect(page.locator('[data-cell-state="selected"]')).toHaveCount(2);
});
test('GFM merge and explicit empty paragraph convert only after review and each Undo restores original bytes',async({page})=>{
 const original='before\n\n| A | B |\n| :--- | :--- |\n| **bold** | [label](secret.md) |\n\nafter';await load(page,original);const left=page.getByRole('button',{name:'Edit table cell: **bold**',exact:true});await left.focus();await left.press('Shift+ArrowRight');await page.getByLabel('Table actions',{exact:true}).selectOption('merge-cells');await expect(page.locator('.md-table-paste-review')).toBeVisible();expect(await source(page)).toBe(original);await page.getByRole('button',{name:'Apply reviewed change',exact:true}).click();await expect.poll(()=>source(page)).toContain('<td align="left" colspan="2"><strong>bold</strong><br><a href="secret.md">label</a></td>');await page.locator('.cm-live-html-table td').first().focus();await uiUndo(page,original);
 await page.getByRole('button',{name:'Edit table cell: **bold**',exact:true}).focus();await page.getByLabel('Table actions',{exact:true}).selectOption('keep-empty-paragraph');expect(await source(page)).toBe(original);await page.getByRole('button',{name:'Apply reviewed change',exact:true}).click();await expect.poll(()=>source(page)).toContain('<p><br></p>');expect((await source(page)).match(/<p><br><\/p>/g)).toHaveLength(1);await page.locator('.cm-live-html-table td').first().focus();await uiUndo(page,original);
});
test('HTML merged horizontal navigation retains the entered row through a rowspan',async({page})=>{
 const original='<table><tbody><tr><td>L1</td><td rowspan="2">Merged</td><td>R1</td></tr><tr><td>L2</td><td>R2</td></tr></tbody></table>';await load(page,original);const left=page.locator('.cm-live-html-table td').filter({hasText:'L2'});await left.focus();await left.press('ArrowRight');await expect(page.locator('.cm-live-html-table td').filter({hasText:'Merged'})).toBeFocused();await page.keyboard.press('ArrowRight');await expect(page.locator('.cm-live-html-table td').filter({hasText:'R2'})).toBeFocused();await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowLeft');await expect(left).toBeFocused();expect(await source(page)).toBe(original);
});
test('HTML Keep empty paragraph retains exactly one canonical empty block and has local then parent Undo',async({page})=>{
 const original='<table><tr><td><p data-original="keep">Text</p></td><td>Other</td></tr></table>';await load(page,original);const cell=page.locator('.cm-live-html-table td').first();await cell.focus();await cell.press('F2');await cell.press('End');await page.locator('.md-html-table-controls summary').click();await page.locator('.cm-live-html-table').getByRole('button',{name:'Keep empty paragraph',exact:true}).click();expect(await source(page)).toBe(original);await expect(cell.locator('p:not([data-tegg-temporary])')).toHaveCount(2);await expect(cell.locator('p:not([data-tegg-temporary])').last().locator('br')).toHaveCount(1);await cell.press('ControlOrMeta+z');await expect(cell.locator('p')).toHaveCount(1);await cell.press('ControlOrMeta+Shift+z');await expect(cell.locator('p:not([data-tegg-temporary])')).toHaveCount(2);await page.locator('.cm-live-html-table').getByRole('button',{name:'Done',exact:true}).click();await expect.poll(()=>source(page)).toBe(original.replace('<p data-original="keep">Text</p>','<p data-original="keep">Text</p><p><br></p>'));await page.locator('.cm-live-html-table td').first().focus();await uiUndo(page,original);
});

test('HTML rich list paragraph and sibling item actions preserve author attributes with local then one parent Undo',async({page})=>{
 const original="<table><tr><td><ul class='keep'><li data-x='keep'><strong title='rich'>AB</strong></li><li>other</li></ul></td><td>Untouched</td></tr></table>";await load(page,original);const cell=page.locator('.cm-live-html-table td').first();await cell.focus();await cell.press('F2');const strong=cell.locator('strong');await strong.click();await page.keyboard.press(await page.evaluate(()=>/Mac/.test(navigator.platform)?'Meta+ArrowLeft':'Home'));await page.keyboard.press('ArrowRight');await page.locator('.md-html-table-controls summary').click();await page.locator('.cm-live-html-table').getByRole('button',{name:'Insert list item',exact:true}).click();await expect(cell.locator('li')).toHaveCount(3);expect(await source(page)).toBe(original);await expect(cell.locator('li').nth(0)).toHaveText('A');await expect(cell.locator('li').nth(1)).toHaveText('B');await cell.press('ControlOrMeta+z');await expect(cell.locator('li')).toHaveCount(2);await strong.click();await page.keyboard.press(await page.evaluate(()=>/Mac/.test(navigator.platform)?'Meta+ArrowLeft':'Home'));await page.keyboard.press('ArrowRight');await page.locator('.md-html-table-controls summary').click();await page.locator('.cm-live-html-table').getByRole('button',{name:'Insert paragraph',exact:true}).click();await expect(cell.locator('li')).toHaveCount(2);await expect(cell.locator('li').first().locator(':scope > p')).toHaveCount(2);await expect(cell.locator('ul > p')).toHaveCount(0);expect(await source(page)).toBe(original);await page.locator('.cm-live-html-table').getByRole('button',{name:'Done',exact:true}).click();await expect.poll(()=>source(page)).toBe(original.replace("<strong title='rich'>AB</strong>","<p><strong title='rich'>A</strong></p><p><strong title='rich'>B</strong></p>"));await page.locator('.cm-live-html-table td').first().focus();await uiUndo(page,original);
});
