import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_CLIPBOARD_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
test.use({hasTouch:true,viewport:{width:390,height:844}});
async function tap(page:Page,selector:string){const box=await page.locator(selector).boundingBox();expect(box).not.toBeNull();await page.touchscreen.tap(box!.x+box!.width/2,box!.y+box!.height/2);}
test('touch GFM table selection and its later second tap enter a local rich editor without committing',async({page})=>{
 const original='Before\n\n| H | R |\n| --- | --- |\n| old | untouched |\n\nAfter';await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),original);const preview='.cm-live-table tbody tr:first-child td:first-child .cm-live-table-preview';await tap(page,preview);await expect(page.locator('.cm-live-table tbody tr:first-child td:first-child')).toHaveAttribute('data-cell-state','selected');await expect(page.locator('.md-table-inline-editor')).toHaveCount(0);expect(await source(page)).toBe(original);await page.waitForTimeout(750);await tap(page,preview);const child=page.locator('.md-table-inline-editor .cm-content');await expect(child).toBeVisible();await expect(child).toBeFocused();await page.keyboard.press('ControlOrMeta+a');await page.keyboard.type('Changed');await expect(child).toHaveText('Changed');expect(await source(page)).toBe(original);await child.press('Escape');await expect(page.locator('.md-table-inline-editor')).toHaveCount(0);expect(await source(page)).toBe(original);
});
test('touch HTML table selection and its later second tap enter the same cell draft and retain source until Done',async({page})=>{
 const original="Before\n\n<table class='keep'><tr><td><strong>old</strong></td><td>untouched</td></tr></table>\n\nAfter";await page.goto(url);await page.evaluate(value=>(window as any).host.load(value),original);const selector='.cm-live-html-table td:first-child';await tap(page,selector);await expect(page.locator(selector)).toHaveAttribute('aria-selected','true');await expect(page.locator(selector)).not.toHaveAttribute('contenteditable','true');expect(await source(page)).toBe(original);await page.waitForTimeout(750);await tap(page,selector);const cell=page.locator(selector);await expect(cell).toHaveAttribute('contenteditable','true');await cell.evaluate(node=>{const text=node.querySelector('strong')!.firstChild!,range=document.createRange();range.selectNodeContents(text);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);});await page.keyboard.type('Changed');expect(await source(page)).toBe(original);await page.locator('.md-html-table-controls').getByRole('button',{name:'Done',exact:true}).click();await expect.poll(()=>source(page)).toBe(original.replace('<strong>old</strong>','<strong>Changed</strong>'));await cell.focus();await page.keyboard.press('ControlOrMeta+z');await expect.poll(()=>source(page)).toBe(original);
});
