import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_VIEWER_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const raw='```text\nExact <&> code\nsecond line\n```\n\nEnd';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function boot(page:Page,mode:'reader'|'live'){
 await page.goto(url);await page.evaluate(({raw,mode})=>{const requests:Array<{text:string;resolve:()=>void;reject:(reason:unknown)=>void}>=[];(window as any).copyProof={requests};const host=(window as any).host;host.load(raw,{copyText:(text:string)=>new Promise<void>((resolve,reject)=>requests.push({text,resolve,reject}))});if(mode==='reader')host.editor.setMode('reader');},{raw,mode});const button=page.locator(mode==='reader'?'.tegg-reader':'.cm-content').getByRole('button',{name:'Copy code',exact:true});await expect(button).toHaveCount(1);return button;
}
test('technical Copy waits for the real Host completion contract and failures stay visible in Reader and Live',async({page})=>{
 for(const mode of ['reader','live'] as const){const button=await boot(page,mode);await button.focus();await button.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).copyProof.requests.length)).toBe(1);expect(await page.evaluate(()=>(window as any).copyProof.requests[0].text)).toBe('Exact <&> code\nsecond line');expect(await button.getAttribute('title')).not.toBe('Copied');await expect(button.locator('svg path[d="m5 12 4 4L19 6"]')).toHaveCount(0);await page.evaluate(()=>(window as any).copyProof.requests[0].reject(Error('actual denied')));await expect(page.getByRole('status').filter({hasText:'Copy unavailable'})).toBeVisible();expect(await button.getAttribute('title')).not.toBe('Copied');await expect(button.locator('svg path[d="m5 12 4 4L19 6"]')).toHaveCount(0);expect(await source(page)).toBe(raw);await button.focus();await button.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).copyProof.requests.length)).toBe(2);expect(await button.getAttribute('title')).not.toBe('Copied');await expect(button.locator('svg path[d="m5 12 4 4L19 6"]')).toHaveCount(0);await page.evaluate(()=>(window as any).copyProof.requests[1].resolve());await expect(button.locator('svg path[d="m5 12 4 4L19 6"]')).toBeVisible();expect(await source(page)).toBe(raw);}
});
test('a late Copy failure after document replacement cannot report into the next Reader or Live session',async({page})=>{
 for(const mode of ['reader','live'] as const){const button=await boot(page,mode);await button.focus();await button.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).copyProof.requests.length)).toBe(1);await page.evaluate(mode=>{const host=(window as any).host;host.editor.replaceDocument({documentId:'new-document',revision:'1',source:'Replacement'});if(mode==='reader')host.editor.setMode('reader');},mode);await page.evaluate(()=>(window as any).copyProof.requests[0].reject(Error('late failure')));await page.waitForTimeout(50);await expect(page.getByRole('status').filter({hasText:'Copy unavailable'})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).host.errors)).toEqual([]);expect(await source(page)).toBe('Replacement');}
});

test('IME takes precedence over the code Copy control without focus loss or replay',async({page})=>{
 const button=await boot(page,'live'),field=page.locator('.md-code-editor textarea');await field.focus();await field.evaluate(input=>{const f=input as HTMLTextAreaElement;f.setSelectionRange(2,6,'backward');f.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await button.click();await expect(field).toBeFocused();expect(await field.evaluate(input=>[input.selectionStart,input.selectionEnd,input.selectionDirection])).toEqual([2,6,'backward']);expect(await page.evaluate(()=>(window as any).copyProof.requests.length)).toBe(0);await field.evaluate(input=>input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await page.waitForTimeout(50);expect(await page.evaluate(()=>(window as any).copyProof.requests.length)).toBe(0);expect(await source(page)).toBe(raw);
});
test('old code Copy results do not decorate a changed current code body',async({page})=>{
 const button=await boot(page,'live');await button.focus();await button.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).copyProof.requests.length)).toBe(1);const field=page.locator('.md-code-editor textarea');await field.focus();await field.evaluate(input=>input.setSelectionRange(0,5));await page.keyboard.type('Updated');await expect.poll(()=>source(page)).toBe(raw.replace('Exact','Updated'));await page.evaluate(()=>(window as any).copyProof.requests[0].reject(Error('old body failure')));await page.waitForTimeout(50);await expect(page.getByRole('status').filter({hasText:'Copy unavailable'})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).host.errors)).toEqual([]);expect(await button.getAttribute('title')).not.toBe('Copied');await expect(button.locator('svg path[d="m5 12 4 4L19 6"]')).toHaveCount(0);expect(await source(page)).toBe(raw.replace('Exact','Updated'));
});
