import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_TECHNICAL_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
async function open(page:Page,original:string,kind:'math'|'mermaid'|'graphviz',object=original.slice(0,original.indexOf('\n\nEnd'))){
 await page.goto(url);await page.evaluate(({original,kind,object})=>{const h=(window as any).host;h.load(original);const from=original.indexOf(object);h.ui.openObject(kind,{from,to:from+object.length});},{original,kind,object});const panel=page.locator('.tegg-editing-panel:not([hidden])');await expect(panel).toBeVisible();return panel;
}
async function oneUndo(page:Page,original:string){expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(true);expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);}
for(const entry of [
 {kind:'math' as const,original:'$$\nx+1\n$$\n\nEnd',body:'x+1',invalid:'\\frac{1}{',valid:'x^2+2',label:'Formula source'},
 {kind:'mermaid' as const,original:'```mermaid\nflowchart TD\n A --> B\n```\n\nEnd',body:'flowchart TD\n A --> B',invalid:'flowchart TD\n A -->',extraInvalid:['flowchart TD\n A[unterminated','flowchart TD\n A @ B','pie\n "X": abc'],valid:'flowchart TD\n A --> C',label:'Diagram source'},
 {kind:'graphviz' as const,original:'```dot\ndigraph { a -> b }\n```\n\nEnd',body:'digraph { a -> b }',invalid:'digraph { a -> }',extraInvalid:['digraph { a[label=<<TABLE><TR><TD>no</TABLE>>] }'],valid:'digraph { a -> c }',label:'Diagram source'},
])test(`${entry.kind} real syntax errors block Done and protective Complete until corrected, with one exact Undo`,async({page})=>{
 const panel=await open(page,entry.original,entry.kind),field=panel.getByLabel(entry.label,{exact:true}),done=panel.getByRole('button',{name:'Done',exact:true});
 await expect(panel).toHaveAttribute('data-validation','valid');await field.fill(entry.invalid);await expect(panel).toHaveAttribute('data-validation','invalid');await expect(field).toHaveAttribute('aria-invalid','true');await expect(panel.locator('.tegg-technical-error')).toBeVisible();await expect(done).toBeDisabled();await field.press('ControlOrMeta+Enter');expect(await source(page)).toBe(entry.original);await expect(panel).toBeVisible();
 await field.press('Escape');const guard=panel.getByRole('dialog',{name:'Unsaved changes',exact:true});await expect(guard).toBeVisible();await expect(guard.getByRole('button',{name:'Complete and continue',exact:true})).toBeDisabled();await guard.getByRole('button',{name:'Keep editing',exact:true}).click();for(const invalid of entry.extraInvalid??[]){await field.fill(invalid);await expect(panel).toHaveAttribute('data-validation','invalid');await expect(done).toBeDisabled();expect(await source(page)).toBe(entry.original);}await field.fill(entry.valid);await expect(panel.locator('.tegg-technical-error')).toHaveCount(0);await expect(panel).toHaveAttribute('data-validation','valid');await expect(done).toBeEnabled();expect(await source(page)).toBe(entry.original);await done.click();await expect(panel).toHaveCount(0);expect(await source(page)).toBe(entry.original.replace(entry.body,entry.valid));await oneUndo(page,entry.original);
});
test('inline LaTeX validation preserves its author delimiters and surrounding rich source',async({page})=>{
 const original='Before **bold** $x+1$ after\n\nEnd',panel=await open(page,original,'math','$x+1$'),field=panel.getByLabel('Formula source',{exact:true});await field.fill('\\frac{1}{');await expect(panel.getByRole('button',{name:'Done',exact:true})).toBeDisabled();await field.fill('x^2+2');await expect(panel).toHaveAttribute('data-validation','valid');await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace('$x+1$','$x^2+2$'));await oneUndo(page,original);
});
test('controlled HTML math validates only decoded TeX body and preserves the author wrapper',async({page})=>{
 const object='<span data-tegg-math="inline" data-tex="x+1">Authored fallback</span>',original=object+'\n\nEnd',panel=await open(page,original,'math',object),field=panel.getByLabel('Formula source',{exact:true});await expect(field).toHaveValue('x+1');await expect(panel).toHaveAttribute('data-validation','valid');await field.fill('\\frac{1}{');await expect(panel).toHaveAttribute('data-validation','invalid');expect(await source(page)).toBe(original);await field.fill('x^2+2');await expect(panel).toHaveAttribute('data-validation','valid');await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace('data-tex="x+1"','data-tex="x^2+2"'));await oneUndo(page,original);
});
test('a real missing engine capability allows a valid technical draft to finish despite unavailable preview',async({page})=>{
 const original='$$\nx+1\n$$\n\nEnd';await page.goto(url);await page.evaluate(original=>{const h=(window as any).host;h.load(original,{engines:{}});h.ui.openObject('math',{from:0,to:original.indexOf('\n\nEnd')});},original);const panel=page.locator('.tegg-editing-panel:not([hidden])');await panel.getByLabel('Formula source',{exact:true}).fill('x^2+2');await expect(panel.getByRole('button',{name:'Done',exact:true})).toBeEnabled();expect(await source(page)).toBe(original);await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace('x+1','x^2+2'));await oneUndo(page,original);
});
test('late adapter validation cannot overwrite the current draft outcome or a replacement panel',async({page})=>{
 const original='$$\nx+1\n$$\n\nEnd';await page.goto(url);await page.evaluate(original=>{const w=window as any,h=w.host;w.validationRequests=[];const math=Object.assign(()=>'<span>Controlled preview adapter</span>',{validate:()=>new Promise(resolve=>w.validationRequests.push({resolve}))});h.load(original,{engines:{math}});h.ui.openObject('math',{from:0,to:original.indexOf('\n\nEnd')});},original);const panel=page.locator('.tegg-editing-panel:not([hidden])'),field=panel.getByLabel('Formula source',{exact:true}),done=panel.getByRole('button',{name:'Done',exact:true});await expect.poll(()=>page.evaluate(()=>(window as any).validationRequests.length)).toBe(1);await field.fill('x+2');await expect.poll(()=>page.evaluate(()=>(window as any).validationRequests.length)).toBe(2);await page.evaluate(()=>(window as any).validationRequests[1].resolve({status:'valid'}));await expect(done).toBeEnabled();await page.evaluate(()=>(window as any).validationRequests[0].resolve({status:'invalid',message:'Obsolete parser outcome'}));await expect(panel.locator('.tegg-technical-error')).toHaveCount(0);await expect(done).toBeEnabled();expect(await source(page)).toBe(original);await done.click();expect(await source(page)).toBe(original.replace('x+1','x+2'));await oneUndo(page,original);
 await page.evaluate(original=>(window as any).host.ui.openObject('math',{from:0,to:original.indexOf('\n\nEnd')}),original);await expect.poll(()=>page.evaluate(()=>(window as any).validationRequests.length)).toBe(3);await page.locator('.tegg-editing-panel:not([hidden])').getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(original=>(window as any).host.ui.openObject('math',{from:0,to:original.indexOf('\n\nEnd')}),original);const reopened=page.locator('.tegg-editing-panel:not([hidden])');await expect.poll(()=>page.evaluate(()=>(window as any).validationRequests.length)).toBe(4);await page.evaluate(()=>(window as any).validationRequests[2].resolve({status:'invalid',message:'Cancelled panel outcome'}));await expect(reopened).toHaveAttribute('data-validation','pending');await expect(reopened.locator('.tegg-technical-error')).toHaveCount(0);await page.evaluate(()=>(window as any).validationRequests[3].resolve({status:'valid'}));await expect(reopened.getByRole('button',{name:'Done',exact:true})).toBeEnabled();await reopened.getByRole('button',{name:'Cancel',exact:true}).click();expect(await source(page)).toBe(original);expect(await page.evaluate(()=>(window as any).host.editor.command('undo'))).toBe(false);
});
test('the preview validation budget permits saving a valid draft after an unavailable adapter',async({page})=>{
 const original='$$\nx+1\n$$\n\nEnd';await page.goto(url);await page.evaluate(original=>{const h=(window as any).host;const math=Object.assign(()=>{throw Error('Controlled preview load failure');},{validate:()=>new Promise(()=>{})});h.load(original,{engines:{math}});h.ui.openObject('math',{from:0,to:original.indexOf('\n\nEnd')});},original);const panel=page.locator('.tegg-editing-panel:not([hidden])');await panel.getByLabel('Formula source',{exact:true}).fill('x^2+2');await expect(panel.getByRole('button',{name:'Done',exact:true})).toBeDisabled();await expect(panel).toHaveAttribute('data-validation','unavailable',{timeout:5500});await expect(panel.getByRole('button',{name:'Done',exact:true})).toBeEnabled();expect(await source(page)).toBe(original);await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace('x+1','x^2+2'));await oneUndo(page,original);
});
test('IME blocks syntax completion and mode leave without focus loss or replay after composition',async({page})=>{
 const original='$$\nx+1\n$$\n\nEnd',panel=await open(page,original,'math'),field=panel.getByLabel('Formula source',{exact:true});await field.fill('x^2+2');await expect(panel).toHaveAttribute('data-validation','valid');await field.evaluate(node=>{const f=node as HTMLTextAreaElement;f.setSelectionRange(1,3,'backward');f.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await expect(panel.getByRole('button',{name:'Done',exact:true})).toBeDisabled();await field.press('ControlOrMeta+Enter');await expect(field).toBeFocused();expect(await field.evaluate(node=>{const f=node as HTMLTextAreaElement;return [f.selectionStart,f.selectionEnd,f.selectionDirection]})).toEqual([1,3,'backward']);expect(await page.evaluate(()=>(window as any).host.editor.setMode('reader'))).toBe(false);expect(await source(page)).toBe(original);await field.evaluate(node=>node.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await expect(panel).toBeVisible();expect(await page.evaluate(()=>(window as any).host.editor.mode)).toBe('live');expect(await source(page)).toBe(original);await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace('x+1','x^2+2'));await oneUndo(page,original);
});

test('a real failed Mermaid module request is preview unavailable and keeps valid draft completion available',async({page})=>{
 const blockedURLs:string[]=[];const mermaidModule=/\/(?:mermaid\.js|assets\/mermaid\.core-[A-Za-z0-9_-]+\.js)(?:\?|$)/;await page.route(mermaidModule,async route=>{blockedURLs.push(route.request().url());await route.abort('failed');});
 const original='```mermaid\nflowchart TD\n A --> B\n```\n\nEnd',panel=await open(page,original,'mermaid');await expect.poll(()=>blockedURLs.length).toBeGreaterThan(0);for(const blockedURL of blockedURLs)expect(new URL(blockedURL).pathname).toMatch(/\/(?:mermaid\.js|assets\/mermaid\.core-[A-Za-z0-9_-]+\.js)$/);await expect(panel).toHaveAttribute('data-validation','unavailable');const field=panel.getByLabel('Diagram source',{exact:true});await field.fill('flowchart TD\n A --> C');await expect(panel).toHaveAttribute('data-validation','unavailable');await expect(panel.getByRole('button',{name:'Done',exact:true})).toBeEnabled();expect(await source(page)).toBe(original);await panel.getByRole('button',{name:'Done',exact:true}).click();expect(await source(page)).toBe(original.replace('A --> B','A --> C'));await oneUndo(page,original);
});
