import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEGG_VIEWER_TEST_URL??'http://127.0.0.1:18930/reliable.html';
const raw='```dot\ndigraph { A -> B }\n```\n\nOriginal **text**.';
const source=(page:Page)=>page.evaluate(()=>(window as any).host.editor.source as string);
for(const role of [{name:'Large',font:17,line:22,label:13,labelLine:18},{name:'AX1',font:28,line:34,label:23,labelLine:27},{name:'AX5',font:53,line:62,label:42,labelLine:51}])test(`viewer ${role.name} interface roles are independent of reading scale and remain accessible in both modes`,async({page})=>{
 for(const width of [390,640])for(const readingScale of [1,4])for(const mode of ['reader','live']){
  await page.setViewportSize({width,height:840});await page.goto(url);
  await page.evaluate(({role,readingScale,mode,raw})=>{const root=document.body;for(const [key,value] of Object.entries({'--tegg-ui-font':'system-ui,sans-serif','--tegg-ui-title-size':`${role.font}px`,'--tegg-ui-title-line':`${role.line}px`,'--tegg-ui-action-size':`${role.font}px`,'--tegg-ui-action-line':`${role.line}px`,'--tegg-ui-label-size':`${role.label}px`,'--tegg-ui-label-line':`${role.labelLine}px`}))root.style.setProperty(key,value);const host=(window as any).host;host.load(raw);host.editor.setUI({mobile:true,overlayContainer:document.body});host.editor.view.dom.style.setProperty('--md-body',`${17*readingScale}px`);host.editor.view.dom.style.fontSize=`${17*readingScale}px`;if(mode==='reader'&&!host.editor.setMode('reader'))throw Error('Reader rejected');},{role,readingScale,mode,raw});
  const root=page.locator(mode==='reader'?'.tegg-reader':'.cm-content'),canvas=root.locator('.diagram-canvas');await expect(canvas).toHaveAttribute('data-render-state','ready');await canvas.locator('svg').first().evaluate(node=>{node.setAttribute('width','1000');node.setAttribute('height','2000');node.setAttribute('viewBox','0 0 1000 2000');});const entry=root.getByRole('button',{name:'View diagram',exact:true});await entry.focus();await entry.press('Enter');
  const viewer=page.locator('.md-object-viewer');await expect(viewer).toHaveAttribute('data-mobile','true');await expect(viewer).toHaveAttribute('data-natural-size','1000x2000');await expect(viewer).toHaveAttribute('data-viewer-scale',/^[0-9.]+$/);const before=await viewer.getAttribute('data-viewer-scale');
  const metrics=await viewer.evaluate(node=>{const title=node.querySelector('header strong')!,body=node.querySelector('.md-object-body')!;return {title:{font:getComputedStyle(title).fontSize,line:getComputedStyle(title).lineHeight},body:getComputedStyle(body).overflowY,buttons:[...node.querySelectorAll<HTMLButtonElement>('button')].map(button=>({label:button.getAttribute('aria-label')||button.textContent,font:getComputedStyle(button).fontSize,line:getComputedStyle(button).lineHeight,box:button.getBoundingClientRect().toJSON()})),width:node.clientWidth,scrollWidth:node.scrollWidth};});expect(metrics.title).toEqual({font:`${role.font}px`,line:`${role.line}px`});expect(metrics.body).toBe('auto');expect(metrics.scrollWidth-metrics.width).toBeLessThanOrEqual(1);for(const button of metrics.buttons){expect(button.font).toBe(`${role.font}px`);expect(button.line).toBe(`${role.line}px`);expect(button.box.width).toBeGreaterThanOrEqual(44);expect(button.box.height).toBeGreaterThanOrEqual(44);}
  const close=viewer.getByRole('button',{name:'Close',exact:true});await expect(close).toBeInViewport();for(const label of ['Fit','Actual size','+','\u2212']){const button=viewer.getByRole('button',{name:label,exact:true});await button.scrollIntoViewIfNeeded();await expect(button).toBeInViewport();const box=await button.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(width);}
  expect(await viewer.getAttribute('data-viewer-scale')).toBe(before);await close.click();await expect(viewer).toHaveCount(0);expect(await source(page)).toBe(raw);
 }
});
