import {registerRenderedClipboardOpaque} from './renderedSourceClipboard';
import {attachEditingUI} from './editingUI';
import {EditingController} from './editingController';
import {undo,history} from '@codemirror/commands';
// @vitest-environment jsdom
import {describe,it,expect,beforeAll,afterEach,vi} from 'vitest';
import {EditorState,EditorSelection} from '@codemirror/state';
import {EditorView} from '@codemirror/view';
import {markdown} from '@codemirror/lang-markdown';
import {GFM} from '@lezer/markdown';
import {resourceContext} from './editorHost';
import {semanticSelectionClipboard,copySemanticSelection,attachDomSemanticClipboard,attachInputSemanticClipboard,readContentClipboard} from './contentClipboard';
import {writeSemanticClipboard,contentClipboardType} from './clipboardTransport';
import {preparePaste,captureClipboard} from './clipboard';
import {markdownTableCopy,convertMarkdownTable,prepareMarkdownTablePaste} from './markdownTableClipboard';
const views:EditorView[]=[];
beforeAll(()=>{vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}});Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect=()=>new DOMRect();});
afterEach(()=>{for(const view of views)view.destroy();views.length=0;document.body.replaceChildren();});
function state(source:string,from=0,to=source.length){return EditorState.create({doc:source,selection:EditorSelection.single(from,to),extensions:[markdown({extensions:GFM}),resourceContext.of({documentPath:'',profile:'tegg'})]});}
function mount(source='**old** after'){const parent=document.body.appendChild(document.createElement('div')),view=new EditorView({parent,state:state(source)});views.push(view);return view;}
const tick=async()=>{for(let n=0;n<5;n++)await Promise.resolve();};
describe('semantic clipboard representations and acknowledgment',()=>{
 it('copies visible formatted labels without leaking the destination as ordinary text',()=>{const source='**bold** [label](https://example.com "title") &amp; `*literal*`',data=semanticSelectionClipboard(state(source));expect(data.text).toBe('bold label & *literal*');expect(data.html).toContain('<strong>bold</strong>');expect(data.html).toContain('href="https://example.com"');expect(readContentClipboard(data.structured).source).toBe(source);});
 it('keeps a selected part of strong text and a link in its original inline context',()=>{const source='**strong** and [label](target.md)';const strong=semanticSelectionClipboard(state(source,3,6));expect(strong.text).toBe('tro');expect(strong.html).toContain('<strong>tro</strong>');const from=source.indexOf('abel');const link=semanticSelectionClipboard(state(source,from,from+3));expect(link.text).toBe('abe');expect(link.html).toContain('href="target.md"');});
 it('includes hidden Callout content, literal code whitespace, image alt and TeX without generated descriptions',()=>{const source='> [!warning]- Title\n> hidden\n\n```text\n\t**literal**\n\n```\n\n![actual alt](image.png)\n\n$x+1$';const data=semanticSelectionClipboard(state(source));expect(data.text).toContain('Title');expect(data.text).toContain('hidden');expect(data.text).toContain('\t**literal**\n\n');expect(data.text).toContain('actual alt');expect(data.text).toContain('x+1');expect(readContentClipboard(data.structured).source).toBe(source);});
 it('copies only selected footnote dependencies from the full document and excludes literal code references',()=>{const full='body[^n]\n\n[^n]: rich **note**\n\n[^other]: untouched';const data=readContentClipboard(semanticSelectionClipboard(state('body[^n]'),full).structured);expect(data.definitions).toEqual(['[^n]: rich **note**']);expect(readContentClipboard(semanticSelectionClipboard(state('`[^n]`'),full).structured).definitions).toBeUndefined();});
 it('writes the exact three representations into one system copy event',async()=>{const trigger=document.body.appendChild(document.createElement('div')),values=new Map<string,string>();await writeSemanticClipboard(trigger,{text:'readable',html:'<strong>readable</strong>',structured:'semantic'},'content',{setData:(type,value)=>{values.set(type,value);}});expect([...values.keys()]).toEqual(['text/plain','text/html',contentClipboardType]);});
 it('does not perform a deletion before all native representations have been acknowledged',async()=>{const view=mount();let ack!:(ok:boolean)=>void,called=0;view.dom.addEventListener('tegg-copy-content',event=>{event.preventDefault();ack=(event as CustomEvent).detail.complete;});const copying=copySemanticSelection(view,{cut:true,delete:()=>{called++;return true;}});expect(called).toBe(0);ack(false);expect(await copying).toBe(false);expect(called).toBe(0);expect(view.state.doc.toString()).toBe('**old** after');});
 it('retains a changed document, selection and readonly transition after successful copying',async()=>{const view=mount();let ack!:(ok:boolean)=>void,called=0;view.dom.addEventListener('tegg-copy-content',event=>{event.preventDefault();ack=(event as CustomEvent).detail.complete;});const copying=copySemanticSelection(view,{cut:true,delete:()=>{called++;return true;}});view.dispatch({selection:{anchor:0,head:2}});ack(true);expect(await copying).toBe(false);expect(called).toBe(0);expect(view.state.doc.toString()).toBe('**old** after');expect(view.dom.textContent).toContain('Copied, but not cut');});
 it('captures Tegg semantic MIME and gives it priority without silently downgrading a corrupt copy',()=>{const source='> [!note]- Label\n> body',structured=JSON.stringify({version:1,kind:'content',format:'tegg',source});const input=captureClipboard({getData:type=>type===contentClipboardType?structured:type==='text/plain'?'plain':''});expect(preparePaste(input).markdown).toBe(source);expect(preparePaste({...input,structured:'{broken'}).status).toBe('needs-review');expect(preparePaste({...input,structured:'{broken'},{plainText:true}).markdown).toBe('plain');});
 it('cuts a literal input only after successful native acknowledgment and retains its innermost range',async()=>{const input=document.body.appendChild(document.createElement('textarea'));input.value='a\t**literal**\nz';input.focus();input.setSelectionRange(1,13);let ack!:(ok:boolean)=>void;input.addEventListener('tegg-copy-content',event=>{event.preventDefault();const data=(event as CustomEvent).detail;expect(data.text).toBe('\t**literal**');expect(data.html).toContain('<pre><code>');ack=data.complete;});attachInputSemanticClipboard(input,{format:'code',readOnly:()=>false,composing:()=>false,current:()=>true});input.dispatchEvent(new Event('cut',{bubbles:true,cancelable:true}));expect(input.value).toBe('a\t**literal**\nz');ack(true);await tick();expect(input.value).toBe('a\nz');});
});
describe('native semantic paste target ownership',()=>{
 function surface(){const view=mount('target');view.dispatch({selection:{anchor:0,head:6}});const controller=new EditingController(view,{identity:()=>({documentId:'native-doc',generation:'one',mode:'live',profile:'tegg'})}),ui=attachEditingUI(controller,document.body);return {view,controller,ui};}
 function paste(view:EditorView){const event=new Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:(type:string)=>type==='text/plain'?'contradictory plain':type==='text/html'?'<p>contradictory HTML</p>':'',types:['text/plain','text/html'],files:[]}});view.contentDOM.dispatchEvent(event);}
 it('uses the native content structure and copied definitions before contradictory event HTML/plain text',async()=>{const {view,controller,ui}=surface();let complete!:(data:unknown)=>void;view.dom.addEventListener('tegg-read-content',event=>{event.preventDefault();complete=(event as CustomEvent).detail.complete;});paste(view);expect(view.state.doc.toString()).toBe('target');const source='[Linked][ref] **bold** &amp; text',definition='[ref]: <secret.md> "exact"';complete({text:'readable',html:'<p>different</p>',structured:JSON.stringify({version:1,kind:'content',format:'tegg',source,definitions:[definition]})});for(let n=0;n<16;n++)await Promise.resolve();expect(view.state.doc.toString()).toBe(source+'\n\n'+definition);ui.destroy();controller.destroy();});
 it('refuses a delayed native paste after the actual target selection moves',async()=>{const {view,controller,ui}=surface();let complete!:(data:unknown)=>void;view.dom.addEventListener('tegg-read-content',event=>{event.preventDefault();complete=(event as CustomEvent).detail.complete;});paste(view);view.dispatch({selection:{anchor:0}});complete({text:'new'});for(let n=0;n<16;n++)await Promise.resolve();expect(view.state.doc.toString()).toBe('target');expect(ui.element.textContent).toContain('The paste target changed. Paste again.');ui.destroy();controller.destroy();});
});
describe('GFM range fidelity and reviewed conversions',()=>{
 const source='| H | R |\n| :--- | ---: |\n| **A** | [B](target.md) |',range={from:{row:0,column:0},to:{row:1,column:1}};
 it('copies readable cells plus rich HTML and the same controlled table schema',()=>{const data=markdownTableCopy(source,range);expect(data.text).toBe('H\tR\nA\tB');const matrix=JSON.parse(data.structured);expect(matrix.cells[2].html).toContain('<strong>A</strong>');expect(data.html).toContain('href="target.md"');});
 it('fills an explicitly selected rectangle from one scalar and refuses mismatched matrices',()=>{const result=prepareMarkdownTablePaste(source,range,{text:'x'});expect(result.requiresConfirmation).toBe(false);expect(result.source).toContain('| x | x |');expect(()=>prepareMarkdownTablePaste(source,range,{text:'a\tb\tc'})).toThrow(/different dimensions/);});
 it('preserves permanent image references and reports exact expansion counts without an unresolved token',()=>{const data=prepareMarkdownTablePaste(source,{from:{row:1,column:0},to:{row:1,column:0}},{text:'actual alt',html:'<img src="images/author.png" alt="actual alt" title="title">'});expect(data.source).toContain('![actual alt](<images/author.png> \"title\")');expect(data.source).not.toContain('TEGG');const expanded=prepareMarkdownTablePaste('| H |\n| --- |\n| old |',{from:{row:1,column:0},to:{row:1,column:0}},{text:'a\tb\nc\td'});expect(expanded.requiresConfirmation).toBe(true);expect(expanded.message).toContain('3 rows and 2 columns');expect(expanded.message).toContain('1 existing cells');expect(()=>prepareMarkdownTablePaste(source,{from:{row:1,column:0},to:{row:1,column:0}},{text:'image',html:'<img src="data:image/png;base64,x" alt="a">'})).toThrow(/persistent/);});
 it('reviews GFM-to-HTML merge with header roles, alignment, other formatting and no source mutation',()=>{expect(()=>convertMarkdownTable(source,{type:'merge',rectangle:{from:{row:1,column:0},to:{row:1,column:1}}})).toThrow(/attributes/);const merged=convertMarkdownTable(source.replace('---:',':---'),{type:'merge',rectangle:{from:{row:1,column:0},to:{row:1,column:1}}});expect(merged).toContain('colspan="2"');expect(merged).toContain('<strong>A</strong>');expect(merged).toContain('href="target.md"');expect(merged).toContain('align="left"');expect(merged).toContain('<th');expect(source).toContain('| **A** |');});
 it('requires a reviewed conversion for rich paragraphs and makes an explicit empty paragraph canonical',()=>{const result=prepareMarkdownTablePaste(source,{from:{row:1,column:0},to:{row:1,column:0}},{text:'first\nsecond',html:'<p>first</p><p>second</p>'});expect(result.requiresConfirmation).toBe(true);expect(result.source).toContain('<p>first</p><p>second</p>');const empty=convertMarkdownTable(source,{type:'paragraph',at:{row:1,column:0},before:'**A**',after:'',empty:true});expect(empty).toContain('<p><br></p>');expect(empty).toContain('<strong>A</strong>');});
});

describe('DOM copy author and generated-node ownership',()=>{
 async function copy(root:HTMLElement,range:Range){let data:Record<string,string>|undefined;const listener=(event:Event)=>{event.preventDefault();data=(event as CustomEvent).detail; (event as CustomEvent).detail.complete(true);};root.addEventListener('tegg-copy-content',listener);const stop=attachDomSemanticClipboard(root,{readOnly:()=>true}),selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);root.dispatchEvent(new Event('copy',{bubbles:true,cancelable:true}));await tick();stop();root.removeEventListener('tegg-copy-content',listener);return data!;}
 it('retains selected author classes and attributes while excluding only actual registered chrome',async()=>{const root=document.body.appendChild(document.createElement('div'));root.innerHTML='<p>before <span class="callout-icon" data-tegg-editor-projection="true">authored visible</span> after</p>';const chrome=document.createElement('span');chrome.className='callout-icon';chrome.textContent='generated icon';registerRenderedClipboardOpaque(chrome);root.querySelector('p')!.append(chrome);const range=document.createRange();range.setStart(root.querySelector('p')!.firstChild!,2);range.setEndAfter(chrome);const copied=await copy(root,range);expect(copied.text).toContain('authored visible');expect(copied.text).not.toContain('generated icon');expect(copied.html).toContain('authored visible');expect(copied.html).not.toContain('generated icon');expect(root.textContent).toContain('generated icon');});
 it('retains an inline ancestor and clips selected text while excluding a generated descendant',async()=>{const root=document.body.appendChild(document.createElement('div'));root.innerHTML='<p><strong>alpha <em>beta</em> gamma</strong></p>';const strong=root.querySelector('strong')!,chrome=document.createElement('button');chrome.textContent='generated actions';registerRenderedClipboardOpaque(chrome);strong.insertBefore(chrome,strong.lastChild);const range=document.createRange();range.setStart(strong.firstChild!,2);range.setEnd(strong.lastChild!,4);const data=await copy(root,range);expect(data.text).toBe('pha beta gam');expect(data.html).toContain('<strong>pha <em>beta</em> gam</strong>');expect(data.structured).not.toContain('generated actions');});
});

it('keeps a complete Reader CRLF selection and its exact reference dependency',()=>{const source='Before\r\n\r\n[Linked][ref] **bold**\r\n\r\nSecond &amp; text\r\n\r\nAfter\r\n\r\n[ref]: <secret.md> "Exact title"\r\n[unused]: other.md',from=source.indexOf('[Linked]'),to=source.indexOf('\r\n\r\nAfter'),value=EditorState.create({doc:source,selection:{anchor:from,head:to},extensions:[EditorState.lineSeparator.of('\n'),markdown({extensions:GFM}),resourceContext.of({documentPath:'',profile:'tegg'})]});expect(value.doc.toString()).toBe(source);const data=readContentClipboard(semanticSelectionClipboard(value).structured);expect(data.source).toBe(source.slice(from,to));expect(data.definitions).toEqual(['[ref]: <secret.md> "Exact title"']);});

it('refuses to copy generated control text when a selection endpoint is inside its actual owned UI',async()=>{const root=document.body.appendChild(document.createElement('div')),control=document.createElement('button');control.textContent='Generated title';root.append(control);registerRenderedClipboardOpaque(control);const stop=attachDomSemanticClipboard(root,{readOnly:()=>true}),listener=vi.fn();root.addEventListener('tegg-copy-content',listener);const range=document.createRange();range.selectNodeContents(control);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);const event=new Event('copy',{bubbles:true,cancelable:true});root.dispatchEvent(event);await tick();expect(event.defaultPrevented).toBe(true);expect(listener).not.toHaveBeenCalled();stop();});
