// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";
import {TeggMarkdownEditor} from "./editor";
import {ControlledExtensionRegistry,type ControlledExtension,type PreparedExtension} from "./controlledExtensions";
import {attachEditingUI} from "./editingUI";
import {bindUI} from "./uiContext";
const cleanup:Array<()=>void>=[];
const make=(source="before one after",profile:"tegg"|"gfm"="tegg")=>{const root=document.createElement("div");document.body.append(root);const editor=new TeggMarkdownEditor(root,{documentId:"one",revision:"r1",source,profile},{},"source");cleanup.push(()=>editor.destroy());return {editor,controller:editor.editing,root};};
const extension=(prepare:ControlledExtension["prepare"]=(context)=>({draft:context.session.draft.toUpperCase()})):ControlledExtension=>({id:"test.uppercase",version:"1.0.0",label:"Uppercase",prepare});
const deferred=<T,>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};};
afterEach(()=>{for(const stop of cleanup.splice(0).reverse())stop();document.body.replaceChildren();vi.useRealTimers();});
describe("controlled source draft extensions",()=>{
 it("requires namespaced unique IDs, versions and known capabilities",()=>{const {controller}=make();expect(()=>new ControlledExtensionRegistry(controller,[{...extension(),id:"plain"}])).toThrow("namespace");expect(()=>new ControlledExtensionRegistry(controller,[extension(),extension()])).toThrow("duplicate");expect(()=>new ControlledExtensionRegistry(controller,[{...extension(),version:"latest"}])).toThrow("metadata");});
 it("prepares a frozen local snapshot without editing then commits a reviewed draft once with undo",async()=>{const {controller,editor}=make();const session=controller.begin("selection",{from:7,to:10});const registry=new ControlledExtensionRegistry(controller,[extension(context=>{expect(Object.isFrozen(context.session)).toBe(true);expect(Object.keys(context)).toEqual(["identity","session","signal"]);return {draft:"ONE"};})]);cleanup.push(()=>registry.dispose());const prepared=await registry.prepare("test.uppercase",session.token);expect(prepared.status).toBe("ready");expect(editor.source).toBe("before one after");expect(controller.session?.draft).toBe("one");expect(registry.commit({...prepared} as PreparedExtension).ok).toBe(false);expect(registry.commit(prepared as PreparedExtension,"reviewed")).toEqual({ok:true,changed:true});expect(registry.commit(prepared as PreparedExtension)).toEqual({ok:true,changed:false});expect(editor.source).toBe("before reviewed after");controller.command("undo");expect(editor.source).toBe("before one after");});
 it("rejects whole-document selection, large drafts, parser/patch outputs and unsupported profiles",async()=>{const {controller}=make();let session=controller.begin("selection",{from:0,to:16});const prepare=vi.fn(()=>({draft:"x"}));const registry=new ControlledExtensionRegistry(controller,[extension(prepare)]);cleanup.push(()=>registry.dispose());expect(await registry.prepare("test.uppercase",session.token)).toMatchObject({status:"rejected",reason:"whole-document-extension-forbidden"});expect(prepare).not.toHaveBeenCalled();controller.cancel();session=controller.begin("selection",{from:1,to:2});const forbidden=new ControlledExtensionRegistry(controller,[extension(()=>({draft:"x",patches:[]}))]);expect(await forbidden.prepare("test.uppercase",session.token)).toMatchObject({status:"rejected",reason:"extension-must-return-local-draft"});forbidden.dispose();const large=new ControlledExtensionRegistry(controller,[extension(()=>({draft:"x".repeat(65_537)}))]);expect(await large.prepare("test.uppercase",session.token)).toMatchObject({status:"rejected",reason:"extension-draft-too-large"});large.dispose();const gfm=make("one","gfm");const unsupported=new ControlledExtensionRegistry(gfm.controller,[{...extension(),profiles:["tegg"]}]);expect(unsupported.list()[0]).toMatchObject({enabled:false,reason:"unsupported-profile"});unsupported.dispose();});
 it.each(["cancel","destroy","mode","target"] as const)("promptly rejects %s even when async preparation ignores abort",async operation=>{const {controller,editor}=make();const session=controller.begin("selection",{from:7,to:10});let signal!:AbortSignal;const result=deferred<{draft:string}>();const registry=new ControlledExtensionRegistry(controller,[extension(context=>{signal=context.signal;return result.promise;})]);const preparing=registry.prepare("test.uppercase",session.token);await Promise.resolve();if(operation==="cancel")registry.cancel();else if(operation==="destroy")registry.dispose();else if(operation==="mode")editor.setMode("live");else editor.view.dispatch({changes:{from:7,insert:"x"}});expect(signal.aborted).toBe(true);expect((await preparing).status).toBe("rejected");result.resolve({draft:"TOO LATE"});await Promise.resolve();expect(editor.source).not.toContain("TOO LATE");registry.dispose();});
 it("preserves draft changes and maps safe disjoint source edits",async()=>{const {controller,editor}=make();const session=controller.begin("selection",{from:7,to:10});const pending=deferred<{draft:string}>();const registry=new ControlledExtensionRegistry(controller,[extension(()=>pending.promise)]);const preparing=registry.prepare("test.uppercase",session.token);controller.updateDraft(session.token,"my words");pending.resolve({draft:"returned"});expect(await preparing).toMatchObject({status:"rejected",reason:"draft-changed"});expect(controller.session?.draft).toBe("my words");registry.dispose();const mapped=new ControlledExtensionRegistry(controller,[extension(()=>({draft:"ONE"}))]);const ready=await mapped.prepare("test.uppercase",session.token);editor.view.dispatch({changes:{from:0,insert:"prefix "}});expect(mapped.commit(ready as PreparedExtension).ok).toBe(true);expect(editor.source).toBe("prefix before ONE after");mapped.dispose();});
 it("times out ignored promises and rejects thrown errors without editing",async()=>{const {controller,editor}=make();const session=controller.begin("selection",{from:7,to:10});const registry=new ControlledExtensionRegistry(controller,[extension(()=>new Promise(()=>{}))],{timeoutMs:5});expect(await registry.prepare("test.uppercase",session.token)).toMatchObject({status:"rejected",reason:"extension-timeout"});registry.dispose();const failed=new ControlledExtensionRegistry(controller,[extension(()=>{throw new Error("offline");})]);expect(await failed.prepare("test.uppercase",session.token)).toMatchObject({status:"rejected",reason:"offline"});expect(editor.source).toBe("before one after");failed.dispose();});
 it("blocks read-only and IME prepare and never applies a result after composition starts",async()=>{const {controller,editor}=make();const session=controller.begin("selection",{from:7,to:10});const pending=deferred<{draft:string}>();const prepare=vi.fn(()=>pending.promise);const registry=new ControlledExtensionRegistry(controller,[extension(prepare)]);Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>true});expect(await registry.prepare("test.uppercase",session.token)).toMatchObject({status:"rejected",reason:"composing"});expect(prepare).not.toHaveBeenCalled();Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>false});const running=registry.prepare("test.uppercase",session.token);await Promise.resolve();Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>true});pending.resolve({draft:"ONE"});expect(await running).toMatchObject({status:"rejected",reason:"composing"});expect(editor.source).toBe("before one after");registry.dispose();});
 it("requires explicit UI Apply and inherits localization outside the editor surface",async()=>{const {root,controller,editor}=make();const outer=document.createElement("div");document.body.append(outer);const binding=bindUI(editor.view.dom,{locale:"zh-CN",messages:{"Review extension draft":"扩展草稿","Uppercase":"大写"}});cleanup.push(()=>binding.destroy());const ui=attachEditingUI(controller,outer,{extensions:[extension()]});cleanup.push(()=>ui.destroy());editor.view.dispatch({selection:{anchor:7,head:10}});await ui.openExtension("test.uppercase");await Promise.resolve();expect(outer.lang).toBe("");expect(ui.element.lang).toBe("zh-CN");expect(outer.querySelector("h2")?.textContent).toBe("扩展草稿");expect(editor.source).toBe("before one after");const raw=outer.querySelector("textarea")!;raw.value="reviewed";raw.dispatchEvent(new Event("input"));ui.setUI({locale:"en-US",messages:{}});[...outer.querySelectorAll("button")].find(button=>button.dataset.label==="Apply")!.click();expect(editor.source).toBe("before reviewed after");expect(root.querySelector(".cm-editor")).not.toBeNull();});
 it("keeps Cancel available while a Host extension waits and never reopens a closed panel",async()=>{const {root,controller,editor}=make();let signal!:AbortSignal;const ui=attachEditingUI(controller,root,{extensions:[extension(context=>{signal=context.signal;return new Promise(()=>{});})]});cleanup.push(()=>ui.destroy());editor.view.dispatch({selection:{anchor:7,head:10}});const running=ui.openExtension("test.uppercase");await Promise.resolve();ui.close();expect(signal.aborted).toBe(true);await running;expect(root.querySelector<HTMLElement>(".tegg-editing-panel")?.hidden).toBe(true);expect(editor.source).toBe("before one after");});
});
