// @vitest-environment jsdom
import {it,expect,vi,beforeEach} from 'vitest';
import {diagramDefaults,graphvizDisplaySource,mermaidDisplaySource} from './diagramDefaults';
const render=vi.fn(async(_id:string,source:string)=>({svg:source})),initialize=vi.fn();vi.mock('mermaid',()=>({default:{initialize,render}}));
beforeEach(()=>{document.body.replaceChildren();render.mockClear();initialize.mockClear();});
function surface(size:number,dark=false){const root=document.body.appendChild(document.createElement('div'));root.className='tegg-surface';root.dataset.theme=dark?'dark':'light';root.style.setProperty('--md-user-scale','1');root.style.setProperty('--background',dark?'#141416':'#ffffff');const target=root.appendChild(document.createElement('div'));target.style.fontSize=size+'px';target.style.fontFamily='system-ui';target.style.color=dark?'rgb(230, 230, 235)':'rgb(34, 35, 39)';return target;}
it('resolves actual body font before layout and mixes neutral nodes against the canvas',()=>{const normal=diagramDefaults(surface(15)),large=diagramDefaults(surface(24,true));expect(normal.fontSize).toBe(15);expect(large.fontSize).toBe(24);expect(normal.node).toBe('#f6f6f6');expect(large.canvas).toBe('#141416');expect(large.border).toBe('#7A7E85');});
it('prepends DOT defaults before author declarations without rewriting author bytes',()=>{const source='digraph "a{b" { /* { */ graph [bgcolor="red"]; node [fontsize=28]; A [color="green"] -> B; }',value=diagramDefaults(surface(20));const rendered=graphvizDisplaySource(source,value);expect(rendered).toContain('fontsize=15');expect(rendered.indexOf('fontsize=15')).toBeLessThan(rendered.indexOf('fontsize=28'));expect(rendered.endsWith(source.slice(source.indexOf('{ /*')+1))).toBe(true);expect(graphvizDisplaySource('not a graph',value)).toBe('not a graph');});
it('flowchart render defaults retain author default styles and leave other diagram languages unchanged',()=>{const value=diagramDefaults(surface(18)),source='flowchart LR\nA-->B\nclassDef default fill:red,stroke-width:5px;\nlinkStyle default stroke-width:4px';expect(mermaidDisplaySource(source,value)).toBe(source);expect(mermaidDisplaySource('sequenceDiagram\nA->>B: hi',value)).toBe('sequenceDiagram\nA->>B: hi');expect(mermaidDisplaySource('flowchart LR\nA-->B',value)).toContain('linkStyle default stroke-width:1.5px');});
it('serializes multi-root font and theme configuration through completed renders',async()=>{const {mermaidEngine}=await import('./engines/mermaid');let release!:()=>void;render.mockImplementationOnce(async()=>{await new Promise<void>(resolve=>release=resolve);return {svg:'first'};});const first=mermaidEngine('flowchart LR\nA-->B',surface(15),()=>true),second=mermaidEngine('flowchart LR\nC-->D',surface(24,true),()=>true);await vi.waitFor(()=>expect(render).toHaveBeenCalledTimes(1));expect(initialize.mock.calls[0][0].themeVariables.fontSize).toBe('15px');release();await expect(first).resolves.toBe('first');await second;expect(initialize.mock.calls[1][0].themeVariables.fontSize).toBe('24px');expect(initialize.mock.calls[1][0].themeVariables.darkMode).toBe(true);});
