// @vitest-environment jsdom
import {describe,it,expect,vi} from 'vitest';
import {inspectDocument,queryInspection,inspectionLocation,expandInspectionLocation,type InspectionKind} from './documentInspection';
import {EditorState} from '@codemirror/state';
import {EditorView} from '@codemirror/view';
import {markdown} from '@codemirror/lang-markdown';
import {ensureSyntaxTree} from '@codemirror/language';
import {GFM} from '@lezer/markdown';
import {resourceContext} from './editorHost';
import {livePreview} from './livePreview';
import {renderMarkdown} from './markdown';
import {ContentDisplaySession} from './contentDisplaySession';
const kinds=(source:string,kind:InspectionKind)=>queryInspection(inspectDocument(source),{kind});
const exact=(source:string,entry:{raw:string;sourceRange:{from:number;to:number}})=>expect(source.slice(entry.sourceRange.from,entry.sourceRange.to)).toBe(entry.raw);
describe('source-backed read-only document inspection',()=>{
 it('lists actual inline/hidden HTML comments and locates a standalone comment at its visible owner',()=>{const source='Before\r\n\r\n<!-- hidden &amp; text -->\r\n\r\nVisible <!-- inline --> tail\r\n';const model=inspectDocument(source),comments=queryInspection(model,{kind:'comment'});expect(comments.map(item=>item.raw)).toEqual(['<!-- hidden &amp; text -->','<!-- inline -->']);comments.forEach(item=>exact(source,item));expect(source.slice(comments[0].ownerRange.from,comments[0].ownerRange.to)).toBe('Visible <!-- inline --> tail');expect(source.slice(comments[1].ownerRange.from,comments[1].ownerRange.to)).toBe('Visible <!-- inline --> tail');expect(model.source).toBe(source);});
 it.each(['```html\n<!-- literal -->\n<a id="fake" style="color:red"></a>\n[r]: fake.md\n[^n]: fake note\n```','    <!-- literal -->\n    [r]: fake.md','`<!-- inline --> <a id="fake"></a>`','<pre><!-- literal --><span id="fake" style="color:red">text</span></pre>','<code><!-- literal --> <a id="fake"></a></code>','$[r]:fake.md$','$$\n<!-- literal -->\n[r]: fake.md\n$$'])('does not classify literal syntax %s',source=>{expect(inspectDocument(source).entries).toEqual([]);});
 it('excludes frontmatter but preserves original CRLF ranges for actual Markdown definitions',()=>{const source='---\r\nsecret: "<!-- metadata -->"\r\n---\r\n\r\n[label][ref]\r\n\r\n  [ref]:\r\n    <target.md>\r\n    "Title"\r\n[unused]: other.md\r\n';const defs=kinds(source,'shared-definition');expect(defs.map(item=>item.raw)).toEqual(['  [ref]:\r\n    <target.md>\r\n    "Title"','[unused]: other.md']);expect(defs.map(item=>item.referenceCount)).toEqual([1,0]);expect(defs.every(item=>item.definitionKind==='reference')).toBe(true);expect(kinds(source,'comment')).toEqual([]);defs.forEach(item=>exact(source,item));expect(source.slice(defs[0].ownerRange.from,defs[0].ownerRange.to)).toBe('[label][ref]');});
 it('only treats parser-accepted reference definitions as shared definitions',()=>{const source='[r]: javascript:alert(1)\n\n[label][r]\n\n> [valid]: target.md\n\n[valid]\n\n[x]: ok.md\n[x]: second.md';const defs=kinds(source,'shared-definition');expect(defs.map(item=>item.raw)).toEqual(['[valid]: target.md','[x]: ok.md','[x]: second.md']);expect(defs.map(item=>item.referenceCount)).toEqual([1,0,0]);expect(defs[0].sourceRange.from).toBe(source.indexOf('[valid]:'));});
 it('captures real footnote definitions, their usage count and visible owner without parsing code labels',()=>{const source='body[^a] and again[^a]\n\n[^a]: first **note**\n\n    continued\tline\n\n[^unused]: hidden\n\n`[^unused]`';const defs=kinds(source,'shared-definition').filter(item=>item.definitionKind==='footnote');expect(defs.map(item=>item.raw)).toEqual(['[^a]: first **note**\n\n    continued\tline','[^unused]: hidden']);expect(defs.map(item=>item.referenceCount)).toEqual([2,0]);expect(source.slice(defs[0].ownerRange.from,defs[0].ownerRange.to)).toBe('body[^a] and again[^a]');defs.forEach(item=>exact(source,item));expect(inspectDocument(source,'gfm').entries.some(item=>item.definitionKind==='footnote')).toBe(false);});
 it('records only actual heading IDs and applied HTML anchor attributes',()=>{const source='# A heading {#actual}\n\n# `literal {#fake}`\n\n<p id="body&amp;id">text <a name="legacy">mark</a></p>\n\n`<b id="inline-code">fake</b>`';const anchors=kinds(source,'anchor');expect(anchors.map(item=>item.label)).toEqual(['actual','body&id','legacy']);expect(anchors.map(item=>item.raw)).toEqual(['{#actual}','id="body&amp;id"','name="legacy"']);anchors.forEach(item=>exact(source,item));expect(inspectDocument('# heading {#not-enabled}','gfm').entries).toEqual([]);});
 it('distinguishes removed declarations from valid safe attributes and keeps source unchanged',()=>{const source='<p id="safe" title="title" class="author" style="color:red" onclick="run()" data-tegg-ui-text="fake">text <a href="javascript&#58;alert(1)" ping="https://example.test">link</a><img src="photo.png" alt="alt" srcset="photo2.png 2x"></p>';const removed=kinds(source,'unapplied-declaration');expect(removed.map(item=>item.raw)).toEqual(['style="color:red"','onclick="run()"','data-tegg-ui-text="fake"','href="javascript&#58;alert(1)"','ping="https://example.test"','srcset="photo2.png 2x"']);removed.forEach(item=>exact(source,item));expect(inspectDocument(source).source).toBe(source);});
 it('reports forbidden HTML elements without interpreting their literal contents as other hidden items',()=>{const source='<script>const s="<a id=\"fake\">"; <!-- fake --></script>\n\n<style>.x { color:red }</style>\n\n<iframe src="https://example.test"></iframe>';const model=inspectDocument(source);expect(model.entries.map(item=>item.kind)).toEqual(['unapplied-declaration','unapplied-declaration','unapplied-declaration']);expect(model.entries.map(item=>item.label)).toEqual(['script','style','iframe']);expect(model.entries[0].raw).toBe('<script>const s="<a id="fake">"; <!-- fake --></script>');});
 it('inventories explicitly written attributes in incomplete/implicit HTML without inventing a nested owner tree',()=>{const source='<p id="one" style="color:red">first<p id="two" onclick="run()">second';const model=inspectDocument(source);expect(queryInspection(model,{kind:'anchor'}).map(item=>item.label)).toEqual(['one','two']);expect(queryInspection(model,{kind:'unapplied-declaration'}).map(item=>item.raw)).toEqual(['style="color:red"','onclick="run()"']);expect(model.folds).toEqual([]);model.entries.forEach(item=>exact(source,item));});
 it('lists parser-owned HTML declarations without reading declarations inside literal code',()=>{const source='<!DOCTYPE html>\n<p>visible</p>\n\n`<!DOCTYPE fake>`';const model=inspectDocument(source),declaration=queryInspection(model,{kind:'unapplied-declaration'});expect(declaration.map(item=>item.raw)).toEqual(['<!DOCTYPE html>']);exact(source,declaration[0]);});
 it('locates an unused hidden definition at the next existing visible boundary rather than its invisible source',()=>{const source='[unused]: target.md\n\n# Visible heading';const model=inspectDocument(source),definition=model.entries.find(item=>item.kind==='shared-definition')!;expect(source.slice(definition.ownerRange.from,definition.ownerRange.to)).toBe('# Visible heading');});
 it('searches and filters the readonly inventory without changing it',()=>{const model=inspectDocument('<!-- Hidden alpha -->\n\n# Heading {#beta}\n\n[r]: target.md');const before=JSON.stringify(model);expect(queryInspection(model,{search:' ALPHA '}).map(item=>item.kind)).toEqual(['comment']);expect(queryInspection(model,{kind:'anchor',search:'beta'})).toHaveLength(1);expect(queryInspection(model,{kind:'anchor',search:'alpha'})).toEqual([]);expect(JSON.stringify(model)).toBe(before);});
 it('locates through only current collapsed Callout layers and expands once without changing source',()=>{const source='> [!note]- Outer\n> > [!tip]- Inner\n> > visible <!-- nested -->';const model=inspectDocument(source),comment=queryInspection(model,{kind:'comment'})[0],session=new ContentDisplaySession();expect(comment.foldPath.map(item=>item.kind)).toEqual(['callout','callout']);const location=inspectionLocation(model,comment,source,session,{projection:'live'});expect(location.foldsToExpand).toHaveLength(2);const first=comment.foldPath[0];session.setExpanded(first.kind,first.sessionFrom,first.sessionTo,true);expect(inspectionLocation(model,comment,source,session).foldsToExpand).toHaveLength(1);expandInspectionLocation(location,session);expect(inspectionLocation(model,comment,source,session).foldsToExpand).toEqual([]);expect(model.source).toBe(source);expect(source).toContain('[!note]-');});
 it('uses whole HTML container keys for nested Details and only expands currently closed levels',()=>{const source='<details><summary>Outer</summary><details open><summary>Inner</summary><p><!-- nested -->body</p></details></details>';const model=inspectDocument(source),comment=queryInspection(model,{kind:'comment'})[0],session=new ContentDisplaySession();expect(comment.foldPath).toHaveLength(2);expect(model.folds.map(item=>item.sessionTo)).toEqual([source.length,source.length]);const location=inspectionLocation(model,comment,source,session);expect(location.foldsToExpand).toHaveLength(1);expect(location.foldsToExpand[0].keyFrom).toBe(0);expect(location.foldsToExpand[0].keyTo).toBe(source.length);expandInspectionLocation(location,session);expect(inspectionLocation(model,comment,source,session).foldsToExpand).toEqual([]);expect(source).toBe(model.source);});
 it('maps Reader fold keys to its normalized body offsets while retaining exact source ranges',()=>{const source='---\r\na: 1\r\n---\r\n\r\n> [!note]- Outer\r\n> visible <!-- hidden -->\r\n';const model=inspectDocument(source),comment=queryInspection(model,{kind:'comment'})[0],fold=comment.foldPath[0],session=new ContentDisplaySession();const location=inspectionLocation(model,comment,source,session,{projection:'reader'});expect(location.foldsToExpand[0].keyFrom).toBe(source.replace(/\r\n/g,'\n').indexOf('> [!note]'));expect(location.foldsToExpand[0].keyTo).toBe(source.replace(/\r\n/g,'\n').trimEnd().length);expect(fold.from).toBe(source.indexOf('> [!note]'));exact(source,comment);});
 it.each(['> [!note]- Outer\r\n> > [!tip]- Inner\r\n> > visible <!-- nested -->','<details><summary>Outer</summary><details><summary>Inner</summary><p><!-- nested -->body</p></details></details>','> [!note]- Outer\r\n> <details><summary>Inner</summary><p><!-- nested -->body</p></details>'])('uses the same real Reader renderer session keys for every collapsed ancestor: %s',async body=>{const source='---\r\na: 1\r\n---\r\n\r\n'+body+'\r\n';const calls:{kind:string;from:number;to:number;initial:boolean}[]=[];class Session extends ContentDisplaySession{override expanded(kind:string,from:number,to:number,initial:boolean){calls.push({kind,from,to,initial});return super.expanded(kind,from,to,initial);}}const session=new Session(),root=document.createElement('div');document.body.append(root);await renderMarkdown(source,root,{displaySession:session});const rendererCalls=calls.slice();const model=inspectDocument(source),entry=model.entries.find(item=>item.kind==='comment')!,location=inspectionLocation(model,entry,source,session,{projection:'reader'});expect(location.foldsToExpand).toHaveLength(2);for(const fold of location.foldsToExpand)expect(rendererCalls).toContainEqual({kind:fold.kind,from:fold.keyFrom,to:fold.keyTo,initial:false});expandInspectionLocation(location,session);await renderMarkdown(source,root,{displaySession:session});expect([...root.querySelectorAll<HTMLDetailsElement>('details')].every(node=>node.open)).toBe(true);expect([...root.querySelectorAll<HTMLElement>('blockquote.callout')].every(node=>node.dataset.calloutExpanded==='true')).toBe(true);expect(source).toBe(model.source);root.remove();});
 it('maps unused definitions and hidden-only Callout comments to existing visible boundaries',()=>{const source='> [!note]- Title\n> <!-- hidden -->\n\nAfter';const model=inspectDocument(source),entry=model.entries.find(item=>item.kind==='comment')!;expect(source.slice(entry.ownerRange.from,entry.ownerRange.to)).toBe('[!note]- Title');expect(entry.foldPath).toHaveLength(1);});
 it('keeps nested quote footnote source rails and excludes literal dependency labels from its count',()=>{const source='body[^n]\n\n> [^n]: quoted **note**\n>\n>     more';const model=inspectDocument(source),entry=model.entries.find(item=>item.definitionKind==='footnote')!;expect(entry.raw).toBe('> [^n]: quoted **note**\n>\n>     more');expect(entry.referenceCount).toBe(1);exact(source,entry);});
 it.each(['> [!note]- Outer\r\n> > [!tip]- Inner\r\n> > body <!-- hidden -->','<details><summary>Outer</summary><details><summary>Inner</summary><p><!-- hidden -->body</p></details></details>','> [!note]- Outer\r\n> <details><summary>Inner</summary><p><!-- hidden -->body</p></details>'])('uses normalized CM inventory against original CRLF Reader session keys: %s',async body=>{const original='---\r\na: 1\r\n---\r\n\r\n'+body+'\r\n',normalized=original.replace(/\r\n/g,'\n'),session=new ContentDisplaySession(),root=document.createElement('div');document.body.append(root);await renderMarkdown(original,root,{displaySession:session});const model=inspectDocument(normalized),entry=model.entries.find(item=>item.kind==='comment')!,location=inspectionLocation(model,entry,normalized,session,{projection:'reader'});expect(location.foldsToExpand).toHaveLength(2);expandInspectionLocation(location,session);await renderMarkdown(original,root,{displaySession:session});expect([...root.querySelectorAll<HTMLDetailsElement>('details')].every(node=>node.open)).toBe(true);expect([...root.querySelectorAll<HTMLElement>('blockquote.callout')].every(node=>node.dataset.calloutExpanded==='true')).toBe(true);expect(model.source).toBe(normalized);expect(original).not.toBe(normalized);expect(original.slice(original.indexOf('<!--'),original.indexOf('-->')+3)).toBe(entry.raw);root.remove();});
 it('maps an indented unused reference to a visible owner while preserving all author indentation',()=>{const source='  [unused]: target.md\n\nVisible';const model=inspectDocument(source),entry=model.entries[0];expect(entry.raw).toBe('  [unused]: target.md');expect(source.slice(entry.ownerRange.from,entry.ownerRange.to)).toBe('Visible');});
 it.each(['> [!note]- Outer\r\n> > [!tip]- Inner\r\n> > body <!-- hidden -->','<details><summary>Outer</summary><details><summary>Inner</summary><p><!-- hidden -->body</p></details></details>'])('maps original CRLF inventory onto actual Live CodeMirror projection session keys: %s',body=>{vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});if(!Range.prototype.getClientRects)Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;if(!Range.prototype.getBoundingClientRect)Range.prototype.getBoundingClientRect=()=>new DOMRect();const source='Before\r\n\r\n'+body+'\r\n\r\nAfter';const calls:{kind:string;from:number;to:number;initial:boolean}[]=[];class Session extends ContentDisplaySession{override expanded(kind:string,from:number,to:number,initial:boolean){calls.push({kind,from,to,initial});return super.expanded(kind,from,to,initial);}}const session=new Session(),parent=document.createElement('div');document.body.append(parent);const view=new EditorView({parent,state:EditorState.create({doc:source,selection:{anchor:source.replace(/\r\n/g,'\n').length},extensions:[markdown({extensions:GFM}),resourceContext.of({documentPath:'',profile:'tegg',displaySession:session}),livePreview]})});try{ensureSyntaxTree(view.state,view.state.doc.length,1000);view.dispatch({});const projectionCalls=calls.slice();expect(view.state.doc.toString()).toBe(source.replace(/\r\n/g,'\n'));const model=inspectDocument(source),entry=model.entries.find(item=>item.kind==='comment')!,location=inspectionLocation(model,entry,source,session,{projection:'live'});expect(location.foldsToExpand).toHaveLength(2);for(const fold of location.foldsToExpand)expect(projectionCalls).toContainEqual({kind:fold.kind,from:fold.keyFrom,to:fold.keyTo,initial:false});expandInspectionLocation(location,session);expect(inspectionLocation(model,entry,source,session,{projection:'live'}).foldsToExpand).toEqual([]);expect(view.state.doc.toString()).toBe(source.replace(/\r\n/g,'\n'));expect(model.source).toBe(source);}finally{view.destroy();parent.remove();vi.unstubAllGlobals();}});
 it('excludes literal Details from fold indices and retains following actual hidden HTML',()=>{const source='<pre><details><summary>literal</summary></details></pre><details><summary>Actual</summary><p><!-- hidden -->body</p></details>';const model=inspectDocument(source);expect(model.folds).toHaveLength(1);expect(model.folds[0].sessionFrom).toBe(0);expect(model.entries.filter(item=>item.kind==='comment')).toHaveLength(1);});
 it('retains definitions after a CRLF HTML boundary rather than treating the rest of the document as HTML',()=>{const source='<p>HTML</p>\r\n\r\n[label][r]\r\n\r\n[r]: target.md';const model=inspectDocument(source),definition=model.entries.find(item=>item.definitionKind==='reference')!;expect(definition.raw).toBe('[r]: target.md');expect(definition.referenceCount).toBe(1);expect(source.slice(definition.ownerRange.from,definition.ownerRange.to)).toBe('[label][r]');});
 it('does not expand display state when locating in Source',()=>{const source='> [!note]- Title\n> <!-- hidden -->\n> body',model=inspectDocument(source),session=new ContentDisplaySession(),comment=model.entries.find(item=>item.kind==='comment')!;expect(inspectionLocation(model,comment,source,session,{projection:'source'}).foldsToExpand).toEqual([]);expect(inspectionLocation(model,comment,source,session,{projection:'live'}).foldsToExpand).toHaveLength(1);});
 it('rejects changed source or a foreign entry instead of silently locating or expanding it',()=>{const model=inspectDocument('text <!-- hidden -->'),session=new ContentDisplaySession(),entry=model.entries[0];expect(()=>inspectionLocation(model,entry,model.source+'!',session)).toThrow(/changed/);expect(()=>inspectionLocation(model,{...entry},model.source,session)).toThrow(/changed/);});
});

describe('inspection sanitizer uses real table source context',()=>{
 const samples={
  caption:'<caption>Title</caption>',colgroup:'<colgroup><col></colgroup>',col:'<colgroup><col></colgroup>',
  thead:'<thead><tr><th>Heading</th></tr></thead>',tbody:'<tbody><tr><td>Body</td></tr></tbody>',tfoot:'<tfoot><tr><td>Footer</td></tr></tfoot>',
  tr:'<tr><td>Body</td></tr>',td:'<tbody><tr><td>Body</td></tr></tbody>',th:'<thead><tr><th>Heading</th></tr></thead>'
 };
 it.each(Object.entries(samples))('retains an applied %s in its actual table ancestry',(tag,body)=>{
  const source='<table>'+body+'</table>',model=inspectDocument(source);
  expect(model.entries.filter(entry=>entry.kind==='unapplied-declaration')).toEqual([]);
  expect(model.source).toBe(source);
 });
 it('does not label valid table containers as Cell secret declarations and keeps exact comment ownership',()=>{
  const source='<table><caption>Title</caption><colgroup><col></colgroup><thead><tr><th>Head</th></tr></thead><tbody><tr><td><details><summary>Folded</summary><p>Before <!-- Cell secret --> after</p></details></td></tr></tbody><tfoot><tr><td>Foot</td></tr></tfoot></table>\r\n\r\nEnd';
  const model=inspectDocument(source),matches=queryInspection(model,{search:'Cell secret'});
  expect(matches).toHaveLength(1);expect(matches[0].kind).toBe('comment');expect(matches[0].raw).toBe('<!-- Cell secret -->');
  expect(source.slice(matches[0].ownerRange.from,matches[0].ownerRange.to)).toBe('<p>Before <!-- Cell secret --> after</p>');
  expect(matches[0].foldPath).toHaveLength(1);expect(model.entries.filter(entry=>entry.kind==='unapplied-declaration')).toEqual([]);
  expect(model.source).toBe(source);
 });
 it('still reports truly unsafe table attributes and children while preserving exact source ranges',()=>{
  const source='<table><tbody><tr onclick="bad()"><td style="color:red"><iframe src="remote"></iframe><!-- hidden --></td></tr></tbody></table>';
  const model=inspectDocument(source),entries=queryInspection(model,{kind:'unapplied-declaration'});
  expect(entries.map(entry=>entry.raw)).toEqual(['onclick="bad()"','style="color:red"','<iframe src="remote"></iframe>']);
  for(const entry of entries)expect(source.slice(entry.sourceRange.from,entry.sourceRange.to)).toBe(entry.raw);
  expect(queryInspection(model,{kind:'comment'}).map(entry=>entry.raw)).toEqual(['<!-- hidden -->']);expect(model.source).toBe(source);
 });
 it('does not grant orphan table cells another valid table elsewhere as their rendering context',()=>{
  const source='<table><tbody><tr><td>applied</td></tr></tbody></table><td>orphan</td>',model=inspectDocument(source);
  expect(queryInspection(model,{kind:'unapplied-declaration'}).map(entry=>entry.raw)).toEqual(['<td>orphan</td>']);expect(model.source).toBe(source);
 });
});
describe('inspection follows the actual accepted footnote body projection',()=>{
 it.each(['\n','\r\n'])('maps the nested Details owner and fold to actual Reader/Live keys with %j',async newline=>{
  const source=['Use[^n]','','[^n]: <details><summary>Folded</summary><p>Before <!-- Secret --> after</p></details>'].join(newline),normalized=source.replace(/\r\n/g,'\n'),model=inspectDocument(source),entry=queryInspection(model,{kind:'comment'})[0];
  expect(entry.raw).toBe('<!-- Secret -->');exact(source,entry);expect(source.slice(entry.ownerRange.from,entry.ownerRange.to)).toBe('<p>Before <!-- Secret --> after</p>');expect(entry.foldPath).toHaveLength(1);
  expect(entry.foldPath[0]).toMatchObject({sessionFrom:15,sessionTo:94,readerSessionFrom:15,readerSessionTo:94});
  const readerSession=new ContentDisplaySession(),reader=document.body.appendChild(document.createElement('div'));await renderMarkdown(source,reader,{displaySession:readerSession});const readerDetails=reader.querySelector<HTMLDetailsElement>('.footnotes details')!;expect(readerDetails.open).toBe(false);expandInspectionLocation(inspectionLocation(model,entry,source,readerSession,{projection:'reader'}),readerSession);expect(readerDetails.open).toBe(true);expect(reader.querySelector('.footnotes details')).toBe(readerDetails);expect(model.source).toBe(source);reader.remove();
  vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});if(!Range.prototype.getClientRects)Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;if(!Range.prototype.getBoundingClientRect)Range.prototype.getBoundingClientRect=()=>new DOMRect();
  const session=new ContentDisplaySession(),parent=document.body.appendChild(document.createElement('div')),view=new EditorView({parent,state:EditorState.create({doc:source,selection:{anchor:0},extensions:[markdown({extensions:GFM}),resourceContext.of({documentPath:'',profile:'tegg',displaySession:session}),livePreview]})});
  try{ensureSyntaxTree(view.state,view.state.doc.length,1000);view.dispatch({});const child=parent.querySelector<HTMLDetailsElement>('.cm-live-footnotes details')!;expect(child).not.toBeNull();expect(child.open).toBe(false);const selection=view.state.selection;expandInspectionLocation(inspectionLocation(model,entry,source,session,{projection:'live'}),session);expect(child.open).toBe(true);expect(parent.querySelector('.cm-live-footnotes details')).toBe(child);expect(view.state.doc.toString()).toBe(normalized);expect(view.state.selection.eq(selection)).toBe(true);expect(inspectionLocation(model,entry,source,session,{projection:'live'}).foldsToExpand).toEqual([]);}finally{view.destroy();parent.remove();vi.unstubAllGlobals();}
 });
 it.each(['\n','\r\n'])('keeps continuation rails in original ranges while excluding the definition header from its nested owner: %j',newline=>{
  const source=['Use[^n]','','[^n]: <details>','    <summary>Folded</summary>','    <p>Before <!-- Secret --> after</p>','    </details>'].join(newline),model=inspectDocument(source),entry=queryInspection(model,{kind:'comment'})[0];
  exact(source,entry);expect(entry.raw).toBe('<!-- Secret -->');expect(source.slice(entry.ownerRange.from,entry.ownerRange.to)).toBe('<p>Before <!-- Secret --> after</p>');expect(entry.foldPath).toHaveLength(1);expect(entry.foldPath[0].sessionFrom).toBe(15);expect(queryInspection(model,{kind:'shared-definition'})[0].raw).toBe(source.slice(source.indexOf('[^n]:')));expect(model.source).toBe(source);
 });
 it.each(['`[^n]: <details><!-- literal --></details>`','```md\n[^n]: <details><!-- literal --></details>\n```'])('does not invent an accepted footnote body inside literal syntax: %s',source=>{expect(inspectDocument(source).entries).toEqual([]);expect(inspectDocument(source).folds).toEqual([]);});
});
describe('accepted footnote body inspection retains real syntax authority',()=>{
 it('keeps global shared-reference usage in the projected footnote body',()=>{const source='Use[^n]\n\n[^n]: [label][r] <!-- note -->\n\n[r]: target.md',model=inspectDocument(source),reference=model.entries.find(entry=>entry.definitionKind==='reference')!;expect(reference.raw).toBe('[r]: target.md');expect(reference.referenceCount).toBe(1);const comment=queryInspection(model,{kind:'comment'})[0];expect(comment.raw).toBe('<!-- note -->');expect(source.slice(comment.ownerRange.from,comment.ownerRange.to)).toBe('[label][r] <!-- note -->');expect(model.source).toBe(source);});
 it('classifies actual nested anchors and removed attributes without admitting code-literal markup',()=>{const source='Use[^n]\n\n[^n]: <details><summary>Folded</summary><p id="actual" onclick="bad()">Before <!-- Secret --> after <code>&lt;a id="fake"&gt;<!-- literal --></code></p></details>',model=inspectDocument(source);expect(queryInspection(model,{kind:'anchor'}).map(entry=>entry.raw)).toEqual(['id="actual"']);expect(queryInspection(model,{kind:'unapplied-declaration'}).map(entry=>entry.raw)).toEqual(['onclick="bad()"']);expect(queryInspection(model,{kind:'comment'}).map(entry=>entry.raw)).toEqual(['<!-- Secret -->']);for(const entry of model.entries)exact(source,entry);expect(model.source).toBe(source);});
 it('maps both actual nested Details keys through the footnote header and metadata CRLF',()=>{const source='---\r\na: 1\r\n---\r\n\r\nUse[^n]\r\n\r\n[^n]: <details><summary>Outer</summary><details><summary>Inner</summary><p><!-- Secret -->body</p></details></details>',normalized=source.replace(/\r\n/g,'\n'),model=inspectDocument(source),entry=queryInspection(model,{kind:'comment'})[0],bodyFrom=normalized.indexOf('<details>');expect(entry.foldPath).toHaveLength(2);expect(entry.foldPath.map(fold=>fold.sessionFrom)).toEqual([bodyFrom,bodyFrom+1]);expect(entry.foldPath.map(fold=>fold.readerSessionFrom)).toEqual([bodyFrom,bodyFrom+1]);expect(source.slice(entry.ownerRange.from,entry.ownerRange.to)).toBe('<p><!-- Secret -->body</p>');for(const item of model.entries)exact(source,item);expect(model.source).toBe(source);});
});
