// @vitest-environment jsdom
import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {EditorState} from '@codemirror/state';
import {TeggMarkdownEditor} from './editor';
import {attachEditingUI} from './editingUI';
import {displaySessionFor} from './editorHost';
const cleanup:Array<()=>void>=[];
beforeAll(()=>{Range.prototype.getClientRects??=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect??=()=>new DOMRect();});
afterEach(()=>{cleanup.splice(0).reverse().forEach(stop=>stop());vi.restoreAllMocks();document.body.replaceChildren();});
function fixture(source:string,readOnly=false,copyText?:(text:string)=>Promise<void>){const root=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'inventory',revision:'r1',source,profile:'tegg'},{},readOnly?'reader':'source'),ui=attachEditingUI(editor.editing,root,{copyText});cleanup.push(()=>editor.destroy(),()=>ui.destroy());return {root,editor,ui};}
it('grants only an actual readonly inventory, supports raw search and ACK copy while leaving document and history unchanged',async()=>{
 let accept!:()=>void;const copy=vi.fn(()=>new Promise<void>(resolve=>accept=resolve)),source='<!-- Exact raw -->\n\n# Heading {#anchor}\n\n[ref]: old.md\n\n[Current][ref]',f=fixture(source,true,copy);
 expect(f.ui.inspectionElement).toBeNull();expect(f.ui.openInspection({projection:'reader'})).toBe(true);const panel=f.ui.inspectionElement!;expect(panel.getAttribute('role')).toBe('dialog');expect(f.ui.captureActiveDrafts()).toEqual([]);expect(panel.querySelectorAll('[data-label="Apply"]')).toHaveLength(0);
 const query=panel.querySelector<HTMLInputElement>('input')!;query.value='Exact';query.dispatchEvent(new Event('input',{bubbles:true}));expect(panel.querySelectorAll('.tegg-inspection-entries>details')).toHaveLength(1);panel.querySelector('details')!.open=true;panel.querySelector<HTMLButtonElement>('[data-label="Copy"]')!.click();expect(copy).toHaveBeenCalledWith('<!-- Exact raw -->');expect(panel.textContent).not.toContain('Copied');accept();await vi.waitFor(()=>expect(panel.textContent).toContain('Copied'));expect(f.editor.source).toBe(source);
 panel.querySelector<HTMLButtonElement>('[data-label="Close"]')!.click();expect(f.ui.inspectionElement).toBeNull();f.ui.openSearch();expect(f.ui.inspectionElement).toBeNull();expect(f.editor.source).toBe(source);
});
it('expands current session folds once and emits source-owned location without changing author open or text',()=>{
 const source='<details><summary>Title</summary><p>Hidden <!-- secret --></p></details>',f=fixture(source);expect(f.ui.openInspection({projection:'live'})).toBe(true);let result:any;f.root.addEventListener('tegg-inspection-locate',event=>result=(event as CustomEvent).detail);
 const panel=f.ui.inspectionElement!,item=panel.querySelector('details')!;item.open=true;const locate=item.querySelector<HTMLButtonElement>('[data-label="Locate"]')!;expect(locate.textContent).toBe('Locate and expand 1 levels');locate.click();expect(result).toMatchObject({sourceRange:{from:source.indexOf('<!--'),to:source.indexOf('-->')+3},identity:{documentId:'inventory',generation:expect.any(String)},expandedCount:1});expect(displaySessionFor(f.editor.view).expanded('html-details',0,source.length,false)).toBe(true);expect(f.editor.source).toBe(source);expect(f.ui.inspectionElement).toBeNull();expect(f.editor.command('undo')).toBe(false);
});
it('refuses IME and a dirty existing object without replaying inspection, and rejects stale inventory location',()=>{
 const source='$x$\n\n<!-- secret -->\n\nBody',f=fixture(source);f.ui.openObject('math',{from:0,to:3});const field=f.ui.element.querySelector<HTMLTextAreaElement>('.tegg-object-body')!;field.focus();field.value='local';field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(f.ui.openInspection()).toBe(false);expect(f.ui.inspectionElement).toBeNull();expect(document.activeElement===field||f.ui.element.contains(document.activeElement)).toBe(true);field.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(f.ui.openInspection()).toBe(false);expect(f.ui.awaitingLeaveChoice).toBe(true);f.ui.element.querySelector<HTMLButtonElement>('[data-label="Discard changes"]')!.click();expect(f.ui.inspectionElement).toBeNull();expect(f.editor.source).toBe(source);expect(f.ui.openInspection()).toBe(true);
 const panel=f.ui.inspectionElement!,item=panel.querySelector('details')!;item.open=true;f.editor.view.dispatch({changes:{from:f.editor.source.length,insert:' external'}});item.querySelector<HTMLButtonElement>('[data-label="Locate"]')!.click();expect(f.ui.inspectionElement).toBe(panel);expect(panel.textContent).toContain('The document changed. Reopen document inspection.');expect(f.editor.source).toBe(source+' external');
});

it('preserves original CRLF declaration bytes and original locate coordinates independently of normalized CodeMirror positions',()=>{
 const source='Visible\r\n\r\n[shared]: old.md "Keep"\r\n\r\n[Current][shared]',f=fixture(source),rangeStart=source.indexOf('[shared]:');expect(f.ui.openInspection({projection:'source'})).toBe(true);const panel=f.ui.inspectionElement!,item=panel.querySelector('details')!,raw=item.querySelector('pre')!;expect(raw.textContent).toBe('[shared]: old.md "Keep"');let located:any;f.root.addEventListener('tegg-inspection-locate',event=>located=(event as CustomEvent).detail);item.open=true;item.querySelector<HTMLButtonElement>('[data-label="Locate"]')!.click();expect(located.coordinates).toBe('source');expect(located.sourceRange.from).toBe(rangeStart);expect(located.ownerRange.from).toBe(source.indexOf('[Current]'));expect(f.editor.locateSourceRange(located.ownerRange)).toBe(true);expect(f.editor.view.state.selection.main.from).toBe(source.slice(0,source.indexOf('[Current]')).replace(/\r\n/g,'\n').length);expect(f.editor.source).toBe(source);
});
