// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";
import {TeggMarkdownEditor} from "./editor";
import {EditingController,objectAt} from "./editingController";
import {attachEditingUI} from "./editingUI";
import {ResourceTask,assertPersistentReference} from "./resourceTasks";
import {preparePaste} from "./clipboard";
import {bindEngines} from "./renderEngines";
import {readLinkDraft,serializeLinkDraft,serializeImageReference,unwrapLinkDraft} from "./objectDraft";
const cleanup:Array<()=>void>=[];
const make=(source="one two three",profile:"tegg"|"gfm"|"github"="tegg")=>{const root=document.createElement("div");document.body.append(root);const editor=new TeggMarkdownEditor(root,{documentId:"one",revision:"r1",source,profile},{},"source");cleanup.push(()=>editor.destroy());return {editor,controller:editor.editing,root};};
afterEach(()=>{for(const stop of cleanup.splice(0).reverse())stop();document.body.replaceChildren();});
describe("transactional object sessions",()=>{
 it("maps a target after a disjoint insertion, applies once and undoes as one action",()=>{const {editor,controller}=make();const draft=controller.begin("selection",{from:4,to:7});controller.updateDraft(draft.token,"TWO");editor.view.dispatch({changes:{from:0,insert:"prefix "}});expect(controller.session?.from).toBe(11);expect(controller.commit(draft.token)).toEqual({ok:true,changed:true});expect(controller.commit(draft.token)).toEqual({ok:true,changed:false});expect(editor.source).toBe("prefix one TWO three");controller.command("undo");expect(editor.source).toBe("prefix one two three");controller.command("redo");expect(editor.source).toBe("prefix one TWO three");});
 it.each([{from:4,to:5,insert:"x"},{from:4,insert:"x"},{from:7,insert:"x"}])("retains a stale draft when the target or boundary changes: %j",changes=>{const {editor,controller}=make();const session=controller.begin("selection",{from:4,to:7});controller.updateDraft(session.token,"my draft");editor.view.dispatch({changes});expect(controller.commit(session.token).ok).toBe(false);expect(controller.session).toMatchObject({draft:"my draft",status:"stale"});});
 it("cancel writes nothing and permits a new session",()=>{const {editor,controller}=make();const session=controller.begin();controller.updateDraft(session.token,"draft");controller.cancel(session.token);expect(controller.commit(session.token).ok).toBe(false);expect(editor.source).toBe("one two three");expect(()=>controller.begin()).not.toThrow();});
 it("rejects tokens from another instance",()=>{const a=make(),b=make();const session=a.controller.begin();expect(b.controller.commit(session.token).ok).toBe(false);});
 it("rejects stale generations while retaining the unsaved object draft",()=>{const {editor,controller}=make();const session=controller.begin();controller.updateDraft(session.token,"keep me");editor.replaceDocument({documentId:"two",revision:"r2",source:"different"});expect(controller.session?.draft).toBe("keep me");expect(controller.commit(session.token).ok).toBe(false);controller.cancel();const next=controller.begin("selection",{from:0,to:1});editor.view.dispatch({changes:{from:0,to:1,insert:"D"}});expect(controller.commit(next.token).ok).toBe(false);});
 it("gates read-only mode, composition and unsupported commands",()=>{const {editor,controller}=make("one","gfm");expect(controller.command("unknown")).toBe(false);expect(controller.command("mathBlock")).toBe(false);expect(()=>controller.begin("math")).toThrow();Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>true});expect(()=>controller.begin()).toThrow("composing");expect(controller.replace("one","two").ok).toBe(false);Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>false});editor.setMode("reader");expect(controller.command("bold")).toBe(false);});
 it("mode transitions preserve draft but invalidate its commit",()=>{const {editor,controller}=make();const session=controller.begin();controller.updateDraft(session.token,"retained");editor.setMode("live");expect(controller.commit(session.token).ok).toBe(false);expect(controller.session?.draft).toBe("retained");});
 it("detects object kinds without interpreting code contents",()=>{const {editor}=make("[link](url)\n\n```md\n![not](image)\n```\n\n$$\nx+y\n$$\n");expect(objectAt(editor.view.state,2)?.kind).toBe("link");expect(objectAt(editor.view.state,24)?.kind).toBe("code");expect(objectAt(editor.view.state,41)?.kind).toBe("math");});
 it("preserves CRLF and BOM on a local edit",()=>{const {editor,controller}=make("\ufeffone\r\ntwo\r\n");const session=controller.begin("selection",{from:1,to:4});controller.commit(session.token,"ONE");expect(editor.source).toBe("\ufeffONE\r\ntwo\r\n");});
 it("protects mixed newline sources from normal editing commands",()=>{const {editor,controller}=make("one\r\ntwo\n");expect(editor.view.state.readOnly).toBe(true);expect(controller.command("bold")).toBe(false);expect(editor.source).toBe("one\r\ntwo\n");});
 it("detaches listeners when repeatedly attaching a controller",()=>{const {editor,controller}=make();controller.destroy();for(let i=0;i<100;i++){const listener=vi.fn();const next=new EditingController(editor.view,{identity:()=>({documentId:"one",generation:"one"}),onSessionChange:listener});next.destroy();}const next=new EditingController(editor.view,{identity:()=>({documentId:"one",generation:"one"})});cleanup.push(()=>next.destroy());const session=next.begin("selection",{from:0,to:3});editor.view.dispatch({changes:{from:0,to:1,insert:"O"}});expect(next.commit(session.token).ok).toBe(false);});
});
describe("find and save contracts",()=>{
 it("replaces literal Unicode whole words in one undo",()=>{const {editor,controller}=make("🐈 Cat cat scatter CAT");expect(controller.find("cat",{wholeWord:true})).toHaveLength(3);expect(controller.replace("cat","猫",{wholeWord:true,all:true}).ok).toBe(true);expect(editor.source).toBe("🐈 猫 猫 scatter 猫");controller.command("undo");expect(editor.source).toBe("🐈 Cat cat scatter CAT");});
 it("bounds selection searches and rejects invalid offsets",()=>{const {controller}=make("one one one");expect(controller.find("one",{range:{from:4,to:7}})).toEqual([{from:4,to:7}]);expect(()=>controller.find("one",{range:{from:-1,to:3}})).toThrow();expect(controller.find("")).toEqual([]);});
 it("rejects forged saved source and retains later changes",()=>{const {editor}=make();const saved=editor.beginSave();expect(editor.acknowledgeSaved({...saved,source:"invented"},"r2")).toBe(false);editor.view.dispatch({changes:{from:0,insert:"new "}});expect(editor.acknowledgeSaved({...saved},"r2")).toBe(true);expect(editor.saveState).toBe("dirty");});
 it("blocks saves until all incoming hunks are resolved and preserves undo",()=>{const {editor}=make("first\nsecond\nthird\n");editor.view.dispatch({changes:{from:0,to:5,insert:"local"}});const incoming={documentId:"one",revision:"r2",source:"first\nexternal\nthird\n"};expect(editor.update(incoming)).toBe("conflict");expect(()=>editor.beginSave()).toThrow();const conflict=editor.conflict!;const decisions=Object.fromEntries(conflict.hunks.map(h=>[h.id,"apply" as const]));const result=editor.reconcile(conflict,decisions,incoming);expect(result.status).toBe("ready");expect(editor.source).toBe("local\nexternal\nthird\n");expect(editor.snapshot().baseRevision).toBe("r2");expect(editor.dirty).toBe(true);editor.command("undo");expect(editor.source).toBe("local\nsecond\nthird\n");});
});
describe("attachment operations",()=>{
 const file={id:"f",name:"cat.png",type:"image/png",size:3,blob:new Blob(["cat"],{type:"image/png"})};
 it("writes only a persistent reference after completion",async()=>{const {editor,controller}=make("");const session=controller.begin();const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:async()=>({reference:"assets/cat.png"})});expect((await task.run()).ok).toBe(true);expect(editor.source).toBe("![cat.png](<assets/cat.png>)");controller.command("undo");expect(editor.source).toBe("");task.destroy();});
 it("retains source after a failed upload and supports retry",async()=>{const {editor,controller}=make("");let attempt=0;const session=controller.begin();const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:async()=>{if(!attempt++)throw new Error("offline");return {reference:"assets/cat.png"};}});expect((await task.run()).ok).toBe(false);expect(editor.source).toBe("");expect(task.state.status).toBe("failed");expect((await task.run()).ok).toBe(true);task.destroy();});
 it("ignores a completion after cancellation even when the Host ignores AbortSignal",async()=>{const {editor,controller}=make("");let done!:(value:{reference:string})=>void;const session=controller.begin();const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:()=>new Promise(resolve=>{done=resolve;})});const running=task.run();task.cancel();done({reference:"assets/cat.png"});expect((await running).ok).toBe(false);expect(editor.source).toBe("");task.destroy();});
 it("ignores upload completion after a conflicting target edit",async()=>{const {editor,controller}=make("one");let done!:(value:{reference:string})=>void;const session=controller.begin("selection",{from:0,to:3});const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:()=>new Promise(resolve=>{done=resolve;})});const running=task.run();editor.view.dispatch({changes:{from:0,insert:"x"}});done({reference:"assets/cat.png"});expect((await running).ok).toBe(false);expect(editor.source).toBe("xone");task.destroy();});
 it.each(["blob:temporary","data:image/png;base64,abc","javascript:alert(1)","file:///tmp/cat.png"])("rejects nonportable references: %s",ref=>{expect(()=>assertPersistentReference(ref)).toThrow();});
});
describe("optional shared UI",()=>{
 it("retains raw draft on validation failure and commits a link once",()=>{const {root,editor,controller}=make("[one](https://example.com)");const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());editor.view.dispatch({selection:{anchor:3}});ui.openObject();const text=root.querySelector<HTMLTextAreaElement>("textarea")!;text.value="[two](https://example.com)";text.dispatchEvent(new Event("input"));[...root.querySelectorAll("button")].find(b=>b.textContent==="Apply")!.click();expect(editor.source).toBe("[two](https://example.com)");controller.command("undo");expect(editor.source).toBe("[one](https://example.com)");});
 it("complex paste cancellation leaves source and keeps no live panel",async()=>{const {root,editor,controller}=make("");const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());await ui.paste({html:'<table><tr><td colspan="2">hello</td></tr></table>',text:"hello"});expect(root.querySelector('[role="dialog"]')).not.toBeNull();ui.close();expect(editor.source).toBe("");expect(controller.session?.status).toBe("cancelled");});
 it("source-style reference links remain source drafts",()=>{expect(readLinkDraft("[label][ref]")).toBeNull();expect(()=>serializeLinkDraft({label:"new",url:"url"},"[label][ref]")).toThrow();expect(readLinkDraft('[hello](<assets/a%20b.md> "title")')).toEqual({label:"hello",url:"assets/a%20b.md",title:"title"});});
});

describe("lifecycle and semantic regressions",()=>{
 const deferred=<T,>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};};
 const file={id:"f",name:"cat.png",type:"image/png",size:3,blob:new Blob(["cat"],{type:"image/png"})};
 const click=(root:HTMLElement,label:string)=>[...root.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent===label)!.click();
 it("aborts resources synchronously when the session ends and never retries a cancelled task",async()=>{const {controller,editor}=make("");const stored=deferred<{reference:string}>();let signal!:AbortSignal;const session=controller.begin();const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:async(_file,context)=>{signal=context.signal;return stored.promise;}});const run=task.run();controller.cancel();expect(signal.aborted).toBe(true);stored.resolve({reference:"assets/x.png"});expect((await run).ok).toBe(false);expect((await task.run()).ok).toBe(false);expect(editor.source).toBe("");task.destroy();});
 it("does no resource I/O when composition or readonly blocks the captured session",async()=>{const {controller,editor}=make("");const session=controller.begin();const store=vi.fn();const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:store});Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>true});expect(await task.run()).toMatchObject({ok:false,reason:"composing"});Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>false});editor.setMode("reader");expect((await task.run()).ok).toBe(false);expect(store).not.toHaveBeenCalled();task.destroy();});
 it("retains stored assets for retry after temporary IME and isolates throwing observers",async()=>{const {controller,editor}=make("");const session=controller.begin();const store=vi.fn(async()=>{Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>true});return {reference:"assets/cat.png"};});const task=new ResourceTask(controller,session.token,preparePaste({files:[file]}),{storeResource:store});task.subscribe(()=>{throw new Error("observer");});expect((await task.run()).ok).toBe(false);expect(task.state.references.f).toBe("assets/cat.png");Object.defineProperty(editor.view,"composing",{configurable:true,get:()=>false});expect((await task.run()).ok).toBe(true);expect(store).toHaveBeenCalledTimes(1);task.destroy();});
 it("old applied tokens cannot approve or close a later session",()=>{const {controller}=make("one");const old=controller.begin("selection",{from:0,to:1});controller.commit(old.token,"O");const next=controller.begin("selection",{from:1,to:2});expect(controller.commit(old.token).ok).toBe(false);expect(controller.session?.token).toBe(next.token);});
 it("matches full Unicode code points and treats combining marks as word characters",()=>{const {controller}=make("𐐀cat cat𐐀 cat́ cat 🐈");expect(controller.find("cat",{wholeWord:true})).toEqual([{from:17,to:20}]);expect(controller.find("\ud83d")).toEqual([]);});
 it("preserves raw labels while roundtripping titles and safe unwrapping",()=>{const original='[**bold** `x]y` &amp; \\[z\\]](<old> "title")';const fields=readLinkDraft(original)!;expect(fields.label).toBe("bold x]y & [z]");expect(unwrapLinkDraft(original)).toBe('**bold** `x]y` &amp; \\[z\\]');expect(unwrapLinkDraft("[label][reference]")).toBeNull();const title='a "quote" &copy; \\ slash\nline\ttab';const changed=serializeLinkDraft({...fields,url:"new",title},original);expect(readLinkDraft(changed)).toEqual({...fields,url:"new",title});expect(unwrapLinkDraft(changed)).toBe(unwrapLinkDraft(original));const image=serializeImageReference("assets/image.png","[alt] &copy;",title);expect(readLinkDraft(image)).toEqual({label:"[alt] &copy;",url:"assets/image.png",title});expect(readLinkDraft("[empty]()")).toEqual({label:"empty",url:""});expect(readLinkDraft("[balanced](path(a))")).toEqual({label:"balanced",url:"path(a)"});});
 it("automatically reinstalls optional paste UI after replaceDocument with no active draft",async()=>{const {root,controller,editor}=make("");const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());editor.replaceDocument({documentId:"new",revision:"r2",source:""});await Promise.resolve();const event=new Event("paste",{bubbles:true,cancelable:true});Object.defineProperty(event,"clipboardData",{value:{getData:(type:string)=>type==="text/html"?"<b>bold</b>":"",files:[],types:["text/html"]}});editor.view.contentDOM.dispatchEvent(event);await Promise.resolve();expect(event.defaultPrevented).toBe(true);await Promise.resolve();expect(editor.source).toBe("**bold**");});
 it("does not let a search panel replace another document and keeps own selection edits mapped",async()=>{const {root,controller,editor}=make("one one outside");const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());editor.view.dispatch({selection:{anchor:0,head:7}});ui.openSearch();const inputs=root.querySelectorAll<HTMLInputElement>("input");inputs[0].value="one";inputs[1].value="x";inputs[4].checked=true;click(root,"Replace");click(root,"Replace");expect(editor.source).toBe("x x outside");editor.replaceDocument({documentId:"new",revision:"r2",source:"one one"});await Promise.resolve();click(root,"Replace all");expect(editor.source).toBe("one one");expect(root.querySelector('.tegg-editing-ui [role="status"]')?.textContent).toContain("changed");});
 it("stages image replacement with original alt and title and supports generic file insertion",async()=>{const {root,controller,editor}=make('![**cat**](old "title")');const ui=attachEditingUI(controller,root,{chooseResource:async()=>({reference:"assets/new.png",alt:"ignored",title:"ignored"})});cleanup.push(()=>ui.destroy());ui.openObject("image",{from:0,to:editor.source.length});await ui.chooseResource(controller.session!);expect(editor.source).toBe('![**cat**](old "title")');expect(root.querySelector("textarea")?.value).toBe('![**cat**](<assets/new.png> "title")');click(root,"Apply");expect(editor.source).toContain("assets/new.png");controller.command("undo");expect(editor.source).toBe('![**cat**](old "title")');ui.destroy();editor.view.dispatch({selection:{anchor:editor.view.state.doc.length}});const files=attachEditingUI(controller,root,{chooseResource:async()=>({kind:"file",reference:"assets/report.pdf",alt:"report"})});cleanup.push(()=>files.destroy());await files.chooseResource();expect(editor.source).toContain("[report](<assets/report.pdf>)");});
 it("ignores a late Host picker after cancel and recovers cleanly from picker errors",async()=>{const {root,controller,editor}=make("");const completion=deferred<{reference:string}>();let signal!:AbortSignal;const ui=attachEditingUI(controller,root,{chooseResource:context=>{signal=context.signal;return completion.promise;}});cleanup.push(()=>ui.destroy());const run=ui.chooseResource();ui.close();expect(signal.aborted).toBe(true);completion.resolve({reference:"assets/late.png"});await run;expect(editor.source).toBe("");ui.destroy();const failed=attachEditingUI(controller,root,{chooseResource:async()=>{throw new Error("unavailable");}});cleanup.push(()=>failed.destroy());await failed.chooseResource();expect(controller.session?.status).toBe("cancelled");expect(()=>controller.begin()).not.toThrow();});
 it("keeps sanitized SVG in diagram draft previews and bounds large engine calls",async()=>{const {root,controller,editor}=make("```mermaid\nflowchart TD\nA --> B\n```");const render=vi.fn(async()=>'<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script><rect width="20" height="20" onclick="bad()"/></svg>');cleanup.push(bindEngines(editor.view.dom,{mermaid:render}));const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());ui.openObject("mermaid",{from:0,to:editor.source.length});await new Promise(r=>setTimeout(r,300));expect(root.querySelector(".tegg-object-preview svg rect")).not.toBeNull();expect(root.querySelector(".tegg-object-preview script")).toBeNull();expect(root.querySelector(".tegg-object-preview rect")?.hasAttribute("onclick")).toBe(false);const raw=root.querySelector<HTMLTextAreaElement>("textarea")!;raw.value="x".repeat(2049);raw.dispatchEvent(new Event("input"));await new Promise(r=>setTimeout(r,300));expect(render).toHaveBeenCalledTimes(1);expect(root.querySelector(".tegg-object-preview")?.textContent).toContain("too large");ui.close();expect(editor.source).toContain("flowchart");});
 it("preserves the absence of an existing image title when a picker supplies metadata",async()=>{const {root,controller,editor}=make("![cat](old)");const ui=attachEditingUI(controller,root,{chooseResource:async()=>({reference:"assets/new.png",title:"metadata"})});cleanup.push(()=>ui.destroy());ui.openObject("image",{from:0,to:editor.source.length});await ui.chooseResource(controller.session!);expect(readLinkDraft(root.querySelector("textarea")!.value)).toEqual({label:"cat",url:"assets/new.png"});expect(editor.source).toBe("![cat](old)");});

});


describe("structured object field preservation",()=>{
 const field=(root:HTMLElement,name:string)=>[...root.querySelectorAll("label")].find(label=>label.querySelector("span")?.textContent===name)!.querySelector<HTMLInputElement>("input")!;
 const edit=(root:HTMLElement,name:string,value:string)=>{const input=field(root,name);input.value=value;input.dispatchEvent(new Event("input"));};
 const apply=(root:HTMLElement)=>[...root.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent==="Apply")!.click();
 it.each(["link","image"] as const)("preserves untouched title entities and multiline label when editing a %s target",kind=>{
  const original=(kind==="image"?"!":"")+'[**first**\nsecond](old "line&#10;next&#9;tab &amp;copy;")';
  const {root,controller,editor}=make(original);const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());ui.openObject(kind,{from:0,to:editor.source.length});
  edit(root,"Target","assets/new.md");const raw=root.querySelector("textarea")!.value;
  expect(raw).toContain("[**first**\nsecond]");expect(readLinkDraft(raw)).toEqual({label:"first\nsecond",url:"assets/new.md",title:"line\nnext\ttab &copy;"});expect(editor.source).toBe(original);
  apply(root);expect(editor.source).toBe(raw);controller.command("undo");expect(editor.source).toBe(original);
 });
 it.each(["link","image"] as const)("preserves the current raw title when editing a %s label",kind=>{
  const original=(kind==="image"?"!":"")+'[first](old "initial")';
  const {root,controller,editor}=make(original);const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());ui.openObject(kind,{from:0,to:editor.source.length});
  const raw=root.querySelector("textarea")!;raw.value=(kind==="image"?"!":"")+'[first](old "line&#10;next&#9;tab &amp;copy;")';raw.dispatchEvent(new Event("input"));
  edit(root,kind==="image"?"Alternative text":"Text","replacement");expect(readLinkDraft(raw.value)).toEqual({label:"replacement",url:"old",title:"line\nnext\ttab &copy;"});expect(editor.source).toBe(original);
  apply(root);expect(readLinkDraft(editor.source)).toEqual({label:"replacement",url:"old",title:"line\nnext\ttab &copy;"});controller.command("undo");expect(editor.source).toBe(original);
 });
 it.each(["Target","Alternative text"])("retains existing image attributes after replacement and editing %s",async name=>{
  const original='![**first**\nsecond](old "line&#10;next&#9;tab &amp;copy;")';const {root,controller,editor}=make(original);
  const ui=attachEditingUI(controller,root,{chooseResource:async()=>({reference:"assets/replaced.png",alt:"metadata",title:"metadata"})});cleanup.push(()=>ui.destroy());ui.openObject("image",{from:0,to:editor.source.length});await ui.chooseResource(controller.session!);
  edit(root,name,name==="Target"?"assets/edited.png":"edited alt");const raw=root.querySelector("textarea")!.value;
  expect(readLinkDraft(raw)).toEqual({label:name==="Target"?"first\nsecond":"edited alt",url:name==="Target"?"assets/edited.png":"assets/replaced.png",title:"line\nnext\ttab &copy;"});expect(editor.source).toBe(original);
  apply(root);expect(editor.source).toBe(raw);controller.command("undo");expect(editor.source).toBe(original);
 });
 it("edits only the title and retains raw multiline label formatting",()=>{
  const original='[**first**\nsecond](old "previous")';const {root,controller,editor}=make(original);const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());ui.openObject("link",{from:0,to:editor.source.length});
  edit(root,"Title","");const raw=root.querySelector("textarea")!.value;expect(raw).toBe('[**first**\nsecond](<old> "")');expect(readLinkDraft(raw)).toEqual({label:"first\nsecond",url:"old"});apply(root);controller.command("undo");expect(editor.source).toBe(original);
 });
 it("keeps an absent title absent when another field changes",()=>{
  const {root,controller,editor}=make("[first](old)");const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());ui.openObject("link",{from:0,to:editor.source.length});edit(root,"Target","new");expect(root.querySelector("textarea")!.value).toBe("[first](<new>)");
 });
});


describe("literal editing UI input policy",()=>{
 const check=(root:HTMLElement)=>{
  const controls=[...root.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input[type="text"],textarea')];
  expect(controls.length).toBeGreaterThan(0);
  for(const control of controls){expect(control.getAttribute("autocorrect")).toBe("off");expect(control.getAttribute("autocapitalize")).toBe("none");expect(control.getAttribute("autocomplete")).toBe("off");expect(control.spellcheck).toBe(false);}
 };
 it("requests literal find/replace input and retains lowercase through blur and undo",()=>{
  const {root,controller,editor}=make("alpha beta alpha");const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());ui.openSearch();check(root);
  const fields=root.querySelectorAll<HTMLInputElement>('input[type="text"]');fields[0].value="alpha";fields[1].value="omega";
  fields[1].dispatchEvent(new Event("input"));fields[1].dispatchEvent(new FocusEvent("blur"));
  [...root.querySelectorAll("button")].find(b=>b.textContent==="Replace all")!.click();expect(editor.source).toBe("omega beta omega");controller.command("undo");expect(editor.source).toBe("alpha beta alpha");
 });
 it.each(['[alpha](target "omega")','```mermaid\ngraph LR; alpha-->omega\n```','---\nname: omega\n---'])('keeps object fields literal and cancellation source-faithful: %s',source=>{
  const {root,editor,controller}=make(source);const ui=attachEditingUI(controller,root);cleanup.push(()=>ui.destroy());editor.view.dispatch({selection:{anchor:Math.min(4,source.length)}});ui.openObject();check(root);ui.close();expect(editor.source).toBe(source);
 });
});
