// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {EditorView} from '@codemirror/view';
import {EditorState,Compartment} from '@codemirror/state';
import {resourceContext} from './editorHost';
import {createMetadataPanel,disposeMetadataPanel} from './metadata';
import {undo} from '@codemirror/commands';
import {liveLinks,editCurrentLink} from './liveLinks';
import {attachHtmlTableEditing,commitHtmlTableDrafts} from './htmlTableWidget';
import {createHtmlPreview} from './renderKit';
import {markdown} from '@codemirror/lang-markdown';
import {TeggMarkdownEditor} from './editor';
import {attachEditingUI,attachNestedEditingUI} from './editingUI';
const cleanup:Array<()=>void>=[];
afterEach(()=>{cleanup.splice(0).reverse().forEach(stop=>stop());vi.restoreAllMocks();document.body.replaceChildren();});
function fixture(){const root=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'one',revision:'r1',source:'$main$',profile:'tegg'},{},'source'),ui=attachEditingUI(editor.editing,root);cleanup.push(()=>editor.destroy(),()=>ui.destroy());return {editor,ui,root};}
function nested(parent:EditorView,source='$child$'){const root=document.body.appendChild(document.createElement('div')),view=new EditorView({parent:root,state:EditorState.create({doc:source,extensions:[markdown()]})}),scope=attachNestedEditingUI(parent,view)!;expect(scope).not.toBeNull();cleanup.push(()=>view.destroy(),()=>scope.destroy());return {view,scope,open:()=>scope.ui.openObject('math',{from:0,to:view.state.doc.length})};}
it('captures actual main and recursively registered nested draft ownership without using DOM classes',()=>{const f=fixture();f.ui.openObject('math',{from:0,to:f.editor.source.length});const child=nested(f.editor.view);child.open();const grand=nested(child.view,'$grand$');grand.open();const drafts=f.ui.captureActiveDrafts();expect(drafts.map(draft=>draft.controller)).toEqual([f.editor.editing,child.scope.controller,grand.scope.controller]);for(const draft of drafts){expect(draft.current()).toBe(true);expect(draft.kind).toBe('object');if(draft.kind==='object')expect(draft.controller.session!.token).toBe(draft.token);expect(draft.panel.getAttribute('role')).toBe('dialog');}const impostor=document.createElement('div');impostor.className='tegg-editing-panel';f.ui.element.append(impostor);expect(f.ui.captureActiveDrafts()).toHaveLength(3);});
it('excludes search, closed panels and unregistered Viewer DOM even when an external controller begins a session',()=>{const f=fixture();f.ui.openSearch();const fake=document.createElement('dialog');fake.className='md-object-panel';f.ui.element.append(fake);f.editor.editing.begin('selection',{from:0,to:1});expect(f.ui.captureActiveDrafts()).toEqual([]);f.ui.close();expect(f.ui.captureActiveDrafts()).toEqual([]);});
it('invalidates a captured nested ownership after cancellation and reuse of the same panel element',()=>{const f=fixture(),child=nested(f.editor.view);child.open();const [captured]=f.ui.captureActiveDrafts();expect(captured.current()).toBe(true);child.scope.ui.close();expect(captured.current()).toBe(false);child.open();const [next]=f.ui.captureActiveDrafts();expect(next.panel).toBe(captured.panel);expect(next.token).not.toBe(captured.token);expect(captured.current()).toBe(false);expect(next.current()).toBe(true);});
it('keeps existing fields and composition source-bound while rejecting document changes or destroyed children',()=>{const f=fixture(),child=nested(f.editor.view);child.open();const [captured]=f.ui.captureActiveDrafts(),raw=child.scope.ui.element.querySelector<HTMLTextAreaElement>('textarea')!;raw.value='$local$';raw.dispatchEvent(new Event('input',{bubbles:true}));expect(captured.current()).toBe(true);captured.panel.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(captured.current()).toBe(true);expect(child.scope.ui.isComposing).toBe(true);captured.panel.querySelector<HTMLButtonElement>('[data-label="Apply"]')!.click();expect(child.scope.controller.session!.status).toBe('editing');expect(child.view.state.doc.toString()).toBe('$child$');captured.panel.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));child.view.dispatch({changes:{from:1,to:2,insert:'X'}});expect(captured.current()).toBe(false);const [stale]=f.ui.captureActiveDrafts();expect(stale.kind).toBe('object');if(stale.kind==='object')expect(stale.controller.session!.status).toBe('stale');expect(stale.current()).toBe(true);child.scope.destroy();expect(stale.current()).toBe(false);expect(f.ui.captureActiveDrafts()).toEqual([]);});
it('invalidates a main ownership when its document identity changes and requires a new explicit snapshot',()=>{const f=fixture();f.ui.openObject('math',{from:0,to:f.editor.source.length});const [captured]=f.ui.captureActiveDrafts();f.editor.replaceDocument({documentId:'two',revision:'r2',source:'$main$'});expect(captured.current()).toBe(false);expect(f.ui.captureActiveDrafts()).toEqual([]);});

it('includes real dedicated nested links while generic panels are hidden and revokes close, reuse and identity changes',()=>{
 const f=fixture(),root=document.body.appendChild(document.createElement('div')),view=new EditorView({parent:root,state:EditorState.create({doc:'[old](old.md)',selection:{anchor:2},extensions:[markdown(),liveLinks]})});
 const scope=attachNestedEditingUI(f.editor.view,view)!;cleanup.push(()=>view.destroy(),()=>scope.destroy());vi.spyOn(view,'coordsAtPos').mockReturnValue({left:20,right:30,top:20,bottom:40});expect(editCurrentLink(view)).toBe(true);
 const [lease]=f.ui.captureActiveDrafts();expect(lease.kind).toBe('link');expect(lease.controller).toBeUndefined();expect(lease.token).toBeUndefined();expect(lease.current()).toBe(true);
 const field=lease.panel.querySelector<HTMLInputElement>('[data-tegg-ui-label="Link destination"]')!;field.value='draft.md';field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(lease.current()).toBe(true);field.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));
 lease.panel.querySelector<HTMLButtonElement>('[data-tegg-ui-text="Cancel"]')!.click();expect(lease.current()).toBe(false);expect(f.ui.captureActiveDrafts()).toEqual([]);expect(editCurrentLink(view)).toBe(true);const [next]=f.ui.captureActiveDrafts();expect(next.current()).toBe(true);expect(lease.current()).toBe(false);
 f.editor.replaceDocument({documentId:'two',revision:'r2',source:'$main$'});expect(next.current()).toBe(false);scope.destroy();expect(f.ui.captureActiveDrafts()).toEqual([]);
});

it.each([false,true])('extension drafts put their single Done action in the proper desktop/mobile location and preserve C4 composition and Undo (%s)',async mobile=>{
 const root=document.body.appendChild(document.createElement('div')),source='[old](old.md)',editor=new TeggMarkdownEditor(root,{documentId:'extension',revision:'r1',source,profile:'tegg'},{},'source'),ui=attachEditingUI(editor.editing,root,{mobile,extensions:[{id:'example.relabel',version:'1.0.0',label:'Relabel',profiles:['tegg'],kinds:['link'],prepare:async()=>({draft:'[reviewed](old.md)'})}]});cleanup.push(()=>editor.destroy(),()=>ui.destroy());editor.view.dispatch({selection:{anchor:2}});await ui.openExtension('example.relabel');
 const panel=ui.element.querySelector<HTMLElement>('.tegg-editing-panel')!,done=panel.querySelector<HTMLButtonElement>('[data-label="Apply"]')!,raw=panel.querySelector<HTMLTextAreaElement>('textarea')!;
 expect(done.textContent).toBe('Done');expect(panel.querySelectorAll('[data-label="Apply"]')).toHaveLength(1);expect(done.parentElement?.tagName).toBe(mobile?'HEADER':'FOOTER');expect(editor.source).toBe(source);expect(ui.captureActiveDrafts()).toHaveLength(1);
 raw.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));done.click();expect(editor.source).toBe(source);raw.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));done.click();expect(editor.source).toBe('[reviewed](old.md)');expect(ui.captureActiveDrafts()).toEqual([]);expect(editor.command('undo')).toBe(true);expect(editor.source).toBe(source);
});

it('unifies an HTML-cell lease with a true nested panel and retains the existing cell while focus moves into that panel',()=>{
 const f=fixture(),source='<table><tr><td><p>Original</p></td></tr></table>';f.editor.replaceDocument({documentId:'html',revision:'r2',source});
 const wrapper=createHtmlPreview({kind:'html',source,display:'block'});f.editor.view.dom.append(wrapper);const dispose=attachHtmlTableEditing(wrapper,f.editor.view,0,source)!;cleanup.push(dispose);const cell=wrapper.querySelector<HTMLTableCellElement>('td')!;cell.click();cell.dispatchEvent(new KeyboardEvent('keydown',{key:'F2',bubbles:true,cancelable:true}));const [lease]=f.ui.captureActiveDrafts();expect(lease.kind).toBe('html-cell');expect(lease.panel).toBe(cell);expect(lease.controller).toBeUndefined();
 const child=nested(f.editor.view);child.open();const field=child.scope.ui.element.querySelector<HTMLTextAreaElement>('textarea')!;field.focus();expect(document.activeElement).toBe(field);expect(lease.current()).toBe(true);expect(f.ui.captureActiveDrafts().map(draft=>draft.kind)).toEqual(['html-cell','object']);child.scope.ui.close();expect(lease.current()).toBe(true);
 cell.querySelector('p')!.textContent='Changed';cell.dispatchEvent(new InputEvent('input',{bubbles:true}));expect(f.editor.source).toBe(source);expect(commitHtmlTableDrafts(f.editor.view)).toBe(true);expect(f.editor.source).toBe(source.replace('Original','Changed'));expect(lease.current()).toBe(false);expect(undo(f.editor.view)).toBe(true);expect(f.editor.source).toBe(source);
});

it('collects actual metadata value forms and permanently revokes old form, source and document authority',()=>{
 const source='---\ntitle: Old\n---\n\nBody',root=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'metadata',revision:'r1',source,profile:'tegg'},{},'live'),ui=attachEditingUI(editor.editing,root);cleanup.push(()=>editor.destroy(),()=>ui.destroy());
 const edit=root.querySelector<HTMLButtonElement>('[aria-label="Edit title"]')!;expect(edit).not.toBeNull();edit.click();const [lease]=ui.captureActiveDrafts();expect(lease.kind).toBe('metadata');expect(lease.controller).toBeUndefined();expect(lease.token).toBeUndefined();expect(lease.current()).toBe(true);const input=lease.panel.querySelector<HTMLInputElement>('input')!;input.value='Local';input.dispatchEvent(new Event('input',{bubbles:true}));expect(editor.source).toBe(source);expect(lease.current()).toBe(true);input.focus();input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(ui.isComposing).toBe(true);expect(editor.prepareLeave()).toBe(false);expect(ui.openInspection()).toBe(false);expect(document.activeElement).toBe(input);expect(editor.source).toBe(source);input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(ui.isComposing).toBe(false);expect(ui.inspectionElement).toBeNull();expect(editor.mode).toBe('live');expect(editor.source).toBe(source);
 const cancel=Array.from(lease.panel.querySelectorAll<HTMLButtonElement>('button')).find(button=>button.textContent==='Cancel')!;cancel.click();expect(lease.current()).toBe(false);expect(ui.captureActiveDrafts()).toEqual([]);edit.click();const [next]=ui.captureActiveDrafts();expect(next.kind).toBe('metadata');expect(next.current()).toBe(true);expect(lease.current()).toBe(false);editor.view.dispatch({changes:{from:editor.view.state.doc.length,insert:' external'}});expect(next.current()).toBe(false);
 const fake=root.appendChild(document.createElement('section'));fake.className='frontmatter';fake.innerHTML='<form class="md-metadata-value-form"><input value="author"><button>Save</button></form>';expect(ui.captureActiveDrafts().some(draft=>fake.contains(draft.panel))).toBe(false);
});

it('keeps existing metadata authority through an equivalent facet allocation but refuses a different resource authority',()=>{
 const f=fixture(),compartment=new Compartment(),context={documentPath:'same.md',resolveImage:(src:string)=>src},root=document.body.appendChild(document.createElement('div')),view=new EditorView({parent:root,state:EditorState.create({doc:'title: Old',extensions:[markdown(),compartment.of(resourceContext.of(context))]})}),scope=attachNestedEditingUI(f.editor.view,view)!;cleanup.push(()=>view.destroy(),()=>scope.destroy());const panel=createMetadataPanel('title: Old',undefined,{onChange:()=>true});view.dom.append(panel);cleanup.push(()=>disposeMetadataPanel(panel));panel.querySelector<HTMLButtonElement>('[aria-label="Edit title"]')!.click();const [lease]=f.ui.captureActiveDrafts();expect(lease.kind).toBe('metadata');expect(lease.current()).toBe(true);view.dispatch({effects:compartment.reconfigure(resourceContext.of({...context}))});expect(lease.current()).toBe(true);view.dispatch({effects:compartment.reconfigure(resourceContext.of({...context,documentPath:'other.md'}))});expect(lease.current()).toBe(false);
});
