// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {EditorState,Prec,StateEffect} from '@codemirror/state';
import {TeggMarkdownEditor} from './editor';
import {attachEditingUI} from './editingUI';
const cleanup:Array<()=>void>=[];
afterEach(()=>{cleanup.splice(0).reverse().forEach(stop=>stop());document.body.replaceChildren();});
function deferred(){let resolve!:()=>void,reject!:(error:unknown)=>void;const promise=new Promise<void>((ok,no)=>{resolve=ok;reject=no;});return {promise,resolve,reject};}
function fixture(copyText:(text:string)=>Promise<void>){const root=document.createElement('div');document.body.append(root);const source='$$\nx+1\n$$',editor=new TeggMarkdownEditor(root,{documentId:'one',revision:'r1',source,profile:'tegg'},{},'source'),onError=vi.fn(),ui=attachEditingUI(editor.editing,root,{copyText,onError});cleanup.push(()=>editor.destroy(),()=>ui.destroy());const open=()=>ui.openObject('math',{from:0,to:editor.source.length});open();const copy=()=>root.querySelector<HTMLButtonElement>('[data-label="Copy expression"]')!.click();const status=()=>ui.element.querySelector('[role="status"]')!.textContent;return {root,editor,ui,onError,copy,status,open,source};}
const settle=async()=>{await Promise.resolve();await Promise.resolve();};
it('reports Copied only after the Host write resolves and remains available when mutation access becomes readonly',async()=>{const write=deferred(),copyText=vi.fn(()=>write.promise),f=fixture(copyText);f.editor.view.dispatch({effects:StateEffect.appendConfig.of(Prec.highest(EditorState.readOnly.of(true)))});f.copy();expect(copyText).toHaveBeenCalledWith('x+1');expect(f.status()).not.toBe('Copied');expect(f.editor.source).toBe(f.source);write.resolve();await settle();expect(f.status()).toBe('Copied');expect(f.editor.source).toBe(f.source);});
it.each(['new-panel','draft-change','document-change','composition'] as const)('does not report an old clipboard success after %s',async(change)=>{const write=deferred(),f=fixture(()=>write.promise);f.copy();if(change==='new-panel'){f.ui.close();f.open();}else if(change==='draft-change'){const raw=f.root.querySelector<HTMLTextAreaElement>('textarea')!;raw.value='$$\nlocal\n$$';raw.dispatchEvent(new Event('input',{bubbles:true}));}else if(change==='document-change')f.editor.view.dispatch({changes:{from:3,to:4,insert:'y'}});else f.root.querySelector('.tegg-editing-panel')!.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));await settle();const status=f.status();write.resolve();await settle();expect(f.status()).toBe(status);expect(f.status()).not.toBe('Copied');expect(f.onError).not.toHaveBeenCalled();});
it('keeps an old clipboard failure out of a replacement panel and its diagnostic callback',async()=>{const write=deferred(),f=fixture(()=>write.promise);f.copy();f.ui.close();f.open();write.reject(new Error('old writer failed'));await settle();expect(f.status()).not.toContain('old writer failed');expect(f.onError).not.toHaveBeenCalled();});
it('presents a current clipboard failure without altering the source',async()=>{const write=deferred(),f=fixture(()=>write.promise);f.copy();const error=new Error('writer failed');write.reject(error);await settle();expect(f.status()).toBe('writer failed');expect(f.onError).toHaveBeenCalledWith(error);expect(f.editor.source).toBe(f.source);});
it('refuses clipboard I/O throughout composition and restores the background toolbar only when the modal closes',async()=>{const copyText=vi.fn(async()=>{}),f=fixture(copyText),panel=f.root.querySelector<HTMLElement>('.tegg-editing-panel')!,toolbar=f.root.querySelector<HTMLElement>('.tegg-editing-toolbar')!;expect(toolbar.inert).toBe(true);panel.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));f.copy();await settle();expect(copyText).not.toHaveBeenCalled();panel.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));f.copy();await settle();expect(copyText).toHaveBeenCalledTimes(1);expect(f.status()).toBe('Copied');f.ui.close();expect(toolbar.inert).toBe(false);expect(f.editor.source).toBe(f.source);});
