/** @vitest-environment jsdom */
import {afterEach,it,expect,vi} from 'vitest';
import {bindHtmlTableControlsPlacement} from './htmlTableControlsPlacement';
const stops:Array<()=>void>=[];
afterEach(()=>{stops.splice(0).forEach(stop=>stop());vi.unstubAllGlobals();document.body.replaceChildren();});
function rect(x:number,y:number,width:number,height:number){return {x,y,width,height,left:x,top:y,right:x+width,bottom:y+height,toJSON(){return {x,y,width,height};}} as DOMRect;}
function fixture(){const wrapper=document.body.appendChild(document.createElement('section')),table=wrapper.appendChild(document.createElement('table'));table.innerHTML='<tr><td><a href="author">A&amp;B</a></td></tr>';const cell=table.querySelector('td')!,controls=wrapper.appendChild(document.createElement('div'));controls.innerHTML='<button>Cancel</button><button>Done</button><button>Line break</button><details><summary>More</summary><div><button>Append row</button></div></details>';wrapper.dataset.cellSelected='true';vi.spyOn(table,'getBoundingClientRect').mockReturnValue(rect(20,100,300,80));vi.spyOn(cell,'getBoundingClientRect').mockReturnValue(rect(20,100,150,80));vi.spyOn(controls,'getBoundingClientRect').mockReturnValue(rect(0,0,290,54));Object.defineProperties(window,{innerWidth:{configurable:true,value:390},innerHeight:{configurable:true,value:844}});return {wrapper,table,cell,controls};}
it('places chrome outside the actual grid without moving or rewriting its nodes',()=>{const f=fixture(),original=f.table.outerHTML,cell=f.cell,binding=bindHtmlTableControlsPlacement(f.wrapper,f.table,f.controls,()=>f.cell);stops.push(binding.dispose);binding.sync();expect(Number.parseFloat(f.controls.style.top)).toBeGreaterThanOrEqual(f.table.getBoundingClientRect().bottom);expect(f.controls.getBoundingClientRect().width).toBeGreaterThan(0);expect(f.table.outerHTML).toBe(original);expect(f.table.querySelector('td')).toBe(cell);});
it('keeps large offscreen tables at the viewport edge away from the active cell',()=>{const f=fixture();vi.mocked(f.table.getBoundingClientRect).mockReturnValue(rect(20,-10,300,1200));const b=bindHtmlTableControlsPlacement(f.wrapper,f.table,f.controls,()=>f.cell);stops.push(b.dispose);b.sync();expect(Number.parseFloat(f.controls.style.top)).toBeGreaterThan(f.cell.getBoundingClientRect().bottom);expect(Number.parseFloat(f.controls.style.top)+54).toBeLessThanOrEqual(844);});
it('lets a Host take placement authority without deleting its newly written values',()=>{const f=fixture(),b=bindHtmlTableControlsPlacement(f.wrapper,f.table,f.controls,()=>f.cell);stops.push(b.dispose);b.sync();f.wrapper.dataset.mdTableControls='draft';f.controls.style.left='123px';b.sync();expect(f.controls.dataset.defaultPlacement).toBeUndefined();expect(f.controls.style.left).toBe('123px');expect(f.controls.style.top).toBe('');});
it('coalesces resize callbacks and rejects a queued callback after disposal',()=>{let resize!:()=>void,queued!:FrameRequestCallback;const disconnect=vi.fn(),cancel=vi.fn();vi.stubGlobal('ResizeObserver',class{constructor(callback:()=>void){resize=callback;}observe(){}disconnect=disconnect;});vi.spyOn(window,'requestAnimationFrame').mockImplementation(callback=>{queued=callback;return 9;});vi.spyOn(window,'cancelAnimationFrame').mockImplementation(cancel);const f=fixture(),b=bindHtmlTableControlsPlacement(f.wrapper,f.table,f.controls,()=>f.cell);resize();resize();expect(window.requestAnimationFrame).toHaveBeenCalledTimes(1);b.dispose();expect(disconnect).toHaveBeenCalledOnce();expect(cancel).toHaveBeenCalledWith(9);queued(0);expect(f.controls.dataset.defaultPlacement).toBeUndefined();});
