/** Literal text edits retain untouched author elements and attributes. */
export type HtmlLiteralSelection={start:number;end:number;backward:boolean};
type Change={from:number;to:number;insert:string};
export function htmlTextSelection(root:HTMLElement):HtmlLiteralSelection|null {
 const selection=root.ownerDocument.getSelection();if(!selection?.rangeCount)return null;const range=selection.getRangeAt(0);
 if(!root.contains(range.startContainer)||!root.contains(range.endContainer))return null;
 const offset=(node:Node,at:number)=>{const prefix=range.cloneRange();prefix.selectNodeContents(root);prefix.setEnd(node,at);return units(prefix.cloneContents()).reduce((count,node)=>count+length(node),0);};
 return {start:offset(range.startContainer,range.startOffset),end:offset(range.endContainer,range.endOffset),backward:selection.anchorNode===range.endContainer&&selection.anchorOffset===range.endOffset&&!range.collapsed};
}
export function htmlLiteralSelection(root:HTMLElement){return root.matches('[contenteditable="false"]')||root.querySelector('[contenteditable="false"]')?null:htmlTextSelection(root);}
export function restoreHtmlTextSelection(root:HTMLElement,selection:HtmlLiteralSelection){const limit=htmlLiteralText(root).length,first=locate(root,Math.min(selection.start,limit)),last=locate(root,Math.min(selection.end,limit)),current=root.ownerDocument.getSelection();if(!current)return;if(selection.backward&&current.setBaseAndExtent)current.setBaseAndExtent(last.node,last.offset,first.node,first.offset);else{const range=root.ownerDocument.createRange();range.setStart(first.node,first.offset);range.setEnd(last.node,last.offset);current.removeAllRanges();current.addRange(range);}}

type Unit=Text|HTMLBRElement;
function units(root:Node){const result:Unit[]=[];const visit=(node:Node)=>{if(node instanceof Text||node instanceof HTMLBRElement)result.push(node);else for(const child of node.childNodes)visit(child);};visit(root);return result;}
function length(node:Unit){return node instanceof Text?node.length:1;}
export function htmlLiteralText(root:HTMLElement){return units(root).map(node=>node instanceof Text?node.data:'\n').join('');}
function locate(root:HTMLElement,offset:number):{node:Node;offset:number}{for(const node of units(root)){const count=length(node);if(offset<=count){if(node instanceof Text)return{node,offset};const index=Array.prototype.indexOf.call(node.parentNode!.childNodes,node);return{node:node.parentNode!,offset:index+(offset?1:0)};}offset-=count;}const parent=(root.matches('pre')?root.querySelector('code'):null)??root;return {node:parent,offset:parent.childNodes.length};}
function replaceText(root:HTMLElement,change:Change){let at=0;for(const node of units(root)){const end=at+length(node),from=Math.max(0,change.from-at),to=Math.min(length(node),change.to-at);if(to>from){if(node instanceof Text)node.deleteData(from,to-from);else node.remove();}at=end;}if(change.insert){const point=locate(root,change.from);if(point.node instanceof Text)point.node.insertData(point.offset,change.insert);else point.node.insertBefore(root.ownerDocument.createTextNode(change.insert),point.node.childNodes[point.offset]??null);}}
function mapPosition(position:number,changes:Change[],left=false){let delta=0;for(const change of changes){if(position<change.from||left&&position===change.from)break;if(position<change.to)return change.from+delta+change.insert.length;delta+=change.insert.length-(change.to-change.from);}return position+delta;}
function apply(root:HTMLElement,changes:Change[],selection:HtmlLiteralSelection,start=selection.start,end=selection.end,includeIndent=false){if(!changes.length)return false;for(const change of [...changes].reverse())replaceText(root,change);const first=locate(root,mapPosition(start,changes,includeIndent)),last=locate(root,mapPosition(end,changes));const current=root.ownerDocument.getSelection();if(!current)return true;if(selection.backward&&typeof current.setBaseAndExtent==='function')current.setBaseAndExtent(last.node,last.offset,first.node,first.offset);else{const range=root.ownerDocument.createRange();range.setStart(first.node,first.offset);range.setEnd(last.node,last.offset);current.removeAllRanges();current.addRange(range);}return true;}
export function insertHtmlLiteral(root:HTMLElement,text:string){const selection=htmlLiteralSelection(root);if(!selection)return false;const change={from:selection.start,to:selection.end,insert:text};return apply(root,[change],{...selection,backward:false},selection.end,selection.end);}
/** Tab affects selected actual lines; an endpoint at the next line start excludes it. */
export function indentHtmlLiteral(root:HTMLElement,outdent=false){const selection=htmlLiteralSelection(root);if(!selection)return false;if(!outdent&&selection.start===selection.end)return insertHtmlLiteral(root,'    ');
 const text=htmlLiteralText(root),lineStart=selection.start===0?0:text.lastIndexOf('\n',selection.start-1)+1,affectedEnd=selection.end>selection.start&&text[selection.end-1]==='\n'?selection.end-1:selection.end,changes:Change[]=[];
 let position=lineStart;while(position<=affectedEnd){const length=outdent?(/^(?: {1,4}|\t)/.exec(text.slice(position))?.[0].length??0):0;if(!outdent||length)changes.push({from:position,to:position+length,insert:outdent?'':'    '});const next=text.indexOf('\n',position);if(next<0||next+1>affectedEnd)break;position=next+1;}
 return apply(root,changes,selection,selection.start===selection.end?selection.start:lineStart,selection.start===selection.end?selection.end:affectedEnd,selection.start!==selection.end);
}
