// @vitest-environment jsdom
import {afterEach,describe,it,expect} from 'vitest';
import {EditorView} from '@codemirror/view';
import {EditorState} from '@codemirror/state';
import {history,undo} from '@codemirror/commands';
import {attachHtmlDirectEditing,focusedHtmlDirectState,executeHtmlDirectCommand} from './htmlDirectEditing';
import {displaySessionFor} from './editorHost';
const disposals:Array<()=>void>=[];afterEach(()=>{disposals.splice(0).forEach(dispose=>dispose());document.body.replaceChildren();});
function fixture(source='<p data-original="yes">原<strong>文</strong> &amp; text</p>'){
 const parent=document.createElement('div');document.body.append(parent);const view=new EditorView({parent,state:EditorState.create({doc:'before\n'+source+'\nafter',extensions:[history()]})});const wrapper=document.createElement('div');wrapper.innerHTML=source;view.dom.append(wrapper);const handle=attachHtmlDirectEditing(wrapper,view,7,source)!;disposals.push(()=>{handle.dispose();view.destroy();});return{source,view,wrapper,handle};
}
describe('safe HTML direct content edits',()=>{
 it('the default direct HTML caller retains its existing inline link editing entry',()=>{
  const {view,wrapper,source}=fixture('<p>Before <a href="target.md" rel="author" title="keep &amp; exact">label</a> after</p>'),a=wrapper.querySelector('a')!,bar=a.nextElementSibling;
  expect(bar?.classList.contains('md-html-object-actions')).toBe(true);expect(bar?.querySelector<HTMLButtonElement>('button')?.textContent).toBe('Edit link');expect(bar?.querySelector<HTMLButtonElement>('button')?.getAttribute('aria-label')).toBe('Edit link');expect(a.outerHTML).toBe('<a href="target.md" rel="author" title="keep &amp; exact">label</a>');expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');expect(undo(view)).toBe(false);
 });
 it('writes adjacent text directly without rewriting original tags, attributes or entities',()=>{const{source,view,wrapper}=fixture();wrapper.querySelector('strong')!.textContent='新';wrapper.dispatchEvent(new InputEvent('input',{bubbles:true}));expect(view.state.doc.toString()).toBe('before\n'+source.replace('<strong>文</strong>','<strong>新</strong>')+'\nafter');});
 it('protects composition then commits the complete text with no deferred button replay',async()=>{const{source,view,wrapper,handle}=fixture();wrapper.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));wrapper.querySelector('strong')!.textContent='中文';wrapper.dispatchEvent(new InputEvent('input',{bubbles:true}));expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');expect(handle.composing).toBe(true);expect(view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}))).toBe(false);wrapper.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await Promise.resolve();expect(view.state.doc.toString()).toContain('<strong>中文</strong>');});
 it('retains unsubmitted text on stale identity without replacing another source range',()=>{const{view,wrapper}=fixture();view.dispatch({changes:{from:0,insert:'changed'}});wrapper.querySelector('strong')!.textContent='retained';wrapper.dispatchEvent(new InputEvent('input',{bubbles:true}));expect(view.state.doc.toString()).not.toContain('retained');expect(wrapper.textContent).toContain('retained');expect(view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}))).toBe(false);});
 it('summary Return creates only a temporary body landing until real input',()=>{const{source,view,wrapper}=fixture('<details><summary>Title</summary></details>');const text=wrapper.querySelector('summary')!.firstChild!,range=document.createRange();range.setStart(text,5);range.collapse(true);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');const temporary=wrapper.querySelector('[data-tegg-temporary=true]')!;expect(temporary.querySelector('br[data-tegg-temporary=true]')).not.toBeNull();temporary.insertBefore(document.createTextNode('body'),temporary.firstChild);wrapper.dispatchEvent(new InputEvent('input',{bubbles:true}));expect(view.state.doc.toString()).toContain('<details><summary>Title</summary><p>body</p></details>');expect(view.state.doc.toString()).not.toContain('open');expect(view.state.doc.toString()).not.toContain('<br>');});
 it('summary Return enters existing body without creating a temporary extra paragraph',()=>{const{source,view,wrapper}=fixture('<details><summary>Title</summary><p data-original="yes">Body</p></details>');const text=wrapper.querySelector('summary')!.firstChild!,range=document.createRange();range.setStart(text,5);range.collapse(true);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));expect(wrapper.querySelector('[data-tegg-temporary=true]')).toBeNull();expect(document.getSelection()!.anchorNode).toBe(wrapper.querySelector('p'));expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');});

 it('captures current details state before leaving even while its toggle event is pending',()=>{const{source,view,wrapper}=fixture('<details><summary>Title</summary></details>');const details=wrapper.querySelector('details')!,session=displaySessionFor(view);details.open=true;view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}));expect(session.expanded('html-details',7,7+source.length,false)).toBe(true);details.open=false;view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}));expect(session.expanded('html-details',7,7+source.length,true)).toBe(false);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');});

});

function select(wrapper:HTMLElement,selector:string,start?:number,end?:number,backward=false){wrapper.tabIndex=0;wrapper.focus();const node=wrapper.querySelector(selector)!,text=node.firstChild!,selection=document.getSelection()!;if(start===undefined){const range=document.createRange();range.selectNodeContents(node);selection.removeAllRanges();selection.addRange(range);}else selection.setBaseAndExtent(text,backward?end??start:start,text,backward?start:end??start);}
it('direct literal code refuses display formats and preserves source and author attributes',()=>{for(const source of ['<p><code data-x="keep">literal</code></p>','<div><pre><code data-x="keep">literal</code></pre></div>']){const {view,wrapper}=fixture(source);select(wrapper,'code');expect(focusedHtmlDirectState(view)?.inlineFormattingEnabled).toBe(false);expect(executeHtmlDirectCommand(view,'bold')).toBe(false);expect(executeHtmlDirectCommand(view,'highlight')).toBe(false);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');if(source.includes('<pre>')){expect(focusedHtmlDirectState(view)?.code).toBe(false);expect(executeHtmlDirectCommand(view,'code')).toBe(false);}else{expect(focusedHtmlDirectState(view)?.code).toBe(true);expect(executeHtmlDirectCommand(view,'code')).toBe(true);expect(view.state.doc.toString()).toBe('before\n<p>literal</p>\nafter');}}});
it('direct code selected-line indentation keeps the code and has isolated Undo transactions',()=>{const {source,view,wrapper}=fixture('<div data-x="keep"><pre><code>alpha\nbeta\ngamma</code></pre><p>body</p></div>');select(wrapper,'code',0,11,true);wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));expect(view.state.doc.toString()).toBe('before\n'+source.replace('alpha\nbeta','    alpha\n    beta')+'\nafter');wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toContain('    alpha\n    beta');});
it('soft-keyboard Return writes a real code LF and protects code boundary deletion',()=>{const {view,wrapper}=fixture('<div><pre><code>x</code></pre></div>');select(wrapper,'code',1);const input=new InputEvent('beforeinput',{inputType:'insertParagraph',bubbles:true,cancelable:true});wrapper.dispatchEvent(input);expect(input.defaultPrevented).toBe(true);expect(view.state.doc.toString()).toBe('before\n<div><pre><code>x\n</code></pre></div>\nafter');select(wrapper,'code',0);const key=new KeyboardEvent('keydown',{key:'Backspace',bubbles:true,cancelable:true});wrapper.dispatchEvent(key);expect(key.defaultPrevented).toBe(true);expect(view.state.doc.toString()).toContain('<pre><code>x\n</code></pre>');});
it('summary Shift Return is a real HTML hard break and keeps its caret in the title',()=>{const {view,wrapper}=fixture('<details><summary>Title</summary><p>Body</p></details>');select(wrapper,'summary',5);wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true,cancelable:true}));expect(view.state.doc.toString()).toBe('before\n<details><summary>Title<br></summary><p>Body</p></details>\nafter');expect(document.getSelection()!.anchorNode).toBe(wrapper.querySelector('summary'));expect(wrapper.querySelector('details')!.open).toBe(false);});
it('allows leaving unchanged direct HTML after permissions change but retains dirty input',()=>{const {view,wrapper}=fixture('<p><strong>old</strong></p>');view.setState(EditorState.create({doc:view.state.doc,extensions:[history(),EditorState.readOnly.of(true)]}));expect(view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}))).toBe(true);wrapper.querySelector('strong')!.textContent='retained';wrapper.dispatchEvent(new InputEvent('input',{bubbles:true}));expect(view.state.doc.toString()).toContain('<strong>old</strong>');expect(view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}))).toBe(false);});

it('opaque HTML inputs cannot route format or code keys into an old adjacent prose selection',()=>{const {view,wrapper,source}=fixture('<p><code>keep</code><input value="display"></p>');select(wrapper,'code');const input=wrapper.querySelector('input')!;input.focus();expect(focusedHtmlDirectState(view)?.inlineFormattingEnabled).toBe(false);expect(focusedHtmlDirectState(view)?.code).toBe(false);expect(executeHtmlDirectCommand(view,'code')).toBe(false);input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');});


it('child document-edge navigation collapses native node selections into author text and excludes the status notice',()=>{const {view,wrapper,source}=fixture('<p data-x="keep">old</p>');select(wrapper,'p');wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'End',metaKey:true,bubbles:true,cancelable:true}));const selected=document.getSelection()!;expect(selected.anchorNode).toBe(wrapper.querySelector('p')!.firstChild);expect(selected.anchorOffset).toBe(3);expect(selected.isCollapsed).toBe(true);const input=new InputEvent('beforeinput',{inputType:'insertText',data:' before',bubbles:true,cancelable:true});wrapper.dispatchEvent(input);expect(input.defaultPrevented).toBe(true);expect(view.state.doc.toString()).toBe('before\n'+source.replace('old','old before')+'\nafter');wrapper.dispatchEvent(new KeyboardEvent('keydown',{key:'Home',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true}));expect(document.getSelection()!.toString()).toBe('old before');expect(document.getSelection()!.anchorOffset).toBe(10);expect(document.getSelection()!.focusOffset).toBe(0);});

it('cross-parent input is rejected before native mutation and explicit child activation clamps an empty boundary range',()=>{const {view,wrapper,source}=fixture('<p data-x="keep">old</p>');select(wrapper,'p',3);const end=view.dom.appendChild(document.createElement('p'));end.textContent='after';const range=document.createRange();range.setStart(wrapper.querySelector('p')!.firstChild!,3);range.setEnd(end.firstChild!,0);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);const input=new InputEvent('beforeinput',{inputType:'insertText',data:' ',bubbles:true,cancelable:true});wrapper.dispatchEvent(input);expect(input.defaultPrevented).toBe(true);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');wrapper.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));expect(selection.isCollapsed).toBe(true);expect(selection.anchorNode).toBe(wrapper.querySelector('p')!.firstChild);expect(selection.anchorOffset).toBe(3);});


it('activation preserves valid inline code and rich label DOM boundaries through queued focus synchronization',async()=>{for(const tag of ['code','strong']){const source='<p>start <'+tag+' data-x="keep">literal</'+tag+'> end</p>',{view,wrapper}=fixture(source);select(wrapper,tag);const element=wrapper.querySelector(tag)!,selection=document.getSelection()!;wrapper.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));await Promise.resolve();expect(selection.anchorNode).toBe(element);expect(selection.focusNode).toBe(element);expect(selection.toString()).toBe('literal');expect(focusedHtmlDirectState(view)?.[tag==='code'?'code':'bold']).toBe(true);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');if(tag==='code'){expect(executeHtmlDirectCommand(view,'code')).toBe(true);expect(view.state.doc.toString()).toBe('before\n<p>start literal end</p>\nafter');}}});
it('activation clamps an outside endpoint while preserving backward author text selection',()=>{const {view,wrapper,source}=fixture('<p>old text</p>');select(wrapper,'p',4,8,true);const outside=view.dom.appendChild(document.createElement('p'));outside.textContent='after';const text=wrapper.querySelector('p')!.firstChild!,selection=document.getSelection()!;selection.setBaseAndExtent(outside.firstChild!,0,text,4);wrapper.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));expect(selection.anchorNode).toBe(text);expect(selection.anchorOffset).toBe(8);expect(selection.focusNode).toBe(text);expect(selection.focusOffset).toBe(4);expect(selection.toString()).toBe('text');expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');});


it('collapsed wrapper activation keeps start, paragraph boundary and end caret collapsed in the corresponding author text',()=>{for(const [offset,paragraph,position] of [[0,0,0],[1,1,0],[2,1,4]]){const {wrapper,view,source}=fixture('<p>first</p><p>last</p>');wrapper.tabIndex=0;wrapper.focus();const range=document.createRange();range.setStart(wrapper,offset);range.collapse(true);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);wrapper.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));expect(selection.isCollapsed).toBe(true);expect(selection.anchorNode).toBe(wrapper.querySelectorAll('p')[paragraph].firstChild);expect(selection.anchorOffset).toBe(position);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');}});


it('activation of an empty source-mappable author paragraph keeps the caret before its existing break',()=>{const {wrapper,view,source}=fixture('<p data-x="keep"><br></p>');wrapper.tabIndex=0;wrapper.focus();const range=document.createRange();range.setStart(wrapper,0);range.collapse(true);const selection=document.getSelection()!;selection.removeAllRanges();selection.addRange(range);wrapper.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));expect(selection.isCollapsed).toBe(true);expect(selection.anchorNode).toBe(wrapper.querySelector('p'));expect(selection.anchorOffset).toBe(0);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');});


it('shared Details expansion repaints mounted author nodes without source, history or text-caret changes',()=>{const{source,view,wrapper,handle}=fixture('<details><summary>Outer</summary><details><summary>Inner</summary><p data-x="keep">Body</p></details></details>'),details=wrapper.querySelectorAll('details'),doc=view.state.doc,selection=view.state.selection;const display=displaySessionFor(view);display.setExpanded('html-details',7,7+source.length,true);display.setExpanded('html-details',8,7+source.length,true);expect(details[0].open).toBe(true);expect(details[1].open).toBe(true);expect(view.state.doc).toBe(doc);expect(view.state.selection).toBe(selection);expect(undo(view)).toBe(false);expect(view.dom.dispatchEvent(new CustomEvent('tegg-editing-preflight',{cancelable:true}))).toBe(true);expect(handle.source).toBe(source);expect(view.state.doc.toString()).toBe('before\n'+source+'\nafter');expect(wrapper.querySelectorAll('details')[0]).toBe(details[0]);});
