import {describe,it,expect} from 'vitest';
import {applyHtmlTableOperation as edit,parseHtmlTable,htmlTableRectangle,HtmlTableEditingError} from './htmlTableEditing';
const table='<table class="original"><tbody>\n<tr><td rowspan="2" data-x="keep"><strong>研究</strong></td><td>资料</td><td>后</td></tr>\n<tr><td>样张</td><td>末</td></tr>\n</tbody></table>';
describe('source-faithful HTML table editing',()=>{
 it('edits one actual merged cell without reserializing unselected source',()=>{const result=edit(table,{type:'cell',at:{row:1,column:0},html:'<strong>修改</strong><p>二段</p>'});expect(result.source).toBe(table.replace('<strong>研究</strong>','<strong>修改</strong><p>二段</p>'));expect(result.patches).toHaveLength(1);});
 it('computes merged closure from the requested endpoints and can shrink',()=>{const model=parseHtmlTable(table);expect(htmlTableRectangle(model,{from:{row:1,column:1},to:{row:1,column:0}})).toEqual({from:{row:0,column:0},to:{row:1,column:1}});expect(htmlTableRectangle(model,{from:{row:1,column:1},to:{row:1,column:1}})).toEqual({from:{row:1,column:1},to:{row:1,column:1}});});
 it('clears content while retaining all spans, attributes, and unselected bytes',()=>{const result=edit(table,{type:'clear',range:{from:{row:1,column:0},to:{row:1,column:1}}});expect(result.source).toContain('<td rowspan="2" data-x="keep"></td>');expect(result.source).toContain('<td>后</td>');expect(result.source).toContain('<td>末</td>');expect(parseHtmlTable(result.source).cells).toHaveLength(5);});
 it('merges content in row order, then unmerges with content retained only at the anchor',()=>{const source='<table><tbody><tr><td><b>A</b></td><td>B</td></tr><tr><td>C</td><td></td></tr></tbody></table>';const merged=edit(source,{type:'merge',range:{from:{row:0,column:0},to:{row:1,column:1}}}).source;expect(parseHtmlTable(merged).cells[0].content).toBe('<b>A</b><br>B<br>C');const split=edit(merged,{type:'unmerge',at:{row:1,column:1}}).source;const model=parseHtmlTable(split);expect(model.cells).toHaveLength(4);expect(model.cells[0].content).toBe('<b>A</b><br>B<br>C');expect(model.cells.slice(1).every(cell=>cell.content==='')).toBe(true);});
 it('retains a unique anchor id without duplicating it when unmerging',()=>{const source='<table><tr><td id="one" colspan="2">A</td></tr></table>';const split=edit(source,{type:'unmerge',at:{row:0,column:0}}).source;expect(split.match(/id="one"/g)).toHaveLength(1);});
 it('expands a span on insertion strictly inside it, but not at its boundary',()=>{const inside=edit(table,{type:'insert-row',index:1}).source;expect(parseHtmlTable(inside).cells[0].rowspan).toBe(3);const before=edit(table,{type:'insert-row',index:0}).source;expect(parseHtmlTable(before).cells.find(cell=>cell.content.includes('研究'))!.rowspan).toBe(2);expect(parseHtmlTable(before).rows).toHaveLength(3);});
 it('moves a merged anchor when its start row is deleted without losing its full content',()=>{const removed=edit(table,{type:'delete-row',index:0}).source;const model=parseHtmlTable(removed);expect(model.rows).toHaveLength(1);expect(model.grid[0][0].content).toBe('<strong>研究</strong>');expect(model.grid[0][0].attributes['data-x']).toBe('keep');expect(removed).not.toContain('资料');expect(removed).toContain('样张');});
 it('symmetrically expands and reduces horizontal spans, preserving anchor content',()=>{const source='<table><tr><td colspan="2">A</td><td>B</td></tr><tr><td>C</td><td>D</td><td>E</td></tr></table>';const added=edit(source,{type:'insert-column',index:1}).source;expect(parseHtmlTable(added).cells[0].colspan).toBe(3);const removed=edit(source,{type:'delete-column',index:0}).source;expect(parseHtmlTable(removed).cells[0].content).toBe('A');expect(parseHtmlTable(removed).cells[0].colspan).toBe(1);expect(removed).toContain('<td>D</td><td>E</td>');});
 it('blocks cross-group and mixed-identity merges and conflicting attributes',()=>{const source='<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>C</td><td>D</td></tr></tbody></table>';expect(()=>edit(source,{type:'merge',range:{from:{row:0,column:0},to:{row:1,column:1}}})).toThrow(HtmlTableEditingError);expect(()=>edit(table,{type:'merge',range:{from:{row:0,column:0},to:{row:1,column:1}}})).toThrow(/attributes/);});
 it('refuses malformed grids, open-ended spans, implicit closes, and deletion of the last track',()=>{for(const source of ['<table><tr><td>A</tr></table>','<table><tr><td rowspan="0">A</td></tr></table>','<table><tr><td>A</td><td>B</td></tr><tr><td>C</td></tr></table>'])expect(()=>parseHtmlTable(source)).toThrow();expect(()=>edit('<table><tr><td>A</td></tr></table>',{type:'delete-column',index:0})).toThrow(/last track/);});
 it('does not allow a cell payload to replace neighboring structure',()=>{expect(()=>edit('<table><tr><td>A</td><td>B</td></tr></table>',{type:'cell',at:{row:0,column:0},html:'A</td><td>injected'})).toThrow();});
});

it('deletes the whole table only through the explicit operation and keeps the exact undo patch',()=>{const result=edit(table,{type:'delete-table'});expect(result.source).toBe('');expect(result.patches).toEqual([{from:0,to:table.length,expected:table,insert:''}]);});
