// @vitest-environment jsdom
import {afterEach,describe,it,expect} from 'vitest';
import {EditorView} from '@codemirror/view';
import {EditorState} from '@codemirror/state';
import {history,undo} from '@codemirror/commands';
import {resourceContext,displaySessionFor} from './editorHost';
import {htmlLiteralSelection} from './htmlLiteralEditing';
import {createHtmlPreview} from './renderKit';
import {attachHtmlTableEditing,commitHtmlTableDrafts,executeHtmlTableCommand,captureHtmlTableDrafts} from './htmlTableWidget';
const disposals:Array<()=>void>=[];
afterEach(()=>{disposals.splice(0).forEach(dispose=>dispose());document.body.replaceChildren();});
function fixture(source='<table class="keep"><tr><td><p data-x="retain">原<strong>文</strong></p></td><td>旁</td></tr></table>',readonly=false){
 const parent=document.createElement('div');document.body.append(parent);const prefix='before\n',view=new EditorView({parent,state:EditorState.create({doc:prefix+source+'\nafter',extensions:[history(),EditorState.readOnly.of(readonly)]})});
 const wrapper=createHtmlPreview({kind:'html',source,display:'block'});view.dom.append(wrapper);const cleanup=attachHtmlTableEditing(wrapper,view,prefix.length,source)!;disposals.push(()=>{cleanup();view.destroy();});const cells=wrapper.querySelectorAll<HTMLTableCellElement>('td');return{view,wrapper,cells,source,prefix};
}
const key=(cell:HTMLElement,name:string,options:KeyboardEventInit={})=>cell.dispatchEvent(new KeyboardEvent('keydown',{key:name,bubbles:true,cancelable:true,...options}));
describe('rendered HTML table drafts',()=>{
 it('allows the details summary direct control to fold in selected-cell preview without editing source',()=>{const{view,cells,source,prefix}=fixture('<table><tr><td><details><summary>Title</summary><p>Body</p></details></td><td>next</td></tr></table>');const summary=cells[0].querySelector('summary')!,event=new MouseEvent('click',{bubbles:true,cancelable:true});summary.dispatchEvent(event);expect(event.defaultPrevented).toBe(false);expect(cells[0].querySelector('details')!.open).toBe(true);summary.click();expect(cells[0].querySelector('details')!.open).toBe(false);expect(cells[0].contentEditable).not.toBe('true');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
 it('provides a source-free details summary fallback before rich draft mapping',()=>{const{view,cells,source,prefix}=fixture('<table><tr><td><details><p>Body</p></details></td><td>next</td></tr></table>');const summary=cells[0].querySelector('summary');expect(summary).not.toBeNull();expect(summary!.dataset.teggTemporary).toBe('true');expect(summary!.dataset.placeholder).toBe('Details');cells[0].click();key(cells[0],'F2');expect(cells[0].contentEditable).toBe('true');cells[0].querySelector('p')!.textContent='Changed';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true}));expect(commitHtmlTableDrafts(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source.replace('Body','Changed')+'\nafter');expect(view.state.doc.toString()).not.toContain('<summary');});
 it('single click selects without revealing syntax or writing source',()=>{const{view,cells,source,prefix}=fixture();cells[0].click();expect(cells[0].contentEditable).not.toBe('true');expect(cells[0].classList.contains('md-html-cell-selected')).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
 it('F2 opens a rich draft and Escape retains exact source and rendered content',()=>{const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');cells[0].querySelector('strong')!.firstChild!.textContent='修改';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true}));expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');key(cells[0],'Escape');expect(cells[0].querySelector('strong')!.textContent).toBe('文');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
 it('commits a changed rich cell in one parent undo and preserves surrounding bytes',()=>{const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');cells[0].querySelector('strong')!.firstChild!.textContent='新';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true}));expect(commitHtmlTableDrafts(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source.replace('<strong>文</strong>','<strong>新</strong>')+'\nafter');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
 it('ordinary typing replaces the selected actual cell only as a draft',()=>{const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'x');expect(cells[0].textContent).toBe('x');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');key(cells[0],'Escape');expect(cells[0].textContent).toBe('原文');});
 it('retains details display state after local history restores fresh source-backed nodes',()=>{const{view,cells,source,prefix}=fixture('<table><tr><td><details><summary>Title</summary><p>Body</p></details></td><td>next</td></tr></table>');cells[0].click();key(cells[0],'F2');let details=cells[0].querySelector('details')!;details.open=true;details.dispatchEvent(new Event('toggle'));cells[0].querySelector('p')!.textContent='Changed';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true}));expect(executeHtmlTableCommand(view,'undo')).toBe(true);details=cells[0].querySelector('details')!;expect(details.open).toBe(true);details.open=false;details.dispatchEvent(new Event('toggle'));expect(executeHtmlTableCommand(view,'redo')).toBe(true);expect(cells[0].querySelector('details')!.open).toBe(false);expect(cells[0].querySelector('p')!.textContent).toBe('Changed');key(cells[0],'Escape');expect(cells[0].querySelector('details')!.open).toBe(false);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
 it('composition prevents leaving and does not replay a pending request',()=>{const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');cells[0].dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));cells[0].querySelector('strong')!.textContent='输入';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true}));expect(commitHtmlTableDrafts(view)).toBe(false);key(cells[0],'Enter',{isComposing:true});cells[0].dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(commitHtmlTableDrafts(view)).toBe(true);});
 it('readonly table remains selectable but cannot open or clear a draft',()=>{const{view,cells,source,prefix}=fixture(undefined,true);cells[0].click();key(cells[0],'F2');key(cells[0],'Delete');expect(cells[0].contentEditable).not.toBe('true');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
 it('retains a draft when its source version changes',()=>{const{view,cells}=fixture();cells[0].click();key(cells[0],'x');view.dispatch({changes:{from:0,insert:'changed'}});expect(commitHtmlTableDrafts(view)).toBe(false);expect(cells[0].textContent).toBe('x');expect(cells[0].contentEditable).toBe('true');});
});

function menuButton(wrapper:HTMLElement,text:string){return [...wrapper.querySelectorAll<HTMLButtonElement>('button')].find(button=>button.textContent===text)!;}
async function tick(){await Promise.resolve();await Promise.resolve();}
describe('HTML table explicit operations',()=>{
 it('offers copy and cut directly in More while preserving structure until copy succeeds',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();let complete!:(success:boolean,error?:string)=>void;
  wrapper.addEventListener('tegg-copy-table',event=>{event.preventDefault();const data=(event as CustomEvent).detail;expect(data.html).toContain('<strong>文</strong>');expect(data.structured).toContain('data-x');complete=data.complete;});
  menuButton(wrapper,'Cut cells').click();expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');complete(true);await tick();expect(view.state.doc.toString()).toBe(prefix+source.replace('<p data-x="retain">原<strong>文</strong></p>','')+'\nafter');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('does not cut after failed copy or a changed range, source or permissions',async()=>{
  for(const change of ['failed','range','source','readonly']){const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();let complete!:(success:boolean,error?:string)=>void;wrapper.addEventListener('tegg-copy-table',event=>{event.preventDefault();complete=(event as CustomEvent).detail.complete;});menuButton(wrapper,'Cut cells').click();if(change==='range')cells[1].click();if(change==='source')view.dispatch({changes:{from:view.state.doc.length,insert:'extra'}});if(change==='readonly')view.setState(EditorState.create({doc:view.state.doc,extensions:[history(),EditorState.readOnly.of(true)]}));const current=view.state.doc.toString();complete(change!=='failed','copy denied');await tick();expect(view.state.doc.toString()).toBe(current);expect(current).toContain(source);expect(wrapper.querySelector('.md-html-table-error')!.textContent).toMatch(/denied|not cut/);}
 });
 it('previews overflow without mutation and applies one undo only after Expand and paste',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[1].click();wrapper.addEventListener('tegg-read-table',event=>{event.preventDefault();(event as CustomEvent).detail.complete({text:'x\ty\nz\tw'});});menuButton(wrapper,'Paste').click();await tick();expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(wrapper.querySelector('.md-html-table-review')!.textContent).toContain('2 rows and 3 columns');menuButton(wrapper,'Expand and paste').click();expect(view.state.doc.toString()).toContain('<td>x</td><td>y</td>');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('retains malformed structured input and only uses plain text after explicit selection',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[1].click();wrapper.addEventListener('tegg-read-table',event=>{event.preventDefault();(event as CustomEvent).detail.complete({text:'safe',structured:'{broken'});});menuButton(wrapper,'Paste').click();await tick();expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');const review=wrapper.querySelector('.md-html-table-review')!;[...review.querySelectorAll<HTMLButtonElement>('button')].find(button=>button.textContent==='Paste plain text')!.click();expect(view.state.doc.toString()).toBe(prefix+source.replace('<td>旁</td>','<td>safe</td>')+'\nafter');
 });
 it('requires explicit Delete table after deleting the last track',()=>{
  const{view,wrapper,cells,source,prefix}=fixture('<table><tr><td>A</td></tr></table>');cells[0].click();menuButton(wrapper,'Delete row').click();expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');const review=wrapper.querySelector('.md-html-table-review')!;expect(review.textContent).toContain('Delete this table?');review.querySelector<HTMLButtonElement>('button')!.click();expect(view.state.doc.toString()).toBe(prefix+'\nafter');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('stops local Undo from reaching the document owner during a rich draft',()=>{
  const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');const previous=document.execCommand;let called=false;document.execCommand=()=>{called=true;return true;};let leaked=false;view.dom.addEventListener('keydown',()=>{leaked=true;});key(cells[0],'z',{metaKey:true});expect(called).toBe(false);expect(leaked).toBe(false);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');document.execCommand=previous;
 });
 it('code subtree Return, four-space Tab and Escape stay inside the cell draft',()=>{
  const{view,cells,source,prefix}=fixture('<table><tr><td><pre><code>x</code></pre></td><td>next</td></tr></table>');cells[0].click();key(cells[0],'F2');const text=cells[0].querySelector('code')!.firstChild!,range=document.createRange();range.setStart(text,1);range.collapse(true);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);key(cells[0],'Tab');expect(cells[0].querySelector('code')!.textContent).toBe('x    ');key(cells[0],'Enter');expect(cells[0].querySelector('code')!.textContent).toContain('\n');key(cells[0],'Escape');expect(cells[0].contentEditable).toBe('true');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(executeHtmlTableCommand(view,'table-cancel')).toBe(true);
 });
});

describe('isolated HTML rich-cell history',()=>{
 it('undoes and redoes a rich draft locally without losing attributes or changing document history',()=>{
  const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');cells[0].querySelector('strong')!.textContent='变';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));
  expect(executeHtmlTableCommand(view,'undo')).toBe(true);expect(cells[0].textContent).toBe('原文');expect(cells[0].querySelector('p')!.getAttribute('data-x')).toBe('retain');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
  expect(executeHtmlTableCommand(view,'redo')).toBe(true);expect(cells[0].textContent).toBe('原变');expect(commitHtmlTableDrafts(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source.replace('<strong>文</strong>','<strong>变</strong>')+'\nafter');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('splits a rich list only through the explicit sibling-item action and keeps paragraph insertion inside the current item',()=>{const {view,cells,source,prefix}=fixture("<table><tr><td><ul class='keep'><li data-x='keep'><strong title='rich'>AB</strong></li><li>other</li></ul></td></tr></table>");cells[0].click();key(cells[0],'F2');const place=()=>{const text=cells[0].querySelector('strong')!.firstChild!,range=document.createRange();range.setStart(text,1);range.collapse(true);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);};place();expect(executeHtmlTableCommand(view,'table-list-item')).toBe(true);expect(cells[0].querySelectorAll('li')).toHaveLength(3);expect(cells[0].querySelector('li')!.textContent).toBe('A');expect(cells[0].querySelectorAll('li')[1].textContent).toBe('B');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(executeHtmlTableCommand(view,'undo')).toBe(true);place();expect(executeHtmlTableCommand(view,'table-paragraph')).toBe(true);expect(cells[0].querySelectorAll('li')).toHaveLength(2);expect(cells[0].querySelectorAll('li:first-child > p')).toHaveLength(2);expect(cells[0].querySelector('ul > p')).toBeNull();expect(executeHtmlTableCommand(view,'table-apply')).toBe(true);expect(view.state.doc.toString()).toContain("<ul class='keep'><li data-x='keep'><p><strong title='rich'>A</strong></p><p><strong title='rich'>B</strong></p></li><li>other</li></ul>");});
 it('inserts paragraphs as sibling blocks and can undo the local structural edit',()=>{
  const{view,cells,source,prefix}=fixture('<table><tr><td><p data-x="retain">AB</p></td></tr></table>');cells[0].click();key(cells[0],'F2');const text=cells[0].querySelector('p')!.firstChild!,range=document.createRange();range.setStart(text,1);range.collapse(true);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);
  expect(executeHtmlTableCommand(view,'table-paragraph')).toBe(true);expect(cells[0].querySelectorAll('p')).toHaveLength(2);expect(cells[0].querySelector('p p')).toBeNull();expect(cells[0].children[0].textContent).toBe('A');expect(cells[0].children[1].textContent).toBe('B');expect(executeHtmlTableCommand(view,'undo')).toBe(true);expect(cells[0].innerHTML).toBe('<p data-x="retain">AB</p>');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('routes keyboard copy and cut through all native representations before changing cells',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();let complete!:(success:boolean)=>void,count=0;wrapper.addEventListener('tegg-copy-table',event=>{event.preventDefault();const data=(event as CustomEvent).detail;expect(data.text).toBe('原文');expect(data.html).toContain('<strong>文</strong>');expect(JSON.parse(data.structured).cells[0].attributes).toEqual({});complete=data.complete;count++;});
  cells[0].dispatchEvent(new Event('copy',{bubbles:true,cancelable:true}));expect(count).toBe(1);complete(true);await tick();expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
  cells[0].dispatchEvent(new Event('cut',{bubbles:true,cancelable:true}));expect(count).toBe(2);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');complete(true);await tick();expect(view.state.doc.toString()).not.toContain('<strong>文</strong>');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
});

describe('HTML table title and explicit commit routing',()=>{
 it('opens a details title into its body before parent-cell Return can commit',()=>{
  const{view,cells,source,prefix}=fixture('<table><tr><td><details><summary>Title</summary><p>Body</p></details></td><td>next</td></tr></table>');cells[0].click();key(cells[0],'F2');const summary=cells[0].querySelector('summary')!,range=document.createRange();range.selectNodeContents(summary);range.collapse(false);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);key(cells[0],'Enter');expect(cells[0].querySelector('details')!.open).toBe(true);const anchor=document.getSelection()!.anchorNode!;expect((anchor instanceof Element?anchor:anchor.parentElement)!.closest('p')).not.toBeNull();expect(cells[0].contentEditable).toBe('true');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('Command-Return first commits but retains the selected cell',()=>{
  const{view,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');cells[0].querySelector('strong')!.textContent='新';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));key(cells[0],'Enter',{metaKey:true});expect(view.state.doc.toString()).toBe(prefix+source.replace('<strong>文</strong>','<strong>新</strong>')+'\nafter');expect(cells[1].getAttribute('aria-selected')).not.toBe('true');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
});

describe('HTML parent history at cell selection',()=>{
 it('exposes document Undo/Redo when no cell draft owns a local history',()=>{
  const{view,cells,source,prefix}=fixture();const remount=()=>{const current=view.state.doc.sliceString(prefix.length,view.state.doc.length-'\nafter'.length),wrapper=createHtmlPreview({kind:'html',source:current,display:'block'});view.dom.append(wrapper);disposals.push(attachHtmlTableEditing(wrapper,view,prefix.length,current)!);wrapper.querySelector<HTMLTableCellElement>('td')!.click();};cells[0].click();key(cells[0],'Delete');expect(view.state.doc.toString()).not.toBe(prefix+source+'\nafter');remount();expect(executeHtmlTableCommand(view,'undo')).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');remount();expect(executeHtmlTableCommand(view,'redo')).toBe(true);expect(view.state.doc.toString()).not.toContain('<strong>文</strong>');
 });
});

describe('HTML paste belongs to the innermost text draft',()=>{
 it('retains a structured matrix until explicit plain paste and never distributes it to adjacent cells',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');wrapper.addEventListener('tegg-read-table',event=>{event.preventDefault();(event as CustomEvent).detail.complete({text:'x\ty',html:'<TABLE><TR><TD>x</TD><TD>y</TD></TR></TABLE>'});});menuButton(wrapper,'Paste').click();await tick();expect(cells[0].textContent).toBe('原文');expect(cells[1].textContent).toBe('旁');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(wrapper.querySelector('.md-html-table-review')!.textContent).toContain('cannot be distributed');[...wrapper.querySelectorAll<HTMLButtonElement>('.md-html-table-review button')].find(button=>button.textContent==='Paste plain text')!.click();expect(cells[0].textContent).toContain('x\ty');expect(cells[1].textContent).toBe('旁');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
 it('reviews multiple blocks before inserting them only into the current rich draft',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');wrapper.addEventListener('tegg-read-table',event=>{event.preventDefault();(event as CustomEvent).detail.complete({text:'one\ntwo',html:'<p>one</p><p><strong>two</strong></p>'});});menuButton(wrapper,'Paste').click();await tick();expect(cells[0].textContent).toBe('原文');expect(wrapper.querySelector('.md-html-table-review')!.textContent).toContain('Insert this rich content');menuButton(wrapper,'Insert into cell').click();expect(cells[0].textContent).toContain('onetwo');expect(cells[1].textContent).toBe('旁');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(executeHtmlTableCommand(view,'undo')).toBe(true);expect(cells[0].textContent).toBe('原文');
 });
 it('does not apply an async read to a changed text draft',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');let complete!:(data:{text:string})=>void;wrapper.addEventListener('tegg-read-table',event=>{event.preventDefault();complete=(event as CustomEvent).detail.complete;});menuButton(wrapper,'Paste').click();cells[0].querySelector('strong')!.textContent='new';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));complete({text:'old clipboard'});await tick();expect(cells[0].textContent).toBe('原new');expect(cells[1].textContent).toBe('旁');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(wrapper.querySelector('.md-html-table-error')!.textContent).toContain('draft or selection changed');
 });
});

describe('rich HTML paste structural caret mapping',()=>{
 it('never creates nested paragraphs when multiple blocks cannot be mapped at an inline caret',async()=>{
  const{view,wrapper,cells,source,prefix}=fixture();cells[0].click();key(cells[0],'F2');const text=cells[0].querySelector('strong')!.firstChild!,caret=document.createRange();caret.setStart(text,1);caret.collapse(true);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(caret);wrapper.addEventListener('tegg-read-table',event=>{event.preventDefault();(event as CustomEvent).detail.complete({text:'one\ntwo',html:'<p>one</p><p>two</p>'});});menuButton(wrapper,'Paste').click();await tick();expect(cells[0].textContent).toBe('原文');expect(cells[0].querySelector('p p')).toBeNull();expect(wrapper.querySelector('.md-html-table-review')!.textContent).toContain('structure conversion');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');
 });
});

describe('HTML literal code selected-line transactions',()=>{
 it('preserves selected code on Tab and locally undoes indentation before a single parent commit',()=>{const {view,cells,source,prefix}=fixture('<table class="keep"><tr><td><pre data-x="1"><code class="retain">alpha\nbeta\ngamma</code></pre></td><td>next</td></tr></table>');cells[0].click();key(cells[0],'F2');const select=()=>{const text=cells[0].querySelector('code')!.firstChild!;document.getSelection()!.setBaseAndExtent(text,11,text,0);};select();key(cells[0],'Tab');expect(cells[0].querySelector('code')!.textContent).toBe('    alpha\n    beta\ngamma');expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');expect(executeHtmlTableCommand(view,'undo')).toBe(true);expect(cells[0].querySelector('code')!.textContent).toBe('alpha\nbeta\ngamma');expect(executeHtmlTableCommand(view,'redo')).toBe(true);expect(cells[0].querySelector('code')!.textContent).toBe('    alpha\n    beta\ngamma');expect(htmlLiteralSelection(cells[0].querySelector('pre')!)?.backward).toBe(true);expect(commitHtmlTableDrafts(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source.replace('alpha\nbeta','    alpha\n    beta')+'\nafter');expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
});

describe('actual HTML cell draft ownership',()=>{
 it('revokes cancel/reopen leases even when the exact td element is reused',()=>{
  const f=fixture();expect(captureHtmlTableDrafts(f.view)).toEqual([]);f.cells[0].click();key(f.cells[0],'F2');const [old]=captureHtmlTableDrafts(f.view);expect(old.current()).toBe(true);expect(old.panel).toBe(f.cells[0]);expect(executeHtmlTableCommand(f.view,'table-cancel')).toBe(true);expect(old.current()).toBe(false);key(f.cells[0],'F2');const [next]=captureHtmlTableDrafts(f.view);expect(next.panel).toBe(old.panel);expect(next.current()).toBe(true);expect(old.current()).toBe(false);expect(commitHtmlTableDrafts(f.view)).toBe(true);expect(next.current()).toBe(false);expect(f.view.state.doc.toString()).toBe(f.prefix+f.source+'\nafter');
 });
 it('keeps an existing local field and composition owned but rejects parent source and context changes',()=>{
  const f=fixture();f.cells[0].click();key(f.cells[0],'F2');const [lease]=captureHtmlTableDrafts(f.view);f.cells[0].querySelector('strong')!.textContent='draft';f.cells[0].dispatchEvent(new InputEvent('input',{bubbles:true}));expect(lease.current()).toBe(true);f.cells[0].dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(lease.current()).toBe(true);expect(commitHtmlTableDrafts(f.view)).toBe(false);expect(f.view.state.doc.toString()).toBe(f.prefix+f.source+'\nafter');f.cells[0].dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));f.view.dispatch({changes:{from:f.view.state.doc.length,insert:' elsewhere'}});expect(lease.current()).toBe(false);
 });
});

it('never cuts another document context after ACK even when the same Text and cell DOM remain',async()=>{
 const f=fixture();f.cells[0].click();let complete!:(success:boolean)=>void;f.wrapper.addEventListener('tegg-copy-table',event=>{event.preventDefault();complete=(event as CustomEvent).detail.complete;});menuButton(f.wrapper,'Cut cells').click();const text=f.view.state.doc;
 f.view.setState(EditorState.create({doc:text,extensions:[history(),resourceContext.of({documentPath:'/other/document.md',profile:'tegg'})]}));expect(f.view.state.doc).toBe(text);complete(true);await tick();expect(f.view.state.doc.toString()).toBe(f.prefix+f.source+'\nafter');expect(undo(f.view)).toBe(false);expect(f.wrapper.querySelector('.md-html-table-error')!.textContent).toContain('not cut');
});


it('shared Details state repaints the actual HTML cell draft without committing or recreating it',()=>{const {view,wrapper,cells,source,prefix}=fixture('<table><tr><td><details><summary>Folded</summary><p>old</p></details></td><td>next</td></tr></table>');cells[0].click();key(cells[0],'F2');const lease=captureHtmlTableDrafts(view)[0],details=cells[0].querySelector('details')!,text=cells[0].querySelector('p')!;text.textContent='local';cells[0].dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));const display=displaySessionFor(view),doc=view.state.doc,selection=view.state.selection;display.setExpanded('html-details',prefix.length,prefix.length+source.length,true);expect(details.open).toBe(true);expect(cells[0].querySelector('details')).toBe(details);expect(lease.current()).toBe(true);expect(text.textContent).toBe('local');expect(view.state.doc).toBe(doc);expect(view.state.selection).toBe(selection);expect(undo(view)).toBe(false);executeHtmlTableCommand(view,'undo');expect(cells[0].querySelector('p')!.textContent).toBe('old');expect(cells[0].querySelector('details')!.open).toBe(true);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');wrapper.querySelector<HTMLButtonElement>('.md-html-table-controls button:nth-child(2)')!.click();expect(lease.current()).toBe(false);expect(view.state.doc.toString()).toBe(prefix+source+'\nafter');});
