// @vitest-environment jsdom
import {it,expect} from 'vitest';
import {readReferenceObject,serializeReferenceObject,changeHtmlAttribute} from './htmlReferenceDraft';
it('changes only the chosen HTML image attribute and retains comments, case and source quoting',()=>{const original="<IMG data-author='keep' SRC = 'assets/a&amp;b.png' alt=old width='120' height=80 />",draft=readReferenceObject(original,true)!;expect(draft).toMatchObject({html:true,url:'assets/a&b.png',width:'120',height:'80'});expect(serializeReferenceObject({...draft,width:'240'},true,original)).toBe(original.replace("width='120'","width='240'"));expect(serializeReferenceObject({...draft,url:'assets/new.png'},true,original)).toBe(original.replace("'assets/a&amp;b.png'","'assets/new.png'"));expect(serializeReferenceObject(draft,true,original)).toBe(original);});
it('does not invent size fields and refuses unapproved attribute updates',()=>{const original='<img src="a.png" alt="A" data-size="author">',draft=readReferenceObject(original,true)!;expect(draft.width).toBeUndefined();expect(()=>serializeReferenceObject({...draft,width:'200'},true,original)).toThrow('existing controlled');expect(()=>serializeReferenceObject({...draft,url:'javascript:bad'},true,original)).toThrow('supported destination');});
it('preserves rich HTML link text when only the target changes',()=>{const original="<a id='keep' href = 'old.md' title='author&amp;title'><strong>Rich</strong> &amp; text</a>",draft=readReferenceObject(original,false)!;expect(draft.richLabel).toBe(true);expect(serializeReferenceObject({...draft,url:'new.md'},false,original)).toBe(original.replace("'old.md'","'new.md'"));expect(()=>serializeReferenceObject({...draft,label:'flat'},false,original)).toThrow('preserve its formatting');});
it('changes a safe HTML math attribute without touching the authored wrapper or children',()=>{const original="<span class='keep' data-tegg-math='inline' data-tex='x&amp;y'><b>fallback</b></span>";expect(changeHtmlAttribute(original,'data-tex','x<y')).toBe(original.replace("'x&amp;y'","'x&lt;y'"));});

it('keeps rich Markdown labels read-only and preserves their authored formatting for target-only edits',()=>{const original='[**Rich** `code` &amp; text](old.md "title")',draft=readReferenceObject(original,false)!;expect(draft.richLabel).toBe(true);expect(serializeReferenceObject({...draft,url:'new.md'},false,original)).toContain('[**Rich** `code` &amp; text]');expect(()=>serializeReferenceObject({...draft,label:'flat'},false,original)).toThrow('preserve its formatting');expect(readReferenceObject('[plain &amp; text](old.md)',false)?.richLabel).toBeUndefined();expect(readReferenceObject('[Original][shared]',false)).toBeNull();});
