// @vitest-environment jsdom
import {it,expect,afterEach} from 'vitest';
import {indentHtmlLiteral,insertHtmlLiteral,htmlLiteralSelection} from './htmlLiteralEditing';
afterEach(()=>document.body.replaceChildren());
function fixture(text:string,start:number,end=start,backward=false){const root=document.createElement('pre'),code=document.createElement('code');code.textContent=text;root.append(code);document.body.append(root);const node=code.firstChild??code.appendChild(document.createTextNode('')),selection=document.getSelection()!;selection.setBaseAndExtent(node,backward?end:start,node,backward?start:end);return{root,code,selection};}
it('indents only selected lines and keeps a next-line-start endpoint out of the operation',()=>{const{root}=fixture('alpha\nbeta\ngamma',0,11);expect(indentHtmlLiteral(root)).toBe(true);expect(root.textContent).toBe('    alpha\n    beta\ngamma');expect(document.getSelection()!.toString()).toBe('    alpha\n    beta');expect(indentHtmlLiteral(root,true)).toBe(true);expect(root.textContent).toBe('alpha\nbeta\ngamma');});
it('outdents actual leading tabs or at most four spaces without removing unindented text',()=>{const{root}=fixture('\talpha\n  beta\ngamma\n      delta',0,31);expect(indentHtmlLiteral(root,true)).toBe(true);expect(root.textContent).toBe('alpha\nbeta\ngamma\n  delta');});
it('a collapsed Shift-Tab only changes its current line and retains the caret',()=>{const{root}=fixture('first\n\t  value\nlast',11);expect(indentHtmlLiteral(root,true)).toBe(true);expect(root.textContent).toBe('first\n  value\nlast');expect(htmlLiteralSelection(root)).toMatchObject({start:10,end:10});});
it('inserts literal newlines and spaces through text nodes while retaining nested author markup',()=>{const root=document.createElement('pre');root.innerHTML='<code class="keep"><span data-x="1">ab</span><span data-y="2">cd</span></code>';document.body.append(root);const first=root.querySelectorAll('span')[0].firstChild!,last=root.querySelectorAll('span')[1].firstChild!,range=document.createRange();range.setStart(first,1);range.setEnd(last,1);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);expect(insertHtmlLiteral(root,'\n')).toBe(true);expect(root.textContent).toBe('a\nd');expect(root.querySelector('code')!.className).toBe('keep');expect(root.querySelectorAll('span')).toHaveLength(2);expect(root.querySelectorAll('span')[1].getAttribute('data-y')).toBe('2');expect(root.querySelector('br')).toBeNull();});
it('retains backward selections after multiline indentation',()=>{const{root}=fixture('a\nb',0,3,true);expect(indentHtmlLiteral(root)).toBe(true);expect(root.textContent).toBe('    a\n    b');expect(htmlLiteralSelection(root)?.backward).toBe(true);});
it('rejects a selection crossing outside the literal object',()=>{const{root,code}=fixture('inside',0);const other=document.body.appendChild(document.createTextNode('outside')),range=document.createRange();range.setStart(code.firstChild!,0);range.setEnd(other,3);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);expect(indentHtmlLiteral(root)).toBe(false);expect(root.textContent).toBe('inside');});

it('indents a selected real blank first line, preserving all literal newlines',()=>{const{root}=fixture('\nalpha\n',0,7);expect(indentHtmlLiteral(root)).toBe(true);expect(root.textContent).toBe('    \n    alpha\n');expect(indentHtmlLiteral(root,true)).toBe(true);expect(root.textContent).toBe('\nalpha\n');});
it('does not mutate opaque child text through a literal range operation',()=>{const{root}=fixture('plain',0,5);const opaque=document.createElement('span');opaque.contentEditable='false';opaque.setAttribute('contenteditable','false');opaque.textContent='opaque';root.append(opaque);expect(indentHtmlLiteral(root)).toBe(false);expect(root.textContent).toBe('plainopaque');});

it('preserves authored HTML breaks while indenting their actual code lines',()=>{const root=document.createElement('pre');root.innerHTML='<code class="keep">alpha<br data-x="author">beta<br>gamma</code>';document.body.append(root);const range=document.createRange(),code=root.querySelector('code')!;range.setStart(code.firstChild!,0);range.setEnd(code.lastChild!,0);document.getSelection()!.removeAllRanges();document.getSelection()!.addRange(range);expect(indentHtmlLiteral(root)).toBe(true);expect(code.innerHTML).toBe('    alpha<br data-x="author">    beta<br>gamma');expect(indentHtmlLiteral(root,true)).toBe(true);expect(code.innerHTML).toBe('alpha<br data-x="author">beta<br>gamma');});
