// @vitest-environment jsdom
import {afterEach,it,expect} from 'vitest';
import {ContentDisplaySession} from './contentDisplaySession';
import {bindHtmlDetailsDisplay} from './htmlDetailsDisplay';
const stops:Array<()=>void>=[];afterEach(()=>{stops.splice(0).forEach(stop=>stop());document.body.replaceChildren();});
function fixture(){const root=document.body.appendChild(document.createElement('div'));root.innerHTML='<details><summary>Outer</summary><details><summary>Inner</summary><p>Body</p></details></details>';const session=new ContentDisplaySession(),entries=()=>Array.from(root.querySelectorAll('details')).map((element,index)=>({element,from:10+index,to:100})),binding=bindHtmlDetailsDisplay(session,entries);stops.push(binding.dispose);return{root,session,entries,binding};}
it('paints the same mounted nested nodes when their shared state changes without an author mutation',()=>{const {root,session,entries}=fixture(),before=root.querySelectorAll('details');session.setExpanded('html-details',10,100,true);session.setExpanded('html-details',11,100,true);expect(entries().every(entry=>entry.element.open)).toBe(true);expect(root.querySelectorAll('details')[0]).toBe(before[0]);expect(root.querySelectorAll('details')[1]).toBe(before[1]);session.setExpanded('html-details',11,100,false);expect(before[0].open).toBe(true);expect(before[1].open).toBe(false);});
it('captures every current native value before its first write broadcasts a repaint',()=>{const {session,entries,binding}=fixture();for(const entry of entries())entry.element.open=true;binding.remember();expect(entries().every(entry=>entry.element.open)).toBe(true);expect(session.expanded('html-details',11,100,false)).toBe(true);});
it('rebinds restored draft nodes dynamically and old detached toggle events cannot overwrite the current state',()=>{const {root,session,binding}=fixture(),old=root.querySelector('details')!;root.innerHTML=root.innerHTML;binding.sync();session.setExpanded('html-details',10,100,true);old.open=false;old.dispatchEvent(new Event('toggle'));expect(root.querySelector('details')!.open).toBe(true);expect(session.expanded('html-details',10,100,false)).toBe(true);});
it('shares parent keys through a remapped child session and stops painting disposed projections',()=>{const {root,session,binding}=fixture();binding.dispose();const child=session.remapped(at=>at+10),details=root.querySelector('details')!,next=bindHtmlDetailsDisplay(child,()=>[{element:details,from:0,to:90}]);session.setExpanded('html-details',10,100,true);expect(details.open).toBe(true);next.dispose();session.setExpanded('html-details',10,100,false);expect(details.open).toBe(true);details.dispatchEvent(new Event('toggle'));expect(session.expanded('html-details',10,100,true)).toBe(false);});

it('registered ID entries keep observing mapped state and revoked IDs cannot recreate a ghost source key',()=>{const {root,session,binding}=fixture();binding.dispose();const element=root.querySelector('details')!,id=session.objectId('html-details',10,100),owned=bindHtmlDetailsDisplay(session,()=>[{element,from:10,to:100,id}]);stops.push(owned.dispose);session.setExpandedById(id,true);expect(element.open).toBe(true);session.clear();element.open=false;owned.remember();expect(session.expandedById(id)).toBeUndefined();owned.sync();expect(session.setExpandedById(id,true)).toBe(false);});
