// @vitest-environment jsdom
import {afterEach,beforeAll,describe,it,expect,vi} from 'vitest';
import {EditorState,EditorSelection,StateEffect} from '@codemirror/state';
import {EditorView} from '@codemirror/view';
import {markdown} from '@codemirror/lang-markdown';
import {GFM} from '@lezer/markdown';
import {history,deleteCharBackward,deleteCharForward,deleteGroupBackward} from '@codemirror/commands';
import {resourceContext} from './editorHost';
import {ContentDisplaySession} from './contentDisplaySession';
import {selectionHistory,undo,redo} from './selectionHistory';
import {markdownParser} from './markdownParser';
import {semanticObjectBoundaries,snapSemanticSelection,planSemanticSelectionDeletion,deleteSemanticSelection,selectSemanticBoundary,leaveSemanticObjectSelection,mergeSemanticParagraphBoundary,semanticSelectAll,moveSemanticWord,deleteSemanticWord,planInlineSelectionDeletion,semanticSelectionExtension,snapSemanticSelectionState} from './objectBoundary';
import {snapLiteralSelection,literalClipboardText} from './literalEditing';
import {preserveCodeStructure,codeSource} from './codeStructure';
import {syntaxTree} from '@codemirror/language';
import {readCode} from './codeEditing';
import {copySemanticSelection} from './contentClipboard';
const views:EditorView[]=[];
beforeAll(()=>{vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}unobserve(){}});Range.prototype.getClientRects=()=>({length:0,item:()=>null,[Symbol.iterator]:function*(){}}) as DOMRectList;Range.prototype.getBoundingClientRect=()=>new DOMRect();});
afterEach(()=>{for(const view of views)view.destroy();views.length=0;document.body.replaceChildren();});
function state(source:string,selection=EditorSelection.single(0),session?:ContentDisplaySession){return EditorState.create({doc:source,selection,extensions:[markdown({extensions:GFM}),history(),selectionHistory,resourceContext.of({documentPath:'fixture.md',profile:'tegg',displaySession:session})]});}
function mount(source:string,selection=EditorSelection.single(0),session?:ContentDisplaySession){const view=new EditorView({parent:document.body.appendChild(document.createElement('div')),state:state(source,selection,session)});views.push(view);return view;}
function deleteSource(source:string,from:number,to:number){const s=state(source,EditorSelection.single(from,to)),plan=planSemanticSelectionDeletion(s);expect(plan).not.toBeNull();return {plan:plan!,next:s.update({changes:plan!.patches,selection:plan!.selection}).state.doc.toString()};}
function semantics(source:string){const node=document.createElement('div');node.innerHTML=markdownParser.render(source,{});return node;}
const code='```js\nvalue\n```';
for(const [kind,source] of [['code',code],['table','| A | B |\n| --- | --- |\n| 1 | 2 |'],['image','![Alt](img.png)'],['math','$$\nx+y\n$$'],['diagram','```mermaid\ngraph LR; A-->B\n```'],['html','<details><summary>A</summary><p>B</p></details>'],['html','<p data-original="true">A</p>']] as const)it(`finds a complete ${kind} source boundary`,()=>{const objects=semanticObjectBoundaries(state('before\n\n'+source+'\n\nafter')),object=objects.find(x=>x.kind===kind)!;expect(object).toBeDefined();expect(object.from).toBe(8);expect(object.to).toBe(8+source.length);expect(object.block).toBe(true);});
it('finds image-only linked images as one inline unit while retaining adjacent text',()=>{const source='a [![Alt](img.png)](https://example.test) z',s=state(source),objects=semanticObjectBoundaries(s);expect(objects).toHaveLength(1);const object=objects[0];expect(s.sliceDoc(object.from,object.to)).toBe('[![Alt](img.png)](https://example.test)');expect(object.block).toBe(false);});
it('snaps reversed inline image and math selections without touching punctuation or spaces',()=>{const source='a, ![Alt](x) / $x+y$ .',view=mount(source);for(const item of semanticObjectBoundaries(view)){const selected=snapSemanticSelection(view,EditorSelection.single(item.to-1,item.from+1));expect(selected.main.anchor).toBe(item.to);expect(selected.main.head).toBe(item.from);const plan=planSemanticSelectionDeletion(view.state,selected)!;const next=view.state.update({changes:plan.patches}).newDoc.toString();expect(next).toBe(source.slice(0,item.from)+source.slice(item.to));}});
it('main-document endpoints inside code always snap to the whole object while code child text stays local',()=>{const source='before\n\n'+code+'\n\nafter',view=mount(source),object=semanticObjectBoundaries(view)[0];expect(snapSemanticSelection(view,EditorSelection.single(2,object.from+8)).main.to).toBe(object.to);const internal=EditorSelection.single(object.from+7,object.from+10);const snapped=snapSemanticSelection(view,internal);expect(snapped.main.from).toBe(object.from);expect(snapped.main.to).toBe(object.to);expect(planSemanticSelectionDeletion(view.state,internal)).not.toBeNull();const child=state('value',EditorSelection.single(1,3));expect(child.update({selection:EditorSelection.single(2,4)}).state.selection.main.to).toBe(4);expect(semanticObjectBoundaries(child)).toHaveLength(0);});
it('never treats code or table contents as a persisted empty paragraph',()=>{for(const source of ['```\n\n```','| A |\n| --- |\n| |'])expect(semanticObjectBoundaries(state(source))).toHaveLength(1);expect(semanticObjectBoundaries(state('<p><br></p>'))).toHaveLength(0);});
it('parses quoted math and preserves its real container identity',()=>{const source='> before\n>\n> $$\n> x+y\n> $$\n>\n> after',s=state(source),objects=semanticObjectBoundaries(s),math=objects.find(x=>x.kind==='math')!;expect(math).toBeDefined();expect(s.sliceDoc(math.from,math.to)).toBe('> $$\n> x+y\n> $$');expect(math.parentName).toBe('Blockquote');});
it('collapsing Callout does not turn title-only selection into its hidden body',()=>{const source='> [!note]- Title\n> hidden body',view=mount(source),object=semanticObjectBoundaries(view).find(x=>x.kind==='callout')!;expect(object).toBeDefined();const title=EditorSelection.single(source.indexOf('Title'),source.indexOf('\n'));expect(snapSemanticSelection(view,title).eq(title)).toBe(true);const external=EditorSelection.single(0,source.indexOf('hidden')+1);expect(snapSemanticSelection(view,external).main.to).toBe(source.length);});
it('shared expanded state overrides the saved Callout fold marker',()=>{const source='> [!note]- Title\n> body',session=new ContentDisplaySession();session.setExpanded('callout',0,source.length,true);expect(semanticObjectBoundaries(state(source,undefined,session)).some(x=>x.kind==='callout')).toBe(false);});
for(const [text,from,to,expected] of [['a &amp; z',3,4,'&amp;'],['a \\* z',3,4,'\\*'],['a 👩🏽‍💻 z',3,5,'👩🏽‍💻'],['a e\u0301 z',3,4,'e\u0301'],['a :smile: z',4,6,':smile:'],['a[^n] z\n\n[^n]: unchanged',2,4,'[^n]']] as const)it(`normalizes visible literal ${expected}`,()=>{const s=state(text),selected=snapLiteralSelection(s,EditorSelection.single(from,to));expect(s.sliceDoc(selected.main.from,selected.main.to)).toBe(expected);});
it('decoded entity clipboard retains visible text after selection normalization',()=>{const source='A &amp; B',s=state(source),selection=snapLiteralSelection(s,EditorSelection.single(3,5)),selected=s.update({selection}).state;expect(literalClipboardText(selected.sliceDoc(selection.main.from,selection.main.to),selected)).toBe('&');});
for(const backwards of [false,true])it(`boundary ${backwards?'Backspace':'Delete'} selects first, Escape and arrows restore only logical positions`,()=>{const source='before\n\n'+code+'\n\nafter',head=backwards?source.indexOf('after'):6,view=mount(source,EditorSelection.single(head));expect(selectSemanticBoundary(view,backwards)).toBe(true);expect(view.state.doc.toString()).toBe(source);expect(view.state.sliceDoc(view.state.selection.main.from,view.state.selection.main.to)).toBe(code);expect(leaveSemanticObjectSelection(view,0)).toBe(true);expect(view.state.selection.main.head).toBe(head);selectSemanticBoundary(view,backwards);expect(leaveSemanticObjectSelection(view,backwards?-1:1)).toBe(true);expect(view.state.selection.main.head).toBe(backwards?6:source.indexOf('after'));expect(view.state.doc.toString()).toBe(source);});
it('a selected independent object deletion retains both untouched paragraphs and exact Undo selection',()=>{const source='before\n\n'+code+'\n\nafter',view=mount(source,EditorSelection.single(source.indexOf('after')));selectSemanticBoundary(view,true);const selected=view.state.selection;expect(deleteSemanticSelection(view)).toBe(true);expect(view.state.doc.toString()).toBe('before\n\n\n\nafter');for(let n=0;n<3;n++){expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.eq(selected)).toBe(true);expect(redo(view)).toBe(true);expect(view.state.doc.toString()).toBe('before\n\n\n\nafter');}});
it('a sole quoted code deletion preserves the quote rail rather than silently deleting its parent',()=>{const source='> ```\n> code\n> ```',view=mount(source,EditorSelection.single(source.length));expect(selectSemanticBoundary(view,true)).toBe(true);expect(deleteSemanticSelection(view)).toBe(true);expect(view.state.doc.toString()).toBe('>');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('deleting a nested object does not outdent or delete a Callout header',()=>{const source='> [!note]+ Title\n>\n> ```\n> code\n> ```\n>\n> after',view=mount(source,EditorSelection.single(source.indexOf('after')));expect(selectSemanticBoundary(view,true)).toBe(true);deleteSemanticSelection(view);expect(view.state.doc.toString()).toContain('> [!note]+ Title');expect(view.state.doc.toString()).toContain('> after');expect(semantics(view.state.doc.toString()).querySelectorAll('blockquote')).toHaveLength(1);});
it('cross-object partial selection joins only same-parent ordinary residuals without adding spaces',()=>{const source='before\n\n'+code+'\n\nafter\n\nthird',from=2,to=source.indexOf('after')+2,view=mount(source,EditorSelection.single(to,from));expect(deleteSemanticSelection(view)).toBe(true);expect(view.state.doc.toString()).toBe('beter\n\nthird');undo(view);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.main.anchor).toBe(to);expect(view.state.selection.main.head).toBe(from);});
it('cross-parent deletion trims quote and outside text separately without importing the outside suffix',()=>{const source='before\n\n> quoted\n> text\n\nafter\n\nthird',from=source.indexOf('quoted')+3,to=source.indexOf('after')+2,{next}=deleteSource(source,from,to);expect(next).toBe('before\n\n> quo\n\nter\n\nthird');const parsed=semantics(next);expect(parsed.querySelector('blockquote')!.textContent!.trim()).toBe('quo');expect(parsed.querySelectorAll('p')[2].textContent).toBe('ter');});
it('cross-parent outside-to-quote deletion retains the quote prefix and both unselected structures',()=>{const source='before\n\n> quoted\n> text\n\nafter',{next}=deleteSource(source,2,source.indexOf('quoted')+3);expect(next).toBe('be\n\n> ted\n> text\n\nafter');});
it('cross-list-item deletion preserves both markers and surviving descendants',()=>{const source='- first\n  - child\n- second\n  - survivor\n\noutside',{next}=deleteSource(source,source.indexOf('first')+2,source.indexOf('second')+2);expect(next).toContain('- fi');expect(next).toContain('- cond');expect(next).toContain('  - survivor');expect(next).toContain('\n\noutside');});
it('clearing Callout body keeps the type, title, fold marker and editable empty body prefix',()=>{const source='> [!warning]+ Title\n> body',{next}=deleteSource(source,source.indexOf('body'),source.length);expect(next).toBe('> [!warning]+ Title\n> ');});
it('deleting a footnote reference does not delete its definition or another reference',()=>{const source='A[^n] B[^n]\n\n[^n]: retained',{next}=deleteSource(source,2,4);expect(next).toBe('A B[^n]\n\n[^n]: retained');});
for(const [source,from,to,expected] of [['**before**\n\n'+code+'\n\n*after*',4,('**before**\n\n'+code+'\n\n').length+3,'<p><strong>be</strong><em>ter</em></p>'],['**before**\n\n'+code+'\n\n**after**',4,('**before**\n\n'+code+'\n\n').length+4,'<p><strong>beter</strong></p>'],['[before](first.md)\n\n'+code+'\n\n[after](last.md)',3,('[before](first.md)\n\n'+code+'\n\n').length+3,'<p><a href="first.md">be</a><a href="last.md">ter</a></p>']] as const)it('preserves unselected inline wrapper semantics across a selected object',()=>{const {next}=deleteSource(source,from,to);expect(semantics(next).innerHTML.trim()).toBe(expected);});
for(const backwards of [false,true])it(`ordinary paragraph merge ${backwards?'backward':'forward'} merges only two and preserves hard breaks/styles`,()=>{const source='**first**\\\nline\n\n*second*\n\nthird',head=backwards?source.indexOf('*second*'):source.indexOf('\n\n'),view=mount(source,EditorSelection.single(head));expect(mergeSemanticParagraphBoundary(view,backwards)).toBe(true);expect(view.state.doc.toString()).toBe('**first**\\\nline*second*\n\nthird');expect(semantics(view.state.doc.toString()).querySelectorAll('br')).toHaveLength(1);undo(view);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.main.head).toBe(head);});
it('paragraph merge blocks a heading or different parent and defers quoted Backspace to existing S16',()=>{for(const source of ['before\n\n# heading\n\nafter','before\n\n> quote\n\nafter']){const view=mount(source,EditorSelection.single(6));expect(mergeSemanticParagraphBoundary(view,false)).toBe(true);expect(view.state.doc.toString()).toBe(source);}const quote='> first\n>\n> second',view=mount(quote,EditorSelection.single(quote.indexOf('second')));expect(mergeSemanticParagraphBoundary(view,true)).toBe(false);expect(view.state.doc.toString()).toBe(quote);});
it('readonly and composing states never select or delete objects, and refuse stale boundaries',()=>{const source='before\n\n'+code,view=mount(source,EditorSelection.single(source.length));Object.defineProperty(view,'composing',{value:true,configurable:true});expect(selectSemanticBoundary(view,true)).toBe(false);expect(deleteSemanticSelection(view)).toBe(false);Object.defineProperty(view,'composing',{value:false,configurable:true});selectSemanticBoundary(view,true);view.dispatch({changes:{from:0,insert:'changed'}});expect(leaveSemanticObjectSelection(view,0)).toBe(false);const readonly=state(source,EditorSelection.single(8,source.length)).update({effects:[]}).state;const locked=EditorState.create({doc:readonly.doc,selection:readonly.selection,extensions:[markdown(),EditorState.readOnly.of(true)]});expect(planSemanticSelectionDeletion(locked)).toBeNull();});

for(const backwards of [false,true])it(`saved explicit blank paragraph is removed before selecting an adjacent object ${backwards}`,()=>{const source=backwards?code+'\n\n<p><br></p>\n\nafter':'before\n\n<p><br></p>\n\n'+code,from=source.indexOf('<p>'),view=mount(source,EditorSelection.single(from+3));expect(selectSemanticBoundary(view,backwards)).toBe(true);expect(view.state.doc.toString()).toBe(source.replace('<p><br></p>',''));expect(view.state.selection.main.empty).toBe(true);expect(view.state.selection.main.head).toBe(backwards?view.state.doc.toString().indexOf('after'):6);undo(view);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.main.head).toBe(from+3);});
for(const backwards of [false,true])it(`formatted paragraph visible endpoint merges without losing either wrapper ${backwards}`,()=>{const source='**before**\n\n*after*\n\nthird',head=backwards?source.indexOf('*after*')+1:source.indexOf('**\n'),view=mount(source,EditorSelection.single(head));expect(mergeSemanticParagraphBoundary(view,backwards)).toBe(true);expect(view.state.doc.toString()).toBe('**before***after*\n\nthird');expect(semantics(view.state.doc.toString()).querySelectorAll('p')).toHaveLength(2);expect(semantics(view.state.doc.toString()).querySelector('strong')!.textContent).toBe('before');expect(semantics(view.state.doc.toString()).querySelector('em')!.textContent).toBe('after');});
it('heading start and end consume boundary deletion without changing source',()=>{const source='before\n\n# heading\n\nafter';for(const [head,backwards] of [[source.indexOf('heading'),true],[source.indexOf('\n\nafter'),false]] as const){const view=mount(source,EditorSelection.single(head));expect(mergeSemanticParagraphBoundary(view,backwards)).toBe(true);expect(view.state.doc.toString()).toBe(source);}});
it('selection extension synchronously snaps before consumers read state and preserves title selection',()=>{const source='before\n\n'+code+'\n\nafter',s=state(source),live=EditorState.create({doc:s.doc,extensions:[markdown({extensions:GFM}),resourceContext.of({profile:'tegg',documentPath:'fixture.md'}),semanticSelectionExtension]}),object=semanticObjectBoundaries(live)[0],next=live.update({selection:EditorSelection.single(2,object.from+9)}).state;expect(next.selection.main.to).toBe(object.to);expect(snapSemanticSelectionState(next,next.selection).eq(next.selection)).toBe(true);const callout='> [!note]- Title\n> hidden',fold=EditorState.create({doc:callout,extensions:[markdown(),resourceContext.of({profile:'tegg',documentPath:'fixture.md'}),semanticSelectionExtension]}),selected=EditorSelection.single(callout.indexOf('Title'),callout.indexOf('\n'));expect(fold.update({selection:selected}).state.selection.eq(selected)).toBe(true);});

function cellState(source:string,selection:EditorSelection){return EditorState.create({doc:source,selection,extensions:[markdown({extensions:GFM}),resourceContext.of({profile:'tegg',documentPath:'fixture.md',editingContext:'table-cell'})]});}
for(const [source,from,to,expected] of [['<strong>before</strong>',9,11,'<strong>bore</strong>'],['<em data-origin="x">before</em>',21,23,'<em data-origin="x">bore</em>'],['**before** and *after*',4,18,'**be***ter*'],['A &amp; B',3,5,'A  B'],['a ![Alt](x) z',4,7,'a  z']] as const)it(`cell cut preserves inline source without promoting HTML into block objects: ${source}`,()=>{const s=cellState(source,EditorSelection.single(from,to)),plan=planInlineSelectionDeletion(s);expect(plan).not.toBeNull();expect(s.update({changes:plan!.patches}).newDoc.toString()).toBe(expected);expect(planSemanticSelectionDeletion(s)!.patches).toEqual(plan!.patches);});
it('cell source with unknown/malformed HTML or endpoints in attributes is refused without changing it',()=>{for(const [source,from,to] of [['<widget>text</widget>',9,11],['<strong>text</em>',9,11],['<em data-origin="x">before</em>',5,8]] as const){const s=cellState(source,EditorSelection.single(from,to));expect(planInlineSelectionDeletion(s)).toBeNull();expect(s.doc.toString()).toBe(source);}});
for(const [atom,label] of [['&amp;','entity'],['\\*','escape'],[':smile:','emoji'],['👩🏽‍💻','extended grapheme'],['[^n]','footnote']] as const)for(const backwards of [false,true])it(`native char deletion removes the whole ${label} ${backwards}`,()=>{const source='A '+atom+' B'+(label==='footnote'?'\n\n[^n]: definition':''),head=backwards?2+atom.length:2,s=state(source,EditorSelection.single(head)),view=new EditorView({parent:document.body.appendChild(document.createElement('div')),state:EditorState.create({doc:s.doc,selection:s.selection,extensions:[markdown({extensions:GFM}),resourceContext.of({profile:'tegg',documentPath:'fixture.md'}),history(),selectionHistory,semanticSelectionExtension]})});views.push(view);expect((backwards?deleteCharBackward:deleteCharForward)(view)).toBe(true);expect(view.state.doc.toString()).toBe('A  B'+(label==='footnote'?'\n\n[^n]: definition':''));undo(view);expect(view.state.doc.toString()).toBe(source);});

it('immutable object/literal caches still respect mutable display folding and editing-context ownership',()=>{const source='> [!note]- Title\n> body',session=new ContentDisplaySession(),s=state(source,undefined,session);expect(semanticObjectBoundaries(s).some(x=>x.kind==='callout')).toBe(true);session.setExpanded('callout',0,source.length,true);expect(semanticObjectBoundaries(s).some(x=>x.kind==='callout')).toBe(false);const html='<p data-original="true">before</p>',main=state(html),cell=cellState(html,EditorSelection.single(9,11));expect(semanticObjectBoundaries(main)[0].kind).toBe('html');expect(semanticObjectBoundaries(cell)).toHaveLength(0);});

for(const source of ['**hello** world','[hello](https://example.test) world','<u>hello</u> world'])it(`word movement and deletion operate on visible words rather than hidden syntax: ${source}`,()=>{const head=source.indexOf('hello'),view=mount(source,EditorSelection.single(head));expect(moveSemanticWord(view,true,true)).toBe(true);expect(view.state.selection.main.to).toBe(head+5);expect(view.state.sliceDoc(view.state.selection.main.from,view.state.selection.main.to)).toBe('hello');expect(deleteSemanticWord(view,true)).toBe(true);expect(view.state.doc.toString()).toBe(' world');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('Chinese words follow Intl system segmentation instead of treating all source characters as one raw group',()=>{const source='你好世界',segments=Array.from(new Intl.Segmenter(undefined,{granularity:'word'}).segment(source)).filter(item=>item.isWordLike),view=mount(source);expect(segments.length).toBeGreaterThan(1);expect(moveSemanticWord(view,true,true)).toBe(true);expect(view.state.selection.main.to).toBe(segments[0].segment.length);expect(deleteSemanticWord(view,false)).toBe(true);expect(view.state.doc.toString()).toBe(source.slice(segments[0].segment.length));});
it('word extension through an inline formula snaps to the complete object and Undo preserves nearby punctuation',()=>{const source='hello, $x+y$ world',view=mount(source,EditorSelection.single(0));expect(moveSemanticWord(view,true,true)).toBe(true);expect(view.state.selection.main.to).toBe(5);expect(moveSemanticWord(view,true,true)).toBe(true);expect(view.state.selection.main.to).toBe(12);deleteSemanticWord(view,true);expect(view.state.doc.toString()).toBe(' world');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('word deletion of a decoded entity and emoji never leaves a partial raw literal',()=>{for(const atom of ['&amp;',':smile:','👩🏽‍💻']){const source='before '+atom+' after',head=7+atom.length,view=mount(source,EditorSelection.single(head));expect(deleteSemanticWord(view,true)).toBe(true);expect(view.state.doc.toString()).not.toContain(atom.slice(0,-1));expect(view.state.doc.toString()).toContain(' after');undo(view);expect(view.state.doc.toString()).toBe(source);}});

function mountLive(source:string,selection=EditorSelection.single(0)){const view=new EditorView({parent:document.body.appendChild(document.createElement('div')),state:state(source,selection).update({effects:StateEffect.appendConfig.of(semanticSelectionExtension)}).state});views.push(view);return view;}
it('only an explicit main-document Select All removes a sole object parent; A6 and arbitrary ranges preserve the rail',()=>{const source='> ```\n> code\n> ```',view=mountLive(source,EditorSelection.single(source.length));expect(selectSemanticBoundary(view,true)).toBe(true);expect(planSemanticSelectionDeletion(view.state)!.patches[0].insert).toBe('>');expect(semanticSelectAll(view)).toBe(true);expect(planSemanticSelectionDeletion(view.state)!.patches[0].insert).toBe('');deleteSemanticSelection(view);expect(view.state.doc.toString()).toBe('');for(let n=0;n<3;n++){undo(view);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.main.from).toBe(0);expect(view.state.selection.main.to).toBe(source.length);expect(planSemanticSelectionDeletion(view.state)!.patches[0].insert).toBe('');redo(view);expect(view.state.doc.toString()).toBe('');}undo(view);view.dispatch({selection:EditorSelection.single(source.length)});view.dispatch({selection:EditorSelection.single(0,source.length)});expect(planSemanticSelectionDeletion(view.state)!.patches[0].insert).toBe('>');});
for(const source of ['# **hello** world','> **hello** world','- **hello** world'])it(`word text boundaries respect heading/container prefix: ${source}`,()=>{const head=source.indexOf('hello'),view=mount(source,EditorSelection.single(head));expect(moveSemanticWord(view,true,true)).toBe(true);expect(view.state.selection.main.to).toBe(head+5);deleteSemanticWord(view,true);expect(view.state.doc.toString()).toBe(source.replace('**hello**',''));});

it('Select All container intent never transfers to a reconfigured document identity with identical bytes',()=>{const source='> ```\n> code\n> ```',view=mountLive(source);semanticSelectAll(view);expect(planSemanticSelectionDeletion(view.state)!.patches[0].insert).toBe('');view.dispatch({effects:StateEffect.reconfigure.of([markdown({extensions:GFM}),history(),selectionHistory,resourceContext.of({documentPath:'other.md',profile:'tegg'}),semanticSelectionExtension])});expect(planSemanticSelectionDeletion(view.state)!.patches[0].insert).toBe('>');});


// These are the real main-document selection and acknowledged-Cut paths, not
// direct raw Source edits. S17 repair remains in the same guarded transaction.
const gapContainers=[['root','paragraph',''],['bullet','- paragraph','  '],['wide','100. paragraph','     '],['nested','- parent\n  - paragraph','    '],['task','- [ ] paragraph','  '],['quote','> paragraph','> '],['quoted list','> - paragraph','>   ']];
function mountCodeGap(source:string,selection:EditorSelection){
  const view=new EditorView({parent:document.body.appendChild(document.createElement('div')),state:state(source,selection).update({effects:StateEffect.appendConfig.of([preserveCodeStructure,semanticSelectionExtension])}).state});views.push(view);return view;
}
function expectGapHistory(view:EditorView,source:string,selection:EditorSelection,changed:string){
  expect(view.state.doc.toString()).toBe(changed);
  for(let round=0;round<3;round++){
    expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.eq(selection)).toBe(true);
    expect(redo(view)).toBe(true);expect(view.state.doc.toString()).toBe(changed);
  }
  expect(undo(view)).toBe(true);expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.eq(selection)).toBe(true);
  expect(undo(view)).toBe(false);
}
for(const [name,lead,prefix]of gapContainers)for(const fenced of [false,true])for(const cut of [false,true])it(`${name} ${fenced?'fenced':'indented'} gap ${cut?'acknowledged Cut':'selection Delete'} preserves exact source, code and three Undo selections`,async()=>{
  const rows=fenced?['```','first','    nested','```']:['    first','        nested'];
  const code=rows.map(row=>prefix+row).join('\n'),gap='\n'+(prefix.includes('>')?'>':'')+'\n',tail=prefix?'- next':'tail';
  const source=lead+gap+code+'\n\n'+tail,selection=EditorSelection.single(lead.length,lead.length+gap.length),view=mountCodeGap(source,selection);
  const expected=lead+'\n'+(fenced?code:['```','first','    nested','```'].map(row=>prefix+row).join('\n'))+'\n\n'+tail;
  const plan=planSemanticSelectionDeletion(view.state)!;expect(plan).not.toBeNull();expect(plan.patches).toEqual([{from:selection.main.from,to:selection.main.to,insert:'',expected:gap}]);
  if(cut){let ack!:(success:boolean)=>void;let data:any;view.dom.addEventListener('tegg-copy-content',event=>{event.preventDefault();data=(event as CustomEvent).detail;ack=data.complete;});
    const copying=copySemanticSelection(view,{cut:true});expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.eq(selection)).toBe(true);expect(data.mime).toBe('application/x-tegg-content+json');expect(JSON.parse(data.structured).source).toBe(gap);expect(typeof data.text).toBe('string');expect(typeof data.html).toBe('string');ack(true);expect(await copying).toBe(true);
  }else expect(deleteSemanticSelection(view)).toBe(true);
  const blocks:{body:string;prefix:string}[]=[];syntaxTree(view.state).iterate({enter(ref){if(['CodeBlock','FencedCode'].includes(ref.name)){const block=codeSource(view.state,ref.node);if(block)blocks.push({body:readCode(block.plain).body,prefix:block.prefix});return false;}}});expect(blocks).toEqual([{body:'first\n    nested',prefix}]);
  expectGapHistory(view,source,selection,expected);
});
for(const fenced of [false,true])it(`gap after ${fenced?'fenced':'indented'} code keeps the untouched following paragraph separate`,()=>{
  const code=fenced?'```\nfirst\n```':'    first',source='before\n\n'+code+'\n\nafter',from=source.indexOf('\n\nafter'),selection=EditorSelection.single(from,from+2),view=mountCodeGap(source,selection);
  expect(deleteSemanticSelection(view)).toBe(true);expectGapHistory(view,source,selection,'before\n\n'+code+'\nafter');
});
it('code gap permission does not extend to a partial quote rail, unsupported mixed prefix or a table gap',()=>{
  for(const [source,from,to]of [['> before\n> >\n> >     code',9,10],['before\n\n- ```\n  code\n  ```',6,8],['before\n\n| A |\n| --- |\n| B |',6,8]] as const){
    const s=state(source,EditorSelection.single(from,to));expect(planSemanticSelectionDeletion(s)).toBeNull();
  }
});
it('a visible > before code remains ordinary selected punctuation rather than granting raw gap deletion',()=>{
  const source='before >\n\n    code',s=state(source,EditorSelection.single(7,10)),plan=planSemanticSelectionDeletion(s);
  expect(plan?.patches).toEqual([{from:7,to:8,insert:'',expected:'>'}]);
});
