import {setProjectedSourceContext} from './projectedSource';
import type MarkdownIt from 'markdown-it';
import {footnoteDocument,footnoteBodyPosition,type FootnoteDocument} from './footnoteModel';
import {footnoteLayout,footnoteNavigation,type FootnoteGroup} from './footnoteLayout';
import {sanitizeRenderedHtml} from './renderKit';
import {focusTarget} from './renderInteraction';
import {setUIText,setUILabel} from './uiContext';
export function readerFootnoteDocument(parser:MarkdownIt,source:string){const lines=source.split('\n'),offsets=[0];for(const line of lines)offsets.push(offsets.at(-1)!+line.length+1);const excluded=parser.parse(source,{}).filter(token=>['fence','code_block','html_block'].includes(token.type)&&token.map).map(token=>({from:offsets[token.map![0]],to:Math.min(source.length,offsets[token.map![1]])}));return footnoteDocument(source,excluded);}
export function configureMissingFootnotes(parser:MarkdownIt){
  parser.inline.ruler.before('footnote_ref','tegg_missing_footnote',(state,silent)=>{const model=state.env?.teggFootnotes as FootnoteDocument|undefined;if(!model)return false;const match=/^\[\^([^\]\n]+)\]/.exec(state.src.slice(state.pos));if(!match||model.definitions.some(note=>note.label===match[1]))return false;if(!silent){const token=state.push('tegg_missing_footnote','',0);token.content=match[1];}state.pos+=match[0].length;return true;});
  parser.renderer.rules.tegg_missing_footnote=(tokens,index)=>'<sup class="footnote-ref is-missing"><a href="#fn-tegg-missing" data-footnote-label="'+parser.utils.escapeHtml(tokens[index].content)+'">?</a></sup>';
}
export function projectReaderFootnotes(root:HTMLElement,model:FootnoteDocument,parser:MarkdownIt,documentPath?:string,resolveImage?:(src:string,path:string)=>string,source="",documentBody=source,renderBody?:(body:HTMLElement,value:string,position:(at:number)=>number)=>void){
  root.querySelectorAll('.footnotes,.footnotes-sep').forEach(node=>node.remove());
  const references=[...root.querySelectorAll<HTMLElement>('.footnote-ref a,.footnote-ref button')];references.forEach((node,index)=>{const reference=model.references[index];if(!reference)return;node.dataset.footnoteLabel=reference.label;node.dataset.footnoteReferenceFrom=String(reference.from);node.id='fnref-tegg-'+index;if(reference.number===undefined)node.setAttribute('href','#fn-tegg-missing-'+encodeURIComponent(reference.label));node.textContent=reference.number===undefined?'?':String(reference.number);setUILabel(node,reference.number===undefined?'Undefined footnote: {label}':'Footnote {value}',{label:reference.label,value:String(reference.number)});});
  if(!model.definitions.length&&!model.missing.length)return;
  const section=document.createElement('section');section.className='footnotes';const layout=footnoteLayout(section),items=[...model.definitions,...model.missing.map(item=>({key:'missing:'+item.label,label:item.label,value:'',from:0,to:0,number:undefined,references:item.references,missing:true,duplicate:false}))];
  const assigned=new Set<string>();for(const note of items){const missing='missing' in note,kind:FootnoteGroup=missing?'missing':note.duplicate?'duplicates':note.number===undefined?'unreferenced':'main',item=document.createElement('li');item.className='footnote-item md-render-footnote-definition';item.dataset.footnoteLabel=note.label;item.dataset.footnoteKey=note.key;item.tabIndex=-1;const ref=references.find(node=>node.dataset.footnoteLabel===note.label);item.id=!assigned.has(note.label)?ref?.getAttribute('href')?.slice(1)??'fn-tegg-'+note.key:'fn-tegg-'+note.key;assigned.add(note.label);const number=document.createElement('span');number.className='footnote-number';number.textContent=missing?'?':note.number===undefined?'':String(note.number);const content=document.createElement('div');content.className='footnote-content';item.append(number,content);
    if(kind!=='main'){const label=document.createElement('code');label.className='footnote-label';label.textContent=note.label;content.append(label);}if(missing){const description=document.createElement('p');description.className='footnote-missing-description';setUIText(description,'This footnote has no definition.');content.append(description);}else{if(note.duplicate){const warning=document.createElement('p');warning.className='footnote-duplicate-description';setUIText(warning,'This label has repeated definitions. Each source definition is preserved.');content.append(warning);}const body=document.createElement('div');body.className='footnote-body';const normalized=source.replace(/\r\n/g,'\n'),base=Math.max(0,normalized.indexOf(documentBody.replace(/\r\n/g,'\n')));const position=(at:number)=>base+note.from+footnoteBodyPosition(normalized.slice(base+note.from,base+note.to),at);setProjectedSourceContext(body,{source:note.value,position});if(renderBody)renderBody(body,note.value,position);else body.innerHTML=sanitizeRenderedHtml(parser.render(note.value,{}),documentPath,resolveImage);content.append(body);}
    if(note.references.length)content.append(footnoteNavigation(note.references,reference=>focusTarget(references.find(node=>node.dataset.footnoteReferenceFrom===String(reference.from)))));layout.group(kind).list.append(item);
  }layout.prune();root.append(section);
}
