// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {observeTypography,refreshTypography} from './typography';
import {EditingUI} from './editingUI';
const cleanup:Array<()=>void>=[];
afterEach(()=>{cleanup.splice(0).reverse().forEach(stop=>stop());vi.unstubAllGlobals();document.body.replaceChildren();});
function runtime(){let next=0;const frames=new Map<number,FrameRequestCallback>(),observers:Array<{callback:ResizeObserverCallback,targets:Element[],disconnected:boolean}>=[];
 vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>{frames.set(++next,cb);return next;});vi.stubGlobal('cancelAnimationFrame',(id:number)=>frames.delete(id));
 vi.stubGlobal('ResizeObserver',class{entry:{callback:ResizeObserverCallback,targets:Element[],disconnected:boolean};constructor(callback:ResizeObserverCallback){this.entry={callback,targets:[],disconnected:false};observers.push(this.entry);}observe(target:Element){this.entry.targets.push(target);}disconnect(){this.entry.disconnected=true;}});
 const deliver=(i=0)=>observers[i].callback(observers[i].targets.map(target=>({target}) as ResizeObserverEntry),{} as ResizeObserver);
 const flush=()=>{const pending=[...frames.values()];frames.clear();pending.forEach(cb=>cb(0));};return {frames,observers,deliver,flush};
}
it('typography keeps initial and explicit sizing synchronous while RO coalesces latest hidden-to-visible allocation',()=>{const r=runtime(),root=document.body.appendChild(document.createElement('div'));let width=0;Object.defineProperty(root,'clientWidth',{get:()=>width});const stop=observeTypography(root);cleanup.push(stop);expect(root.style.getPropertyValue('--md-canvas-width')).toBe('0px');width=480;r.deliver();width=960;r.deliver();expect(r.frames.size).toBe(1);expect(root.dataset.layout).toBe('compact');r.flush();expect(root.style.getPropertyValue('--md-canvas-width')).toBe('960px');expect(root.dataset.layout).toBe('wide');width=672;refreshTypography(root);expect(root.style.getPropertyValue('--md-canvas-width')).toBe('672px');});
it('typography dispose cancels pending work and late delivery cannot alter a replacement owner',()=>{const r=runtime(),root=document.body.appendChild(document.createElement('div'));let width=100;Object.defineProperty(root,'clientWidth',{get:()=>width});const stop=observeTypography(root);width=960;r.deliver();const old=[...r.frames.values()][0];stop();expect(r.frames.size).toBe(0);width=480;const replacement=observeTypography(root);cleanup.push(replacement);expect(root.dataset.layout).toBe('regular');width=1000;old(0);r.deliver(0);expect(r.frames.size).toBe(0);expect(root.style.getPropertyValue('--md-canvas-width')).toBe('480px');stop();r.deliver(1);expect(r.frames.size).toBe(1);r.flush();expect(root.style.getPropertyValue('--md-canvas-width')).toBe('1000px');});
function workspace(){const r=runtime(),panel=document.body.appendChild(document.createElement('div')),content=panel.appendChild(document.createElement('div')),body=content.appendChild(document.createElement('textarea'));panel.dataset.kind='math';body.value='x';body.style.lineHeight='30px';const owner={mobile:true,panelEpoch:1,panel,content,controller:{view:{dom:content}},panelCleanup:undefined as undefined|(()=>void)};Object.defineProperty(window,'innerWidth',{value:390,configurable:true});(EditingUI.prototype as any).watchObjectWorkspace.call(owner,body);cleanup.push(()=>owner.panelCleanup?.());return {r,panel,body,owner};}
it('object workspace RO defers textarea height writes and multiple deliveries use one frame with unchanged sizing',()=>{const {r,body}=workspace();r.flush();expect(body.style.height).toBe('80px');body.style.lineHeight='62px';r.deliver();r.deliver();expect(body.style.height).toBe('80px');expect(r.frames.size).toBe(1);r.flush();expect(body.style.height).toBe('142px');body.value='x\ny';body.dispatchEvent(new Event('input'));expect(body.style.height).toBe('204px');});
it('object workspace cleanup cancels its initial and pending frame and revokes callback writes across a new panel epoch',()=>{const {r,body,owner}=workspace();expect(r.frames.size).toBe(1);const initial=[...r.frames.values()][0];owner.panelCleanup!();expect(r.frames.size).toBe(0);initial(0);r.deliver();expect(r.frames.size).toBe(0);expect(body.style.height).toBe('');const next=workspace();next.r.flush();next.body.style.lineHeight='62px';next.r.deliver();const pending=[...next.r.frames.values()][0];next.owner.panelEpoch++;pending(0);expect(next.body.style.height).toBe('80px');});
