// @vitest-environment jsdom
import {describe,it,expect} from 'vitest';
import {sourcePreservingHtmlDraft} from './richHtmlDraft';
import {sanitizeRenderedHtml} from './renderKit';
function fixture(source:string){const root=document.createElement('div');root.innerHTML=sanitizeRenderedHtml(source);return {root,draft:sourcePreservingHtmlDraft(root,source)};}
describe('rich HTML cell drafts',()=>{
 it('restores independent mapped DOM snapshots without losing original attributes/entities',()=>{const source='<p title="keep">A &amp; <strong>B</strong></p>';const {root,draft}=fixture(source);const initial=draft.snapshot();root.querySelector('strong')!.textContent='first';draft.markChanged();const first=draft.snapshot();root.querySelector('p')!.setAttribute('title','browser-only');root.querySelector('strong')!.textContent='second';first();expect(draft.serialize()).toBe(source.replace('B</strong>','first</strong>'));initial();expect(draft.serialize()).toBe(source);first();expect(draft.serialize()).toBe(source.replace('B</strong>','first</strong>'));});
 it('preserves sanitized opaque objects while editing adjacent mapped paragraphs',()=>{const source='<p>Before</p><script>neverExecute()</script><form><p>Opaque</p></form><p>After</p>';const {root,draft}=fixture(source);expect(root.querySelector('script')).toBeNull();root.querySelector('p')!.firstChild!.textContent='Changed';draft.markChanged();expect(draft.serialize()).toBe(source.replace('Before','Changed'));expect(root.querySelector('[contenteditable=false]')!.textContent).toBe('Opaque');});
 it('preserves original source and entities on entry without input',()=>{const source="<p data-extra='keep'>A &amp; <strong title='x'>粗体</strong></p><!--hidden-->";const {draft}=fixture(source);expect(draft.serialize()).toBe(source);});
 it('edits rendered text without dropping source attributes or hidden comments',()=>{const source="<p data-extra='keep'>A &amp; <strong title='x'>粗体</strong></p><!--hidden-->";const {root,draft}=fixture(source);root.querySelector('strong')!.firstChild!.textContent='新文本';draft.markChanged();expect(draft.serialize()).toBe("<p data-extra='keep'>A &amp; <strong title='x'>新文本</strong></p><!--hidden-->");});
 it('retains two paragraphs, formatting and explicit empty paragraphs',()=>{const source='<p>一</p><p><br></p><p><em>二</em></p>';const {root,draft}=fixture(source);root.querySelector('em')!.firstChild!.textContent='三';draft.markChanged();expect(draft.serialize()).toBe('<p>一</p><p><br></p><p><em>三</em></p>');});
 it('serializes new semantic text without admitting executable markup or author styles',()=>{const {root,draft}=fixture('<p>A</p>');const strong=document.createElement('strong');strong.setAttribute('style','font-size:99px');strong.textContent='<new>';root.querySelector('p')!.append(strong);draft.markChanged();expect(draft.serialize()).toBe('<p>A<strong>&lt;new&gt;</strong></p>');const script=document.createElement('script');script.textContent='x';root.append(script);expect(()=>draft.serialize()).toThrow();});
 it('preserves source entities and rich author attributes through a structural Range split',()=>{const source="<p data-x='keep'><strong title='keep'>A &#38; B</strong></p>",{root,draft}=fixture(source),text=root.querySelector('strong')!.firstChild!,range=document.createRange();range.setStart(text,2);range.setEnd(root.querySelector('p')!,1);const next=document.createElement('p');next.append(draft.extractContents(range));root.append(next);draft.markChanged();expect(draft.serialize()).toBe("<p data-x='keep'><strong title='keep'>A </strong></p><p><strong title='keep'>&#38; B</strong></p>");});
 it('keeps untouched source spaces and numeric entities when native editing inserts NBSP fillers',()=>{const source='<p>Original &#38; text &#160;</p>',{root,draft}=fixture(source);root.querySelector('p')!.firstChild!.textContent='Changed\u00a0& text \u00a0';draft.markChanged();expect(draft.serialize()).toBe('<p>Changed &#38; text &#160;</p>');});
 it('retains authors original hard spaces and rejects a changed object before altering its source mapping',()=>{const source='<p>Hard&#160;Space <img src="old.png" alt="old" width="80"></p>',{root,draft}=fixture(source);const text=root.querySelector('p')!.firstChild!;text.textContent='New\u00a0Space ';draft.markChanged();const image=root.querySelector('img')!;expect(()=>draft.replaceSource(image,'<script>bad()</script>')).toThrow();expect(draft.sourceFor(image)).toBe('<img src="old.png" alt="old" width="80">');expect(draft.serialize()).toBe('<p>New&#160;Space <img src="old.png" alt="old" width="80"></p>');});
});

it('preserves authored class/data flags and an explicit author empty paragraph through edits and snapshots',()=>{const source='<p><span class="md-object-actions" data-tegg-editor-projection="true">Author</span> text</p><p data-tegg-temporary="true"></p>';const {root,draft}=fixture(source);root.querySelector('span')!.textContent='Changed';draft.markChanged();const restore=draft.snapshot();expect(draft.serialize()).toBe(source.replace('Author','Changed'));root.querySelector('p')!.remove();restore();expect(draft.serialize()).toBe(source.replace('Author','Changed'));});

it('preserves an unselected authored ordinary space followed by a numeric space entity during explicit word replacement',()=>{const source='<figcaption>Original &#32;text</figcaption>',root=document.createElement('div');root.innerHTML=source;document.body.append(root);const draft=sourcePreservingHtmlDraft(root,source),text=root.querySelector('figcaption')!.firstChild!,range=document.createRange();range.setStart(text,0);range.setEnd(text,8);expect(draft.insertMappedText(range,'Changed')).toBe(true);expect(draft.serialize()).toBe('<figcaption>Changed &#32;text</figcaption>');root.remove();});
