import {attachEditingUI} from './editingUI';
import {ContentDisplaySession} from './contentDisplaySession';
import {resourceContext,displaySessionMapping} from './editorHost';
import {renderMarkdown} from './markdown';
import {bindContentScroll} from './contentScroll';
import {ChangeSet} from '@codemirror/state';
// @vitest-environment jsdom
import {beforeAll,afterEach,it,expect,vi} from 'vitest';
import {EditorState} from '@codemirror/state';
import {EditorView,runScopeHandlers} from '@codemirror/view';
import {history,undo} from '@codemirror/commands';
import {markdown} from '@codemirror/lang-markdown';
import {GFM} from '@lezer/markdown';
import {livePreview} from './livePreview';
import {editSemanticQuote,insertSemanticParagraph,exitSemanticObject} from './semanticEditing';
import {focusedTableCell,commitTableDrafts} from './tableWidget';
import {focusFootnote,focusedFootnoteEditor,executeFocusedFootnoteCommand} from './footnoteEditing';
import {createMetadataPanel,disposeMetadataPanel,commitMetadataPanel} from './metadata';
import {TeggMarkdownEditor} from './editor';
const views:EditorView[]=[];
beforeAll(()=>{vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}unobserve(){}});Range.prototype.getClientRects=()=>({length:0,item:()=>null,[Symbol.iterator]:function*(){}}) as DOMRectList;Range.prototype.getBoundingClientRect=()=>new DOMRect();});
afterEach(()=>{for(const view of views){const parent=view.dom.parentElement;view.destroy();parent?.remove();}views.length=0;document.body.replaceChildren();});
function mount(source:string,at=source.length){const root=document.body.appendChild(document.createElement('div'));const view=new EditorView({parent:root,state:EditorState.create({doc:source,selection:{anchor:at},extensions:[history(),markdown({extensions:GFM}),livePreview]})});views.push(view);return {view,root};}
function key(target:HTMLElement,key:string,options:KeyboardEventInit={}){target.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...options}));}
function button(root:HTMLElement,value:string){return [...root.querySelectorAll<HTMLButtonElement>('button')].find(node=>node.getAttribute('aria-label')===`Edit table cell: ${value}`)!;}
it('distinguishes semantic paragraphs, hard breaks and retained explicit empty paragraphs',()=>{const {view}=mount('中文 words',2);expect(insertSemanticParagraph(view)).toBe(true);expect(view.state.doc.toString()).toBe('中文\n\n words');expect(insertSemanticParagraph(view)).toBe(true);expect(view.state.doc.toString()).toBe('中文\n\n<p><br></p>\n\n words');undo(view);expect(view.state.doc.toString()).toBe('中文\n\n words');});
it('retains an explicit empty paragraph at document end and projects no HTML tags',()=>{const {view,root}=mount('text');insertSemanticParagraph(view);insertSemanticParagraph(view);expect(view.state.doc.toString()).toBe('text\n\n<p><br></p>\n\n');expect(root.textContent).not.toContain('<p>');});
it('splits a quote as semantic paragraphs while preserving the following paragraph',()=>{const {view}=mount('> hello world\n>\n> later',7);expect(editSemanticQuote(view,true)).toBe(true);expect(view.state.doc.toString()).toBe('> hello\n>\n>  world\n>\n> later');});
it('outdents the entire quoted paragraph including its hard break and preserves other paragraphs',()=>{const source='> first\n>\n> hello\\\n> world\n>\n> final';const {view}=mount(source,source.indexOf('hello'));expect(editSemanticQuote(view,false)).toBe(true);expect(view.state.doc.toString()).toBe('> first\n>\n\nhello\\\nworld\n\n>\n> final');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('protects the first Callout body paragraph and title Return only moves the caret',()=>{const source='> [!note] Title\n> body';const {view}=mount(source,source.indexOf('body'));expect(editSemanticQuote(view,false)).toBe(true);expect(view.state.selection.main.head).toBe(source.indexOf('\n'));expect(view.state.doc.toString()).toBe(source);expect(editSemanticQuote(view,true)).toBe(true);expect(view.state.selection.main.head).toBe(source.indexOf('body'));expect(view.state.doc.toString()).toBe(source);});
it('never lets non-list Tab insert literal indentation',()=>{const {view}=mount('text');expect(runScopeHandlers(view,new KeyboardEvent('keydown',{key:'Tab'}),'editor')).toBe(false);expect(view.state.doc.toString()).toBe('text');});
it('uses adjacent ordinary paragraphs and does not jump across a heading',()=>{const source='before\n\n| A |\n| --- |\n| x |\n\n# heading';const {view}=mount(source);const from=source.indexOf('| A'),to=source.indexOf('\n\n#');exitSemanticObject(view,{from,to},false);expect(view.state.selection.main.head).toBe(6);exitSemanticObject(view,{from,to},true);expect(view.state.doc.toString()).toBe(source.slice(0,to)+'\n\n'+source.slice(to));expect(view.state.selection.main.head).toBe(to+2);});
it('single click selects, F2 edits, typing in selection replaces only a cancellable draft',()=>{const source='| A | B |\n| --- | --- |\n| old | next |';const {view,root}=mount(source);button(root,'old').click();expect(focusedTableCell(view)).toBeNull();button(root,'old').focus();key(button(root,'old'),'x');expect(focusedTableCell(view)!.state.doc.toString()).toBe('x');expect(view.state.doc.toString()).toBe(source);key(focusedTableCell(view)!.dom,'Escape');expect(view.state.doc.toString()).toBe(source);key(button(root,'old'),'F2');expect(focusedTableCell(view)!.state.selection.main.head).toBe(3);});
it('cell drafts have local undo, controlled br, one parent commit and vertical selection',()=>{const source='| A | B |\n| --- | --- |\n| old | next |';const {view,root}=mount(source);button(root,'A').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const child=focusedTableCell(view)!;child.dispatch({changes:{from:0,to:1,insert:'new'},selection:{anchor:3}});key(child.dom,'Enter',{ctrlKey:true,altKey:true});expect(child.state.doc.toString()).toBe('new<br>');expect(view.state.doc.toString()).toBe(source);key(child.dom,'Enter');expect(document.activeElement).toBe(button(root,'old'));expect(focusedTableCell(view)).toBeNull();expect(view.state.doc.toString()).toContain('new<br>');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('IME rejects a leave and never replays it after composition ends',()=>{const source='| A |\n| --- |\n| old |';const {view,root}=mount(source);button(root,'old').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const child=focusedTableCell(view)!;child.dom.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));child.dispatch({changes:{from:0,to:3,insert:'中文'}});expect(commitTableDrafts(view)).toBe(false);child.dom.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(view.state.doc.toString()).toBe(source);expect(focusedTableCell(view)).toBe(child);expect(commitTableDrafts(view)).toBe(true);expect(view.state.doc.toString()).toContain('中文');});
it('metadata commits legal leave but retains invalid values and protects composing actions',()=>{const patches:string[]=[];const panel=createMetadataPanel('count: 12',undefined,{expanded:true,onChange:patch=>{patches.push(patch.insert);return true;}});document.body.append(panel);const trigger=panel.querySelector<HTMLButtonElement>('.md-metadata-value-edit')!;trigger.click();let input=panel.querySelector<HTMLInputElement>('input')!;input.value='invalid';expect(commitMetadataPanel(panel)).toBe(false);expect(input.value).toBe('invalid');input.value='13';input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));panel.querySelectorAll<HTMLButtonElement>('.md-metadata-value-form button')[0].click();expect(patches).toEqual([]);input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(patches).toEqual([]);expect(commitMetadataPanel(panel)).toBe(true);expect(patches).toEqual(['13']);disposeMetadataPanel(panel);});
it('mode changes commit valid cell drafts and refuse an invalid one without leaving',()=>{const root=document.body.appendChild(document.createElement('div'));const source='| A |\n| --- |\n| old |';const editor=new TeggMarkdownEditor(root,{documentId:'contract',source,revision:'1'},{},'live');button(root,'old').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));let child=focusedTableCell(editor.view)!;child.dispatch({changes:{from:0,to:3,insert:'new'}});expect(editor.setMode('source')).toBe(true);expect(editor.source).toContain('new');editor.setMode('live');button(root,'new').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));child=focusedTableCell(editor.view)!;child.dispatch({changes:{from:0,to:3,insert:'invalid\ncell'}});expect(editor.setMode('reader')).toBe(false);expect(editor.mode).toBe('live');expect(focusedTableCell(editor.view)).toBe(child);editor.destroy();});

it('projects complete footnotes at document end and edits the original definition in place',()=>{const source='Text[^n]\n\n[^n]: first\n    second\n\nLast paragraph';const {view,root}=mount(source);const section=root.querySelector<HTMLElement>('.cm-live-footnotes')!;expect(section).not.toBeNull();expect(section.closest('.cm-line')?.textContent?.startsWith('Last paragraph')).toBe(true);expect(focusFootnote(view,'n')).toBe(true);const node=section.querySelector<HTMLElement>('.cm-editor')!;const editor=EditorView.findFromDOM(node)!;editor.dispatch({changes:{from:0,to:5,insert:'edited'}});expect(view.state.doc.toString()).toBe(source.replace('first','edited'));expect(root.querySelector('.cm-live-footnotes')).toBe(section);expect(EditorView.findFromDOM(node)).toBe(editor);expect(editor.hasFocus).toBe(true);});

it('creates a missing footnote only on its first effective input',async()=>{const source='Missing[^new]';const {view,root}=mount(source);root.querySelector<HTMLButtonElement>('.cm-live-footnote-ref')!.click();await Promise.resolve();expect(view.state.doc.toString()).toBe(source);const node=root.querySelector<HTMLElement>('.cm-live-footnote-definition .cm-editor')!;const editor=EditorView.findFromDOM(node)!;editor.dispatch({changes:{from:0,insert:'Actual note'}});expect(view.state.doc.toString()).toBe(source+'\n\n[^new]: Actual note');undo(view);expect(view.state.doc.toString()).toBe(source);});

function temporaryCallout(root:HTMLElement){return EditorView.findFromDOM(root.querySelector<HTMLElement>('.cm-live-callout-temporary-body .cm-editor')!)!;}
it('title-only Callout Return supplies a transient body caret without changing source',async()=>{const source='> [!note] Title';const {view,root}=mount(source);expect(editSemanticQuote(view,true)).toBe(true);await Promise.resolve();const child=temporaryCallout(root);expect(child).toBeTruthy();expect(child.state.doc.length).toBe(0);expect(view.state.doc.toString()).toBe(source);child.dispatch({changes:{from:0,insert:'first body'}});await Promise.resolve();expect(view.state.doc.toString()).toBe(source+'\n> first body');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('Return in a transient empty Callout body exits and Backspace returns to title without fake source',async()=>{const source='> [!note] Title';const {view,root}=mount(source);editSemanticQuote(view,true);await Promise.resolve();key(temporaryCallout(root).dom,'Backspace');expect(view.state.doc.toString()).toBe(source);expect(view.state.selection.main.head).toBe(source.length);editSemanticQuote(view,true);await Promise.resolve();key(temporaryCallout(root).dom,'Enter');expect(view.state.doc.toString()).toBe(source+'\n\n');undo(view);expect(view.state.doc.toString()).toBe(source);});
it('transient Callout body composition creates source only after effective marked text completes',async()=>{const source='> [!note] Title';const {view,root}=mount(source);editSemanticQuote(view,true);await Promise.resolve();const child=temporaryCallout(root);child.dom.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));child.dispatch({changes:{from:0,insert:'中文'}});await Promise.resolve();expect(view.state.doc.toString()).toBe(source);child.dom.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await Promise.resolve();expect(view.state.doc.toString()).toBe(source+'\n> 中文');});
it('first empty Callout title input inserts its required separator only with effective input',()=>{const source='> [!note]';const {view}=mount(source);view.dispatch({changes:{from:source.length,insert:'标题'},selection:{anchor:source.length+2},userEvent:'input.type'});expect(view.state.doc.toString()).toBe(source+' 标题');expect(view.state.selection.main.head).toBe(source.length+3);undo(view);expect(view.state.doc.toString()).toBe(source);});
it('semantic paragraph and Callout title splits preserve crossing inline formats',()=>{const {view}=mount('**bold words**',6);insertSemanticParagraph(view);expect(view.state.doc.toString()).toBe('**bold**\n\n** words**');const source='> [!note] **bold words**\n> existing';const quote=mount(source,source.indexOf(' words'));editSemanticQuote(quote.view,true);expect(quote.view.state.doc.toString()).toBe('> [!note] **bold**\n> ** words**\n>\n> existing');});
it('shift-arrow selection keeps its rectangle when destination preview receives focus',()=>{const source='| A | B |\n| --- | --- |\n| first | second |';const {view,root}=mount(source);button(root,'A').focus();key(button(root,'A'),'ArrowRight',{shiftKey:true});const selected=root.querySelectorAll('[data-cell-state="selected"]');expect(selected).toHaveLength(2);expect(view.state.doc.toString()).toBe(source);});

it('projects unreferenced, undefined and repeated definitions without fake numbering or merging source',()=>{const source='Known[^a] repeated[^a] missing[^none]\n\n[^free]: unreferenced\n\n[^a]: first\n\n[^a]: second';const {view,root}=mount(source);const missing=root.querySelector('[data-footnote-group="missing"]')!;expect(missing.textContent).toContain('none');expect(root.querySelector('[data-footnote-group="unreferenced"] .footnote-number')?.textContent).toBe('');expect(root.querySelectorAll('[data-footnote-group="duplicates"] .cm-live-footnote-definition')).toHaveLength(2);expect(root.querySelectorAll('.cm-live-footnote-ref').item(2).textContent).toBe('?');expect(view.state.doc.toString()).toBe(source);const duplicate=root.querySelectorAll<HTMLElement>('[data-footnote-group="duplicates"] .cm-editor');EditorView.findFromDOM(duplicate[1])!.dispatch({changes:{from:0,to:6,insert:'changed second'}});expect(view.state.doc.toString()).toBe(source.replace('[^a]: second','[^a]: changed second'));});
it('each repeated footnote return control targets its own current reference after source edits',()=>{const source='First[^a], second[^a]\n\n[^a]: note';const {view,root}=mount(source);view.dispatch({changes:{from:0,insert:'Prefix '}});const refs=root.querySelectorAll<HTMLButtonElement>('.cm-live-footnote-ref');const returns=root.querySelectorAll<HTMLButtonElement>('.footnote-backref');expect(returns).toHaveLength(2);returns[1].click();expect(document.activeElement).toBe(refs[1]);returns[0].click();expect(document.activeElement).toBe(refs[0]);});
it('Live footnote hover shows read-only content without moving editor focus or source',()=>{const source='First[^a]\n\n[^a]: note';const {view,root}=mount(source);view.focus();root.querySelector<HTMLElement>('.cm-live-footnote-ref')!.dispatchEvent(new MouseEvent('mouseenter'));expect(view.hasFocus).toBe(true);expect(root.querySelector('dialog')).not.toBeNull();expect(view.state.doc.toString()).toBe(source);});

it('renders rich title-only Callout without fold and annotates only the actual document first block',async()=>{const source='before\n\n> [!note] **rich** title';const {root}=mount(source);expect(root.querySelectorAll('[data-document-first="true"]')).toHaveLength(1);expect(root.querySelector('.callout-fold')).toBeNull();const reader=document.body.appendChild(document.createElement('div'));await renderMarkdown(source,reader);expect(reader.querySelector('.callout-title-text strong')?.textContent).toBe('rich');expect(reader.querySelector('.callout-fold')).toBeNull();});
it('retains scroll object identity after preceding edits and full table replacement and clamps overflow',()=>{const session=new ContentDisplaySession();session.setHorizontalOffset('table',5,25,300);const id=session.objectId('table',5,25);session.map(ChangeSet.of({from:0,insert:'xxx'},30));expect(session.objectId('table',8,28)).toBe(id);session.map(ChangeSet.of({from:8,to:28,insert:'new table content here'},33));expect(session.objectId('table',8,30)).toBe(id);const viewport=document.body.appendChild(document.createElement('div'));Object.defineProperties(viewport,{clientWidth:{value:450},scrollWidth:{value:500}});const stop=bindContentScroll(viewport,session,'table',{from:8,to:30});expect(viewport.scrollLeft).toBe(50);expect(session.horizontalOffset('table',8,30)).toBe(50);stop();});
it('shares code wrap inside a footnote through its original source coordinates',async()=>{const source='Text[^n]\n\n[^n]: ```js\n    long code\n    ```',session=new ContentDisplaySession(),root=document.body.appendChild(document.createElement('div'));const view=new EditorView({parent:root,state:EditorState.create({doc:source,extensions:[history(),markdown({extensions:GFM}),resourceContext.of({documentPath:'',displaySession:session}),displaySessionMapping,livePreview]})});views.push(view);const wrap=root.querySelector<HTMLButtonElement>('.cm-live-footnote-definition .md-code-actions button')!;wrap.click();const reader=document.body.appendChild(document.createElement('div'));await renderMarkdown(source,reader,{displaySession:session});expect(reader.innerHTML).toContain('md-code-wrap-action');expect(reader.querySelector('.footnote-body .md-code-wrap-action')?.getAttribute('aria-pressed')).toBe('true');});
it('Reader details uses shared display state and supplies missing summary without modifying source',async()=>{const source='<details open><p>body</p></details>',session=new ContentDisplaySession();session.setExpanded('html-details',0,source.length,false);const reader=document.body.appendChild(document.createElement('div'));await renderMarkdown(source,reader,{displaySession:session});expect(reader.querySelector('details')?.open).toBe(false);expect(reader.querySelector('summary')?.textContent).toBe('Details');expect(source).toBe('<details open><p>body</p></details>');});

it('a dirty independent object inside a footnote stays in its child UI until explicit completion',async()=>{const source='Text[^n]\n\n[^n]: $$\n    x+y\n    $$',root=document.body.appendChild(document.createElement('div')),overlay=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'nested',source,revision:'1'},{},'live'),ui=attachEditingUI(editor.editing,overlay,{toolbar:false});root.querySelector<HTMLButtonElement>('.cm-live-footnote-definition button[data-tegg-ui-label="Edit formula"]')!.click();const body=overlay.querySelector<HTMLTextAreaElement>('.tegg-object-body')!;expect(body.value.trim()).toBe('x+y');body.value='x+z';body.dispatchEvent(new Event('input',{bubbles:true}));expect(editor.source).toBe(source);expect(editor.prepareLeave()).toBe(false);expect(overlay.querySelectorAll('.tegg-discard-draft')).toHaveLength(1);const complete=[...overlay.querySelectorAll<HTMLButtonElement>('.tegg-discard-draft button')].find(button=>button.dataset.label==='Complete and continue')!;await vi.waitFor(()=>expect(complete.disabled).toBe(false));complete.click();expect(editor.source).toContain('    x+z');expect(editor.prepareLeave()).toBe(true);undo(editor.view);expect(editor.source).toBe(source);ui.destroy();editor.destroy();});

it('routes footnote cell formatting and local undo to the current cell and rejects unsupported or composing commands',()=>{const source='Text[^n]\n\n[^n]: | A | B |\n    | --- | --- |\n    | old | next |', {view,root}=mount(source);const preview=button(root,'old');preview.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const footnote=focusedFootnoteEditor(view)!,cell=focusedTableCell(footnote)!;expect(cell).not.toBeNull();cell.dispatch({selection:{anchor:0,head:3}});expect(executeFocusedFootnoteCommand(view,'bold')).toBe(true);expect(cell.state.doc.toString()).toBe('**old**');expect(view.state.doc.toString()).toBe(source);expect(executeFocusedFootnoteCommand(view,'heading2')).toBe(false);expect(executeFocusedFootnoteCommand(view,'arbitrary')).toBe(false);expect(executeFocusedFootnoteCommand(view,'undo')).toBe(true);expect(cell.state.doc.toString()).toBe('old');cell.dom.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(executeFocusedFootnoteCommand(view,'bold')).toBe(false);expect(cell.state.doc.toString()).toBe('old');cell.dom.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(view.state.doc.toString()).toBe(source);});

it('mode changes finish a valid footnote cell draft and retain an invalid or composing draft',()=>{const source='Text[^n]\n\n[^n]: | A |\n    | --- |\n    | old |',root=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'footnote-table',source,revision:'1'},{},'live');button(root,'old').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));let child=focusedTableCell(focusedFootnoteEditor(editor.view)!)!;child.dispatch({changes:{from:0,to:3,insert:'new'}});expect(editor.commandStatus('heading2').enabled).toBe(false);expect(editor.setMode('reader')).toBe(true);expect(editor.source).toContain('| new |');editor.setMode('live');button(root,'new').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));child=focusedTableCell(focusedFootnoteEditor(editor.view)!)!;child.dispatch({changes:{from:0,to:3,insert:'invalid\ncell'}});expect(editor.setMode('source')).toBe(false);expect(editor.mode).toBe('live');expect(child.state.doc.toString()).toBe('invalid\ncell');child.dispatch({changes:{from:0,to:child.state.doc.length,insert:'valid'}});child.dom.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(editor.setMode('source')).toBe(false);child.dom.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(editor.mode).toBe('live');expect(editor.setMode('source')).toBe(true);expect(editor.source).toContain('| valid |');editor.destroy();});

it('leaves an HTML block into an existing adjacent paragraph despite its parser terminal line feed',()=>{const html='<table><tr><td>A</td></tr></table>',source='before\n\n'+html+'\n\nafter',{view}=mount(source),range={from:source.indexOf(html),to:source.indexOf(html)+html.length};expect(exitSemanticObject(view,range,true)).toBe(true);expect(view.state.selection.main.head).toBe(source.indexOf('after'));expect(view.state.doc.toString()).toBe(source);expect(exitSemanticObject(view,range,false)).toBe(true);expect(view.state.selection.main.head).toBe('before'.length);expect(view.state.doc.toString()).toBe(source);});

it('keeps direct HTML editing in an inner host that CodeMirror cannot mark read-only',()=>{const source='before\n\n<p data-original="yes">A<strong>B</strong></p>\n\nafter',{view,root}=mount(source);const outer=root.querySelector<HTMLElement>('.cm-live-html-block')!,inner=root.querySelector<HTMLElement>('.cm-html-direct-editor')!;expect(outer.contentEditable).toBe('false');expect(inner.contentEditable).toBe('true');expect(inner).not.toBe(outer);inner.querySelector('strong')!.textContent='changed';inner.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));expect(view.state.doc.toString()).toBe(source.replace('<strong>B</strong>','<strong>changed</strong>'));expect(root.querySelector('.cm-html-direct-editor')).toBe(inner);});

it('stores a cell attachment with the parent identity and retains it in the local draft until one isolated leave commit',async()=>{const source='before\n\n| A | B |\n| --- | --- |\n| old | unchanged |\n\nafter',root=document.body.appendChild(document.createElement('div')),overlay=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'resource-note',source,revision:'1'},{},'live');let complete!:(result:{reference:string})=>void;const store=vi.fn((_file:unknown,context:{documentId:string})=>{expect(context.documentId).toBe('resource-note');return new Promise<{reference:string}>(resolve=>{complete=resolve;});}),ui=attachEditingUI(editor.editing,overlay,{toolbar:false,storeResource:store});button(root,'old').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const child=focusedTableCell(editor.view)!;child.dispatch({selection:{anchor:0,head:child.state.doc.length}});const event=new Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:(type:string)=>type==='text/html'?'<table><tr><td><img src="fixture.png" alt="Native fixture"></td></tr></table>':'',types:['text/html'],files:[new File([new Uint8Array([1])],'fixture.png',{type:'image/png'})]}});child.dom.dispatchEvent(event);expect(event.defaultPrevented).toBe(true);expect(store).toHaveBeenCalledOnce();expect(editor.prepareLeave()).toBe(false);expect(editor.source).toBe(source);complete({reference:'Attachments/fixture.png'});await vi.waitFor(()=>expect(child.state.doc.toString()).toContain('Attachments/fixture.png'));expect(editor.source).toBe(source);expect(editor.prepareLeave()).toBe(true);expect(editor.source).toBe(source.replace('old','![Native fixture](<Attachments/fixture.png>)'));undo(editor.view);expect(editor.source).toBe(source);ui.destroy();editor.destroy();});

it('pastes a matrix in text editing only into the captured cell selection after explicit inline simplification',()=>{const source='| A | B |\n| --- | --- |\n| old | untouched |',{view,root}=mount(source);button(root,'old').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const child=focusedTableCell(view)!;child.dispatch({selection:{anchor:1,head:2}});const event=new Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:(type:string)=>type==='text/plain'?'x\ty\nz\tw':'',types:['text/plain'],files:[]}});child.dom.dispatchEvent(event);expect(view.state.doc.toString()).toBe(source);expect(child.state.doc.toString()).toBe('old');expect(root.querySelector<HTMLElement>('.md-table-paste-review')!.hidden).toBe(false);[...root.querySelectorAll<HTMLButtonElement>('button')].find(button=>button.textContent==='Apply simplified paste')!.click();expect(child.state.doc.toString()).toBe('ox\ty<br>z\twd');expect(view.state.doc.toString()).toBe(source);expect(commitTableDrafts(view)).toBe(true);expect(view.state.doc.toString()).toContain('| ox\ty<br>z\twd | untouched |');undo(view);expect(view.state.doc.toString()).toBe(source);});

it('uses direct metadata values without adding a whole YAML action to the content geometry',()=>{const panel=createMetadataPanel('title: Note',()=>{}, {onChange:()=>true});expect(panel.querySelector('.md-metadata-edit')).toBeNull();expect(panel.querySelector('.md-metadata-value-edit')).not.toBeNull();const legacy=createMetadataPanel('title: Note',()=>{});expect(legacy.querySelector('.md-metadata-edit')).not.toBeNull();disposeMetadataPanel(panel);disposeMetadataPanel(legacy);});

it('wraps a safe HTML table in a Reader scroll region with the same display object identity as Live',async()=>{const html='<table><tr><td>wide text</td></tr></table>',source='before\n\n'+html+'\n\nafter',session=new ContentDisplaySession(),reader=document.body.appendChild(document.createElement('div'));await renderMarkdown(source,reader,{displaySession:session});const region=reader.querySelector<HTMLElement>('.md-table-scroll')!;expect(region).not.toBeNull();expect(region.querySelector('table')).not.toBeNull();expect(region.dataset.contentObjectId).toBe(session.objectId('table',source.indexOf(html),source.indexOf(html)+html.length));});

it('namespaces list marker columns by source-backed object across footnote child projections',()=>{const source='1. Main\n\nText[^a] [^b]\n\n[^a]: 1. First\n    2. Second\n\n[^b]: 1. Other',{root}=mount(source);const lists=[...root.querySelectorAll<HTMLElement>('[data-list-id]')].map(node=>node.dataset.listId);expect(new Set(lists).size).toBe(3);expect(lists.filter(id=>id===lists[1])).toHaveLength(2);});


function guardChoice(overlay:HTMLElement,label:string){return [...overlay.querySelectorAll<HTMLButtonElement>('.tegg-discard-draft button')].find(node=>node.dataset.label===label)!;}
function dirtyFormula(ui:ReturnType<typeof attachEditingUI>,overlay:HTMLElement){ui.openObject('math');const body=overlay.querySelector<HTMLTextAreaElement>('.tegg-object-body')!;body.value='changed';body.dispatchEvent(new Event('input',{bubbles:true}));return body;}
it('exposes no queued leave after IME rejection and resolves only a subsequent explicit draft choice',async()=>{const source='$$\nx\n$$',root=document.body.appendChild(document.createElement('div')),overlay=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'leave-ime',source,revision:'1'},{},'live'),ui=attachEditingUI(editor.editing,overlay,{toolbar:false}),resolved=vi.fn(),cancelled=vi.fn();overlay.addEventListener('tegg-editing-leave-resolved',resolved);overlay.addEventListener('tegg-editing-leave-cancelled',cancelled);const body=dirtyFormula(ui,overlay);body.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(editor.prepareLeave()).toBe(false);expect(ui.awaitingLeaveChoice).toBe(false);body.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));expect(ui.awaitingLeaveChoice).toBe(false);expect(resolved).not.toHaveBeenCalled();ui.close();dirtyFormula(ui,overlay);expect(editor.prepareLeave()).toBe(false);expect(ui.awaitingLeaveChoice).toBe(true);await vi.waitFor(()=>expect(guardChoice(overlay,'Complete and continue').disabled).toBe(false));guardChoice(overlay,'Complete and continue').click();expect(ui.awaitingLeaveChoice).toBe(false);expect(resolved).toHaveBeenCalledOnce();expect(cancelled).not.toHaveBeenCalled();ui.destroy();editor.destroy();});
it('Keep editing and explicit cancellation clear pending leave without emitting a resolved navigation',()=>{const source='$$\nx\n$$',root=document.body.appendChild(document.createElement('div')),overlay=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'leave-cancel',source,revision:'1'},{},'live'),ui=attachEditingUI(editor.editing,overlay,{toolbar:false}),resolved=vi.fn(),cancelled=vi.fn();overlay.addEventListener('tegg-editing-leave-resolved',resolved);overlay.addEventListener('tegg-editing-leave-cancelled',cancelled);dirtyFormula(ui,overlay);expect(editor.prepareLeave()).toBe(false);expect(ui.awaitingLeaveChoice).toBe(true);guardChoice(overlay,'Keep editing').click();expect(ui.awaitingLeaveChoice).toBe(false);expect(cancelled).toHaveBeenCalledOnce();expect(resolved).not.toHaveBeenCalled();expect(editor.source).toBe(source);expect(editor.prepareLeave()).toBe(false);ui.close();expect(ui.awaitingLeaveChoice).toBe(false);expect(cancelled).toHaveBeenCalledTimes(2);expect(resolved).not.toHaveBeenCalled();dirtyFormula(ui,overlay);expect(editor.prepareLeave()).toBe(false);guardChoice(overlay,'Discard changes').click();expect(cancelled).toHaveBeenCalledTimes(2);expect(resolved).toHaveBeenCalledOnce();expect((resolved.mock.lastCall![0] as CustomEvent).detail.choice).toBe('discard');expect(ui.awaitingLeaveChoice).toBe(false);ui.destroy();editor.destroy();});
it('aggregates a nested footnote leave choice on the parent UI and forwards cancellation through the actual overlay',()=>{const source='Text[^n]\n\n[^n]: $$\n    x\n    $$',root=document.body.appendChild(document.createElement('div')),overlay=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'leave-nested',source,revision:'1'},{},'live'),ui=attachEditingUI(editor.editing,overlay,{toolbar:false}),cancelled=vi.fn();overlay.addEventListener('tegg-editing-leave-cancelled',cancelled);root.querySelector<HTMLButtonElement>('.cm-live-footnote-definition button[data-tegg-ui-label="Edit formula"]')!.click();const body=overlay.querySelector<HTMLTextAreaElement>('.tegg-object-body')!;body.value='nested draft';body.dispatchEvent(new Event('input',{bubbles:true}));expect(editor.prepareLeave()).toBe(false);expect(ui.awaitingLeaveChoice).toBe(true);guardChoice(overlay,'Keep editing').click();expect(ui.awaitingLeaveChoice).toBe(false);expect(cancelled).toHaveBeenCalledOnce();expect(editor.source).toBe(source);ui.destroy();editor.destroy();});

it('starting composition after a leave review cancels that navigation and completion does not replay it',async()=>{const source='$$\nx\n$$',root=document.body.appendChild(document.createElement('div')),overlay=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'leave-review-ime',source,revision:'1'},{},'live'),ui=attachEditingUI(editor.editing,overlay,{toolbar:false}),resolved=vi.fn(),cancelled=vi.fn();overlay.addEventListener('tegg-editing-leave-resolved',resolved);overlay.addEventListener('tegg-editing-leave-cancelled',cancelled);const body=dirtyFormula(ui,overlay);expect(editor.prepareLeave()).toBe(false);expect(ui.awaitingLeaveChoice).toBe(true);body.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));expect(ui.awaitingLeaveChoice).toBe(false);expect(cancelled).toHaveBeenCalledOnce();expect(editor.prepareLeave()).toBe(false);body.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await vi.waitFor(()=>expect(guardChoice(overlay,'Complete and continue').disabled).toBe(false));guardChoice(overlay,'Complete and continue').click();expect(editor.source).toContain('changed');expect(resolved).not.toHaveBeenCalled();expect(ui.awaitingLeaveChoice).toBe(false);ui.destroy();editor.destroy();});

it('code toolbar history keys undo a semantic insertion after Escape and protect composition',()=>{const source='before after\n\n- first\n- second',root=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'code-toolbar-history',source,revision:'1'},{},'live');editor.view.dispatch({selection:{anchor:7}});editor.view.focus();expect(editor.command('codeBlock')).toBe(true);const input=root.querySelector<HTMLTextAreaElement>('.md-code-area textarea')!;input.focus();key(input,'Escape');const language=root.querySelector<HTMLSelectElement>('.md-code-language')!;expect(document.activeElement).toBe(language);key(language,'z',{ctrlKey:true,isComposing:true});expect(editor.source).toContain('```text');key(language,'z',{ctrlKey:true});expect(editor.source).toBe(source);editor.destroy();});

it('public code command remains available to leave inline code in prose and cell drafts',()=>{const source='before `old` after',root=document.body.appendChild(document.createElement('div')),editor=new TeggMarkdownEditor(root,{documentId:'code-toggle',source,revision:'1'},{},'live');editor.view.dispatch({selection:{anchor:8,head:11}});editor.view.focus();expect(editor.state.code).toBe(true);expect(editor.state.inlineFormattingEnabled).toBe(false);expect(editor.commandStatus('bold').enabled).toBe(false);expect(editor.commandStatus('code').enabled).toBe(true);expect(editor.command('code')).toBe(true);expect(editor.source).toBe('before old after');editor.destroy();const table='| A |\n| --- |\n| `old` |',cellRoot=document.body.appendChild(document.createElement('div')),cellEditor=new TeggMarkdownEditor(cellRoot,{documentId:'code-toggle-cell',source:table,revision:'1'},{},'live');button(cellRoot,'`old`').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));const cell=focusedTableCell(cellEditor.view)!;cell.dispatch({selection:{anchor:1,head:4}});expect(cellEditor.state.code).toBe(true);expect(cellEditor.commandStatus('code').enabled).toBe(true);expect(cellEditor.command('code')).toBe(true);expect(cell.state.doc.toString()).toBe('old');expect(cellEditor.source).toBe(table);key(cell.dom,'Enter');expect(cellEditor.source).toBe(table.replace('`old`','old'));undo(cellEditor.view);expect(cellEditor.source).toBe(table);cellEditor.destroy();});
