// @vitest-environment jsdom
import {describe,it,expect} from 'vitest';
import {parserFor} from './markdownParser';
import {sourceSpanClipboard} from './sourceClipboardModel';
import {readContentClipboard} from './contentClipboardText';
import type {MarkdownProfile} from './syntaxProfiles';
const value=(source:string,selected=source,profile:MarkdownProfile='tegg')=>sourceSpanClipboard(source,{from:source.indexOf(selected),to:source.indexOf(selected)+selected.length},profile);
const structured=(source:string,selected=source,profile:MarkdownProfile='tegg')=>readContentClipboard(value(source,selected,profile).structured);
describe('lightweight source clipboard model',()=>{
 it('keeps exact CRLF span bytes, rich text and only its actual reference definition',()=>{const selected='[Linked][ref] **bold**\r\n\r\nSecond &amp; text',source='Before\r\n\r\n'+selected+'\r\n\r\nAfter\r\n\r\n[ref]: <secret.md> "Exact title"\r\n[unused]: other.md';const data=value(source,selected);expect(readContentClipboard(data.structured)).toEqual({version:1,kind:'content',format:'tegg',source:selected,definitions:['[ref]: <secret.md> "Exact title"']});expect(data.text).toBe('Linked bold\n\nSecond & text');expect(data.html).toContain('<strong>bold</strong>');expect(data.html).toContain('href="secret.md"');expect(data.text).not.toContain('secret.md');});
 it.each(['tegg','github','gfm'] as const)('resolves full, collapsed and shortcut image/link references in %s',profile=>{const selected='[shown][key] [key][] [key] ![alt][photo]',source=selected+'\n\n[key]: target.md "Title"\n[photo]: img.png\n[other]: unrelated.md';const data=value(source,selected,profile);expect(readContentClipboard(data.structured).definitions).toEqual(['[key]: target.md "Title"','[photo]: img.png']);expect(data.text).toBe('shown key key alt');expect(data.html).toContain('src="img.png"');expect(data.html).toContain('title="Title"');});
 it('uses actual case-normalized reference keys without inventing entity equivalence',()=>{const selected='[label][a&amp;b]',definition='[A&amp;B]: exact.md',source=selected+'\n\n'+definition+'\n[other]: other.md';expect(structured(source,selected).definitions).toEqual([definition]);expect(structured(selected+'\n\n[a&b]: different.md',selected).definitions).toBeUndefined();});
 it('preserves a multiline definition including title, author spaces and CRLF',()=>{const selected='[label][ref]',definition='  [ref]:\r\n    <target.md>\r\n    "Exact  title"  ',source=selected+'\r\n\r\n'+definition+'\r\n\r\n[other]: other.md';const data=value(source,selected);expect(readContentClipboard(data.structured).definitions).toEqual([definition]);expect(data.html).toContain('title="Exact  title"');});
 it('preserves duplicate definitions for the used key while resolving the first',()=>{const selected='[label][r]',source=selected+'\n\n[r]: first.md\n[r]: second.md\n[other]: no.md';const data=value(source,selected);expect(readContentClipboard(data.structured).definitions).toEqual(['[r]: first.md','[r]: second.md']);expect(data.html).toContain('href="first.md"');expect(data.html).not.toContain('second.md');});
 it.each(['`[literal][ref] [^n]`','```text\n[ref]: fake.md\n[label][ref]\n[^n]\n```','    [label][ref]\n    [^n]','<pre>[label][ref] [^n]</pre>','$[label][ref]+[^n]$','[[ref|label]]','\\[ref]'])('does not infer dependencies from opaque/literal syntax %s',selected=>{const source=selected+'\n\n[ref]: real.md\n[^n]: actual note';expect(structured(source,selected).definitions).toBeUndefined();});
 it('does not treat labels in a normal destination or HTML as reference usage',()=>{const selected='[shown](target.md "[ref]") <a href="[ref]">author</a>',source=selected+'\n\n[ref]: unused.md';expect(structured(source,selected).definitions).toBeUndefined();});
 it('retains a selected footnote and its referenced body dependencies with exact raw bytes',()=>{const selected='body[^n]',first='[^n]: rich **note** [linked][r]\r\n\r\n    continued\ttext',source=selected+'\r\n\r\n'+first+'\r\n\r\n[r]: <target.md> "t"\r\n[^other]: unrelated';const data=value(source,selected);expect(readContentClipboard(data.structured).definitions).toEqual([first,'[r]: <target.md> "t"']);expect(data.html).toContain('<strong>note</strong>');expect(data.html).toContain('href="target.md"');expect(data.text).not.toContain('↩');expect(data.text).not.toContain('unrelated');});
 it('resolves nested footnote dependencies without repeated or unrelated definitions',()=>{const selected='body[^a]',source=selected+'\n\n[^a]: first[^b]\n\n[^b]: second\n\n[^other]: ignored';expect(structured(source,selected).definitions).toEqual(['[^a]: first[^b]','[^b]: second']);});
 it('copies a whole collapsed Callout body and literal code/alt/TeX without UI descriptions',()=>{const source='> [!warning]- Title\n> hidden\n\n```text\n\t**literal**\n\n```\n\n![actual alt](image.png)\n\n$x+1$';const data=value(source);expect(data.text).toContain('Title');expect(data.text).toContain('hidden');expect(data.text).toContain('\t**literal**\n\n');expect(data.text).toContain('actual alt');expect(data.text).toContain('x+1');expect(readContentClipboard(data.structured).source).toBe(source);});
 it('does not append definitions already fully inside the selected source',()=>{const source='[label][r]\n\n[r]: target.md\n';expect(structured(source).definitions).toBeUndefined();expect(value(source).html).toContain('href="target.md"');});
 it('refuses an external container definition rather than stripping its source rails',()=>{const selected='[label][r]',source=selected+'\n\n> [r]: target.md';expect(()=>value(source,selected)).toThrow(/another container/);expect(structured(source).definitions).toBeUndefined();expect(value(source).html).toContain('href="target.md"');});
 it('retains author elements with classes that resemble generated footnote UI',()=>{const source='<p class="footnote-backref">author content</p>';expect(value(source).text).toBe('author content');expect(value(source).html).toContain('author content');});
 it('rejects an invalid/nonempty span rather than silently clamping its source',()=>{for(const span of [{from:-1,to:1},{from:0,to:99},{from:1,to:1},{from:.5,to:1}])expect(()=>sourceSpanClipboard('text',span)).toThrow(/valid source range/);});
 it('maps lone CR line endings back to untouched original dependency bytes',()=>{const selected='[label][r]',definition='[r]:\r  target.md\r  "title"',source='Before\r\r'+selected+'\r\r'+definition+'\r\r[other]: other.md';const data=value(source,selected);expect(readContentClipboard(data.structured).source).toBe(selected);expect(readContentClipboard(data.structured).definitions).toEqual([definition]);expect(data.html).toContain('href="target.md"');});
 it('does not change the cached public parser or turn its renderer into clipboard-only output',()=>{const parser=parserFor('tegg'),source='body[^n]\n\n[^n]: note',before=parser.render(source,{});expect(before).toContain('footnote-backref');value(source,'body[^n]');expect(parser.render(source,{})).toBe(before);expect(parser.block.ruler.getRules('').length).toBe(parserFor('tegg').block.ruler.getRules('').length);});
 it('refuses a partially selected external footnote container while whole-source copy preserves it',()=>{const selected='body[^n]',source=selected+'\n\n> [^n]: quoted note';expect(()=>value(source,selected)).toThrow(/another container/);expect(readContentClipboard(value(source).structured).source).toBe(source);});
 it('does not turn a rejected unsafe reference target into an accepted dependency',()=>{const selected='[label][r]',source=selected+'\n\n[r]: javascript:alert(1)';const data=value(source,selected);expect(readContentClipboard(data.structured).definitions).toBeUndefined();expect(data.html).not.toContain('javascript:');expect(data.text).toBe(selected);});

});
