/** @vitest-environment jsdom */
import {afterEach,expect,it,vi} from "vitest";
import {copySource,type TextCopyEvent} from "./renderInteraction";
import {TeggMarkdownEditor} from "./editor";
import {TechnicalMarkdownReader} from "./reader";
const cleanups:Array<()=>void>=[];
afterEach(()=>{for(const cleanup of cleanups.splice(0))cleanup();document.body.replaceChildren();vi.unstubAllGlobals();});
const mounted=()=>{const owner=document.createElement("div"),button=document.createElement("button");owner.append(button);document.body.append(owner);return {owner,button};};
const deferred=()=>{let resolve!:()=>void,reject!:(reason:unknown)=>void;const promise=new Promise<void>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
it("string-detail handled copies remain pending until the Host acknowledgement",async()=>{const {owner,button}=mounted(),pending=deferred();let settled=false;owner.addEventListener("tegg-copy-text",event=>{expect((event as CustomEvent).detail).toBe("exact\r\nbytes");event.preventDefault();(event as TextCopyEvent).completion=pending.promise;});const copy=copySource("exact\r\nbytes",button).then(result=>{settled=true;return result;});await Promise.resolve();expect(settled).toBe(false);pending.resolve();expect(await copy).toBe(true);});
it("a rejected acknowledgement shows failure and never reports success",async()=>{const {owner,button}=mounted();owner.addEventListener("tegg-copy-text",event=>{event.preventDefault();(event as TextCopyEvent).completion=Promise.reject(Error("denied"));});expect(await copySource("exact",button)).toBe(false);expect(owner.querySelector('[role=status]')?.textContent).toContain("Copy unavailable");});
it("a legacy canceled event without completion is compatible without inventing an ACK",async()=>{const {owner,button}=mounted(),writeText=vi.fn();vi.stubGlobal("navigator",{clipboard:{writeText}});owner.addEventListener("tegg-copy-text",event=>event.preventDefault());expect(await copySource("exact",button)).toBeUndefined();expect(writeText).not.toHaveBeenCalled();expect(owner.querySelector('[role=status]')).toBeNull();});
it("late failures cannot appear in a replacement owner or over a newer copy",async()=>{const {owner,button}=mounted(),old=deferred(),next=deferred();let n=0;owner.addEventListener("tegg-copy-text",event=>{event.preventDefault();(event as TextCopyEvent).completion=(n++?next:old).promise;});const first=copySource("old",button),second=copySource("next",button);old.reject(Error("late"));expect(await first).toBe(false);expect(owner.querySelector('[role=status]')).toBeNull();next.resolve();expect(await second).toBe(true);const removed=deferred();owner.addEventListener("tegg-copy-text",event=>{(event as TextCopyEvent).completion=removed.promise;});const third=copySource("gone",button);owner.replaceChildren(document.createElement("p"));removed.reject(Error("late removed"));expect(await third).toBe(false);expect(owner.querySelector('[role=status]')).toBeNull();});
it("Editor exposes the Host Promise and suppresses failure after its document changes",async()=>{const {owner,button}=mounted(),pending=deferred(),onError=vi.fn(),copyText=vi.fn(()=>pending.promise);const editor=new TeggMarkdownEditor(owner,{documentId:"old",revision:"1",source:"exact"},{copyText,onError},"source");cleanups.push(()=>editor.destroy());editor.view.dom.append(button);const event=new CustomEvent("tegg-copy-text",{detail:"exact",bubbles:true,cancelable:true}) as TextCopyEvent;expect(button.dispatchEvent(event)).toBe(false);expect(event.completion).toBeInstanceOf(Promise);await Promise.resolve();expect(copyText).toHaveBeenCalledWith("exact");editor.replaceDocument({documentId:"new",revision:"1",source:"new"});pending.reject(Error("old failure"));await expect(event.completion).rejects.toThrow("old failure");expect(onError).not.toHaveBeenCalled();expect(editor.source).toBe("new");});
it("Reader exposes failure to the caller without swallowing it and ignores the next render",async()=>{const {owner}=mounted(),pending=deferred(),onError=vi.fn();const reader=new TechnicalMarkdownReader(owner,{copyText:()=>pending.promise,onError});cleanups.push(()=>reader.destroy());await reader.render({documentId:"old",source:"old"});const event=new CustomEvent("tegg-copy-text",{detail:"old",bubbles:true,cancelable:true}) as TextCopyEvent;owner.dispatchEvent(event);expect(event.completion).toBeInstanceOf(Promise);await reader.render({documentId:"new",source:"new"});pending.reject(Error("old failure"));await expect(event.completion).rejects.toThrow("old failure");expect(onError).not.toHaveBeenCalled();expect(owner.querySelector("p")?.textContent).toBe("new");});
it("main composition consumes the action without copying or queuing a replay",async()=>{const {owner}=mounted(),copyText=vi.fn();const editor=new TeggMarkdownEditor(owner,{documentId:"doc",revision:"1",source:"exact"},{copyText},"source");cleanups.push(()=>editor.destroy());editor.view.contentDOM.dispatchEvent(new CompositionEvent("compositionstart",{bubbles:true}));const event=new CustomEvent("tegg-copy-text",{detail:"exact",bubbles:true,cancelable:true}) as TextCopyEvent;expect(editor.view.contentDOM.dispatchEvent(event)).toBe(false);expect(event.completion).toBeUndefined();await Promise.resolve();expect(copyText).not.toHaveBeenCalled();expect(editor.source).toBe("exact");});
